### ISSUE TITLE
PhpStorm advanced metadata, add support for __call

### ISSUE THREAD

**Issue by edcoreweb** [barryvdh/laravel-ide-helper#1002]
PhpStorm 2020.2 added support for __get override.

I created an issue asking for adding support for __call and __callStatic.
https://youtrack.jetbrains.com/issue/WI-54495

If we have this supported by PhpStorm we can basically auto-complete all magic calls, macros, facades, without having the duplicate warnings.

Please vote this issue, to let the PhpStorm devs know there's interest in this.

**Comment by mfn** [comment]
Do we need to keep the issue open here or can we close it?

**Comment by edcoreweb** [comment]
We can close it.
