### ISSUE TITLE
Disable "Simplify full namespaces"

### ISSUE THREAD

**Issue by bbprojectnet** [barryvdh/laravel-ide-helper#1007]
Hi,

How to disable "Simplify full namespaces for already included resources" and keep FQCN like in version 2.7?

**Comment by barryvdh** [comment]
What is the problem with it?

**Comment by bbprojectnet** [comment]
Hi,

Nothing :) but i have conventions adopted in the project, using only FQCN in any PHPDoc. After update to version 2.8, suddenly i have to commit many files because this little change ;) I want to avoid this and stay fine with convention.

I think will be great if i can turn on/off this behaviour in config file. What do you think? :)

**Comment by mfn** [comment]
Yet another config 😢

**Comment by mfn** [comment]
Btw, I can understand it's at least confusing because the changelog mentions nothing related to this.

**Comment by bbprojectnet** [comment]
> Yet another config 😢

No, just one new entry in `ide-helper.php` :)

**Comment by mfn** [comment]
IMHO there should be more technical justification for this instead of not liking / wanting to commit this… 🤷‍♀️

**Comment by bbprojectnet** [comment]
There is - backward compatybility. I like laravel-ide-helper and how it works (until 2.7). So, if that major change is introduced, it should by as an option and in default behave like before, or at least give an option to switch to old behaviour.

For me, laravel-ide-helper is not a only tool for help IDE, but also visual aspect of code (PHPDoc blocks).

**Comment by mfn** [comment]
> backward compatybility

Can you point it what it _breaks_?

**Comment by bbprojectnet** [comment]
Style of PHPDoc block.

**Comment by mfn** [comment]
So you are using php-cs-fixer or similar which now breaks on this?

**Comment by bbprojectnet** [comment]
Yes, I'm also using PHP CS Fixer, but they have plenty of options which i can achieve desirable effect of code formating. There has never been a situation where from version to version change behavior of some functionality without option to control it.

**Comment by bbprojectnet** [comment]
I probably missunderstand your message... yes, php-cs-fixer works fine, code works fine... etc. I know what you're getting at.

Look, if suddenly ide helper change all \n to spaces it will be ok or not? Code will work, everything will be fine but this still was a bug. Same with change FQCN to only class name, but the impact is lower.

**Comment by edvordo** [comment]
I would also very much welcome a way to disable this. I want to use FQCN everywhere, even the class is in the same file. All my projects use FQCN everywhere, even outside of models, simplification is very much undesirable behaviour for me.

**Comment by mfn** [comment]
😢 

I guess we're accepting PRs then!
