### ISSUE TITLE
namespaced route - cannot find declaration to go to

### ISSUE THREAD

**Issue by quantumwebco** [barryvdh/laravel-ide-helper#1008]
"laravel/framework": "^7.0",
"barryvdh/laravel-ide-helper": "^2.7"
PHPStorm 2020.2

Hey there

The declaration navigation works fine for routes in the main namespace but when having a "sub" namespace for controllers like ```App\Http\Controllers\User``` and using ```Route::namespace('User')->group(function () {...});``` in my ```api.php``` routes file it cannot find the declaration. Is it possible the helper can understand that the routes inside the namespace method are assigned to that namespace?

Thanks much

**Comment by mfn** [comment]
> cannot find the declaration

This is the same as https://github.com/barryvdh/laravel-ide-helper/issues/1016#issuecomment-679346397 , please see the answer there
