### ISSUE TITLE
Support needed to use with Laravel Modules package

### ISSUE THREAD

**Issue by ferdousanam** [barryvdh/laravel-ide-helper#1016]
I am trying to use [laravel-modules](https://nwidart.com/laravel-modules) package but I am facing problem to go to definition of the controller if the controller is inside a module. But if I use a controller which is in Laravel's default structure it works. Please look at the screenshot below for better understanding:

![image](https://user-images.githubusercontent.com/40851904/91049628-49943800-e63f-11ea-947d-f3d5aaec843b.png)

```php
// HomeController's namespace App\Http\Controllers;
Route::resource('/home', 'HomeController');
```

![image](https://user-images.githubusercontent.com/40851904/91049928-c6271680-e63f-11ea-92b6-76650d65ae26.png)

```php
// BlogController's namespace Modules\Blog\Http\Controllers;
Route::resource('/blog', 'BlogController');
```

`composer.json`

```json
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
```

**Comment by mfn** [comment]
This isn't related to this package, these kind of IDE integration features are provided by plugins like https://plugins.jetbrains.com/plugin/7532-laravel/ or https://plugins.jetbrains.com/plugin/13441-laravel-idea/

**Comment by sergx** [comment]
This command do what you expect:
`php artisan ide-helper:models --dir="Modules\*\Entities"`

**Comment by ferdousanam** [comment]
> This command do what you expect:
> `php artisan ide-helper:models --dir="Modules\*\Entities"`

I think you have not understood my query. This is not the command I expected.
Thank you.
