### ISSUE TITLE
[L8] Too few arguments to function Illuminate\View\Engines\PhpEngine::__construct()

### ISSUE THREAD

**Issue by SlyDeath** [barryvdh/laravel-ide-helper#1024]
With **Laravel 8** when i run `php artisan ide-helper:generate` or ` php artisan ide-helper:meta` i've got an error:

>  Too few arguments to function Illuminate\View\Engines\PhpEngine::__construct(), 0 passed in /vendor/barryvdh/laravel-ide-helper/src/IdeHelperServiceProvider.php on line 119 and exactly 1 expected  at /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:24

Problem is here:
https://github.com/barryvdh/laravel-ide-helper/blob/707ec990e7657d4a75d793895b996b3d7b7543e8/src/IdeHelperServiceProvider.php#L119

Need pass **Filesystem**:
```
return new PhpEngine($this->app['files']);
```
Or it's Laravel issue? Anyway why not add ¯\\_(ツ)_/¯

**Comment by mfn** [comment]
> Or it's Laravel issue? Anyway why not add ¯\_(ツ)_/¯

You're right it's an "upcoming" bug for L8 because they added a constructor. ide-helper needs to be fixed here.

Are you up for an PR + tests which works in L7/L8?

**Comment by SlyDeath** [comment]
I dont know what is "PR + tests", sorry :) 
I tried thus fix in mine the 7+ and 8+ projects. In both cases the commands were executed without errors.

**Comment by mfn** [comment]
I see, no worries. I didn't realize you already made a PR in your repo and already started one.

**Comment by SlyDeath** [comment]
Thanx!

**Comment by mfn** [comment]
> I dont know what is "PR + tests", sorry :)

- PR => "Pull Request
- "tests" => write tests for the code change ;)

**Comment by SlyDeath** [comment]
Where can I read the manual? :)
