### ISSUE TITLE
 array_merge(): Expected parameter 2 to be an array, null given

### ISSUE THREAD

**Issue by ap-coder** [barryvdh/laravel-ide-helper#1033]
the package wont generate anything just keeps giving that error out. 

SYSTEM DETIALS
LARAVEL 5.7
"barryvdh/laravel-ide-helper": "^2.8",

```
vagrant@homestead:~/code$ php artisan ide-helper:generate

   ErrorException

  array_merge(): Expected parameter 2 to be an array, null given

  at vendor/barryvdh/laravel-ide-helper/src/Generator.php:54
    50|
    51|         // Find the drivers to add to the extra/interfaces
    52|         $this->detectDrivers();
    53|
  > 54|         $this->extra = array_merge($this->extra, $this->config->get('ide-helper.extra'));
    55|         $this->magic = array_merge($this->magic, $this->config->get('ide-helper.magic'));
    56|         $this->interfaces = array_merge($this->interfaces, $this->config->get('ide-helper.interfaces'));
    57|         // Make all interface classes absolute
    58|         foreach ($this->interfaces as &$interface) {

      +16 vendor frames
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by mfn** [comment]
You need to publish the default configuration, see the README:

`php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config`

Please report back if it then works for you, thanks

**Comment by razjar** [comment]
Same issue here, publishing the default configuration dit not work

```
   ErrorException 

  array_merge(): Expected parameter 2 to be an array, null given

  at vendor/barryvdh/laravel-ide-helper/src/Generator.php:54
    50| 
    51|         // Find the drivers to add to the extra/interfaces
    52|         $this->detectDrivers();
    53| 
  > 54|         $this->extra = array_merge($this->extra, $this->config->get('ide-helper.extra'));
    55|         $this->magic = array_merge($this->magic, $this->config->get('ide-helper.magic'));
    56|         $this->interfaces = array_merge($this->interfaces, $this->config->get('ide-helper.interfaces'));
    57|         // Make all interface classes absolute
    58|         foreach ($this->interfaces as &$interface) {

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by mfn** [comment]
Ah sorry, slight mix-up 😅, sorry; please ignore until OP comes back.

> also clear config after doing this

Well, "yes" **but**: ide-helper is for development and you should never ever cache config in development to begin with. That's an anti-pattern.

**Comment by furopi** [comment]
> You need to publish the default configuration, see the README:
> 
> `php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config`
> 
> Please report back if it then works for you, thanks

Thanks bro

**Comment by furopi** [comment]
> > You need to publish the default configuration, see the README:
> > `php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config`
> > Please report back if it then works for you, thanks
> 
> also clear config after doing this: php artisan config:cache then run php artisan ide-helper:generate again

Thanks bro

**Comment by mfn** [comment]
Closing, OP never came back

**Comment by kyawsithu** [comment]
> > You need to publish the default configuration, see the README:
> > `php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config`
> > Please report back if it then works for you, thanks
> 
> also clear config after doing this: php artisan config:cache then run php artisan ide-helper:generate again

This solution worked
