### ISSUE TITLE
Error: Class 'Illuminate\Foundation\Application' not found in file (When using Lumen)

### ISSUE THREAD

**Issue by pataar** [barryvdh/laravel-ide-helper#1042]
### Versions:
- ide-helper Version: 2.8.1
- Lumen Version: 7.2.1 
- PHP Version: 7.2.24

### Description:

It seems that a change broke the integration with Lumen. IlluminateFoundation\Application is not available there.

**Comment by DannyvdSluijs** [comment]
I guess for anyone trying to reproduce this some additional info can be very helpful. Perhaps you have a stack trace or could you share your composer.lock and composer.json?

**Comment by pataar** [comment]
Due to company restrictions I can't share those files fully. But I can provide more information when needed

**Comment by mfn** [comment]
I stacktrace would be helpful but I can imagine a simple test with lumen and installing it will already expose it (don't have the time right now though)

**Comment by pataar** [comment]
1. `composer create-project --prefer-dist laravel/lumen sample && cd sample`
2. `composer require --dev barryvdh/laravel-ide-helper`
3. `composer require league/flysystem #otherwise it won't run`
4.  Follow the Lumen guidelines from `README.md`
5. `php artisan ide-helper:generate`

6:
![image](https://user-images.githubusercontent.com/3403851/92494178-aeca5a80-f1f5-11ea-89be-0a5df90dd86a.png)

**Comment by mfn** [comment]
Thanks!

The Laravel 8 comaptibility PR https://github.com/barryvdh/laravel-ide-helper/pull/1026 broke Lumen 😢

**Comment by mfn** [comment]
@pataar can you give https://github.com/barryvdh/laravel-ide-helper/pull/1043 a try?

Applying the source change locally and see if generate works should be sufficient.

Thanks

**Comment by pataar** [comment]
Yes, I'll let you know tomorrow

**Comment by pataar** [comment]
Thanks in advance for the fix!

**Comment by pataar** [comment]
@mfn I tested #1043 and the issue seems to be resolved after applying the fix.
