### ISSUE TITLE
Invalid reference to Application::VERSION in Lumen/Laravel < 8

### ISSUE THREAD

**Issue by rozwell** [barryvdh/laravel-ide-helper#1045]
Because of this line:
https://github.com/barryvdh/laravel-ide-helper/blob/affa55122f83575888d4ebf1728992686e8223de/src/IdeHelperServiceProvider.php#L119

Lumen/Laravel versions below 8 are failing with this error:
>
>  Class 'Illuminate\Foundation\Application' not found  
>

Since **v2.8.0** works just fine, for those who are in a hurry, here is a temporary solution:
```$ composer require --dev barryvdh/laravel-ide-helper:=2.8.0```

**Comment by mfn** [comment]
Duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/1042 , please give feedback over there if https://github.com/barryvdh/laravel-ide-helper/pull/1043 works for you.

Thanks
