### ISSUE TITLE
Livewire Support

### ISSUE THREAD

**Issue by coolsam726** [barryvdh/laravel-ide-helper#1051]
### This is a request to add support for livewire auto-completion if possible.

With Laravel 8 now moving to Tailwindcss and livewire/inertiajs, is it possible for you to add support for livewire components and auto-completion? This will be highly appreciated. Thanks for the good work.

**Comment by barryvdh** [comment]
What would that mean, what is to be auto-completed?

**Comment by coolsam726** [comment]
1. Auto detect data type of the public properties from the Livewire components and offer intellisense features based on that,
2. Alpine.js component tags autocompletion for tags inside the views/components folder (e.g <x-jet-button>, <x-data-picker> etc) together with the attributes they expect,
3. Livewire directives auto-completion e.g <div wire:click="">

**Comment by barryvdh** [comment]
This package can only generate meta-data/phpdocs so that PHPstorm (or any other IDE) supports it. Not sure if this is possible at all.

**Comment by coolsam726** [comment]
Alright. We will keep digging.
