### ISSUE TITLE
Add models php doc for Laravel 8 HasFactory::factory method

### ISSUE THREAD

**Issue by dmason30** [barryvdh/laravel-ide-helper#1055]
### Summary

It would be great if we could add autocomplete to the static factory method so that we know which factory class it is using. 

And could detect it by checking if it uses the `HasFactory` trait and also if the assumed factory class exists.

This will be specifically useful for classes that us custom methods for state etc. So it could also only add the doc if the factory class has custom methods if needed.

There is further scope to add phpdocs to the factory classes so that we get autocompletion on the model/collections returned from `create` but that will have to be done separately if wanted.

Happy to work on a PR if you think it will be accepted. 

e.g.

```php
/**
 * App\Models\User.
 *
 * @property etc...
 * @method static \Database\Factories\UserFactory factory()
 */
class User extends Authenticatable {
    use HasFactory;
}
```

**Comment by miken32** [comment]
It looks like what's missing from the PR is to scan the model for relations and then add `has*` methods to the autocomplete. So `Post::factory()->hasComments(3)->create();` will autocomplete.

**Comment by mfn** [comment]
Implemented via https://github.com/barryvdh/laravel-ide-helper/pull/1074 and released via https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.9.1
