### ISSUE TITLE
Class 'Illuminate\Support\Facades\Route' not found

### ISSUE THREAD

**Issue by Batur123** [barryvdh/laravel-ide-helper#1062]
- Laravel Version: 8.4.0
- PHP Version: 7.4.10

I was trying to use Laravel Framework and when i run this code on browser i get this error. I couldnt find a problem like this on the ide-helper issues or the internet. Can anyone help please

![2](https://user-images.githubusercontent.com/32031460/93604730-70d7ee00-f9ce-11ea-865e-27956b144f6f.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/32031460/93604733-72091b00-f9ce-11ea-9465-b8ce68c16d6f.PNG)

**Comment by mfn** [comment]
I'm closing this as this is not related to ide-helper in any way.

---
You seem to have some intrinsic setup issue here. The Facade reference looks correct, but it seems your autoloading or so does not work.

**Comment by hebaahmed1993** [comment]
Were you able to solve this problem? I am also facing the same problem

**Comment by hebaahmed1993** [comment]
Were you able to solve this problem? I am also facing the same problem
