### ISSUE TITLE
Laravel 8 Automatic Controller Namespace Prefixing not working...

### ISSUE THREAD

**Issue by jadamec** [barryvdh/laravel-ide-helper#1072]
### Versions:
- ide-helper Version: 2.8.1
- Laravel Version: 8.7.1
- PHP Version: 7.4.10

PHPstom cannot recognize _Automatic Controller Namespace Prefixing_ even I have `RouteServiceProvider.php` configured correctly (acc. https://laravel.com/docs/8.x/upgrade). Thanks.

`web.php` - https://prnt.sc/uqmia8
`RouteServiceProvider.php` - https://prnt.sc/uqmjlh

**Comment by mfn** [comment]
> PHPstom cannot recognize _Automatic Controller Namespace Prefixing_ even

IMHO this is the same as https://github.com/barryvdh/laravel-ide-helper/issues/1016#issuecomment-679346397 (and https://github.com/barryvdh/laravel-ide-helper/issues/1008 ) , please see the answer there
