### ISSUE TITLE
[Feature] Add enable/disable flag in .env

### ISSUE THREAD

**Issue by Braunson** [barryvdh/laravel-ide-helper#1073]
### Summary

As I do not work in PHP Storm but my colleagues do, it would be handy to have a flag in the config that grabs from the `.env` file allowing me to disable the plugin running (it's in the composer hooks). 

I can put in a PR for this if this is of interest?

**Comment by mfn** [comment]
I suggest to just include the env check in the composer hook directly.

Sounds like an edge case a project uses ide-helper and then members not wanting to use it?

**Comment by Braunson** [comment]
Yeah it's a very specific use-case, certain developers use it (they use PHPStorm), I do not use it (I'm using VSCode), it takes a good 30+ seconds to run every composer update/install/remove/require/etc. So being able to have it skip pass the command somehow would be helpful and save 30+ seconds every time I run composer xxx locally.

How would you add the env check in the composer hook?

```
"post-update-cmd": [
    "Illuminate\\Foundation\\ComposerScripts::postUpdate",
    "@php artisan ide-helper:generate", // Here
    "@php artisan ide-helper:meta"      // Here
],
```

**Comment by mfn** [comment]
Dunno, I thought I saw some project doing this, don't remember which one.

I just found https://github.com/laravel/laravel/blob/a6ca5778391b150102637459ac3b2a42d78d495b/composer.json#L55 , maybe it helps find a solution

**Comment by hulkur** [comment]
Maybe I didn't understand correctly, but ide-helper does not take 30s to run so your time saving will not be that relevant actually.

**Comment by Braunson** [comment]
@mfn Hmm that checks if the .env file exists instead of reading from it. I'll just throw the two ide-helper commands in a new custom command and wrap that with an env check for the environment.

@hulkur In my case, measured it and yes it is. 


Closing this as I have a workaround. Hope this issue can help others with similar use-cases.
