### ISSUE TITLE
Respect default file namespace for docblocks

### ISSUE THREAD

**Issue by FractalizeR** [barryvdh/laravel-ide-helper#108]
``` php
namespace ForumHouse\Common\Conversion\Converters;

interface IConverter {}

class Factory
{
    /**
     * @param string $name Converter name
     * @returns IConverter
     */
    public function create($name) {}
}
```

`IConverter` in `Factory::create()` is actually `ForumHouse\Common\Conversion\Converters\IConverter`.

But in `_ide_helper.php` it is `\IConverter`

**Comment by m4tthumphrey** [comment]
So there is no way to fix this? I've noticed it for a while but get around it by just defining the type with a `/** @var /Full/Path/To/Class $class */` tag.

**Comment by mycarrysun** [comment]
@barryvdh any word on getting this fixed? showing me all kinds of warnings when trying to make commits...

**Comment by barryvdh** [comment]
Is this still an issue then?

**Comment by mfn** [comment]
@barryvdh this can be closed as duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/627 :} (which IMHO has more/better details)

**Comment by mfn** [comment]
Closing per my comment https://github.com/barryvdh/laravel-ide-helper/issues/108#issuecomment-650617938
