### ISSUE TITLE
Target class [Illuminate\Database\Eloquent\Factory] does not exist

### ISSUE THREAD

**Issue by hatamiarash7** [barryvdh/laravel-ide-helper#1080]
### Versions:
- ide-helper Version: 2.8.1
- Laravel Version: 8.10.0
- PHP Version: 7.4.3

### Description:

There is an exception for `ide-helper:generate` command in a **fresh installed** laravel project : 

```
   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [Illuminate\Database\Eloquent\Factory] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
    807▕ 
    808▕         try {
    809▕             $reflector = new ReflectionClass($concrete);
    810▕         } catch (ReflectionException $e) {
  ➜ 811▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812▕         }
    813▕ 
    814▕         // If the type is not instantiable, the developer is attempting to resolve
    815▕         // an abstract type such as an Interface or Abstract Class and there is

      +25 vendor frames 
  26  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

### Steps To Reproduce:

- Change `include_factory_builders` option to `true`
- Run `php artisan ide-helper:generate`

**Comment by squatto** [comment]
Per #1047, #1074, and the [readme](https://github.com/barryvdh/laravel-ide-helper#auto-completion-for-factory-builders), `include_factory_builders` is deprecated for Laravel 8.0+. The fix (for now) is to set it to `false` and wait for #1074 to be completed and merged 👍🏻

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/99949304-ddcf8180-2d8b-11eb-9f89-cd3beed134c1.png)

https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Factories.php#L6

**Comment by mfn** [comment]
https://github.com/barryvdh/laravel-ide-helper/pull/1074 was merged and the fix will be part of the next release (no ETA)
