### ISSUE TITLE
Overwrite return value of Eloquent relationship methods like `save(Model $model)`

### ISSUE THREAD

**Issue by MartinP7r** [barryvdh/laravel-ide-helper#1083]
### Summary

The `save` method returns the saved object of the model's type, however the abstract class only defines `Eloquent\Model`.

```php
 /**
     * Attach a model instance to the parent model.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return \Illuminate\Database\Eloquent\Model|false
     */
    public function save(Model $model)
    {
        $this->setForeignAttributesForCreate($model);

        return $model->save() ? $model : false;
    }
```

wouldn't it be possible to infer and write this into the ide-helper model file?

best regards,
Martin

**Comment by mfn** [comment]
Had to dig a bit to figure out you talk about e.g. https://github.com/laravel/framework/blob/f8fd88fae5234a739e0146db31a2282f18716f8b/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L259-L270

But that mode is dynamically depending on which relation, how could we do this? E.g. this is defined on `\Illuminate\Database\Eloquent\Relations\HasOneOrMany` but depends on the context.

I think this can only be "fixed" by something with Generics like https://phpstan.org/blog/generics-in-php-using-phpdocs or https://psalm.dev/docs/annotating_code/templated_annotations/ and at best that would be done in the Laravel framework.

**Comment by MartinP7r** [comment]
That makes sense, yes. I had some misguided notion about what the relationship constrains you to in this context. Sorry to bother you with this!
