### ISSUE TITLE
Tag for Version 1.11.7 ?

### ISSUE THREAD

**Issue by svilborg** [barryvdh/laravel-ide-helper#1085]
I know it is very old, and not supported any more ..

Could you create a tag for version 1.11.7, this commit has some needed fixes for old projects :
 https://github.com/barryvdh/laravel-ide-helper/commit/0a8e5436d45383f5b83fa5bdffdf95bdab6616ee

**Comment by mfn** [comment]
@svilborg unlikely to happen at this point, it's best to add a custom repository to your composer for this, see https://getcomposer.org/doc/05-repositories.md#package-2
