### ISSUE TITLE
Is there option to store _ide_helper.php and _ide_helper_models.php in custom folder?

### ISSUE THREAD

**Issue by fico7489** [barryvdh/laravel-ide-helper#1090]
Because PHP-CS-Fixer takes me 10-20 second for fixing this file

**Comment by mfn** [comment]
To the best of my knowledge, you can change all of it, see the config file:
- https://github.com/barryvdh/laravel-ide-helper/blob/0168e7256bfec301864bd1c75b0cc1804c3b874e/config/ide-helper.php#L14
- https://github.com/barryvdh/laravel-ide-helper/blob/0168e7256bfec301864bd1c75b0cc1804c3b874e/config/ide-helper.php#L27

Seems that the ide helper for models has no config, but can be changed via an option, see:
- https://github.com/barryvdh/laravel-ide-helper/blob/0168e7256bfec301864bd1c75b0cc1804c3b874e/src/Console/ModelsCommand.php#L190

Hmm, btw your question: a bit of reading in ide-helper _or_ also on php-cs-fixer, which allows to ignore certain files using it's finder, could have given you your answers already.

**Comment by fico7489** [comment]
thanks for an assistance
