### ISSUE TITLE
Lumen 8.0 are not support

### ISSUE THREAD

**Issue by YouLiLiao** [barryvdh/laravel-ide-helper#1092]
### Versions:
- ide-helper Version: 2.8.1
- Lumen Version: 8.2.0
- PHP Version: 7.3.4

### Description:

Later versions of lumen 8.0 are not compatible because lumen does not have the class "Illuminate\Foundation\Application"

### Steps To Reproduce:

- …
![image](https://user-images.githubusercontent.com/11286354/99138921-6608a500-266f-11eb-85da-06ad13e13025.png)

**Comment by pataar** [comment]
This is fixed in #1043. But it's not in a released version yet. @barryvdh any idea when the new version is avaiable?

**Comment by Wulfheart** [comment]
This fix is already merged and released. Therefore this issue can be closed.

**Comment by mfn** [comment]
Indeed, it was released starting with 2.8.2; thank you :) closing
