### ISSUE TITLE
Is it possible to ignore a section of code

### ISSUE THREAD

**Issue by adampatterson** [barryvdh/laravel-ide-helper#1097]
### Versions:
- ide-helper Version: 2.8
- Laravel Version: 7.24
- PHP Version: 7.4.9

### Question:
I have an unusual use case where the Laravel is loaded after a CMS has been initialized. 

Laravel is basically on its own but has access to the CMS code, Unfortunately, Artisan is totally unaware of this so I am unable to generate the ide-helper file.

Is it possible to wrap a code bock in some kind of ignore, or to check if `artisan ide-helper` is running?

Thanks!

**Comment by mfn** [comment]
@adampatterson I'm unable to follow, specifically the relation between composer and ide-helper

Are you saying you cannot install ide-helper due to the lack of no support for composer on this project?

**Comment by adampatterson** [comment]
@mfn Sorry, not composer, when Artisan is running.

**Comment by adampatterson** [comment]
Well, Since you pointed out my error. I found this solution `php_sapi_name() !== 'cli'`
