### ISSUE TITLE
How to delete generated docs from model?

### ISSUE THREAD

**Issue by sn0rk64** [barryvdh/laravel-ide-helper#1098]
### Versions:
- ide-helper Version: 2.2
- Laravel Version: 6.18
- PHP Version: 7.2

### Question:

Hi. How can I delete generated docs from all models?
I tried this:
`php artisan ide-helper:models --reset --nowrite`
but it doesn't work.

Any ideas?

**Comment by mfn** [comment]
There's no such functionality
