### ISSUE TITLE
Getting an error when running artisan command

### ISSUE THREAD

**Issue by fuzaylov** [barryvdh/laravel-ide-helper#11]
php artisan ide-helper:generate -S

returns the following error:

"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found","file":"\/www\/site\/bootstrap\/compiled.php","line":7075}}

**Comment by adrian7** [comment]
Had the same problem as @fuzaylov but adding the line  `'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',` in app.php `'providers'` array fixed it.

**Comment by alexglue** [comment]
I have 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' string in my config/local/app.php file;
and php artisan ide-helper:generate gave the same error. What should i do on dev environment? (if i add this provider to app.php (not /local/app.php) all works fine)

**Comment by barryvdh** [comment]
Are you using the appends function in your local file?

**Comment by o1eksiy** [comment]
php artisan config:clear

**Comment by JorisVanEijden** [comment]
Apparently Laravel 5 doesn't use the environment folders in config anymore:
https://laracasts.com/discuss/channels/general-discussion/l5-append-config-problem

**Comment by alisajjad160** [comment]
First after installing laravel ide helper, Update dependencies and then add this to your providers. it works like charm. 
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

And after this run this and anymore...
php artisan ide-helper:generate

**Comment by MoPHL** [comment]
For me it only worked after I did ```php artisan config:cache``` and ```php artisan cache:clear```, otherwise it still wasn't recognized.

**Comment by fotobank** [comment]
to MoPHL : Thanks to me it also helped

**Comment by heroselohim** [comment]
Resolved in my **Laravel 4** doing this:

Register the command in \app\start\artisan.php
Artisan::add(new CustomCommand);

Clearing the artisan cache
php artisan cache:clear

**Comment by pipegris** [comment]
This happened to me today, I'm on L5.2, After some commits at home, I came to work and this happened, it has to be something with the git ignores, and preconfigured/precomnpiled stuff, the `php artisan config:clear` solved it.

**Comment by kasparsklavins** [comment]
Encountered the same problem. My fix:
I have separated configs for each environment. My environment wasnt detected properly after a reinstall which caused this error.

**Comment by frogydiak** [comment]
Got curious with this project and I got the same error with Laravel 5.4. I added:

- `'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',` to config/app.php under providers then
- run php artisan config:clear
- then run: composer update

No more errors... let see if it work..
