### ISSUE TITLE
can not find Model‘s Builder

### ISSUE THREAD

**Issue by burtgithub** [barryvdh/laravel-ide-helper#1104]
### Versions:
- ide-helper Version: ^2.8
- Laravel Version: ^7.29
- PHP Version: v7.3.8

### Description:

where i use mode Builder can not find just like firstOrCreate

demo 

### Steps To Reproduce:

- …

**Comment by burtgithub** [comment]
<?php
namespace App\Http\Models\Ai;

use Illuminate\Database\Eloquent\Model;

class AiBz extends Model
{
    protected $connection = 'ai';

    protected $table = 'tbl_horoscope';


    protected $guarded = [];
}


use:

$a = new AiBz();
$a->firstOrCreate([xxx]);  


the firstOrCreate is not find

**Comment by mfn** [comment]
Your issue lacks basically every kind of information what you tried or not.

For me in works in PhpStorm, I can autocomplete for `firstOrCreate`:
![image](https://user-images.githubusercontent.com/87493/100932784-acbe2200-34ec-11eb-8341-bd5a158c4b69.png)

Please make sure you generated the `_ide_helper.php` file via `./artisan ide-helper:generate` and it's in your project discoverable by the IDE.

I'm closing this as I don't believe there's a bug in ide-helper regarding this.

Thank you!

**Comment by burtgithub** [comment]
@mfn can help me 
https://github.com/barryvdh/laravel-ide-helper/issues/1107
