### ISSUE TITLE
Make release please. Current 2.8.1 version contains bugs. But have fixes in master

### ISSUE THREAD

**Issue by 4n70w4** [barryvdh/laravel-ide-helper#1119]
### Versions:
- ide-helper Version: 2.8.1
- Laravel Version: 7.25.0

https://github.com/barryvdh/laravel-ide-helper/pull/1059

**Comment by mfn** [comment]
Yeah, that would be nice indeed 👍 @barryvdh

**Comment by barryvdh** [comment]
Done

**Comment by mfn** [comment]
`\o/`
