### ISSUE TITLE
Support for Laravel 5.0 planned?

### ISSUE THREAD

**Issue by stefanbauer** [barryvdh/laravel-ide-helper#112]
After Laravel 5.0 uses namespaces for all the stuff, this ide_helper doesn't work anymore. Is there an update planned? Or is there any idea how to fix? Of course you can customize the namespace in the ide_helper to Whatever\Http\Controllers, but then it is only working for Controllers. Is there already a solution for it?

**Comment by mfn** [comment]
I think we can close this, we're at Laravel 6.0 and 5.0 is long gone.
