### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by maksimklimenko** [barryvdh/laravel-ide-helper#1122]
Hello! I'm create package maaxim/admincore (in development).
Run command: `php artisan ide-helper:generate`
Error: `A non-numeric value encountered`
An: `barryvdh\laravel-ide-helper\src\Method.php:327`

What could be the problem?

P.s: Sorry, bad English.
![Снимок экрана (7)_LI](https://user-images.githubusercontent.com/20988222/101724895-485a1e80-3afb-11eb-8a0a-48dde3afda5a.jpg)

**Comment by mfn** [comment]
Please follow the issue templates, they are there for a reason => https://github.com/barryvdh/laravel-ide-helper/issues/new/choose

thank you!

ps: don't paste screenshots, please paste complete backtraces as text
