### ISSUE TITLE
vscode php 8.0

### ISSUE THREAD

**Issue by leonardochen30** [barryvdh/laravel-ide-helper#1125]
### Versions:
- ide-helper Version: 2.8.2
- Laravel Version: 8.18.1 
- PHP Version: 8.0

### Steps To Reproduce:

Just paste any code using new syntax.

**Comment by mfn** [comment]
> Just paste any code using new syntax.

Sorry, I've no idea what this is supposed to mean. Can you elaborate?

To make things short, no idea about vscode. Despite it's generic name `ide-helper`, it's pretty much tailored at PhpStorm as it simply is the most advanced IDE for PHP out there, supporting the advanced features necessary to make this library useful (and also aids static analyzers, I might add).

**Comment by leonardochen30** [comment]
sorry bro, wrong repository, my mistake
