### ISSUE TITLE
Missing property's type declaration 

### ISSUE THREAD

**Issue by gilvaju** [barryvdh/laravel-ide-helper#1130]
### Versions:
- ide-helper Version: 2.8
- Laravel Version: 8.15
- PHP Version: 7.4.13

### Description:

Just declare property in model:
![image](https://user-images.githubusercontent.com/677039/102699972-e64e9700-4227-11eb-9e65-c3fbf897af23.png)

**Comment by gilvaju** [comment]
I understand the problem and understand that it is best to ignore the warnings

**Comment by mfn** [comment]
Correct, and also it's entirely unrelated to ide-helper
