### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sobirjonovs** [barryvdh/laravel-ide-helper#1142]
array_merge(): Expected parameter 2 to be an array, null given

  at vendor/barryvdh/laravel-ide-helper/src/Generator.php:57
    53| 
    54|         // Find the drivers to add to the extra/interfaces
    55|         $this->detectDrivers();
    56| 
  > 57|         $this->extra = array_merge($this->extra, $this->config->get('ide-helper.extra'));
    58|         $this->magic = array_merge($this->magic, $this->config->get('ide-helper.magic'));
    59|         $this->interfaces = array_merge($this->interfaces, $this->config->get('ide-helper.interfaces'));
    60|         // Make all interface classes absolute
    61|         foreach ($this->interfaces as &$interface) {

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by mfn** [comment]
Please fill out the template properly

**Comment by tomcrofty** [comment]
Having this issue also
