### ISSUE TITLE
How is type hint shown for callable type parameters?

### ISSUE THREAD

**Issue by mertasan** [barryvdh/laravel-ide-helper#1143]
### Versions:
- ide-helper Version: 2.8
- Laravel Version: 8.x
- PHP Version: 7.4

### Question:

How is type hint shown for callable type parameters?

**This is it works.**

![https://i.ibb.co/hdZDLp0/screenshot-37.png](https://i.ibb.co/hdZDLp0/screenshot-37.png)

**Yes, it works that way too.**

![https://i.ibb.co/HHT8xmr/screenshot-38.png](https://i.ibb.co/HHT8xmr/screenshot-38.png)

But it doesn't work for me. Errors occur due to nested and different types of elements.

![https://i.ibb.co/jW1cchW/screenshot-35.png](https://i.ibb.co/jW1cchW/screenshot-35.png)

I want to define this in the make () method. I need your experience in this regard.

Thank you.

```php
class Myclass {
    /**
    * @param string   $name
    * @param callable $callback
    * @return Builder
    */
    public function make(string $name, callable $callback): ?Builder
    {
        if (!is_callable($callback)) {
            return null;
        }
    
        if (!Arr::exists($this->items, $name)) {
            $this->items[$name] = new Builder($name);
        }
    
        // Registering the items
        $callback($this->items[$name]);
    
        .......
    
        return $this->items[$name];
    }
}
```

```php
Myclass::make('title', function($item)) {

    $item->add('item title')
});
```

**Comment by mfn** [comment]
I don't think there's a way and I don't think this is related to ide-helper.

I would say your first version with the explicit type _is_ the "modern correct way".

**Comment by mertasan** [comment]
@mfn I think so. I could not find another way. thank you.
