### ISSUE TITLE
withQueryString() on paginate() dont work

### ISSUE THREAD

**Issue by patie** [barryvdh/laravel-ide-helper#1144]
Hi,

im trying to autocomplete `Model::paginate()->withQueryString()` part, Model and paginate() parts are ok, but **withQueryString() is unknown**. Its because generated `@return` doc is `\Illuminate\Contracts\Pagination\LengthAwarePaginator` and not `\Illuminate\Pagination\LengthAwarePaginator` which contains all methods.

When i manually change in generated _ide_helper.php from
`* @return \Illuminate\Contracts\Pagination\LengthAwarePaginator`
to
`* @return \Illuminate\Pagination\LengthAwarePaginator`
it works... 

Its possible to say IDE generator somehow to do it automaticly? Or there is other way how put in operation withQueryString() part?

thanks!

**Comment by dmitry-ivanov** [comment]
There's a similar issue with `paginate()->through()`.

As it was already stated above, the `paginate()` method has:
> @return \Illuminate\Contracts\Pagination\LengthAwarePaginator

And the `through()` method is located in the `Illuminate\Pagination\AbstractPaginator`.

**Comment by yaegassy** [comment]
I believe this problem still occurs, but will it ever be fixed?

**Comment by Temepest74** [comment]
Yes, this issue is still present. This happened to me when I did
```
        $recipes = Recipe::orderBy('id')->cursorPaginate(10)->withQueryString();
``` 
in Visual Studio Code. I even get this error Undefined method 'withQueryString'.intelephense(1013)
The method is not present in any of the files generated by gen-ide-helper. I already checked them

**Comment by jdevinemt** [comment]
I'm pretty sure this is a Laravel issue. The return type in laravel should be `\Illuminate\Pagination\LengthAwarePaginator` instead of `\Illuminate\Contracts\Pagination\LengthAwarePaginator`. Not sure the best way to resolve this. I just manually updated my _ide_helper.php file to include updated PHPDoc tags for this class/method.


`namespace Illuminate\Database\Eloquent {

    class Builder {

        /**
         * @static
         * @return \Illuminate\Pagination\LengthAwarePaginator
         */
        public static function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
        {
            /** @var Illuminate\Database\Eloquent\Builder $instance */
            return $instance->paginate($perPage, $columns, $pageName, $page);
        }

    }

}`

**Comment by Temepest74** [comment]
I found this issue in laravel too. I asked them to fix it, but they said that the class need to stay the same in case someone wants to extend it

**Comment by fahmiegerton** [comment]
Any update with this?

**Comment by Phojie** [comment]
No wonder why phpStorm exist, tsk! hate to say this but VSCODE with this package is 👎

**Comment by Phojie** [comment]
heres an alternative way, probably the correct way. 🚀 

https://github.com/barryvdh/laravel-ide-helper/issues/1278#issuecomment-1312369937

**Comment by jalexmelendez** [comment]
I found another solution, Laravel uses interfaces (or contracts) to define classes that must implement them as a way to allow us to load custom providers,  eg. we can make or own custom paginator using the LengthAwarePaginatorInterface and then register it as our default paginator, what i did is using phpdoc hint the concrete type of return, here are 2 examples we used in our codebase:

![image](https://github.com/barryvdh/laravel-ide-helper/assets/62973941/44885400-040d-4cfb-9a86-c34be7028c74)
![image](https://github.com/barryvdh/laravel-ide-helper/assets/62973941/e0883abb-4e85-4f9c-b8ce-bf2de7a5c0f2)
