### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by rbruhn** [barryvdh/laravel-ide-helper#115]
Having "php artisan ide-helper:generate" in the update command now causes error:
"post-update-cmd": [
    "php artisan clear-compiled",
    "php artisan ide-helper:generate",
    "php artisan optimize"
],

Script php artisan ide-helper:generate handling the post-update-cmd event returned with an error

[RuntimeException]
Error Output:

[InvalidArgumentException]
There are no commands defined in the "ide-helper" namespace.

**Comment by scil** [comment]
I has the same error, and i edit  app config correctly.  ... how?

because i run ` php artisan config:cache`

now i run `php artisan config:clear`

Everything ok.

just share.
