### ISSUE TITLE
If the database field like Camel Case

### ISSUE THREAD

**Issue by windqyoung** [barryvdh/laravel-ide-helper#1151]
### Versions:
- ide-helper Version: v2.9.0
- Laravel Version: 8.26.1
- PHP Version: 7.4
- MySQL Version: 5.7.33
 
### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/3234076/107330371-6d174600-6aec-11eb-88ce-022165ddb1a5.png)
![image](https://user-images.githubusercontent.com/3234076/107330439-84eeca00-6aec-11eb-924e-5fec9a038bcd.png)
![image](https://user-images.githubusercontent.com/3234076/107330494-96d06d00-6aec-11eb-89d6-6ce3602a8779.png)

![image](https://user-images.githubusercontent.com/3234076/107330723-eadb5180-6aec-11eb-83d7-3c4e58ac3fb7.png)

- …

**Comment by mfn** [comment]
This is a behaviour of Laravel itself and is not related to ide-helper
