### ISSUE TITLE
Carbon methods is undefined

### ISSUE THREAD

**Issue by jbersamin-vitech** [barryvdh/laravel-ide-helper#1152]
### Versions:
- ide-helper Version: 2.9
- Laravel Version:8.12
- PHP Version: 7.14

### Question:
The format method is undefined by intelephense extension after installing the laravel-ide-helper and generating the models.

Could it be because the date field type is "\Illuminate\Support\Carbon", that's why intelephense can't find the "format" method?

but that Support\Carbon is extending the Original Carbon.

**Comment by mfn** [comment]
In principle, the "gold standard" ide-helper supports is PhpStorm, as it's has the most advanced introspection of all PHP related IDEs so we make the best experience out of it.

From time to time we also get reports for Netbeans but if the respective engine are not advanced enough, there's nothing we can do.

So this was just for setting the scene.

Now what you describe, and I'm not _entirely_ clear, sounds like something basic actually. If you were to ask me, I would expect this to work. But I don't use any of the software you mentioned.

Can you share screenshots with the errors you get? Maybe that helps to figure out things…

**Comment by lucascorrea30** [comment]
I have the same issues.
PHP: 8.2
Intelephense: 1.9.3
VSCode:  1.78.2 (Universal)

And Carbon functions has the most annoying false errors. All this code on this print are working well.
I bought Intelephense Premiu to test more features and try to fix this errors, but I failed.

![image](https://github.com/barryvdh/laravel-ide-helper/assets/18143612/af7a7e38-20d2-4b0d-b685-1f27570e4446)

![image](https://github.com/barryvdh/laravel-ide-helper/assets/18143612/47411611-7c8b-4bb2-b942-68dc4b930bac)

![image](https://github.com/barryvdh/laravel-ide-helper/assets/18143612/a6a30813-034d-4f10-b1e7-7d8f78107b50)


These prints are taken on "simple" Laravel Model
