### ISSUE TITLE
Usage as a PHPStan stub

### ISSUE THREAD

**Issue by danabrey** [barryvdh/laravel-ide-helper#1153]
### Versions:
- ide-helper Version: 2.9.0
- Laravel Version: 8.26.1
- PHP Version: 7.4.14

### Question:

We're using the new [squashing migrations](https://laravel.com/docs/8.x/migrations#squashing-migrations) concept alongside PHPStan/Larastan. I'm not sure whether to ask this here or Larastan, but I can always go there instead if that makes sense!

I always assumed Larastan inspected the DB - alas, it doesn't, it inspects migrations - migrations that are no longer there once you've squashed them. So I followed [the advice](https://github.com/nunomaduro/larastan/issues/711#issuecomment-723801294) to try using your awesome package (that we already use for IDE help) to give PHPStan a stub file. However, I get a lot of errors from PHPStan when I do this from `_ide_helper_models.php`, e.g.:

```
 2654   Class App\XXXXXX extends unknown class Eloquent.                        
 2654   Class App\XXXXXX implements unknown interface App\Contracts\XXXXXXXX.                                              
 2710   Class App\XXXXXX extends unknown class Eloquent.                    
 2784   Class App\XXXXXX extends unknown class Eloquent.           
 2817   Class App\XXXXXX extends unknown class Eloquent.                   
 2833   Class App\XXXXXX extends unknown class Eloquent.              
 2891   Class App\XXXXXX extends unknown class Eloquent.                       
 2926   Class App\XXXXXX extends unknown class Eloquent.                
```

(XXXXXX redacted, just model names/interface names)

This seems to be because PHPStan requires all classes defined in stubs to also be defined within the stub file, even if they're not overridden in any way (see bottom of https://phpstan.org/user-guide/stub-files). Is there any way to use laravel-ide-helper to generate these stubs alongside?

**Comment by mfn** [comment]
IMHO you get the most out of this if you just let the phpdoc be written into the models: then any todays static analyzer picks them up for free! even phpstan / larastan in fact.

Of course we could generate more apt stubs but that adds more configuration and variation to maintain where a working solution exists.

Unless I missed something, sorry :)

**Comment by danabrey** [comment]
Thanks @mfn ! Makes sense.

**Comment by mfn** [comment]
Let me know if it works for you and we close this issue, thank you!

**Comment by danabrey** [comment]
Works perfectly, thanks. Will close.

**Comment by jeffchown** [comment]
> so it's impossible to use `_ide_helper_models.php` with **larastan** ?!
> 
> is there any workround (other than using phpdoc in the Models) ?

Was there ever any answer to this question?
