### ISSUE TITLE
Macro as a method of an object.

### ISSUE THREAD

**Issue by mj4444ru** [barryvdh/laravel-ide-helper#1159]
### Versions:
- ide-helper Version: 2.9.0
- Laravel Version: 8.25.0
- PHP Version: 7.4

### Question:
I use macros as methods of an object, but in the file "_ide_helper.php" they are declared as static methods.
https://github.com/barryvdh/laravel-ide-helper/blob/b21324b20e24a3c36bedc184b4cf273bfa0a2d32/resources/views/helper.php#L33

In connection with the above, PhpStorm considers this to be an error and does not display these methods in the drop-down list (does not suggest for use).
How to deal with this?

**Comment by netpok** [comment]
Interesting, static methods are perfectly valid in object context too, so it shouldn't behave this way.

**Comment by jonnywilliamson** [comment]
@mj4444ru Thank you!

Perfectly summed up very concisely!

Having the exact same issue. I've a number of macros for Builder and Response and they only appear in phpStorm autocomplete if I call them statically. 


So for example. If I register this Macro in a service provider:

```
        Builder::macro('qwerty', function (string $header): string {
                return 'qwerty';
            });
```

Then in `_ide_helper.php` it only appears as a static method:

```
            /**
             * @see \App\Providers\AppServiceProvider::boot()
             * @param string $header
             * @return string 
             * @static 
             */ 
            public static function qwerty($header)
            {
                return \Illuminate\Database\Eloquent\Builder::qwerty($header);
            }

```


When I attempt to use it, the following works great if called statically:
![image](https://user-images.githubusercontent.com/2513663/112022393-2cb6d900-8b2a-11eb-9b69-38531db08951.png)


But not so good if called from the object

![image](https://user-images.githubusercontent.com/2513663/112022833-8fa87000-8b2a-11eb-9188-65a6de15f4d1.png)

**Comment by netpok** [comment]
Okay, I looked a bit into this:
1. PhpStorm will only static methods when called statically and dynamic methods when called dynamically
2. To my best knowledge there is no way to disambiguate between a static and a dynamic macro
3. It is still possible to display it in the autocomplete list by invoking completion (ctrl + space by default)
4. The only way to automatically have them both is to have two different file with both declaration as phpstorm wont handle two declarations in the same file.

**Comment by ArielMejiaDev** [comment]
This package adds this type of support https://github.com/KristofMorva/laravel-ide-macros#use-of-non-static-macros
