### ISSUE TITLE
Issue with MySQL Point Spatial Type

### ISSUE THREAD

**Issue by leecolarelli** [barryvdh/laravel-ide-helper#1170]
### Versions:
- ide-helper Version: 2.9.0
- Laravel Version: 8.27.0
- PHP Version: 7.3

### Question:

I have an address model with a point mysql spatial type `$table->point('address_point'); // Point spatial data for the address`

When I run `ide-helper:models` i get an error on the address model as follows:-
```
Exception: Unknown database type point requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.
Could not analyze class App\Models\Address
```

I understand the issue, I just don't know how to fix it. In case it helps the mysql version is  8.0.21-0ubuntu0.20.04.4 and the point spatial type is working well throughout the application.

Any idea's how to fix the issue? Thanks.

**Comment by mfn** [comment]
I think you can use custom DB types to map this , please check if https://github.com/barryvdh/laravel-ide-helper#unsupported-or-custom-database-types is appropriate for your use case here

**Comment by leecolarelli** [comment]
> I think you can use custom DB types to map this , please check if https://github.com/barryvdh/laravel-ide-helper#unsupported-or-custom-database-types is appropriate for your use case here

Thank you... where do I insert the custom_db_types? It's not clear in the docs.

**Comment by mfn** [comment]
Oh! It's supposed to be in the config, see https://github.com/barryvdh/laravel-ide-helper/blob/6c4dcd9049e7e9aabc78673de7d1b9d428f3dc10/config/ide-helper.php#L177-L205

**Comment by leecolarelli** [comment]
> Oh! It's supposed to be in the config, see
> 
> https://github.com/barryvdh/laravel-ide-helper/blob/6c4dcd9049e7e9aabc78673de7d1b9d428f3dc10/config/ide-helper.php#L177-L205

Ok so I need to copy that file to root directory /config don't I? thanks

**Comment by leecolarelli** [comment]
> Oh! It's supposed to be in the config, see
> 
> https://github.com/barryvdh/laravel-ide-helper/blob/6c4dcd9049e7e9aabc78673de7d1b9d428f3dc10/config/ide-helper.php#L177-L205

Great, it worked. Thank you!

**Comment by mfn** [comment]
> Ok so I need to copy that file to root directory /config don't I? thanks

As part of following https://github.com/barryvdh/laravel-ide-helper#automatic-phpdoc-generation-for-laravel-facades this should have been published like any other packages configuration file.
