### ISSUE TITLE
How to include the --helpers or -H flags when publishing the config file?

### ISSUE THREAD

**Issue by jdmacdiarmid** [barryvdh/laravel-ide-helper#1179]
In the readme.md, under the section for Automatic PHPDoc generation for Laravel Facades, the text that shows how to publish the config file and provides the vendor: publish command. It's not clear how to include the "--helpers" or "-H" flags.   When I include it in the vendor publish command, I get the Laravel red box error saying that the those flags do not exist.  Would it be possible to add an example to the readme.md file how this is done?  

Thank you

**Comment by netpok** [comment]
You turn that feature on either by setting `include_helpers` to true in your config or by using the flag while generating the helper file: `php artisan ide-helper:generate -H`
