### ISSUE TITLE
The package can't work with swoole

### ISSUE THREAD

**Issue by Abbotton** [barryvdh/laravel-ide-helper#1186]
### Versions:
- ide-helper Version: 2.9.0
- Laravel Version: 8.32.1
- PHP Version: 7.4.16
- Swoole Version: 4.6.4
- `swooletw/laravel-swoole` Version: 2.7.0

### Question:
I used [swooletw/laravel-swoole](https://github.com/swooletw/laravel-swoole) package. when run `php artisan ide-helper:generate` command, I got error message:

```bash
Exception: Target class [swoole.room] does not exist.
Skipping \SwooleTW\Http\Websocket\Facades\Room.
Exception: Target class [swoole.websocket] does not exist.
Skipping \SwooleTW\Http\Websocket\Facades\Websocket.
Exception: Target class [swoole.room] does not exist.
Skipping \SwooleTW\Http\Websocket\Facades\Room.
Exception: Target class [swoole.websocket] does not exist.
Skipping \SwooleTW\Http\Websocket\Facades\Websocket.
```

I already read [this issuse](https://github.com/swooletw/laravel-swoole/issues/93#issuecomment-401833711) and [this Q&A](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md#class-swoole-does-not-exist), and understand why I got error. 

now the question is **How to ignore those not supported classes?**

sorry my poor English :-)

**Comment by barryvdh** [comment]
But aren't they skipped already?

**Comment by mfn** [comment]
Yeah, good observation. Whilst it might look annoying, in the end everything is working I think

**Comment by Abbotton** [comment]
Yeah, everything is fine. just a little question flashed by. sorry about this issue. 💯 thx.
