### ISSUE TITLE
PhpStorm not highlight static eloquement

### ISSUE THREAD

**Issue by ArthurPatriot** [barryvdh/laravel-ide-helper#1195]
### Versions:
- ide-helper Version: 2.9.1
- Laravel Version: 8.34.0
- PHP Version: 8.0.1

### Question:

How fix PhpStorm static method highlight?

![image1](https://user-images.githubusercontent.com/36359548/112706914-0c7f7500-8eb0-11eb-9cb9-f8f269a7e573.jpg)

![image2](https://user-images.githubusercontent.com/36359548/112706918-17d2a080-8eb0-11eb-9942-c7089ab895fe.png)

**Comment by mfn** [comment]
This is expected: it can't know that `Builder $query` refers to your `Post` model; it's just not possible.

I don't see a way for ide-helper doing magic here to fix this.

You could maybe help your self use `/** @var Builder|Post $query */`?
