### ISSUE TITLE
query scopes for models

### ISSUE THREAD

**Issue by hardevine** [barryvdh/laravel-ide-helper#12]
is it possible to have autocompletion query scopes methods while using on model eg.
`User::active()->get();`

**Comment by lsalazarm99** [comment]
It's only working when the scope is the very first method you use when you are building the query.

If you need to use 2 scopes or something like the following (assuming an "active" scope), it's not working.

```php
$models = YourModel::query()
    ->when(
        $request->boolean('isActive', false),
        function (Builder $query) {
            $query->active(); // Warning: Method 'active' not found in \Illuminate\Database\Eloquent\Builder
        }
    )
    ->get()
;
```

**Comment by dragg** [comment]
@lsalazarm99 
I don't see any reason why it should works on your example but I assume if you change to some kind of the next example then it should define fine:
```
$models = YourModel::query()
    ->when(
        $request->boolean('isActive', false),
        /** @var Builder|YourModel $query */
        function (Builder $query) {
            $query->active(); // Warning: Method 'active' not found in \Illuminate\Database\Eloquent\Builder
        }
    )
    ->get()
```

**Comment by nandi95** [comment]
@barryvdh Is it possible to have this a a member function on eloquent?
```php
MyModel::where('thing', 1)->myScope()->paginate()
```
I suspect it isn't so straightforward as it should only be applicable for a specific model.
