### ISSUE TITLE
Error installing barryvdh/laravel-ide-helper. Requires require illuminate/console ^8

### ISSUE THREAD

**Issue by classicalguss** [barryvdh/laravel-ide-helper#1200]
### Versions:
- ide-helper Version: 2.9
- Laravel Version: 7.30.1
- PHP Version: 7.4.16

### Question:
Could someone help regarding the foollowing issue that I'm getting when I execute `composer require --dev barryvdh/laravel-ide-helper`

```
  Problem 1
    - barryvdh/laravel-ide-helper[dev-master, v2.9.0, ..., v2.9.2] require illuminate/console ^8 -> found illuminate/console[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper 2.9.x-dev is an alias of barryvdh/laravel-ide-helper dev-master and thus requires it to be installed too.
    - Root composer.json requires barryvdh/laravel-ide-helper ^2.9 -> satisfiable by barryvdh/laravel-ide-helper[v2.9.0, v2.9.1, v2.9.2, 2.9.x-dev (alias of dev-master)].
```

This is my current composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "berkayk/onesignal-laravel": "^1.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "kreait/laravel-firebase": "^2.2",
        "larapack/voyager-hooks": "^1.2",
        "laravel/framework": "^7.0",
        "laravel/passport": "^9.2",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "maatwebsite/excel": "^3.1",
        "pbmedia/laravel-ffmpeg": "^7.0",
        "tcg/voyager": "^1.4"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "repositories": {
        "hooks": {
            "type": "composer",
            "url": "https://larapack.io"
        }
    }
}
```

**Comment by mfn** [comment]
> Laravel Version: 7.30.1

ide-helper requires Laravel 8+ 🤷‍♀️

You can check out https://packagist.org/packages/barryvdh/laravel-ide-helper#v2.8.2 to find a matching version for older Laravel versions

**Comment by angelcabrera-nr** [comment]
Thank you a lot @mfn

**Comment by mfn** [comment]
Closing due to lack of feedback from OP

**Comment by Bishopafl** [comment]
If you are using Laravel 7 or anything under Laravel 8 you need to specify an older version of the code.

`composer require --dev barryvdh/laravel-ide-helper 2.8`

The command above helped me implement this without error.

**Comment by yeminlideveloper** [comment]
> If you are using Laravel 7 or anything under Laravel 8 you need to specify an older version of the code.
> 
> `composer require --dev barryvdh/laravel-ide-helper 2.8`
> 
> The command above helped me implement this without error.

It worked for Laravel `7.30.5` by typing `composer require --dev barryvdh/laravel-ide-helper 2.8 --ignore-platform-reqs`

**Comment by Jalalnx** [comment]
> If you are using Laravel 7 or anything under Laravel 8 you need to specify an older version of the code.
> 
> `composer require --dev barryvdh/laravel-ide-helper 2.8`
> 
> The command above helped me implement this without error.

Thx its work fine for me

**Comment by WellingtonCarneiroBarbosa** [comment]
> If you are using Laravel 7 or anything under Laravel 8 you need to specify an older version of the code.
> 
> `composer require --dev barryvdh/laravel-ide-helper 2.8`
> 
> The command above helped me implement this without error.

Works fine on Laravel 5.8 with PHP 7.4. Thanks a lot!

**Comment by agm1984** [comment]
I am using `"barryvdh/laravel-ide-helper": "^2.7",` with Laravel v10.

For Laravel v11, I was able to update it to the newest version v3.6
