### ISSUE TITLE
_ide_helper.php overrides vendor files when using Go To Declaration action in PHPStorm 

### ISSUE THREAD

**Issue by tzurbaev** [barryvdh/laravel-ide-helper#1209]
### Versions:
- ide-helper Version: 2.9.3
- Laravel Version: 8.36.2 
- PHP Version: 7.4.16
- PHPStorm Version: PhpStorm 2020.3.3 (Build #PS-203.7717.64, built on March 16, 2021)
### Description:

For some reason class definitions in `_ide_helper.php` file override actual class definitions when using the "Go To -> Declaration or Usages" action (CTRL+B hotkey for me). The "Go To -> Type Declaration" action (CTRL+SHIFT+B hotkey for me) shows both class declarations from `_ide_helper.php` and original vendor file (see screenshot).

This also breaks constructor autocompletion, since classes from `_ide_helper.php` doesn't have constructor arguments.

![Screenshot](https://i.imgur.com/Ds7Jsxf.png)

### Steps To Reproduce:

- Create fresh Laravel app;
- Install laravel-ide-helper package;
- Import some Laravel class (for example, `Illuminate\Http\Request`) and try to open original file by navigating to declaration;
- Declaration in `_ide_helper.php` opens instead of `vendor/laravel/framework/src/Illuminate/Http/Request.php` file.

You can check my reproduction repository: https://github.com/tzurbaev/ide-helper-navigation-bug
Clone it, run `composer install`, open `tests/Unit/ExampleTest.php` and try to navigate to the `Request` class.

**Comment by mfn** [comment]
That's how it works 🤷‍♀️

**Comment by mfn** [comment]
See also this recent comment https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-816388888

**Comment by tzurbaev** [comment]
What confused me is a `Illuminate\Http\Request` class. I believe this class was not in _ide_helper.php in older versions of the package and now it's in. Maybe that's why I thought it's a bug.

I'll close this for now. Thanks for a heads up, @mfn!
