### ISSUE TITLE
Method or function <ModelName> has already been declared

### ISSUE THREAD

**Issue by Javier-Rotelli** [barryvdh/laravel-ide-helper#122]
I'm getting the following error in netbeans when generating model docs
![captura de pantalla de 2014-10-08 13 14 49](https://cloud.githubusercontent.com/assets/5343874/4562687/8647edb8-4f06-11e4-8255-1770b0ac469a.png)

and the autocompletion is gone. if i remove the methods section of the docs, the autocomplete works for the attributes

**Comment by mfn** [comment]
This can be closed, all modern IDEs correctly support `static`
