### ISSUE TITLE
Error resolving relation model of App\Models\User:suppliers() : Call to a member function supplier() on null

### ISSUE THREAD

**Issue by mirzazeyrek** [barryvdh/laravel-ide-helper#1220]
### Versions:
- ide-helper Version: 2.10
- Laravel Version: 8
- PHP Version: 7.5

### Question:

When I run the model helper creation I'm getting this warning:

`Error resolving relation model of App\Models\User:suppliers() : Call to a member function supplier() on null`

```
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function suppliers(): ?HasMany
    {
        return $this->company->supplier();
    }
```

What would be the recommended way of handling nested relationships ? Or is this a bug in the helper ?

**Comment by mfn** [comment]
Shouldn't this be done via a pivot table?

Every time you access $user->suppliers you actually have to load `->company`, but this is actually not used for loading the any further relation but for the _definition_ of the relation?

Not an expert here, but I think this approach is wrong.

You should probably just define the relation on `company` and always access it like that via `$user->company->supplier()`
