### ISSUE TITLE
Add mappings for ServiceProvider mapped Classes?

### ISSUE THREAD

**Issue by jamesmills** [barryvdh/laravel-ide-helper#123]
Howdy,

When using Service Providers in Laravel to register a binding between an Interface and a Class and then using Dependency Injection in a class you then have the problem that PHPStorm cannot find the methods for the class.

I wonder if there is a way of extending this IDE Helper to check the app.php service providers and then loop through adding a reference to the methods in the registered class?

Just thinking out loud.

Cheers, James

**Comment by mfn** [comment]
@jamesmills is this still relevant?

This was posted in 2014 so this must have been L4, we're now at L7 :}

Also, at reproducible code fragment would help here showing the problem.

**Comment by jamesmills** [comment]
It's possible that newer versions of everything now handle this better.

**Comment by mfn** [comment]
@jamesmills I don't know, but if you can come up with a reproducible example it makes sense to re-open and investigate this!
