### ISSUE TITLE
Laravel IDE Helper not working Sublime Text

### ISSUE THREAD

**Issue by anhthi92** [barryvdh/laravel-ide-helper#1232]
Note: You do need CodeComplice for Sublime Text: https://github.com/spectacles/CodeComplice

CodeComplice error! when installing Code Complice, it missing "Package Control"

 How to Laravel IDE Helper working on sublime text? Thanks, Guys!!

**Comment by ajoy39** [comment]
Are you saying sublime text doesn't have package control installed? hit ctrl+shift+p (or cmd+shift+p on Mac OS) and type "install package control"

**Comment by mfn** [comment]
What's the exact issue with ide-helper here again? 🤔

**Comment by uuf6429** [comment]
Anyway, sublime text is more of an editor than an ide... hence laravel-*ide*-helper is perhaps not applicable...
