### ISSUE TITLE
Conflict in illuminate/console and doctrine/dbal for Laravel 7

### ISSUE THREAD

**Issue by yudina-m** [barryvdh/laravel-ide-helper#1240]
### Versions:
- ide-helper Version: 2.8.2 vs 2.9.0
- Laravel Version: 7.30.1
- PHP Version: 7.4.22

### Question:
Is it possible to have a release tag with combination of `"illuminate/console": ^7 || ^8"` and `"doctrine/dbal": "^2.6 || ^3"` ?

**Comment by mfn** [comment]
But we don't support Laravel 7

**Comment by yudina-m** [comment]
> But we don't support Laravel 7

Do you support Laravel 8?

**Comment by mfn** [comment]
Yes
