### ISSUE TITLE
PHPDoc generation for Eloquent API Resources

### ISSUE THREAD

**Issue by william-lohan** [barryvdh/laravel-ide-helper#1246]
### Summary

In the following code:
```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class MyModelResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'name' => $this->name
        ];
    }
}
```
"name" has a warning (green squiggly) for "Property accessed via magic method". Could there be a way to generate a PHPDoc like ` php artisan ide-helper:models` does to give `MyModelResource` a `@property string name` some where?

### See

> Note that we can access model properties directly from the $this variable. This is because a resource class will automatically proxy property and method access down to the underlying model for convenient access. Once the resource is defined, it may be returned from a route or controller. The resource accepts the underlying model instance via its constructor: - https://laravel.com/docs/8.x/eloquent-resources#concept-overview

**Comment by rizkyarlin** [comment]
this will be great!

**Comment by jacob418** [comment]
As @PaulMenheere pointed out you can do this via Mixins:

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @mixin \App\Models\MyModel
 */
class MyModelResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'name' => $this->name
        ];
    }
}
```

If you use the mixin setting (`php artisan ide-helper:models --write-mixin`) for models you will also get the props injected by IDE-Helper.
