### ISSUE TITLE
There are no commands defined in the "ide-helper" namespace.

### ISSUE THREAD

**Issue by simplenotezy** [barryvdh/laravel-ide-helper#1249]
### Versions:
- ide-helper Version: 2.10
- Lumen Version: 8
- PHP Version: 7.4.22

### Question:
I am getting this error:

    There are no commands defined in the "ide-helper" namespace.

I have tried following the installation guide here. https://github.com/barryvdh/laravel-ide-helper#adding-additional-facades

Also VSCode complains about this:

    Undefined method 'userFromToken'.intelephense(1013)

![image](https://user-images.githubusercontent.com/3786627/131264726-98c08da9-de69-4b0a-adea-8b3ce55ca2d5.png)

But the code works just fine.

I am not sure what I am missing here

Similar issues:
https://github.com/barryvdh/laravel-ide-helper/issues/829

**Comment by mfn** [comment]
Does the information in https://github.com/barryvdh/laravel-ide-helper/pull/438 help?

**Comment by lucassusanto** [comment]
> There are no commands defined in the "ide-helper" namespace.

I also ran into this problem. I forgot to reset my `APP_ENV ` variable in `.env` file from `production` to `local`. I use the following code in my `AppServiceProvider.php` file as stated in [here](https://github.com/barryvdh/laravel-ide-helper#adding-the-service-provider).

```
if ($this->app->isLocal()) {
    $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
}
```

**Comment by mhmmdtech** [comment]
I faced this error in the deployment process of my project.
My `post-autoload-dump` is like this:
```
"post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:models --nowrite",
            "@php artisan package:discover --ansi"
        ],
```
As soon as I run the `composer install --optimize-autoloader --no-dev` in production, I faced this error.

**Comment by spacemudd** [comment]
@mhmmdtech Use "dev-post-update-cmd" like this:

```
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate"
        ],
        "dev-post-update-cmd": [
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:meta"
        ]
```

**Comment by pishguy** [comment]
Did you added this line to `app/config`?

```
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
```
