### ISSUE TITLE
Phpstorm: "Multiple definitions exist for class ..." for Models

### ISSUE THREAD

**Issue by EloProf** [barryvdh/laravel-ide-helper#126]
I am using laravel 4.2 with laravel-ide-helper v1.11.3. I did generate the helper file for my database models and phpstorm also recognizes it, but whenever I use one of my Models it complains that it has `"Multiple definitions exist for class ..."`.

Any idea how to resolve this without putting the helper information into the model files themselves?

**Comment by df-jablan** [comment]
I've found it helpful to mark the entire **storage** directory as *excluded*.

**Comment by shehi** [comment]
Once you generate your model signature/helper file, just copy and paste the phpDoc from it to the actual model itself and then remove the created helper model. It's a no brainer - I think this issue really needs closing.

**Comment by knugen** [comment]
@shehi That is not really a solution due to the vast amount of manual work that would mean.

However, there is a flag (`-W`) that does exactly this for you as you generate the meta data: https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-for-models

**Comment by shehi** [comment]
@knugen That might be true, but what you plan to do with file sitting inside the same namespace?! :D Its either exclusion or deletion.

**Comment by iraklisg** [comment]
@df-jablan @barryvdh Maybe I am missing something but, after running `php artisan ide-helper:models`, excluding the `storage` folder does not solve the problem....

**Comment by bretto36** [comment]
I'm in the same boat. It stores the _ide_helper_models.php file in the base directory. I don't want to overwrite the model files in anyway as i'm not sure what other issues i might face. I'd prefer to keep it separate. But now it's just introducing more issues.

**Comment by aleixfabra** [comment]
+1

**Comment by Artistan** [comment]
`php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config`

`config/ide-helper.php`
![image](https://user-images.githubusercontent.com/801349/30241061-0fbe1174-9542-11e7-8cba-3b873366fe37.png)


This commit will also allow update of the meta file name...
https://github.com/barryvdh/laravel-ide-helper/commit/55c9bfc33b0e8fc35a8f7939f1d4afe5debf1eb3



![image](https://user-images.githubusercontent.com/801349/30240964-1f522168-9540-11e7-88e0-64f20ef81977.png)

should look like this...
![image](https://user-images.githubusercontent.com/801349/30241079-6704155a-9542-11e7-9f16-17e95085d243.png)


**_I tried this, for sake of a good test.... It then will ignore the ide_helper .. _**

# =   hence making it useless. =

Personally I would rather have the "multiple definitions"
![image](https://user-images.githubusercontent.com/801349/30241171-95a2dd14-9543-11e7-81b8-7dd808018520.png)
It seems to only pertain to facades anyway.

**Comment by dereuromark** [comment]
https://laracasts.com/discuss/channels/general-discussion/phpstorm-warning-multiple-definitions-exists-for-class?page=1
=> you just exclude those dirs in the IDE

But I also use https://github.com/dereuromark/cakephp-ide-helper/commit/fd094212e093bd15ae5f859c15d73f8f67e8d435 now to exclude those test files from all released tags on GitHub, thus when someone doesnt use dev-master but a real version tag he will not get those test_files and the problem resolves itself.
The assumption is: Projects not developing this vendor lib directly, do not use those test files that are only for test casing the vendor lib. No relevance for projects.
