### ISSUE TITLE
Wrong conversion of int variable to octal

### ISSUE THREAD

**Issue by zoispag** [barryvdh/laravel-ide-helper#1266]
### Versions:
- ide-helper Version: v2.10.0
- Laravel Version: v8.63.0
- PHP Version: 7.4.24

### Description:

I stumbled upon this today:

![image](https://user-images.githubusercontent.com/21138205/136616609-389dbf20-78cc-4ae3-852e-be42badcece6.png)
> Notice the `$mode = 493`

The generated method is:

```php
/**
 * Ensure a directory exists.
 *
 * @param string $path
 * @param int $mode
 * @param bool $recursive
 * @return void
 * @static
 */
public static function ensureDirectoryExists($path, $mode = 493, $recursive = true)
{
    /** @var \Illuminate\Filesystem\Filesystem $instance */
    $instance->ensureDirectoryExists($path, $mode, $recursive);
}
```

originating from the original Illuminate\Filesystem\Filesystem:

```php
/**
 * Ensure a directory exists.
 *
 * @param  string  $path
 * @param  int  $mode
 * @param  bool  $recursive
 * @return void
 */
public function ensureDirectoryExists($path, $mode = 0755, $recursive = true)
{
    if (! $this->isDirectory($path)) {
        $this->makeDirectory($path, $mode, $recursive);
    }
}
```

This is coming from: https://github.com/barryvdh/laravel-ide-helper/blob/c733bde1ea229b159920f058911c12a8ae781bf9/src/Method.php#L337-L342 where `var_export` thinks that `0755` is the octal notation of 493 and not the decimal 775.

Not sure what to do about it. I don't consider it a big issue in this context (permissions) and I am not sure how I would tackle it either. In any case, I wanted to mention it as an issue, since there are no discussions in this repo.

If you have any suggestions, feel free to ping me and I can make a PR. Otherwise, feel free to close this issue. ✌🏼 

### Steps To Reproduce:

- Generate the helper file and search for `ensureDirectoryExists` method

**Comment by stof** [comment]
> where `var_export` thinks that `0755` is the octal notation of 493 and not the decimal 775.

which is totally expected. `0755` is indeed **not** the decimal 775.

**Comment by simensen** [comment]
I just ran into this today, too. :) Definitely isn't an actual issue but just feels weird as I had no idea why the mode was being set to some wonky non-mode default of `493`.
