### ISSUE TITLE
How do we ignore a directory?

### ISSUE THREAD

**Issue by CitizenBeta** [barryvdh/laravel-ide-helper#1276]
### Versions:
- ide-helper Version: 2.10.0
- PHP Version: 8

### Question:
How do we specify a more narrow directory for importing models, or is there a way to ignore a directory?

I'm running into multiple definitions warnings in Phpstorm due to classes imported into ide_helper from my app/Services classes which are not models. I read the docs and it seems like maybe something like this would work, but it doesnt:

```
/*
    |--------------------------------------------------------------------------
    | Model locations to include
    |--------------------------------------------------------------------------
    |
    | Define in which directories the ide-helper:models command should look
    | for models.
    |
    | glob patterns are supported to easier reach models in sub-directories,
    | e.g. `app/Services/* /Models` (without the space)
    |
    */

    'model_locations' => [
        'app/Models',
    ],

    /*
    |--------------------------------------------------------------------------
    | Models to ignore
    |--------------------------------------------------------------------------
    |
    | Define which models should be ignored.
    |
    */

    'ignored_models' => [
        'app/Services'
    ],

```

How can we import app/Models but not app/Services?

**Comment by CitizenBeta** [comment]
I updated to the latest version and I'm still getting multiple definitions warnings for my /Services classes.

**Comment by mvehar-preskok** [comment]
Any plans on implementing ignore by namespace prefix?
