### ISSUE TITLE
Code inspection warning because non-static function overridden by static function in generated helper file.

### ISSUE THREAD

**Issue by ThomasCollignon** [barryvdh/laravel-ide-helper#1284]
### Versions:
- ide-helper Version: 2.10.0
- Laravel Version: 8.73.2
- PHP Version: 7.4

### Question:
The tool `ide-helper:generate` has generated the static function `Eloquent.get($columns = [])` in __ide_helper.php_.
There also exists a non-static method `get($columns = ['*'])` in _Illuminate/Database/Eloquent/Builder.php_.
In the PHPStorm editor, writing
```php
MyModel::where('mycolumn', 'like', '%x')->get();
```
gets me a warning under the `get()`:

![image](https://user-images.githubusercontent.com/16621630/146160625-0defc88e-4f3f-42cf-ae2b-aab1b6b3a071.png)

There shouldn't be a warning here because it's not the static get() that is called, it's the one from Builder.php.
It's due to the fact that the function `where()` can return both `Eloquent|Illuminate\Database\Eloquent\Builder`.

My goal is to keep the generated helper files, and to avoid code inspection warnings like this one.
How do you overcome this ?

(error transcript for search engines):
> Static method 'get' should not be called dynamically, but the class has the '__magic' method.

**Comment by roberttolton** [comment]
I'm also facing this issue, anyone found a resolution?
