### ISSUE TITLE
session()->get() function unhandled exception

### ISSUE THREAD

**Issue by schonhoff** [barryvdh/laravel-ide-helper#1295]
### Versions:
- ide-helper Version: v2.10.0
- Laravel Version: v8.76.2
- PHP Version: 8.0.6

### Description:
Hello,

I got an error on the session()->get() functionality in my code. 
```php
session()->get('order.customer_no')
```

It shows the error:
![image](https://user-images.githubusercontent.com/42345405/148959073-491dee67-a73c-4c10-82a9-70e9af67fd72.png)

After I checked the declaration it wasn't fully clear for the PHPStorm which declaration to use for the method:
![image](https://user-images.githubusercontent.com/42345405/148959188-65fcd65b-c8c7-4cb0-a1b1-99643163dd96.png)

I tried to run ide-helper:generate and ide-helper:meta again, but nothing changed. The bug is on all appearances in the code.

Hope someone can me help out with this bug.

**Comment by mfn** [comment]
The behaviour you're seeing is unrelated to ide-helper: it doesn't do anything special for global functions like `session()` etc.

We're at the mercy what phpstorm can or cannot infer here; you would need to bring this to Jetbrains attention.

Alternatively can you use `\Illuminate\Support\Facades\Session::get()`, maybe it works better for your use-case (as much as people hate Facades, I think they still beat usage of global functions).
