### ISSUE TITLE
Removing extends from generated class breaks autocomplete

### ISSUE THREAD

**Issue by Jefemy** [barryvdh/laravel-ide-helper#1299]
### Versions:
- ide-helper Version: 2.11.0
- Laravel Version: 8.79.0
- PHP Version: 8.0

### Description:

https://github.com/barryvdh/laravel-ide-helper/pull/1268 changed mixin mode to not add an extends to the generated class. This breaks the autocomplete for functions like `Model->find()` as my classes no longer extend `\Eloquent`

### Steps To Reproduce:

- Run `ide-helper:models -M`
- Try to use the `find()` function on any model and see that the return type is listed as mixed instead of the proper class

**Comment by mfn** [comment]
Can you use `--write` to write this to the model files directly? Or at least, can you test if it elevates the problem?

**Comment by Jefemy** [comment]
After running that command it appears to have fixed it even after reverting back to just the `-M` command. Must have just been an issue with my IntelliSense extension.

**Comment by Jefemy** [comment]
Actually I do think this is an issue. After looking into it some more I realized my output doesn't include the `@mixin \Eloquent` that the test case includes [here](https://github.com/georgeboot/laravel-ide-helper/blob/79b10da14b8ca98ce18a2c0ba281f22cd66613f9/tests/Console/ModelsCommand/GeneratePhpdocWithMixin/__snapshots__/Test__test__1.php#L184).

This appears to be caused by the line [here](https://github.com/barryvdh/laravel-ide-helper/blob/999167d4c21e2ae748847f7c0e4565ae45f5c9f9/src/Console/ModelsCommand.php#L923) where it ignores adding the tag if there is a mixin present in the Model class, which there always will be after the first run since the command writes a mixin.

The [commit adding it](https://github.com/barryvdh/laravel-ide-helper/commit/83597196f9de73aa57caf76b830df239491e9a46) mentions its for preventing duplicate mixin tags but shouldn't it only be checking for tags with the `\Eloquent` class?

**Comment by edcoreweb** [comment]
@Jefemy I think this was introduced in #1268
