### ISSUE TITLE
support for Model::all()

### ISSUE THREAD

**Issue by nodren** [barryvdh/laravel-ide-helper#130]
should be easy enough to add, if you have a model(in this case User) and hit User::all() phpstorm and others complete this as \Illuminate\Database\Eloquent\Collection|\static[]  instead if the model annotation helper simply adds 

```
 * @method static \Illuminate\Database\Eloquent\Collection|\User[] all()
```

it will auto complete properly.

**Comment by mfn** [comment]
@barryvdh modern IDEs natively support this (method is "physical" => `\Illuminate\Database\Eloquent\Model::all`), there's nothing actionable for ide-helper here => this can be closed :}
