### ISSUE TITLE
Conflicts with another require

### ISSUE THREAD

**Issue by ameer8f26** [barryvdh/laravel-ide-helper#1302]
### Versions:
- ide-helper Version: ^2.11
- Laravel Version: #.#.# 
- Lumen Version: #.#.# 
- PHP Version: #.#.#

### Question:

**A little help here....** 

`Root composer.json requires barryvdh/laravel-ide-helper ^2.11 -> satisfiable by barryvdh/laravel-ide-helper[v2.11.0].`

`- barryvdh/laravel-ide-helper v2.11.0 requires illuminate/console ^8 -> found illuminate/console[v8.0.0, ..., v8.80.0]
but these were not loaded, likely because it conflicts with another require.`

**Comment by ameer8f26** [comment]
{
    "name": "laravel-adminpanel/",
    "description": "The Laravel .",
    "keywords": [
        "framework",
        "laravel",
        "boilerplate",
        "adminpanel",
        "rest-api"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.1.3",
        "beyondcode/laravel-self-diagnosis": "^1.2",
        "creativeorange/gravatar": "~1.0",
        "davejamesmiller/laravel-breadcrumbs": "^5.0",
        "doctrine/dbal": "^2.9",
        "fideloper/proxy": "^4.0",
        "hieu-le/active": "7.x",
        "keithbrink/amazon-mws-laravel": "^7.0",
        "kodeine/laravel-meta": "dev-master",
        "laravel/framework": "^7.0",
        "laravel/passport": "~9.0",
        "laravel/socialite": "^5.2",
        "laravel/telescope": "^3.0",
        "laravel/tinker": "^2.6",
        "laravel/ui": "2.0",
        "laravelcollective/html": "^6.2",
        "maatwebsite/excel": "^3.1",
        "mcs/amazon-mws": "^0.1.26",
        "phpoffice/phpspreadsheet": "^1.18.0",
        "predis/predis": "^1.1",
        "sonnenglas/laravel5-amazon-mws": "^5.0",
        "spatie/array-to-xml": "^2.16",
        "spatie/laravel-permission": "^4.0",
        "spatie/laravel-sluggable": "^2.1",
        "unisharp/laravel-filemanager": "~1.8",
        "yajra/laravel-datatables-buttons": "^4.0",
        "yajra/laravel-datatables-html": "^4.0",
        "yajra/laravel-datatables-oracle": "~9.0"
    },
    "require-dev": {
        "bvipul/generator": "^5.8.1",
        "codedungeon/phpunit-result-printer": "^0.19.10",
        "filp/whoops": "~2.0",
        "friendsofphp/php-cs-fixer": "^2.10",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "1.2.2",
        "nunomaduro/larastan": "^0.7.0",
        "phpunit/phpunit": "~7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories",
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/Helpers/helpers.php",
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "classmap": [
            "tests/TestCase.php"
        ],
        "files": [
            "tests/Utilities/helpers.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "clear-all": [
            "@php artisan clear-compiled",
            "@php artisan cache:clear",
            "@php artisan route:clear",
            "@php artisan view:clear",
            "@php artisan config:clear",
            "composer dumpautoload -o"
        ],
        "cache-all": [
            "@php artisan config:cache",
            "@php artisan route:cache"
        ],
        "cc": [
            "composer clear-all",
            "composer cache-all"
        ],
        "format": [
            "./vendor/bin/php-cs-fixer fix app/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix config/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix database/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix resources/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix routes/  --show-progress=estimating",
            "./vendor/bin/php-cs-fixer fix tests/  --show-progress=estimating"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by mfn** [comment]
You did not paste the full output and your composer.json has some bugs making it not by just copying pasting.

Read this, and try it out:
> `You can also try re-running composer require with an explicit version constraint, e.g. "composer require barryvdh/laravel-ide-helper:*" to figure out if any version is installable, or "composer require barryvdh/laravel-ide-helper:^2.1" if you know which you need.`
