### ISSUE TITLE
Laravel 9.0

### ISSUE THREAD

**Issue by gofish543** [barryvdh/laravel-ide-helper#1303]
With the release of Laravel 9.0 coming within a week or two; what is the release schedule looking like for this package? Would you like any help?

**Comment by barryvdh** [comment]
What is the problem with Laravel 9? It should have been added in https://github.com/barryvdh/laravel-ide-helper/pull/1297 already. Please try the latest dev version with v9 and create an issue if you encounter some issue.

**Comment by mfn** [comment]
We may as well cut a new release, would make sense to me.

@barryvdh WDYT https://github.com/barryvdh/laravel-ide-helper/pull/1304 ?

**Comment by mfn** [comment]
@gofish543 [we just released 2.12.0 with L9 support 🤞🏼 ](https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.12.0)

**Comment by gofish543** [comment]
I didn't do enough research! I completely missed the latest dev version. Thank you!
