### ISSUE TITLE
Is @mixin \Eloquent necessary for model classes?

### ISSUE THREAD

**Issue by rwdevguy** [barryvdh/laravel-ide-helper#1309]
### Versions:
- ide-helper Version: 2.12
- PHP Version: 8.0.14

### Question:

Is there any benefit in adding `@mixin \Eloquent` to model classes?
I only ask because `Eloquent` is just a facade for `\Illuminate\Database\Eloquent\Model::class` which the model will already be extending. 

Also, this seems to require the `ide-helper:generate` command to have run for the facade to be resolved.

Previous mention: https://github.com/barryvdh/laravel-ide-helper/issues/811#issuecomment-667159676

If there isn't any benefit to it being included, I'd be more that happy to create a PR :)

**Comment by mridul89** [comment]
It is needed to autocomplete `\Illuminate\Database\Eloquent\Builder` class methods such as `where` or `find`

Example- `User::where('id', 1)` or `User::find(1)`
