### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by dvlpr91** [barryvdh/laravel-ide-helper#1318]
### Versions:
- ide-helper Version: 2.12.2
- Laravel Version: 9.0.2
- PHP Version: 8.1

![image](https://user-images.githubusercontent.com/40349371/153798814-b3f0e45e-87d6-491e-9f0d-0336ee37535a.png)

The above code works normally.

As in the written code, when a variable is created through a pointer, an error is displayed.

This may be a problem with the language server, not with this package.

What should I do?

**Comment by mfn** [comment]
Looks like a VC / intelephense extension thing to me rather than ide-helper

**Comment by dvlpr91** [comment]
I think "coc-phpls" is the problem.

**Comment by dvlpr91** [comment]
https://github.com/marlonfan/coc-phpls/issues/108
