### ISSUE TITLE
Class 'Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider' not found

### ISSUE THREAD

**Issue by Capellaro** [barryvdh/laravel-ide-helper#132]
Hello,

Following the steps to install your lib, I keep getting this error typing `php artisan` :

```
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider' not found","file":"\/Users\/alexandre\/Documents\/Dev\/accred\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":158}}
```

**Comment by aaronsturm** [comment]
I've gone through the same steps and I'm encountering the same issue.

**Comment by aaronsturm** [comment]
@AlexCapi  - I had the same issue. I was running php artisan ide-helper:generate from the wrong directory. I included Laravel as a sub-directory of an existing project to transition. I hope that helps.

**Comment by ReyzWB** [comment]
I got same problem here, laravel 4.

**Comment by alfonsan** [comment]
I'm having right now the same issue. I use dompdf, Ide-helper and debugbar, the three of them suddenly not being added to the autoload_classmap.php on Laravel 4.x. Not happening with other packages, only with those from you.

**Comment by erlangp** [comment]
@Capellaro using Heroku?
https://github.com/barryvdh/laravel-ide-helper/issues/813#issuecomment-521936098

**Comment by Capellaro** [comment]
> @Capellaro using Heroku?
> [#813 (comment)](https://github.com/barryvdh/laravel-ide-helper/issues/813#issuecomment-521936098)

2015
