### ISSUE TITLE
date and datetime casting is not always recognized

### ISSUE THREAD

**Issue by FLeudts** [barryvdh/laravel-ide-helper#1322]
### Versions:
- ide-helper Version: v2.12.2
- Laravel Version: v8.81.0
- PHP Version: 8.0.13

### Description:
Carbon Date casting is not recognized if the string representation is defined for that attribute. 
[Laravel Documentation](https://laravel.com/docs/8.x/eloquent-mutators#date-casting)

### Steps To Reproduce:
```
protected $casts = [
        'valid_from' => 'date:Y-m-d',
        'valid_until' => 'date:Y-m-d',
 ];
```
This results in a property mixed typehint.

```
@property mixed $valid_from
@property mixed $valid_until
```

**Comment by mfn** [comment]
We're open to PRs!

**Comment by jamespavett** [comment]
Same issue with datetime

```
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'start_time' => 'datetime:H:i'
    ];
```

This gets output as the below instead of string

 * @property \datetime|null $start_time

**Comment by jamespavett** [comment]
Looking at the ModelsCommand file

```
    case 'date':
    case 'datetime':
        $realType = $this->dateClass;
        break;
```

It seems to be just assuming date/datetime will be dateClass format, when a format can be supplied when defining them that turns them into strings

**Comment by FLeudts** [comment]
But it shouldn't be output as string. The property is a Carbon instance until the model gets serialized. 
Then the definition takes over and the string is formated according to the definition.
But yes it also shouldn't be marked as a datetime.

**Comment by jamespavett** [comment]
It is definitely getting output as a string for me:

Class definition:

```
class Test extends Model
{

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'ddate' => 'datetime:d/m/Y',
        'start_time' => 'datetime:H:i',
    ];

```

Then running the below command:

` dd(\App\Models\TransportPlan\OpsClock::all()->first());`

Output:

![image](https://user-images.githubusercontent.com/10764464/155982791-e75384ab-dad5-4584-9d82-a2a3f6a653b9.png)

Notice in output both show as strings

**Comment by jamespavett** [comment]
Is this not because of the difference in supplying datetime vs datetime:d/m/Y

**Comment by FLeudts** [comment]
yes that is a serialization, which turns the object into a string. But in code you could do something like

```
$this->date->addMonth();
```

So you can still use the Carbon methods. Look for yourself in xdebug if it is immediately turned into a string.

**Comment by jamespavett** [comment]
So ideally then it should output Carbon|string|null ?

**Comment by FLeudts** [comment]
No it should output Carbon|null. The same as a normal date cast.
The serialization of the Carbon instance is not relevant for type hinting as in code it always will be Carbon or null.
