### ISSUE TITLE
laravel-ide-helper doesn't work with Laravel 5

### ISSUE THREAD

**Issue by cavedanus** [barryvdh/laravel-ide-helper#133]
Hi Barry,
thank you for building laravel-ide-helper, it's very precious for every laravel artisan ;-).
I've found some issues about problems of helper with version 5 of Laravel,
I read  I read something about the using, but haven't understood where and how change the use statements.
I'm a Newbie in Laravel: can you explane me how to make usable the helper with version 5.

Thank you previously fo your kind response.

**Comment by mfn** [comment]
@barryvdh can be closed, we don't support Laravel 5 anymore :}
