### ISSUE TITLE
Running ide-helper-generate in post-autoload-dump

### ISSUE THREAD

**Issue by TheFrankman** [barryvdh/laravel-ide-helper#1335]
### Versions:
- ide-helper Version: v3.6.6
- Laravel Version: 8.x 
- PHP Version: 8.1

### Question:

This isn't really an issue with the package but rather a composer questions. In the composer `post-autoload-dump` scripts we are running `@php artisan ide-helper:generate` and `@php artisan ide-helper:meta` so that these are always kept up to date. The issue is that `post-autoload-dump` is run when using `composer install --no-dev` - In this event obviously the ide helper package is not installed so it breaks the execution.

Do you know if there is a way to have a separate  `post-autoload-dump` when running dev and when not running dev. Here is the section for your reference. We obviously don't want to use the `--no-scripts` option because we need other things to execute.

```
"scripts": {
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover --ansi",
      "@php artisan ide-helper:generate",
      "@php artisan ide-helper:meta"
    ],
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@php artisan key:generate --ansi"
    ],
    "test": "./vendor/bin/phpunit"
  }
```

**Comment by Synatiic** [comment]
Hi @TheFrankman,

i fixed this by checking for the APP_ENV environment variable. There might be a better way, but this works for me. In my case the variable will be set by a docker argument during the image creation.

```
"if [[ ${APP_ENV} == \"local\" ]]; then php artisan ide-helper:generate; fi",
"if [[ ${APP_ENV} == \"local\" ]]; then php artisan ide-helper:meta; fi",
```

**Comment by olivsinz** [comment]
My solution:

``` 
"post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "[ -f .env ] && php artisan ide-helper:generate",
            "[ -f .env ] && php artisan ide-helper:models --nowrite",
            "[ -f .env ] && php artisan ide-helper:meta"
        ]
    },
```
