### ISSUE TITLE
Could not find package barryvdh/laravel-ide-helper

### ISSUE THREAD

**Issue by 4927525** [barryvdh/laravel-ide-helper#1341]
### Versions:
- ide-helper Version: lastest
- Laravel Version: 5.8
- PHP Version: 7.3.9

### Description:

$ composer require --dev barryvdh/laravel-ide-helper

In PackageDiscoveryTrait.php line 362:

  Could not find package barryvdh/laravel-ide-helper. It was however found vi
  a repository search, which indicates a consistency issue with the repositor
  y.

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

### Steps To Reproduce:
$ composer require --dev barryvdh/laravel-ide-helper

In PackageDiscoveryTrait.php line 362:

  Could not find package barryvdh/laravel-ide-helper. It was however found vi
  a repository search, which indicates a consistency issue with the repositor
  y.

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
- …

**Comment by mfn** [comment]
Can't reproduce on a clean composer.json; are you able to share yours?

**Comment by 4927525** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-openssl": "*",
        "alibabacloud/sdk": "^1.8",
        "cyd622/laravel-admin-ext-echarts": "^1.0",
        "elasticsearch/elasticsearch": "^7.8",
        "encore/laravel-admin": "^1.8",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.5",
        "intervention/image": "^2.5",
        "jacobcyl/ali-oss-storage": "^2.1",
        "laravel-admin-ext/grid-lightbox": "^1.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "maatwebsite/excel": "^3.1",
        "mews/captcha": "^3.1",
        "php-amqplib/php-amqplib": "^3.0",
        "phpoffice/phpspreadsheet": "^1.17",
        "predis/predis": "^1.1",
        "ramsey/uuid": "^3.7",
        "symfony/translation-contracts": "^1.1.7",
        "toplan/laravel-sms": "~2.6",
        "tymon/jwt-auth": "^1.0",
        "workerman/mysql": "^1.0",
        "zzy0708/systemgreen": "^2.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "files": [
            "app/Library/Common.php",
            "app/Library/Sms.php",
            "app/Library/HttpRequest.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.phpcomposer.com"
        }
    }
}

**Comment by mfn** [comment]
With that composer.json I only get
```
+ $ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires alibabacloud/sdk, it could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires cyd622/laravel-admin-ext-echarts, it could not be found in any version, there may be a typo in the package name.
  Problem 3
    - Root composer.json requires elasticsearch/elasticsearch, it could not be found in any version, there may be a typo in the package name.
  Problem 4
    - Root composer.json requires encore/laravel-admin, it could not be found in any version, there may be a typo in the package name.
  Problem 5
    - Root composer.json requires fideloper/proxy, it could not be found in any version, there may be a typo in the package name.
  Problem 6
    - Root composer.json requires guzzlehttp/guzzle, it could not be found in any version, there may be a typo in the package name.
  Problem 7
    - Root composer.json requires intervention/image, it could not be found in any version, there may be a typo in the package name.
  Problem 8
    - Root composer.json requires jacobcyl/ali-oss-storage, it could not be found in any version, there may be a typo in the package name.
  Problem 9
    - Root composer.json requires laravel-admin-ext/grid-lightbox, it could not be found in any version, there may be a typo in the package name.
  Problem 10
    - Root composer.json requires laravel/framework, it could not be found in any version, there may be a typo in the package name.
  Problem 11
    - Root composer.json requires laravel/tinker, it could not be found in any version, there may be a typo in the package name.
  Problem 12
    - Root composer.json requires maatwebsite/excel, it could not be found in any version, there may be a typo in the package name.
  Problem 13
    - Root composer.json requires mews/captcha, it could not be found in any version, there may be a typo in the package name.
  Problem 14
    - Root composer.json requires php-amqplib/php-amqplib, it could not be found in any version, there may be a typo in the package name.
  Problem 15
    - Root composer.json requires phpoffice/phpspreadsheet, it could not be found in any version, there may be a typo in the package name.
  Problem 16
    - Root composer.json requires predis/predis, it could not be found in any version, there may be a typo in the package name.
  Problem 17
    - Root composer.json requires ramsey/uuid, it could not be found in any version, there may be a typo in the package name.
  Problem 18
    - Root composer.json requires symfony/translation-contracts, it could not be found in any version, there may be a typo in the package name.
  Problem 19
    - Root composer.json requires toplan/laravel-sms, it could not be found in any version, there may be a typo in the package name.
  Problem 20
    - Root composer.json requires tymon/jwt-auth, it could not be found in any version, there may be a typo in the package name.
  Problem 21
    - Root composer.json requires workerman/mysql, it could not be found in any version, there may be a typo in the package name.
  Problem 22
    - Root composer.json requires zzy0708/systemgreen, it could not be found in any version, there may be a typo in the package name.
  Problem 23
    - Root composer.json requires beyondcode/laravel-dump-server, it could not be found in any version, there may be a typo in the package name.
  Problem 24
    - Root composer.json requires filp/whoops, it could not be found in any version, there may be a typo in the package name.
  Problem 25
    - Root composer.json requires fzaninotto/faker, it could not be found in any version, there may be a typo in the package name.
  Problem 26
    - Root composer.json requires mockery/mockery, it could not be found in any version, there may be a typo in the package name.
  Problem 27
    - Root composer.json requires nunomaduro/collision, it could not be found in any version, there may be a typo in the package name.
  Problem 28
    - Root composer.json requires phpunit/phpunit, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
