### ISSUE TITLE
Autocompletion for Model methods is not avaliable

### ISSUE THREAD

**Issue by abelharisov** [barryvdh/laravel-ide-helper#1342]
### Versions:
- ide-helper Version: 2.12.2
- Laravel Version: 9.4.1
- PHP Version: 8.1

### Description:
Autocompletion is not available for some methods.

![image](https://user-images.githubusercontent.com/6592868/163394266-eb017234-7329-46f5-8494-fd5081ce31a3.png)

Commands used to generate helpers:
```
  artisan ide-helper:generate
  artisan ide-helper:models -M
  artisan ide-helper:meta
```

**Comment by mfn** [comment]
I can't reproduce this, `models -M` and `meta` generate the files which allow my models to autocomplete `::whereHas` for me

**Comment by redelschaap** [comment]
Same issue here. My IDE can't see all the "regular" query builder methods anymore (like `find()` or `first()`).

I am using:
* PHP 8.0
* Laravel 8.83.9
* IDE Helper 2.12.3

**Comment by FatBoyXPC** [comment]
@mfn do you have `@mixin \Eloquent` next to `@mixin IdeHelperFoo` or in the `_ide_helper_models.php` list of methods/properties for the `Foo` model? If so, that's why this is working for you. I'm on ide-helper 2.12.3 and I don't see `@mixin \Eloquen` anywhere, nor do the classes defined in `_ide_helper_models.php` extend `\Eloquent` like the file used to in the past.

**Comment by SkoricIT** [comment]
Doing `ide-helper:eloquent` and after that re-doing `ide-helper:models -M` fixed the issue for me. `\Eloquent` is now in the models file.

**Comment by FatBoyXPC** [comment]
Oh wow, I didn't realize `ide-helper:eloquent` was a thing! Thank you!

**Comment by SkoricIT** [comment]
@barryvdh Thanks!

**Comment by radcloudcorp** [comment]
No configuration I make can work here, the options always look like this without showing the rest:

![Screenshot 2024-02-20 at 16 21 54](https://github.com/barryvdh/laravel-ide-helper/assets/52583350/f76f4129-df1f-4738-8a34-f26b7fbe4172)
