### ISSUE TITLE
Model methods are missing with `--write-mixin`

### ISSUE THREAD

**Issue by ptrkcsk** [barryvdh/laravel-ide-helper#1343]
### Versions:
- ide-helper Version: 2.12.3
- Laravel Version: 9.9.0
- PHP Version: 8.1.3

### Description:

Model methods are missing when using `--write-mixin`

| With `--write-mixin` | Without `--write-mixin` |
|---|---|
| ![](https://user-images.githubusercontent.com/4766244/164059464-1dbb2965-cc54-4c8f-b960-fc309af8d824.png) | ![](https://user-images.githubusercontent.com/4766244/164059527-7029f385-2975-41d8-862f-55cd812d33c8.png) |

Basic model methods like `find` appear to be missing when using `--write-mixin`. They work correctly without `--write-mixin`

I've reproduced the following steps in this repo: https://github.com/ptrkcsk/laravel-ide-helper-models

There are two differences in `_ide_helper_models.php` between using `--write-mixin` and not, as seen here: https://github.com/ptrkcsk/laravel-ide-helper-models/compare/write-mixin...no-write-mixin

1. The generated class has `@mixin IdeHelperUser`. This looks like a mistake to me because `IdeHelperUser` appears to not exist
1. The generated class extends `\Eloquent`. I suspect this is the problem, because with `--write-mixin`, the generated class is missing the methods provided by `\Eloquent`

### Steps To Reproduce:

1. Generate facades helper and models helper with `--write-mixin`:

    ```sh
    vendor/bin/sail artisan ide-helper:generate
    vendor/bin/sail artisan ide-helper:models --write-mixin
    ```
   
1. Try to use a model's `find` method, e.g. `User::find()`. Notice "Method 'find' not found..." warning in IDE

1. Re-generate models helper without `--write-mixin`:

    ```sh
    vendor/bin/sail artisan ide-helper:models
    ```
   
1. Try to use a model's `find` method again. Notice `find` method is now found

**Comment by abelharisov** [comment]
I faced with the same [issue](https://github.com/barryvdh/laravel-ide-helper/issues/1342)
