### ISSUE TITLE
--dir setting ignored

### ISSUE THREAD

**Issue by sebastiaanluca** [barryvdh/laravel-ide-helper#137]
Just noticed the `--dir` setting is ignored when doing the following:

``` bash
php artisan ide-helper:models --dir="app/models/offices"
```

It just scans everything in `app/models` and writes documentation to **all** the models, as by default.

I assume setting the `--dir` should result in only that directory being scanned and getting PHPDocs written to the models?

**Comment by comdexxsolutionsllc** [comment]
This doesn't work for me also.  Looking into the code php artisan ide-helper models command looks by default at the app/ directory for Laravel 5 (which it should), but it still doesn't output anything (for example, for my Users table)

**Comment by mfn** [comment]
> I assume setting the `--dir` should result in only that directory being scanned

No, the implementation is _additive_, i.e. it _adds_ the given directory to the existing ones. And we can't easily change this, [it has been this for ~7 years](https://github.com/barryvdh/laravel-ide-helper/blame/107fda3c208ff56c0fdbd6c37fa38b8a99243b3c/src/Barryvdh/LaravelIdeHelper/ModelsCommand.php).

What's your use-case for having this _override_ the config `model_locations`?

A possible solution with the current implementation could be (untested):
- let `model_locations` but the a directory having no models
- then `--dir` could only scan the provided directory anyway

**Comment by joelstein** [comment]
In case anyone else stumbles on this, I can confirm that publishing the config and setting `model_locations` to an empty array works. Then, you can use the `--dir` option to focus the model generation only on that directory.
