### ISSUE TITLE
New Laravel attributes are not correctly recognized when method is protected

### ISSUE THREAD

**Issue by bbprojectnet** [barryvdh/laravel-ide-helper#1378]
### Versions:
- ide-helper Version: 2.12.3
- Laravel Version: 9.29.0
- PHP Version: 8.1

### Description:

Only `public` and type casted get/set methods attributes are detected.

But, according to https://laravel.com/docs/9.x/eloquent-mutators mutator method should be `protected`.

Also, it would be nice if ide helper supported the generic attribute declaration, like that:
```php
	/**
	 * Name attribute.
	 *
	 * @return \Illuminate\Database\Eloquent\Casts\Attribute<string, never>
	 */
	protected function name(): Attribute
	{
		return Attribute::make(
			get: fn () => 'foo',
		);
	}
```
if the get/set methods do not have a return type specified.

**Comment by gajosadrian** [comment]
Yes, it's a new missing feature in ide-helper... the code is located in:
https://github.com/barryvdh/laravel-ide-helper/blob/dda200fd34d2b9151bd6d9ddecaeb421978d6b99/src/Console/ModelsCommand.php#L570
but currently I don't have time to fix it.

**Comment by Derhelios66** [comment]
The problem should already be fixed with this commit https://github.com/barryvdh/laravel-ide-helper/commit/39885645b91b0266290fce03bbfd155a67bb2e27. But since then there was no release.

**Comment by marc31** [comment]
Hey, thanks for fixing this bug. I have one remaining question though. Suppose an attribute returns a collection of Post objects, how should I type hint it?

```php
protected function filteredPosts(): Attribute
{
    return Attribute::make(
        /**
         * @return \Illuminate\Database\Eloquent\Collection<int, \App\Models\Post>
         */
        get: function (): {
            return $this->post->where('post_online');
        }
    );
}
```

I'd like to ensure the correct typing for this scenario. Thanks in advance for your assistance!

**Comment by marc31** [comment]
it's being inferred as @mixed.

**Comment by omaressaouaf** [comment]
@mfn @Derhelios66  Just to confirm on @marc31 answer, the `mixed` type is the only inferred type for the new accessor/mutators even if we docblock the attribute with a generic type like @marc31 did

**Comment by mwargan** [comment]
I see the same thing - still being inferred as mixed, with the following example:
```php
    /**
     * Attribute that gets the Socialite instance.
     *
     * @return Attribute<\Laravel\Socialite\Contracts\Provider, void>
     */
    protected function socialiteInstance(): Attribute
    {
        return CastsAttribute::make(
            get: fn($value): \Laravel\Socialite\Contracts\Provider => Socialite::driver($this->provider),
        )->shouldCache();
    }
```
