### ISSUE TITLE
Attribute with collection with generic annotation return type generates incorrect PHPDoc

### ISSUE THREAD

**Issue by bbprojectnet** [barryvdh/laravel-ide-helper#1382]
### Versions:
- ide-helper Version: 2.12.3
- Laravel Version: 8.83.25
- PHP Version: 7.4

### Description:

Incorrect PHPDoc was generated for attribute with Laravel Collection with generic annotation return type, for example:

```php
	/**
	 * @return \Illuminate\Support\Collection<int, \App\Models\Answer>
	 */
	public function getAnswersAttribute(): Collection
	{
		return collect();
	}
```

result:

```php
 * @property-read \Illuminate\Support\Collection<int, $answers
```

**Comment by grEvenX** [comment]
@bbprojectnet This would improve code-completion in e.g. PHPStorm greatly. What else is needed to support this in laravel-ide-helper?

**Comment by bbprojectnet** [comment]
Hi @grEvenX,
nothing :) this bug was fixed by https://github.com/barryvdh/ReflectionDocBlock/pull/9

**Comment by grEvenX** [comment]
@bbprojectnet Hm, maybe I'm just not understanding the scope of the issue.
I was able to get updated ReflectionDocBlock but when I ran the Laravel IDE helper, the generated doc-block for models using `php artisan ide-helper:models "App\Db\User" --write --reset` still used the old formation without type-hints.

I was expecting
```
* @property-read Collection<int, \App\Db\UserFeedback> $feedbacks
```

but instead got
```
* @property-read Collection|\App\Db\UserFeedback[] $feedbacks
* ```

**Comment by bbprojectnet** [comment]
This issue is not about that :) It is talking about broken PHPDoc for **attributes** which returns Collection, but You probably have case with **model relation**. Am I right?

If yes, this PR is more accurate what You looking for: https://github.com/barryvdh/laravel-ide-helper/pull/1298 - I'm also waiting for that :)

**Comment by grEvenX** [comment]
@bbprojectnet Thanks. I guess this issue can be closed as solved then?

**Comment by bbprojectnet** [comment]
Yes.
