### ISSUE TITLE
Type-Error: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by DelDaGhost** [barryvdh/laravel-ide-helper#1397]
### Versions:
- ide-helper Version: 2.12.3
- Laravel Version: 9.42.2
- PHP Version: 8.1.13

### Description:

I updated my laravel version from 8 to 9. Since the update I always get the following error when I run:
`php artisan ide-helper:generate`

`
TypeError 

  Illegal offset type in isset or empty

  at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:216
    212▕      * @return mixed
    213▕      */
    214▕     protected static function resolveFacadeInstance($name)
    215▕     {
  ➜ 216▕         if (isset(static::$resolvedInstance[$name])) {
    217▕             return static::$resolvedInstance[$name];
    218▕         }
    219▕ 
    220▕         if (static::$app) {

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

I already reinstalled everything with composer and also cleared the composer-cache.
I also ran the command `php artisan clear-compiled`, but sadly it made no difference.

Since the error comes from the laravel-framework itself I guess this is a bug in the library?

Any help would be greatly appreciated :)

Best Regards,
Del

**Comment by MatthewLoffredo** [comment]
Hey, I'm getting this error as well on Laravel 10. Did you ever figure out how to fix it?

**Comment by DelDaGhost** [comment]
No sry,
We ended up archiving the repo for other reasons and started a fresh one with laravel 10.
With the new repo it worked.

**Comment by MatthewLoffredo** [comment]
> No sry, We ended up archiving the repo for other reasons and started a fresh one with laravel 10. With the new repo it worked.

Ok, thank you, still haven't been able to figure it out. @barryvdh Any ideas here?
