### ISSUE TITLE
Class name resolution via ::class

### ISSUE THREAD

**Issue by hongaar** [barryvdh/laravel-ide-helper#143]
Since PHP 5.5 it is possible to resolve classnames with the `::class` construct:

> It is possible to use ClassName::class to get a fully qualified name of class ClassName. For example:
> 
> ```
> <?php
> namespace Name\Space;
> class ClassName {}
> 
> echo ClassName::class;
> 
> echo "\n";
> ?>
> ```

Which is pretty awesome because of a lot of reasons (refactoring, etc.) and it makes me feel I'm writing Java (don't know if that's a good thing).

Would it be somehow possible to resolve the classname of the relationship model from this construct if needed instead of parsing the string? Tricky thing here, that the power of the `::class` construct is that we can use the `use` construct to import classes, which would make it a little more difficult to resolve the right model.

Edit 1:

The current behavior is:

```
* @property-read \Foo::class $foo
* @property-read \Illuminate\Database\Eloquent\Collection|\Bar::class[] $bar
```

Edit 2:

Looking at the above, this could probably be solved quite easily, if we change the above example to:

```
* @property-read Foo $foo
* @property-read \Illuminate\Database\Eloquent\Collection|Bar[] $bar
```

everything works as expected, as those classes will be imported/'`use`d' in this file already.

**Comment by szainmehdi** [comment]
@barryvdh Just saw this notification. Thanks for merging, glad I could help!

@hongaar Happy to help! :+1:
