### ISSUE TITLE
Incorrect PHPDoc being written to model for BelongsTo relation

### ISSUE THREAD

**Issue by calebdw** [barryvdh/laravel-ide-helper#1474]
### Versions:
- ide-helper Version: 2.13.0
- Laravel Version: 10.x
- PHP Version: 8.2.x

### Description:
Hello! 

I'm currently writing the PHPDocs to a few models and I noticed the wrong doc was being generated for the `BelongsTo` relation (and possibly other relations that return single models):

```php
/** @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\User> $createdByUser */
```

However, a `BelongsTo` relation *never* returns a collection so this instead should be:

```php
/** @property-read null|\App\Models\User $createdByUser */
```

This is causing PHPStan Level 2 to fail with:

```
  27     Access to an undefined property Illuminate\Database\Eloquent\Collection<int, App\Models\User>::$name.                                   
```
when trying to call `$model->createdByUser->name`

### Steps To Reproduce:

- Create model with `BelongsTo` relation defined
- Write PHPDocs to model

Thanks!

**Comment by CalebDW** [comment]
Turns out this was due to the following config:

```php
    'additional_relation_return_types' => [
        'belongsTo' => 'many',
    ],
```

A developer added this to prevent the model helper file generator from failing when using the Compoships]
