### ISSUE TITLE
Why are Mysql Decimal types mapped as strings?

### ISSUE THREAD

**Issue by WordsofDefiance** [barryvdh/laravel-ide-helper#1483]
https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L548

This is causing static analysis errors in my app.

**Comment by barryvdh** [comment]
If you use the decimal cast from Laravel, it will convert to string. Or are you working with floats? Because I think that would lead to more errors.

**Comment by WordsofDefiance** [comment]
I am using a `decimal(8,2)` column in the database, and the first time I ran the ide-helper, it wrote the column as a `string` in the docblock. The app expects this column to be a float. I ended up using the `custom_db_types` config to override this behavior.

I'm not using casts of any sort.

**Comment by Patabugen** [comment]
I'm having trouble with this too, I'm using a Decimal database type which I'd like to be recognised as a 'float' in PHP that phpStan doesn't get unhappy with me setting the value to a float.

I've tried 

(I can't change the decimal type at the moment, but I'm open to changing anything else)

This is the error I'm trying to resolve:

<img width="1398" alt="image" src="https://github.com/barryvdh/laravel-ide-helper/assets/196795/0a2a8b52-b8a7-4c6a-accd-3eed87a33bb6">

ide-helper outputs string, even if I try casting it to Decimal (as suggested above).

<img width="575" alt="image" src="https://github.com/barryvdh/laravel-ide-helper/assets/196795/69c3b280-2d88-4bc4-831a-c5af7e1fa376">

<img width="349" alt="image" src="https://github.com/barryvdh/laravel-ide-helper/assets/196795/05f917d5-f76a-48fc-b3ca-94a2c623541f">
