### ISSUE TITLE
ide-helper:models fails to fetch database data if $table property has database prefix

### ISSUE THREAD

**Issue by shuergab** [barryvdh/laravel-ide-helper#1487]
### Versions:
- ide-helper Version: 2.13.0
- Laravel Version: 10.34.2
- PHP Version: 8.2

### Description:
I have multiple databases on the same connection, so my models have database prefix. If i run php artisan ide-helper:models the models with a prefix won't work, but if I change default database and remove the prefix it works.

### Steps To Reproduce:
Create a model with a $table property  with database prefix: 
$table = 'laravel.users';
run php artisan ide-helper:models "App\Models\User" -R -W
The generated phpdoc won't have the table fields
Change $table property:
$table = 'users';
run php artisan ide-helper:models "App\Models\User" -R -W
The phpdoc has now the fields

**Comment by barryvdh** [comment]
Above pr is merged
