### ISSUE TITLE
Version conflict with Laravel 9

### ISSUE THREAD

**Issue by enikeishik** [barryvdh/laravel-ide-helper#1489]
### Versions:
- ide-helper Version: last (for laravel 9)
- Laravel Version: v9.5.2
- PHP Version: 8.2.5

### Description:

Version conflict with doctrine/dbal via nesbot/carbon.

### Steps To Reproduce:

- composer create-project laravel/laravel:~9.0 laravel9
- cd laravel9
- composer require barryvdh/laravel-ide-helper

### Fix

Use nesbot/carbon v2.71.0  - `composer require nesbot/carbon:~2.71.0` before `composer require barryvdh/laravel-ide-helper`.

**Comment by iodintsovua** [comment]
The same for Laravel Framework 10.35.0

sail@a7070c02bf49:/var/www/html$ composer require --dev barryvdh/laravel-ide-helper
./composer.json has been updated
Running composer update barryvdh/laravel-ide-helper
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v10.35.0 requires nesbot/carbon ^2.67 -> satisfiable by nesbot/carbon[2.72.0].
    - barryvdh/laravel-ide-helper[v1.0.0, ..., v1.5.0] require illuminate/support 4.0.x -> found illuminate/support[v4.0.0, ..., v4.0.10] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v1.5.1, ..., v1.11.6] require illuminate/support 4.x -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.0.0, ..., v2.0.3] require illuminate/support 5.0.x -> found illuminate/support[v5.0.0, ..., v5.0.33] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.0.4, ..., v2.1.0] require illuminate/support 5.0.x|5.1.x -> found illuminate/support[v5.0.0, ..., v5.1.41] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.1.1, ..., v2.1.4] require illuminate/support 5.0.x|5.1.x|5.2.x -> found illuminate/support[v5.0.0, ..., v5.2.45] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.2.0, ..., v2.2.2] require illuminate/support ^5.0,<5.4 -> found illuminate/support[v5.0.0, ..., v5.3.23] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.2.3, ..., v2.3.2] require illuminate/support ^5.0,<5.5 -> found illuminate/support[v5.0.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.4.0, ..., v2.4.1] require illuminate/support ^5.0,<5.6 -> found illuminate/support[v5.0.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.4.2, ..., v2.4.3] require illuminate/support ^5.0,<5.7 -> found illuminate/support[v5.0.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.5.0, ..., v2.5.3] require illuminate/support ^5.5,<5.8 -> found illuminate/support[v5.5.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.6.0, ..., v2.6.2] require illuminate/support ^5.5,<5.9 -> found illuminate/support[v5.5.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.6.3, ..., v2.6.6] require illuminate/support ^5.5|^6 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.6.7, ..., v2.7.0] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper v2.8.0 requires illuminate/console ^5.5 || ^6 || ^7 -> found illuminate/console[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.8.1, ..., v2.8.2] require illuminate/console ^6 || ^7 || ^8 -> found illuminate/console[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.9.0, ..., v2.11.0] require illuminate/console ^8 -> found illuminate/console[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.12.0, ..., v2.12.3] require illuminate/console ^8 || ^9 -> found illuminate/console[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - doctrine/dbal[v2.6.0, ..., v2.9.3] require php ^7.1 -> your php version (8.2.13) does not satisfy that requirement.
    - doctrine/dbal[v2.10.0, ..., 2.10.4] require php ^7.2 -> your php version (8.2.13) does not satisfy that requirement.
    - doctrine/dbal[2.11.0, ..., 2.11.3] require php ^7.3 -> your php version (8.2.13) does not satisfy that requirement.
    - laravel/framework is locked to version v10.35.0 and an update of this package was not requested.
    - barryvdh/laravel-ide-helper v2.13.0 requires doctrine/dbal ^2.6 || ^3 -> satisfiable by doctrine/dbal[v2.6.0, ..., 2.13.9, 3.0.0, ..., 3.7.2].
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.7.2.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.4.6.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.3.8.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.3.5.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.2.2.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.1.5.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.1.0.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 3.0.0.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 2.13.9.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 2.13.8.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 2.13.1.
    - carbonphp/carbon-doctrine-types 3.0.0 conflicts with doctrine/dbal 2.12.1.
    - nesbot/carbon 2.72.0 requires carbonphp/carbon-doctrine-types * -> satisfiable by carbonphp/carbon-doctrine-types[3.0.0].
    - Root composer.json requires barryvdh/laravel-ide-helper * -> satisfiable by barryvdh/laravel-ide-helper[v1.0.0, ..., v1.11.6, v2.0.0, ..., v2.13.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require barryvdh/laravel-ide-helper:*" to figure out if any version is installable, or "composer require barryvdh/laravel-ide-helper:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
