### ISSUE TITLE
Response:: AutoComplete not working

### ISSUE THREAD

**Issue by Kussie** [barryvdh/laravel-ide-helper#149]
I'm having a strange issue with Autocomplete in PHPStorm 8.0.2 and Laravel 4.2  most of the Laravel facades are coming through the auto complete fine (Input, HTML etc all seem to work), but Response doesn't seem to be working at all.

When typing Response:: the only suggested option is "class".  All of my controllers are namespaced and this occurs both with a "use Response;" at the top of the model or through "\Response::"

**Comment by barryvdh** [comment]
Do you import just 'Response' or the full Response class?

**Comment by Kussie** [comment]
At the moment I am just Importing 'Response', which is also what i am doing for 'Input'.

Input works fine however, if i take a look at the _ide_helper.php file, the details for the Response Facade is completely blank:
```PHP
class Response extends \Illuminate\Support\Facades\Response{
        
}
```

Whilst others like Input etc, are fully fleshed out.

**Comment by mfn** [comment]
@Kussie is this still an issue?
