### ISSUE TITLE
Installation error on latest laravel installation

### ISSUE THREAD

**Issue by mdinopol** [barryvdh/laravel-ide-helper#1498]
### Versions:
- ide-helper Version: 2.13
- Laravel Version: 10.10
- PHP Version: 8.2

### Question:
I've been using this package for almost all my laravel projects and have no issue installing until now.

It generates this error:

`Problem 1
    - barryvdh/laravel-ide-helper[v1.0.0, ..., v1.5.0] require illuminate/support 4.0.x -> found illuminate/support[v4.0.0, ..., v4.0.10] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v1.5.1, ..., v1.11.6] require illuminate/support 4.x -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.0.0, ..., v2.0.3] require illuminate/support 5.0.x -> found illuminate/support[v5.0.0, ..., v5.0.33] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.0.4, ..., v2.1.0] require illuminate/support 5.0.x|5.1.x -> found illuminate/support[v5.0.0, ..., v5.1.41] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.1.1, ..., v2.1.4] require illuminate/support 5.0.x|5.1.x|5.2.x -> found illuminate/support[v5.0.0, ..., v5.2.45] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.2.0, ..., v2.2.2] require illuminate/support ^5.0,<5.4 -> found illuminate/support[v5.0.0, ..., v5.3.23] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.2.3, ..., v2.3.2] require illuminate/support ^5.0,<5.5 -> found illuminate/support[v5.0.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.4.0, ..., v2.4.1] require illuminate/support ^5.0,<5.6 -> found illuminate/support[v5.0.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.4.2, ..., v2.4.3] require illuminate/support ^5.0,<5.7 -> found illuminate/support[v5.0.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.5.0, ..., v2.5.3] require illuminate/support ^5.5,<5.8 -> found illuminate/support[v5.5.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.6.0, ..., v2.6.2] require illuminate/support ^5.5,<5.9 -> found illuminate/support[v5.5.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.6.3, ..., v2.6.6] require illuminate/support ^5.5|^6 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.6.7, ..., v2.7.0] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper v2.8.0 requires illuminate/console ^5.5 || ^6 || ^7 -> found illuminate/console[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.8.1, ..., v2.8.2] require illuminate/console ^6 || ^7 || ^8 -> found illuminate/console[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.9.0, ..., v2.11.0] require illuminate/console ^8 -> found illuminate/console[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper[v2.12.0, ..., v2.12.3] require illuminate/console ^8 || ^9 -> found illuminate/console[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - barryvdh/laravel-ide-helper v2.13.0 requires nikic/php-parser ^4.7 -> found nikic/php-parser[v4.7.0, ..., v4.18.0] but the package is fixed to v5.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires barryvdh/laravel-ide-helper * -> satisfiable by barryvdh/laravel-ide-helper[v1.0.0, ..., v1.11.6, v2.0.0, ..., v2.13.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require barryvdh/laravel-ide-helper:*" to figure out if any version is installable, or "composer require barryvdh/laravel-ide-helper:^2.1" if you know which you need.
`
I tried specifying:
- `composer require --dev barryvdh/laravel-ide-helper:^2.1`
- `composer require --dev barryvdh/laravel-ide-helper:*`

but still no luck.

Is this because of the latest laravel version?

EDIT: I really think this is because of the latest laravel version. I checked my other laravel projects' composer.lock, nikic/php-parser's version is locked to 4.17 but the latest laravel version's locked to 5.0

**Comment by chiroruxx** [comment]
I tried this command and it worked. (but it is a workaround...)

```shell
composer require --dev nikic/php-parser:^4.7
composer require --dev barryvdh/laravel-ide-helper
```

**Comment by mdinopol** [comment]
Yeah, installing v4.7 php-parser should work because that's the required version, but latest laravel installations locked php-parser to 5.0.0, and it could have an effect to other part of the app by downgrading it. So, I think this should be fixed anyway.

**Comment by bryandease** [comment]
Having the same issue here with a fresh Laravel 10.10 app.
