### ISSUE TITLE
Modifications required to support Laravel 11

### ISSUE THREAD

**Issue by KentarouTakeda** [barryvdh/laravel-ide-helper#1509]
Hello, Laravel 11 will be released soon.

## Overview

I am using the `11.x-dev` branch under development to check the operation of Laravel IDE Helper, but there are some places where it does not work due to breaking changes on the Laravel side.

This version update will require modifications not only to `composer.json` and CI, but also to the implementation. Here is a summary of them.

### PHPUnit version upgrade

`orchestra/testbench: ^9`, which is required for testing with Laravel 11, requires `phpunit/phpunit: ^10.5`. We need to widen the version range with `require-dev`.

### Support for Doctrine DBAL removal

Related: https://github.com/laravel/framework/pull/48864

All functionality related to Doctrine DBAL has been removed. Not only does Laravel itself not use it, **public methods such as `getDoctrineSchemaManager()` have been removed**, and classes related to `Connection` have also been significantly refactored.

Laravel IDE Helper depends on many of these features, so when supporting Laravel 11 we will need to re-implement it using a different method.

### Change migration method for floating-point types

Related: https://github.com/laravel/framework/pull/48861

Some of migration methods for setting columns using a floating-point type has been changed.

The Laravel IDE Helper implementation code is not involved in the migration method, but it is referenced from the test code. Correcting is required for the relevant parts.

### Adding methods to `Authenticatable` contract

Related: https://github.com/laravel/framework/pull/48665

Implementation of `rehashPasswordIfRequired()` is now required. It is referenced as `User implements Authenticatable` in the test code, so it needs to be modified to be contract compliant.

**Comment by barryvdh** [comment]
Fixed with https://github.com/barryvdh/laravel-ide-helper/pull/1520 
Thanks for your help!
