### ISSUE TITLE
Nova Resources

### ISSUE THREAD

**Issue by Muetze42** [barryvdh/laravel-ide-helper#1527]
Is it a lot of effort to create a helper file for Nova Resources? `_ide_helper_nova-resources.php`

These should only contains the `@property` comments and not the `@method` or `@property-read` commands for each Nova resource based on `static::$model` in the resources.

**Comment by Muetze42** [comment]
Fresh created Laravel app with Nova. The default namespace for Nova resources is `App\Nova`, but I change it always
to `App\Nova\Resources`. (Similar to how it was with the models in the older Laravel versions)

The Nova resource for the User Model:

```php
class User extends Resource
{
    /**
     * The model the resource corresponds to.
     */
    public static string $model = \App\Models\User::class;
```

The extended `Resource` class an abstract class and extends another abstract class `\Laravel\Nova\Resource`.

Method `model()`:

```php
    /**
     * Get the underlying model instance for the resource.
     *
     * @return TModel|null
     */
    public function model()
    {
        return $this->resource;
    }
```

The helper file would then look something like this:

```php
<?php

// _ide_helper_nova.php

// @formatter:off
// phpcs:ignoreFile


namespace App\Nova\Resources {
    /**
     * App\Nova\Resources\User
     *
     * @property int $id
     * @property string $name
     * @property string $email
     * @property \Illuminate\Support\Carbon|null $email_verified_at
     * @property mixed $password
     * @property string|null $remember_token
     * @property \Illuminate\Support\Carbon|null $created_at
     * @property \Illuminate\Support\Carbon|null $updated_at
     */
    class User extends \App\Nova\Resources\Resource
    {
        /**
         * @return \App\Models\User|null
         */
        public function model()
        {
            return \App\Models\User::first();
        }
    }
}
```

**Comment by Muetze42** [comment]
Yes, a Nova resource is "based" on a model and is initialized with it, so a resource also has the model attributes and then also it's possible to use them in a resource for example. (Nova it self use this for the field values etc).

Like here:
https://nova.laravel.com/docs/resources/fields.html#field-help-text  
In the docs they use `$this->name` in a Nova resource and this return Model `$userModel->name`

**Comment by Muetze42** [comment]
```php
/**
 * @mixin \App\Models\User
 * @method \App\Models\User|null model()
 */
```

work

**Comment by Muetze42** [comment]
OK. It is certainly better not to include Nova in the ide-helper. Otherwise you would have to include a lot more.

I just create a simple little command that creates a Nova helper file.

**Comment by Muetze42** [comment]
For the next Nova user, my solution:

Copy the `/vendor/laravel/nova/src/Console/stubs/resource.stub` to `/stubs/nova/resource.stub`, if not already done.  
And add the `mixin` and `method` as comment:
```
<?php

namespace {{ namespace }};

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Http\Requests\NovaRequest;

/**
 * @mixin \{{ namespacedModel }}
 * @method \{{ namespacedModel }}|null model()
 */
class {{ class }} extends Resource
{
    //...
```

**Comment by nastoychev** [comment]
I tried to cover all properties from the `abstract class Resource` as follow:
```text
/**
 * @template TModel of \{{ namespacedModel }}
 *
 * @mixin TModel
 * @property-read TModel|null $resource
 * @method \{{ namespacedModel }}|null model()
 * @method static \{{ namespacedModel }} newModel()
 */
class {{ class }} extends Resource
```

**Comment by Muetze42** [comment]
Nova 5 have generics phpdocs 🎉

My App Resource:

```php
/**
 * @template TModel of \Illuminate\Database\Eloquent\Model
 *
 * @extends \Laravel\Nova\Resource<TModel>
 */
abstract class Resource extends NovaResource
```

My Model Resource:

```php
/**
 * @extends \App\Nova\Resource<\App\Models\User>
 */
class User extends Resource
```
