### ISSUE TITLE
Not working with MSSQL 2016 and below

### ISSUE THREAD

**Issue by bobonov** [barryvdh/laravel-ide-helper#1533]
### Versions:
- ide-helper Version: 3.0.0
- Laravel Version: 10.46.0
- PHP Version: 8.3
- MSsql 2016

### Description:
MSSql 2016 and below does not have string_agg() function

### Steps To Reproduce:
Just run the command for generating model on a 2016 sql server

**Comment by barryvdh** [comment]
I don't think this is an IDE helper issue, but a Laravel issue.

**Comment by bobonov** [comment]
Digging in Laravel the problem reside in Illuminate\Database\Schema\Grammars\SqlServerGrammar
