### ISSUE TITLE
MySqlGrammar: : compileColumns function for mariadb and mysql information_schema. The columns structure difference is an error

### ISSUE THREAD

**Issue by cclilshy** [barryvdh/laravel-ide-helper#1559]
### Versions:
- ide-helper Version: v3.0.0
- Laravel Version: 11.10.0
- PHP Version: 8.3.0
- MariaDB Version: 10.0.38-MariaDB

### Description:

After executing php artisan ide-helper:models, the error text reads

```text
Column not found: 1054 Unknown column 'generation_expression' in 'field list' (Connection: mysql, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'db' and table_name = 'table' order by ordinal_position asc)
```

Comparing the information_schema table in mysql8.0 shows that the generation_expression field does not exist in the corresponding mariadb table

### Steps To Reproduce:

```bash
php artisan ide-helper:models
```

**Comment by hafezdivandari** [comment]
Laravel 11 [supports MariaDB 10.3+](https://laravel.com/docs/11.x/database#introduction).

`generation_expression` column added [on MariaDB 10.2](https://mariadb.com/kb/en/changes-improvements-in-mariadb-10-2/#information-schema:~:text=two%20new%20columns%20added%20providing%20information%20about%20generated%20(virtual%2C%20or%20computed)%20columns)
