### ISSUE TITLE
Issues after Laravel 11.15

### ISSUE THREAD

**Issue by Sergiobop** [barryvdh/laravel-ide-helper#1572]
### Versions:
- ide-helper Version: 3.1
- Laravel Version: 11.15
- PHP Version: 8.3

### Description:
Additionally to issues like https://github.com/barryvdh/laravel-ide-helper/issues/1571, Laravel 11.15 also ruined some other _ide_helper.php methods (find, findOrFail, etc)

I think is related to https://github.com/laravel/framework/pull/51851 and https://github.com/laravel/framework/pull/52037

Before 11.15:
```
/**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array|string $columns
             * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static|static[] 
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException<\Illuminate\Database\Eloquent\Model>
             * @static 
             */            public static function findOrFail($id, $columns = [])
            {
                                /** @var \Illuminate\Database\Eloquent\Builder $instance */
                                return $instance->findOrFail($id, $columns);
            }
```

After 11.15:
```
/**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array|string $columns
             * @return \Illuminate\Database\Eloquent\($id is (\Illuminate\Contracts\Support\Arrayable<array-key, mixed>|array<mixed>) ? \Illuminate\Database\Eloquent\Collection<int, TModel> : TModel)
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException<TModel>
             * @static 
             */            public static function findOrFail($id, $columns = [])
            {
                                /** @var \Illuminate\Database\Eloquent\Builder $instance */
                                return $instance->findOrFail($id, $columns);
            }
```

Now for example this is wrong:
$pack = Pack::query()->findOrFail($packId);

Previous to 11.15: $pack: Pack|Pack[]|Builder|Builder[]|Collection|Model|null
After 11.15: $pack: |Collection|Model|null

I don't know if we have to do something to make it work again in our end.

Thanks

**Comment by joelstein** [comment]
Same here.

For example, `User::first()` returns a User object. However, after Laravel 11.15, I get an intelephense error if I try to typehint it.

> Expected type 'App\Models\User'. Found 'Illuminate\Database\Eloquent\TValue|null'.

From _ide_helper.php:

```
/**
 * Execute the query and get the first result.
 *
 * @param array|string $columns
 * @return \Illuminate\Database\Eloquent\TValue|null 
 * @static 
 */
public static function first($columns = [])
{
    /** @var \Illuminate\Database\Eloquent\Builder $instance */
    return $instance->first($columns);
}
```

**Comment by max13fr** [comment]
Hello,

Same for me, all models are viewed as Illuminate\Database\Eloquent\Builder instead of an instance of App\Models\MODELNAME.

Thanks in advance,
Max

**Comment by mengidd** [comment]
Same issue here. It seems that Laravel changed the DocBlocks for the Eloquent Builder class in Laravel 11.

It now has a template tag on the class itself `@template TModel of \Illuminate\Database\Eloquent\Model`, and it references this template on some of the methods `@return TModel`.

**Comment by tlevi101** [comment]
What worked for me is that i disabled inteliphense and i only had [this php intelisense](https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode) enabled. Then i added this phpdoc to MyModel: `@mixin \Illuminate\Database\Eloquent\Model<MyModel>` then regenerate `_ide_helper_models.php`.

**Comment by wattnpapa** [comment]
I have the same problem

**Comment by alexandre-tobia** [comment]
Same problem here

**Comment by KentarouTakeda** [comment]
I created a draft pull request #1591 to fix this issue. The tests don't pass, but the fix is ​​done.

A simple fix would require Laravel to only support versions 11.15 and later, which is a breaking change.

For compatibility, we could change the behavior depending on the running Laravel version, but because the Laravel Framework allows type changes even in minor versions, we might need to continue implementing similar version detection in the future. In my opinion, I don't recommend it.

After hearing your opinions on the versioning approach, I will complete the pull request.

**Comment by KentarouTakeda** [comment]
After further trial and error, it seemed like maintaining compatibility with versions below Laravel 11.15 would be a tough road to overcome, so I completed a pull request narrowing the supported version.

**Comment by pataar** [comment]
While the changes are really good, one thing is still working incorrectly.

Model::create(), Model::find(), Model::make() are still returning the wrong type. This is due the `\Eloquent` mixin which is not working with generics. My suggestion would still be to replace the default `@mixin \Eloquent` with `@mixin Builder<static>` which would improve the autocompletion.

Eloquent mixin:
![image](https://github.com/user-attachments/assets/a480a975-b80e-4626-94a9-9af76b048421)


Builder<static> mixin:
![image](https://github.com/user-attachments/assets/30412b5a-a135-4948-a09a-082bc3de9460)

@KentarouTakeda What do you think?

**Comment by KentarouTakeda** [comment]
Yes, I think it would be useful if it were fixed. On the other hand, I prefer to explicitly call the Eloquent Builder with `query()`.

```php
$user = User::query()->create();
// Identified as `\App\Models\User`

$user = User::create();
// Identified as `mixed`
```

In my opinion, `Model` and `Builder` are different classes even in terms of their inheritance, so I think it's better not to mix them.

By the way, the Eloquent mixin example you showed did not produce the same results in my environment. I don't know if it's Laravel or IDE Helper, but it may be written in a way that is interpreted differently depending on the editor. I use VSCode and PHP Intellephense.

![vscode-intelephense-result](https://github.com/user-attachments/assets/8d929854-0a38-4ee6-8edb-e68343b8520b)

**Comment by pataar** [comment]
> Yes, I think it would be useful if it were fixed. On the other hand, I prefer to explicitly call the Eloquent Builder with `query()`.
> 
> ```
> $user = User::query()->create();
> // Identified as `\App\Models\User`
> 
> $user = User::create();
> // Identified as `mixed`
> ```
> 
> In my opinion, `Model` and `Builder` are different classes even in terms of their inheritance, so I think it's better not to mix them.
> 
> By the way, the Eloquent mixin example you showed did not produce the same results in my environment. I don't know if it's Laravel or IDE Helper, but it may be written in a way that is interpreted differently depending on the editor. I use VSCode and PHP Intellephense.
> 
> ![vscode-intelephense-result](https://private-user-images.githubusercontent.com/4785040/377889284-8d929854-0a38-4ee6-8edb-e68343b8520b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTc3OTEsIm5iZiI6MTcyOTQ5NzQ5MSwicGF0aCI6Ii80Nzg1MDQwLzM3Nzg4OTI4NC04ZDkyOTg1NC0wYTM4LTRlZTYtOGVkYi1lNjgzNDNiODUyMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMDc1ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmYmE5MTMyMzNkNmY5Zjg0MTAxODUwMzgyZjc5Njg2MjY4ODUwNzBmNTZkNTI1MTM2NGFhNTkxN2MwNWNlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gAduL4T-AVCuIYJs6aJhlFflto7VjQETFx_UiAE9K4E)

That might be caused due the `@mixin \Eloquent` entry. What happens if you remove that one? Does it still indicate 'mixed'?

**Comment by gyulavoros** [comment]
@pataar Would it make sense to reopen this ticket unit "create returns `Tmodel`" problem is fixed? I've just run into the same issue.

**Comment by hauthorn** [comment]
@pataar I second @gyulavoros, and would like to add that it also affects `Model::find()` and similar. Calling explicitly with `query()` every time is in conflict with the succinctness that Eloquent offers IMO.

**Comment by chack1172** [comment]
@pataar @hauthorn  I'm not sure if this is the correct way of fix this, but adding this docbloc for TModel of Eloquent class in ide-helper fix the return type in vscode:

![image](https://github.com/user-attachments/assets/47fa53d9-973a-4839-ab7b-bd9495bfba96)

single:
![image](https://github.com/user-attachments/assets/18786d1e-9125-4071-8d10-21c750a954b0)

multiple:
![image](https://github.com/user-attachments/assets/d68d6e1a-819d-4d6a-afda-819edf5b589f)

**Comment by ekateiva** [comment]
Is it really fixed in version 3.4.0? 
I see `TModel` was added in https://github.com/barryvdh/laravel-ide-helper/pull/1631
However, after [this change ](https://github.com/barryvdh/laravel-ide-helper/pull/1634/) `TModel` is not there anymore. Now it has double `TValue`
```
/**
     * 
     *
     * @template TCollection of static
     * @template TValue of static
     * @template TValue of static
     */
    class Eloquent extends \Illuminate\Database\Eloquent\Model {        /**
```

It was fine with:
```
"barryvdh/laravel-ide-helper": "dev-master#a25b9478514ef50e12a6f241d0bd93bc3c610910"
```

**Comment by barryvdh** [comment]
Ah yes. Can you try with latest dev-master? https://github.com/barryvdh/laravel-ide-helper/pull/1645

**Comment by chack1172** [comment]
@barryvdh it still needs some tweaks, to make it work templates should be passed to the method's PHPDoc implementing this change https://github.com/barryvdh/ReflectionDocBlock/pull/22 or we will get this:

![immagine](https://github.com/user-attachments/assets/a7af48b5-77f5-4775-8352-b6d740398a69)

**Comment by barryvdh** [comment]
Do you have a minimal example of what you’re trying to do? Where does chaining give incorrect results?

**Comment by barryvdh** [comment]
With me it links correctly, just using the `@mixin \Eloquent` tag.
![Screenshot 2024-12-30 at 13 42 20](https://github.com/user-attachments/assets/d8b0611c-fa5a-42d0-87fa-68e3ac24b395)

Using the Builder<static> class can work but that gives warnings about static calls when using Model::where() instead of Model::query()->where
![Screenshot 2024-12-30 at 13 45 30](https://github.com/user-attachments/assets/b595cc56-1f6d-45b3-bf00-f58773add354)

**Comment by chack1172** [comment]
@barryvdh what I was saying is that if you take a look at the _ide_helper.php file there are still some types that adds the namespace to the types of templates. For example check firstOrNew or updateOrCreate methods.

**Comment by barryvdh** [comment]
Hmm yeah, but phpstorm still accepts this for me:

![Screenshot 2024-12-30 at 15 42 30](https://github.com/user-attachments/assets/7b40ee7a-a5cd-45c1-9248-9511c99f0f41)

But I'll see what I can do.
