### ISSUE TITLE
Is this a bug...? Is this a dream...?

### ISSUE THREAD

**Issue by dvlpr91** [barryvdh/laravel-ide-helper#1578]
### Versions:
- ide-helper Version: 3.1.0
- Laravel Version: 11.19.0
- PHP Version: 8.3.7

### Question:
![image](https://github.com/user-attachments/assets/47ba52b9-55d2-4df1-bf4f-280462cbaae9)

I don't know if this is a bug or my mistake, thanks to the laravel-ide-helper which is getting weirder and weirder as I go.

Over time, the IDE will recognize this as an error, even if it was previously fine.

In the screenshot above, we see that `cookie` don't have `make` and `forever` methods.

**Comment by Tofandel** [comment]
This has nothing to do with laravel-ide-helper, which does not annotate this kind of laravel utils.

It doesn't need to because they have the correct annotations:

```
     * @return ($name is null ? \Illuminate\Cookie\CookieJar : \Symfony\Component\HttpFoundation\Cookie)
```

That might be an issue of your ide not understanding the `$name is null ?` phpdoc

**Comment by dvlpr91** [comment]
> This has nothing to do with laravel-ide-helper, which does not annotate this kind of laravel utils.
> 
> It doesn't need to because they have the correct annotations:
> 
> ```
>      * @return ($name is null ? \Illuminate\Cookie\CookieJar : \Symfony\Component\HttpFoundation\Cookie)
> ```
> 
> That might be an issue of your ide not understanding the `$name is null ?` phpdoc

Thanks for the answer.

However, my IDE at the time confirmed that there was no problem reading the phpdoc.

I don't know why, but this works again.

I'm not sure, but I expect it to be a temporary error in the IDE.
