### ISSUE TITLE
recent L5 change makes branch 2.0 don't work again, simple fix

### ISSUE THREAD

**Issue by steve3d** [barryvdh/laravel-ide-helper#158]
in most recent change of L5, the ServiceProvider::mergeConfigFrom reversed the parameter order, 

so this line should also change to
$this->mergeConfigFrom($configPath, 'ide-helper');

instead of current:
$this->mergeConfigFrom('ide-helper', $configPath);

seems this changes breaks a log l5 ready packages, include intervention/image.

**Comment by barryvdh** [comment]
Fixed
