### ISSUE TITLE
Generate `numeric-string` type for model fields with a `decimal` cast

### ISSUE THREAD

**Issue by ekisu** [barryvdh/laravel-ide-helper#1582]
### Summary

Right now, model fields with a `decimal` type cast are annotated with the `string` type. This is correct, however typing them with a `numeric-string` type would help static analysis tools to better understand the code, and also to not flag valid code as incorrect. An example would be the following code:

```php
/**
 * @property-read string $value
 */
readonly class ModelWithString {
    public function __construct(
        public string $value,
    ) {}
}

/**
 * @property-read numeric-string $value
 */
readonly class ModelWithNumericString {
    public function __construct(
        public string $value,
    ) {}
}

$a = new ModelWithString('1.23');
$result = $a->value + 3;

$b = new ModelWithNumericString('1.23');
$result2 = $b->value + 3;
```

In the above snippet, PHPStan flags the addition operation using the `ModelWithString` `value` property as invalid, but is able to check that the operation using the `ModelWithNumericString` `value` property is valid code ([link to PHPStan's playground](https://phpstan.org/r/c7a056b7-8ea6-4dfe-b455-38d2f5e1315c)).

I am willing to work on this.

**Comment by ekisu** [comment]
I managed to change the properties' types to `numeric-string` using a model hook, however I couldn't quite figure out how to keep the same nullability as the original ones :thinking:. Here's the code:
```php
class ChangeDecimalCastsToNumericString implements ModelHookInterface
{
    public function run(ModelsCommand $command, Model $model): void
    {
        $casts = $model->getCasts();

        foreach ($casts as $fieldName => $cast) {
            if (!str_starts_with($cast, 'decimal')) {
                continue;
            }

            $command->setProperty($fieldName, 'numeric-string');
        }
    }
}
```

Even if it's possible to add this behavior as a model hook, I do believe it would be useful to have it by default, as it's widely supported by static analysis tools and IDEs/LSPs.

**Comment by barryvdh** [comment]
What is the support for this type?

**Comment by ekisu** [comment]
On static analysis tools, it's supported by:
- PHPStan, for a little over 4 years ([commit](https://github.com/phpstan/phpstan-src/commit/1d27c61ede2f92774fe53b88607a893514ff1fd4))
- Psalm, since pretty much it's beginning ([history](https://github.com/vimeo/psalm/commits/dd24f5b2f06aefffa1fb492c81e3d48674bafef7/src/Psalm/Type/Atomic/TNumericString.php) dates to over 7 years)

On IDE/LSPs, it's supported by:
- Intelephense, for a little over an year ([issue](https://github.com/bmewburn/vscode-intelephense/issues/2152))
- PHPStorm, since 2020 ([feature request](https://youtrack.jetbrains.com/issue/WI-55894/numeric-string-type-marked-as-undefined-class-33))

---

On a second thought, I think that `numeric` will be more useful than `numeric-string` in this case, because the `decimal` cast allows us to write `float|int` into the property, and this isn't really allowed when using `numeric-string`, as shown in the following snippet ([link to PHPStan's playground](https://phpstan.org/r/e2a6f013-e882-4608-8838-bc17895f1a00)). Support should be pretty much the same/wider than `numeric-string`.

```php
/**
 * @property string $value
 */
class ModelWithString {
    public function __construct(
        public string $value,
    ) {}
}

/**
 * @property numeric-string $value
 */
class ModelWithNumericString {
    public function __construct(
        public string $value,
    ) {}
}

/**
 * @property numeric $value
 */
class ModelWithNumeric {
    public function __construct(
        public string $value,
    ) {}
}

$a = new ModelWithString('1.23');
$a->value = $a->value + 3;
$a->value = '4.56';
$a->value = 4.56;

$b = new ModelWithNumericString('1.23');
$b->value = $b->value + 3;
$b->value = '4.56';
$b->value = 4.56;

$c = new ModelWithNumeric('1.23');
$c->value = $c->value + 3;
$c->value = '4.56';
$c->value = 4.56;
```
