### ISSUE TITLE
Concurrency facade issue in Laravel 11.23.x?

### ISSUE THREAD

**Issue by jonnott** [barryvdh/laravel-ide-helper#1586]
### Versions:
- ide-helper Version: 3.1.0
- Laravel Version: 11.23.5
- PHP Version: 8.2.0

### Question:

After updating Laravel from 11.22.0 to 11.23.x, getting this error on `ide-helper:generate`:

```
Exception: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\MultipleInstanceManager
Skipping \Illuminate\Support\Facades\Concurrency.
```

Is this an issue with this package and the new Concurrency facade in Laravel?

**Comment by krismanning** [comment]
I'm having the exact same problem since upgrade to Laravel 11.

**Comment by luka-papez** [comment]
Same problem encountered during upgrade from Laravel 10.48 to 11.24, ide-helper 3.1.0 on PHP 8.2

**Comment by krismanning** [comment]
> Same problem encountered during upgrade from Laravel 10.48 to 11.24, ide-helper 3.1.0 on PHP 8.2
> 
> I managed to resolve it after having a look at the documentation for `Concurrency` facade:
> 
>     * https://laravel.com/docs/11.x/concurrency#concurrency-compatibility
> 
> 
> From the link:
> 
> > If you upgraded to Laravel 11.x from a Laravel 10.x application, you may need to add the ConcurrencyServiceProvider to the providers array in your application's config/app.php configuration file:

Thats fixed it. Many thanks.
