### ISSUE TITLE
PHPStan annotations for models are dropped

### ISSUE THREAD

**Issue by bbprojectnet** [barryvdh/laravel-ide-helper#1598]
PHPStan annotations (or any other description) for models are dropped, for example:

```php
/**
 * Some class.
 *
 * @implements \App\Contracts\Models\SomeContract<...>
 *
 * @property int $id
 * [...]
```

after:

```php
/**
 * Some class.
 *
 * @property int $id
 * [...]
```

Is there any way to preserve these entries? These are critical from a static analysis point of view.

**Comment by barryvdh** [comment]
Are you adding the reset flag?

**Comment by bbprojectnet** [comment]
Hi, yes.

I understand that reset resets everything :) but, the class name itself is preserved, so I would expect that the additional description (also phpstan annotations) should also be preserved.

Maybe it would be a good idea to add some tag to which ide helper does not change the description? For example:

```php
/**
 * Some class.
 *
 * More class description.
 *
 * @implements \App\Contracts\Models\SomeContract<...>
 *
 * @idehelper-ignore-before
 *
 * @property int $id
 * [...]
```

**Comment by barryvdh** [comment]
I think https://github.com/barryvdh/laravel-ide-helper/pull/1603 would be better perhaps. Just remove the property and methods tags, skip the other tags?

**Comment by bbprojectnet** [comment]
Yes, sounds good :)
