### ISSUE TITLE
Plausible error/conflict with "smart-reset" option (`php artisan ide-helper:models --write --smart-reset`)

### ISSUE THREAD

**Issue by KentarouTakeda** [barryvdh/laravel-ide-helper#1599]
### Versions:

- ide-helper Version: 3.2.0

### Description:

> Plausible error/conflict with "smart-reset" option (`php artisan ide-helper:models --write --smart-reset`):
> generics eloquent builder annotations are added over and over.

_Originally posted by @bbprojectnet in https://github.com/barryvdh/laravel-ide-helper/issues/1591#issuecomment-2423831072_

By repeatedly running the generation command, the same tags will be output multiple times in PHPDocs for models.

```php
/**
 *
 *
 * (omittion)
 * 
 * @method static \Database\Factories\UserFactory factory($count = null, $state = [])
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|\App\Models\User query()
 * (...repeat)
 * @mixin \Eloquent
 */
class User extends Authenticatable
```

### Steps To Reproduce:

1. Run `php artisan ide-helper:models`
2. A DocBlock containing `newModelQuery()`, `newQuery()`, and `query()` is written to the Model.
3. Run `php artisan ide-helper:models` again without the `--reset` option.
4. **`newModelQuery()`, `newQuery()`, and `query()` that have already been output will be output again.**
   * This will be printed every time we regenerate.

### Note: 

This is because the upstream library does not support parsing generic syntax for return types.

This is expected to be resolved by incorporating barryvdh/ReflectionDocBlock#18 into this library.

**Comment by barryvdh** [comment]
Upstream is tagged. Is this resolved?

**Comment by KentarouTakeda** [comment]
I have confirmed that the issue has actually been resolved in the published package.

---

A note for anyone who ends up here. This issue can be resolved by:

* Updating only the package that caused the issue:
  ```
  composer update barryvdh/reflection-docblock
  ```
* or updating all packages:
  ```
  composer update
  ```

Either command will resolve the issue.
