### ISSUE TITLE
Error on when processing Auth facade

### ISSUE THREAD

**Issue by superherochris** [barryvdh/laravel-ide-helper#161]
After installing the latest version, when the Auth facade is parsed the following error occurs:

PHP Fatal error:  Call to undefined method Illuminate\Support\Facades\Auth::driver() in /home/developer/sites/cbapi.local.shcc.nl/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 205

**Comment by barryvdh** [comment]
With Laravel 4? Do you have any other Auth extensions?

**Comment by superherochris** [comment]
On laravel 4.2, using the default AuthServiceProvider and facade.

**Comment by barryvdh** [comment]
Can you try with 1.11.4?

**Comment by superherochris** [comment]
Still getting the same error on 1.11.4.

Here's my providers list:

```
'Illuminate\Foundation\Providers\ArtisanServiceProvider',
		'Illuminate\Auth\AuthServiceProvider',
		'Illuminate\Cache\CacheServiceProvider',
		'Illuminate\Session\CommandsServiceProvider',
		'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
		'Illuminate\Routing\ControllerServiceProvider',
		'Illuminate\Cookie\CookieServiceProvider',
		'Illuminate\Database\DatabaseServiceProvider',
		'Illuminate\Encryption\EncryptionServiceProvider',
		'Illuminate\Filesystem\FilesystemServiceProvider',
		'Illuminate\Hashing\HashServiceProvider',
		'Illuminate\Html\HtmlServiceProvider',
		'Illuminate\Log\LogServiceProvider',
		'Illuminate\Mail\MailServiceProvider',
		'Illuminate\Database\MigrationServiceProvider',
		'Illuminate\Pagination\PaginationServiceProvider',
		'Illuminate\Queue\QueueServiceProvider',
		'Illuminate\Redis\RedisServiceProvider',
		'Illuminate\Remote\RemoteServiceProvider',
		'Illuminate\Auth\Reminders\ReminderServiceProvider',
		'Illuminate\Database\SeedServiceProvider',
		'Illuminate\Session\SessionServiceProvider',
		'Illuminate\Translation\TranslationServiceProvider',
		'Illuminate\Validation\ValidationServiceProvider',
		'Illuminate\View\ViewServiceProvider',
		'Illuminate\Workbench\WorkbenchServiceProvider',
		'Intervention\Image\ImageServiceProvider',
        'Jenssegers\Agent\AgentServiceProvider',
        'Fideloper\Proxy\ProxyServiceProvider',
        'Bkwld\CodebaseHQ\ServiceProvider',
        'Shcc\MandrillMailer\MandrillMailerServiceProvider',
'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',
        'Way\Generators\GeneratorsServiceProvider'
```

**Comment by barryvdh** [comment]
You don't overwrite any providers for your local environment? Sometimes people forget to use config_append() and overwrite the Auth provider.

**Comment by superherochris** [comment]
Nope. I only append your package and the Way generators for local (hence the rather weird indentation on my list). The rest comes from the default app.php config file.

**Comment by barryvdh** [comment]
Yes how did you append it? Using `append_config`? Or just an array?

**Comment by superherochris** [comment]
Wasn't using append_config. It works flawlessly now, sorry for the false bug report.

The strange thing is though that it has worked using the "just an array" setup in a different project. Makes me wonder what's changed.
