### ISSUE TITLE
Is ide-helper Idempotent ?

### ISSUE THREAD

**Issue by MaG21** [barryvdh/laravel-ide-helper#1612]
### Versions:
- ide-helper Version: #.#.#
- v3.1.0
- Laravel Version: #.#.#
Laravel Framework 11.23.5
- PHP Version: #.#.#
8.3.12

### Question:
Recently I made a change to a property (a type change) and after running `php artisan ide-helper:models -W` I noticed that ide-helper didn't update the corresponding type in the PHPDoc comment. I was under the impression that every new run will generate the same results regardless.

I could think of a reason or two as of why id-helper preserves the changes. Is there an option that can be used to instruct ide-helper to disregard any changes made and to rewrite the phpdoc (idempotent behaviour).

**Comment by barryvdh** [comment]
—reset? Or -RW
