### ISSUE TITLE
Update composer/class-map-generator to 1.5 to support phpstan 2.0

### ISSUE THREAD

**Issue by ysbrandB** [barryvdh/laravel-ide-helper#1628]
Currently, this package requires ["composer/class-map-generator": "^1.0"] (https://github.com/barryvdh/laravel-ide-helper/blob/4d2728c4f05ae7514e8a4761a2a8bcfaf8f55654/composer.json#L26). This version does not allow phpstan 2.0. 
Two weeks ago composer/class-map-generator was updated to allow the new version of phpstan in this commit: https://github.com/composer/class-map-generator/commit/4b0a223cf5be7c9ee7e0ef1bc7db42b4a97c9915. Therefore it would be nice if the package version could be updated here so all packages that depend on the ide-helper also can upgrade to phpstan 2.0.

**Comment by barryvdh** [comment]
That is in the require-dev section, so it wouldn't matter. Also 1.5 is supported with our requirement of ` "composer/class-map-generator": "^1.0",`
