### ISSUE TITLE
php artisan config:publish on laravel5

### ISSUE THREAD

**Issue by carlituxman** [barryvdh/laravel-ide-helper#163]
Hi at laravel5 the 
php artisan config:publish barryvdh/laravel-ide-helper
not work

the command config:publish not exist at v.5

**Comment by Ardakilic** [comment]
try 

vendor:publish

**Comment by barryvdh** [comment]
Correct, Will change the readme soon
Php artisan vendor:publish

**Comment by carlituxman** [comment]
great!, but without arguments...



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=carlos@informatik.es&idSignature=23>

2015-02-07 11:25 GMT+01:00 Barry vd. Heuvel <notifications@github.com>:

> Correct, Will change the readme soon
> Php artisan vendor:publish
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barryvdh/laravel-ide-helper/issues/163#issuecomment-73358603>
> .
>



-- 
*Carlos Jiménez Mora*
*INFORMATIK SOLUCIONES*
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman <https://twitter.com/carlituxman> - carlos@informatik.es -
www.informatik.es

*Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto.*
