### ISSUE TITLE
Composer require from readme fails for L4.2

### ISSUE THREAD

**Issue by afraca** [barryvdh/laravel-ide-helper#164]
I've noticed the readme in the Laravel 4.2 branch of this package states: 

"composer require barryvdh/laravel-ide-helper" 

But that will pull in the latest version, which is incompatible from what i've seen. Putting a version constraint in there will fix it though.

**Comment by barryvdh** [comment]
Fixed

**Comment by afraca** [comment]
Ehm, this commit should only be applied in the 1.11 branch right? ... In the 2.0 branch readme.md you do not want the constraint right?

**Comment by barryvdh** [comment]
Whoops, it's late already ;)
