### ISSUE TITLE
Atom 

### ISSUE THREAD

**Issue by Goddard** [barryvdh/laravel-ide-helper#166]
How can I get this working with Atom?  Thanks

**Comment by a-moses** [comment]
@Goddard  @barryvdh  :+1: 

plesase .

**Comment by funsterisdafunniest** [comment]
wouldn't it be more correct to post this at the atom, atom's autocomplete or autocomplete-plus page rather than here? since the thing that needs to be modified would be the editor (IDE) itself rather than the script that generates the helper

**Comment by oshanz** [comment]
:+1:

**Comment by barryvdh** [comment]
The ide-helper should be 'IDE agnostic', as it's just valid PHP. So if the autocomplete supports PHP, it should work.

**Comment by Talv** [comment]
For anyone interested in getting it working in ``php-integrator`` for atom, thumbs up & subscribe this issue php-integrator/atom-base#246

**Comment by mfn** [comment]
@barryvdh yup, should be closed as the IDE needs to support this feature => IMHO can be closed :}
