### ISSUE TITLE
Support for custom collections

### ISSUE THREAD

**Issue by Anahkiasen** [barryvdh/laravel-ide-helper#171]
Currently all relationships are said to return instances of `\Illuminate\Database\Eloquent\Collection`. Would be nice if in the configuration you could set the FQN of a custom collection class in case one is used

**Comment by barryvdh** [comment]
Would be okay with that. Do you want to write a PR?

**Comment by Anahkiasen** [comment]
Will do yeah

**Comment by genintho** [comment]
This was kind of done by https://github.com/barryvdh/laravel-ide-helper/pull/273
The logic seems to have some bugs though. Without unit test, it is hard to fix them 😞

**Comment by dmason30** [comment]
@Anahkiasen @barryvdh Im have made a related PR to cover a scenario I found #903 not sure if it is what you were after though.

**Comment by mfn** [comment]
@barryvdh Yes https://github.com/barryvdh/laravel-ide-helper/pull/903 covers this, issue can be closed :}

**Comment by mfn** [comment]
Closing per my comment https://github.com/barryvdh/laravel-ide-helper/issues/171#issuecomment-649457521
