### ISSUE TITLE
InvalidArgumentException with message 'There are no commands defined in the "ide-helper" namespace.

### ISSUE THREAD

**Issue by GiantCrocodile** [barryvdh/laravel-ide-helper#172]
Hello,

I tried to get your Laravel 5 IDE helper to work with Netbeans. This is what I did:

>composer require barryvdh/laravel-ide-helper
php artisan clear-compiled
php artisan ide-helper:generate
>php artisan optimize`

After executing `php artisan ide-helper:generate` I got this errors:
>exception 'InvalidArgumentException' with message 'There are no commands defined in the "ide-helper" namespace.' in \vendor\symfony\console\Symfony\Component\Console\Application.php:501
Stack trace:
#0 \vendor\symfony\console\Symfony\Component\Console\Application.php(535): Symfony\Component\Console\Application->findNamespace('ide-helper')
#1 \vendor\symfony\console\Symfony\Component\Console\Application.php(192): Symfony\Component\Console\Application->find('ide-helper:gene...')
#2 \vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 \vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 \artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>#5 {main}

I never did this before but I expected to receive a `_ide_helper.php` file. Can you help me please?

**Comment by ttocskcaj** [comment]
Did you add `'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',` to your service providers array in config/app.php?

**Comment by GiantCrocodile** [comment]
Thank you @ttocskcaj. That's what I was missing!

**Comment by abbood** [comment]
I tried all the answers [here](https://stackoverflow.com/questions/34865064/i-m-getting-error-class-predis-client-not-found-in-laravel-5-2).. no luck.

The weird part is that if I simply run the command
`composer update`
I get this:

    forge@development:~/default$ composer update
    Cannot create cache directory /home/forge/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
    Cannot create cache directory /home/forge/.composer/cache/files/, or directory is not writable. Proceeding without cache
    > php artisan clear-compiled
    The compiled class file has been removed.
    > php artisan ide-helper:generate
    
    
      [Symfony\Component\Debug\Exception\FatalThrowableError]
      Class 'Predis\Client' not found

running just `php artisan ide-helper:generate` gives me

      [Symfony\Component\Debug\Exception\FatalThrowableError]
      Class 'Predis\Client' not found

deleting the entire `vendor` directory then running `composer install` gives me [this output][1]. 

this is my [composer.lock][2] and my composer.json files.

running the command `composer require predis/predis` also returns the same error:

    > php artisan clear-compiled
    The compiled class file has been removed.
    > php artisan ide-helper:generate
    
    
      [Symfony\Component\Debug\Exception\FatalThrowableError]
      Class 'Predis\Client' not found

ideas?


  [1]: https://gist.github.com/abbood/7bad7c725684a5a59ed160a50db5a33b
  [2]: https://gist.github.com/abbood/6a62f5440dbb2642c70599fd5d54e78c
