### ISSUE TITLE
ide-helper:generate error on laravel 5

### ISSUE THREAD

**Issue by Cremich** [barryvdh/laravel-ide-helper#174]
Hey ho!

I am trying to setup the ide-helper on laravel 5. Unfortunately i get the following error when trying to execute the artisan command:

$ php artisan ide-helper:generate
  [InvalidArgumentException]
  There are no commands defined in the "ide-helper" namespace.

The Provider is already set in my app.php and all composer tasks are run successfully :(

	'providers' => [

        /*
		 * Laravel Framework Service Providers...
		 */
		'Illuminate\Foundation\Providers\ArtisanServiceProvider',
		'Illuminate\Auth\AuthServiceProvider',
		'Illuminate\Bus\BusServiceProvider',
		'Illuminate\Cache\CacheServiceProvider',
		'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
		'Illuminate\Routing\ControllerServiceProvider',
		'Illuminate\Cookie\CookieServiceProvider',
		'Illuminate\Database\DatabaseServiceProvider',
		'Illuminate\Encryption\EncryptionServiceProvider',
		'Illuminate\Filesystem\FilesystemServiceProvider',
		'Illuminate\Foundation\Providers\FoundationServiceProvider',
		'Illuminate\Hashing\HashServiceProvider',
		'Illuminate\Mail\MailServiceProvider',
		'Illuminate\Pagination\PaginationServiceProvider',
		'Illuminate\Pipeline\PipelineServiceProvider',
		'Illuminate\Queue\QueueServiceProvider',
		'Illuminate\Redis\RedisServiceProvider',
		'Illuminate\Auth\Passwords\PasswordResetServiceProvider',
		'Illuminate\Session\SessionServiceProvider',
		'Illuminate\Translation\TranslationServiceProvider',
		'Illuminate\Validation\ValidationServiceProvider',
		'Illuminate\View\ViewServiceProvider',

		/*
		 * Application Service Providers...
		 */
		'foo\Providers\AppServiceProvider',
		'foo\Providers\BusServiceProvider',
		'foo\Providers\ConfigServiceProvider',
		'foo\Providers\EventServiceProvider',
		'foo\Providers\RouteServiceProvider',

        'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',

	],

**Comment by barryvdh** [comment]
Can you clear your config cache etc?

**Comment by Cremich** [comment]
Wow...thanks a lot for the incredible fast reply :D 
That fixed the issue...thanks a lot.
