### ISSUE TITLE
FatalErrorException: Class not found

### ISSUE THREAD

**Issue by bst27** [barryvdh/laravel-ide-helper#176]
After adding the ide-helper to a laravel project I keep getting this error:
![image](https://cloud.githubusercontent.com/assets/6805736/6410807/99488dce-be72-11e4-8a27-cf877a880639.png)

I followed these instructions:
![image](https://cloud.githubusercontent.com/assets/6805736/6410841/de686f46-be72-11e4-928b-898019fc46cd.png)

Artisan gives me the following messages. There seems to be no error apart from the wrong database connections:
![image](https://cloud.githubusercontent.com/assets/6805736/6410919/9ef5d866-be73-11e4-84db-709aa9738c35.png)

I also tried composer update which gives me nearly the same output:
![image](https://cloud.githubusercontent.com/assets/6805736/6411007/6da924ec-be74-11e4-8297-16ca7cabf15e.png)

This is my composer.json file:
```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"barryvdh/laravel-ide-helper": "~2.0"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan ide-helper:generate",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

My config/app.php looks like this:
![image](https://cloud.githubusercontent.com/assets/6805736/6411034/a689c5fa-be74-11e4-9dcb-5b294a0a62ae.png)

Removing the ide-helper service provider line resolves the FatalErrorException. Nonetheless the auto-completion seems to work in Aptana Studio 3.

**Comment by tomzx** [comment]
Are still having this issue?

**Comment by bst27** [comment]
I was able to solve the problem. Seems like an explicit composer dump-autoload solved the problem.
