### ISSUE TITLE
Short array syntax breaks PHP <5.4 applications

### ISSUE THREAD

**Issue by wdmtech** [barryvdh/laravel-ide-helper#183]
The recent update including the short-array syntax in: `src/Console/MetaCommand.php` breaks things in PHP <5.4 applications. If this is intentional I completely understand! 

Is it possible this class could use the array() syntax instead to preserve compatibility? Cheers :)

**Comment by barryvdh** [comment]
Oops, sorry.Will fix it

**Comment by barryvdh** [comment]
THis better?

**Comment by wdmtech** [comment]
Brilliant! thanks again :)
