### ISSUE TITLE
php artisan ide-helper:meta throws this error

### ISSUE THREAD

**Issue by abderrahmane-tj** [barryvdh/laravel-ide-helper#184]
using `php artisan ide-helper:meta` throws this error : 

    [Symfony\Component\Debug\Exception\FatalErrorException]
      Class 'League\Flysystem\AwsS3v2\AwsS3Adapter' not found

this happens on a fresh installation of laravel5

**Comment by barryvdh** [comment]
Probably remove the s3 setting for cloud from filesystem config.

**Comment by abderrahmane-tj** [comment]
What do I replace it with ?

On 16 March 2015 at 17:02, Barry vd. Heuvel <notifications@github.com>
wrote:

> Probably remove the s3 setting for cloud from filesystem config.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barryvdh/laravel-ide-helper/issues/184#issuecomment-81810470>
> .
>



-- 
Abderrahmane TAHRI JOUTI
(+212)  6 33 14 97 99

**Comment by barryvdh** [comment]
Local
Op 16 mrt. 2015 18:04 schreef "Abderrahmane TAHRI JOUTI" <
notifications@github.com>:

**Comment by abderrahmane-tj** [comment]
thanks !

On 16 March 2015 at 17:06, Barry vd. Heuvel <notifications@github.com>
wrote:

> Local
> Op 16 mrt. 2015 18:04 schreef "Abderrahmane TAHRI JOUTI" <
> notifications@github.com>:
>
> > What do I replace it with ?
> >
> > On 16 March 2015 at 17:02, Barry vd. Heuvel <notifications@github.com>
> > wrote:
> >
> > > Probably remove the s3 setting for cloud from filesystem config.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/barryvdh/laravel-ide-helper/issues/184#issuecomment-81810470
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Abderrahmane TAHRI JOUTI
> > (+212) 6 33 14 97 99
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/barryvdh/laravel-ide-helper/issues/184#issuecomment-81811705
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barryvdh/laravel-ide-helper/issues/184#issuecomment-81812425>
> .
>



-- 
Abderrahmane TAHRI JOUTI
(+212)  6 33 14 97 99

**Comment by mikeerickson** [comment]
@abderrahmane-tj I am experiencing the same error (not a new install but never had to config for S3) 

What did you change to make it work?

@barryvdh Does this have to be changed for EVERY project?

**Comment by abderrahmane-tj** [comment]
@mikeerickson I config > filesystems.php : `'cloud' => 'local',` and then I had an other error :

    exception 'Symfony\Component\Debug\Exception\FatalErrorException'
    with message 'Class 'Predis\Client' not found'

and added it to composer to quiet it down

**Comment by barryvdh** [comment]
I actually mentioned both cases in the readme explicitly bit perhaps need to be a bit more specific.
you can just remove the redid service provider from the list in config/app.php

**Comment by mikeerickson** [comment]
@barryvdh Well now why would I read the 'readme'  ;-)

Sorry about that, I will go and read it now....  My bad!

**Comment by mikeerickson** [comment]
@barryvdh I have disabled redis (commented out the service provider call in config/app.php) but still get the Fatal Error?  Should I do anything else?

**Comment by barryvdh** [comment]
Not sure, perhaps clear the cache, config and compiled files.

**Comment by abderrahmane-tj** [comment]
there is a reference to it in the Service Providers and another one in the Aliases Section in the same file

**Comment by mikeerickson** [comment]
I have already commented out both in the config/app.php file

**Comment by barryvdh** [comment]
Can you check with the above commit? It should filter out the redis and cloud filesystem when not available.

**Comment by barryvdh** [comment]
If it doesn't work, could you add a `dump($abstract);` right before `$concrete = $this->laravel->make($abstract);` in the [MetaCommand](https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/MetaCommand.php) so you can see on what abstract name it crashes.

I can't catch fatal errors for things like classes that don't exists unfortunately :(
