### ISSUE TITLE
[L5] Namespace for models is missing

### ISSUE THREAD

**Issue by Itrulia** [barryvdh/laravel-ide-helper#185]
Example output:

	/**
	 * Battleborn\Project
	 *
	 * @property-read \User                                                $user
	 * @property-read \Illuminate\Database\Eloquent\Collection|\Revision[] $revisions
	 * @property integer                                                   $id
	 * @property string                                                    $name
	 * @property string                                                    $description
	 * @property string                                                    $description_compiled
	 * @property integer                                                   $user_id
	 * @property string                                                    $deleted_at
	 * @property \Carbon\Carbon                                            $created_at
	 * @property \Carbon\Carbon                                            $updated_at
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereId($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereName($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereDescription($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereDescriptionCompiled($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereUserId($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereDeletedAt($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereCreatedAt($value)
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereUpdatedAt($value)
	 * @property integer                                                   $visibility_id
	 * @property-read \Battleborn\Visibility                               $visibility
	 * @method static \Illuminate\Database\Query\Builder|\Battleborn\Project whereVisibilityId($value)
	 */

As you can see it states it returns a \User instead of \Battleborn\User.

**Comment by barryvdh** [comment]
How is your relation defined?

**Comment by Itrulia** [comment]
/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function user() {
		return $this->belongsTo('Battleborn\User');
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function visibility() {
		return $this->belongsTo('Battleborn\Visibility');
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function revisions() {
		return $this->hasMany('Battleborn\Revision');
	}

**Comment by Itrulia** [comment]
Deleting the docBloc and rerunning `php artisan ide-helper:models` fixed it.

**Comment by barryvdh** [comment]
Okay cool. There is also a force or overwrite flag to update existing phpdocs.
