### ISSUE TITLE
Meta completion not working with ::class

### ISSUE THREAD

**Issue by Anahkiasen** [barryvdh/laravel-ide-helper#186]
If I do this in my code:

``` php
use Foo\Bar;

$test = app(Bar::class);
```

And generate the meta completion, I get this generated in the meta file:

``` php
'Foo\Bar' instanceof \Foo\Bar,
```

However as PHPStorm seem to match the arguments exactly, no autocompletion is added, because PHPStorm will now look for `app('Foo\Bar')`. If I use the latter I do get the autocompletion, if I use `::class` I don't

**Comment by FractalizeR** [comment]
What is `meta completion` and how it relates to IDE Helper? :)

**Comment by barryvdh** [comment]
https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/MetaCommand.php
https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

A meta-file to describe the container instances, for phpstorm.

But I think this is a PhpStorm issue, not much I can do with that. Or do you have a suggestion to fix this @Anahkiasen ?

**Comment by Anahkiasen** [comment]
Wouldn't having both the FQN and the `::class` as keys in the generated array work?
