### ISSUE TITLE
ide-helper:generate exceeded the timeout

### ISSUE THREAD

**Issue by itonics-tbeauvais** [barryvdh/laravel-ide-helper#187]
I am getting a rather strange error on Jenkins but no developer is seeing this.

```
  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "php artisan ide-helper:generate" exceeded the timeout of 300 seconds.
```

How would I go about debugging this for you?

**Comment by FractalizeR** [comment]
Why do you generate helper files in your CI environment? I think it is completely useless for testing. It is only for a developer to have some autocomplete in IDE.

**Comment by itonics-tbeauvais** [comment]
I know.. how do I not generate it in a CI environment yet generate it in a Developer environment?

**Comment by FractalizeR** [comment]
@itonics-tbeauvais I think you can just parse `.env` file if you are using some standalone tool.

**Comment by Saibamen** [comment]
Bug is still there!!
Composer 1.4.0 and 1.3.2. The newest version of laravel-ide-helper for today.
I run command `php artisan ide-helper:generate` in my local host

**Comment by FractalizeR** [comment]
I doubt it is a bug. If you can't generate stubs for 300 seconds, something is wrong with your host or environment.

**Comment by Saibamen** [comment]
I don't know what was wrong. Two days ago everything work fine. I just make composer update and ide-helper:generate failed (no changes in composer dependencies - just upgrade existing).
Today I updated my XAMPP with new PHP 5.6.30 and everything work good.

**Comment by bitclaw** [comment]
Same issue here , using homestead with PHP 7.1.2-3+deb.sury.org~xenial+1 (cli) (built: Feb 22 2017 10:08:33) ( NTS ).

**Comment by piotr-kowalski** [comment]
`> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate

                                                                                      
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                      
  The process "php artisan ide-helper:generate" exceeded the timeout of 300 seconds. `

`piotr$ php -v
PHP 7.2.9 (cli) (built: Aug 23 2018 02:08:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.2.9, Copyright (c) 1999-2018, by Zend Technologies
`

**Comment by mfn** [comment]
Running ide-helper and hitting timeouts for something which should only take a few seconds points to a problem in the environment IMHO.

Last report is 2 years old => can anyone with _recent_ versions reproduce this?
