### ISSUE TITLE
How to set Doctrine custom mapping types

### ISSUE THREAD

**Issue by ingro** [barryvdh/laravel-ide-helper#19]
Hello! I'm trying your helpers and I find them very useful, anyway I'm stuck trying to use your models docs generator.

The script return this error:

> Exception: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

Searching on google I found the solution to this problem is to map the unknown type to a safe one, like string, here in the [doctrine's doc](http://symfony.com/doc/current/cookbook/doctrine/dbal.html#registering-custom-mapping-types-in-the-schematool) 

So I tried to add that parameter to my database config array but it's not working:

``` php
'connections' => array(

    'mysql' => array(
        'driver'    => 'mysql',
        'host'      => 'localhost',
                    ...
        'mapping_types' => array(
            'enum' => 'string'
        ),
    ),
```

So is this a Laravel4 related problem? Or I'm just doing it wrong?

**Comment by isclopezm** [comment]
I'm getting the same error message, but with a 'tsvector' type column on many tables of my PostgreSQL databases. Is there any patch for that issue?

Note: Using Laravel 5.1 and IdeHelper 2.1.2

Thanks in advance!

**Comment by nprokopic** [comment]
I had same issue with PostgreSQL [`inet` type](http://www.postgresql.org/docs/9.1/static/datatype-net-types.html).

I solved it by manually appending

`$schema->getDatabasePlatform()->registerDoctrineTypeMapping('_int4', 'string');`

just under

`$schema->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');`

in `laravel-ide-helper\src\Console\ModelsCommand.php` file.

This is obviously a temporary workaround since the modified file is located in vendor folder and it will be overwritten after running a composer update.

**Comment by isclopezm** [comment]
What about add on ide-helper.php config file, on custom_db_types, the rules to "parse" types?

I have used it to map a tsvector column  type

`'custom_db_types' => array(
        'postgresql' => array(
            'tsvector' => 'string'
        )
    )`

**Comment by gonzalom** [comment]
Same problem here with **xml** types with **sqlsrv** driver.

It could be great if it could work out of the box in laravel, same way as it was suppose to work, as it is a Symfony library, isn't it:
http://symfony.com/doc/current/doctrine/dbal.html

```php
// app/config/doctrine.php
return [
    'mysql' => [
       'mapping_types' => [
          'enum'  => 'string',
       ],
    ],
    'postgresql' => [
       'mapping_types' => [
          '_int4'  => 'string',
          'tsvector'  => 'string',
       ],
    ],
    'sqlsrv' => [
       'mapping_types' => [
          'xml'  => 'string',
       ],
    ],
];
```

Or maybe a specific config for laravel-ide-helper:

```php
// app/config/laravel-ide-helper.php
return [
   'doctrine' => [
    'mysql' => [
       'mapping_types' => [
          'enum'  => 'string',
       ],
    ],
    'postgresql' => [
       'mapping_types' => [
          '_int4'  => 'string',
          'tsvector'  => 'string',
       ],
    ],
    'sqlsrv' => [
       'mapping_types' => [
          'xml'  => 'string',
       ],
    ],
    ],
];
```

So in your code, you could load this data (if it's not loaded already by any other tool).

**Comment by yapro** [comment]
```
doctrine:
    dbal:
        default_connection: main
        connections:
            main:
                mapping_types:
                    tsvector: string
                    _int4: string
```

**Comment by Erutan409** [comment]
@gonzalom Thank you for the edit to your last comment.  I found [this](https://github.com/barryvdh/laravel-ide-helper#automatic-phpdoc-generation-for-laravel-facades) useful for determining how to specify the custom DB type(s) that doctrine will use.

In that doc section it specifically outlines how to publish the config file by doing:

```
php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config
```

This creates a config file (`ide-helper.php`) where you can specify the custom types for the `custom_db_types` array element.

Worked like a charm.  Hopes this helps someone else.
