### ISSUE TITLE
Missing Eloquent method

### ISSUE THREAD

**Issue by huyhvq** [barryvdh/laravel-ide-helper#191]
please add this method to your ide helper
firstByAttributes
where
thank you :)

**Comment by mfn** [comment]
- there's no `firstByAttributes`
  (anymore, was removed some years ago in Laravel => https://github.com/laravel/framework/commit/dd0b94ef49a22e6a597f6dfb2d66b766e26c73c6 )
- `where`
  There's no doubt this is working nowadays

@barryvdh nothing to be done, issue can be closed :}
