### ISSUE TITLE
Illuminate\Support\Fluent Methods in Migration not found 

### ISSUE THREAD

**Issue by naabster** [barryvdh/laravel-ide-helper#193]
For example in User table migration:

```
	public function up()
	{
		Schema::create('users', function(Blueprint $table)
		{
			$table->increments('id');
			$table->string('name');
			$table->string('email')->unique();
			$table->string('password', 60);
			$table->rememberToken();
			$table->timestamps();
		});
	}
```

`unique()` is not found

Using PHPStorm.

**Comment by barryvdh** [comment]
Probably because the string() call doesn't return proper phpdoc

**Comment by argentinaluiz** [comment]
![laravel](https://cloud.githubusercontent.com/assets/4926329/7103498/ef91d134-e07f-11e4-88ee-83c9ed2df157.png)

The functions returns phpdoc. The return is Fluent.

**Comment by Alekc** [comment]
It would be great to have support for chaining of schema methods. :(

**Comment by m3esma** [comment]
@barryvdh 

I added the following code to end of  `_ide_helper.php` file. And the problem was solved.

```
namespace Illuminate\Support {

/**
 * @method Fluent first()
 * @method Fluent after($column)
 * @method Fluent change()
 * @method Fluent nullable()
 * @method Fluent unsigned()
 * @method Fluent unique()
 * @method Fluent index()
 * @method Fluent primary()
 * @method Fluent default($value)
 * @method Fluent onUpdate($value)
 * @method Fluent onDelete($value)
 * @method Fluent references($value)
 * @method Fluent on($value)
 */
class Fluent {}
}
```

**Comment by spawnia** [comment]
The same issue is discussed here: https://github.com/barryvdh/laravel-ide-helper/issues/425

A more clean solution is to configure ide-helper to include fluent, as described here: https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-generation-for-laravel-fluent-methods

**Comment by hotdesc** [comment]
@spawnia Lumen dont have vendor:publish command
