### ISSUE TITLE
Why method Input::json() not returns type ParameterBag?

### ISSUE THREAD

**Issue by Sorbing** [barryvdh/laravel-ide-helper#194]
Hi. Why method `Input::json()` in documentation does not describe the return types `Symfony\Component\HttpFoundation\ParameterBag|mixed` and instead returns only `mixed` type. Thanks.

**Comment by barryvdh** [comment]
Don't know. You can file an issue on laravel/framework.

**Comment by Sorbing** [comment]
Can I manually set (correct) the type which returns the method of the facade via config file?
