### ISSUE TITLE
ide-helper:generate requires database connection

### ISSUE THREAD

**Issue by mrwaim** [barryvdh/laravel-ide-helper#197]
I havent looked at the code, but ide-helper:generate fails unless mysqld has been started.

Does the helper take a look at the database? Is it writing to it?

I can take a closer look - and change the error to "unable to write blah blah blah to db" instead of

Please configure your database connection correctly, or use the sqlite memory driver (-M). Skipping \Illuminate\Support\Facades\Password.
PDOException: SQLSTATE[HY000] [2002] No such file or directory
Please configure your database connection correctly, or use the sqlite memory driver (-M). Skipping \Illuminate\Support\Facades\Schema.

**Comment by barryvdh** [comment]
But it generates the rest right? Is says it skips those 2 facades, because they need an initialized DB instance (or something, can't remember exactly).
But it suggest to use the `-M` flag, so did you try that? `php artisan ide-helper:generate -M`.
That uses an sqlite connection during the command.

**Comment by mrwaim** [comment]
I didnt try -M - I assumed it would work

**Comment by mrwaim** [comment]
I was just curious, why would an ide helper read/write to the DB

**Comment by barryvdh** [comment]
It doesn't. It just tries to get the PDO connection for some classes, because they are a dependancy.
See https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Alias.php#L189

**Comment by mrwaim** [comment]
Thanks for take a look - I'll look more into the sideeffects of get_class

**Comment by newtonianb** [comment]
I got the same the same issue when running that command on amazon ec2 instance, probably shouldn't run it on production anyways but it was set in my composer.json. Is there a way to somehow not run this in production?

**Comment by newtonianb** [comment]
Actually it's probaby not related to this script anyways as i'm still getting the issue it seems to be a misconfiguration with db drivers somehow.

**Comment by tswestendorp** [comment]
Same issue here.. also with -M

```$ php artisan ide-helper:generate -M
PDOException: could not find driver
Please configure your database connection correctly, or use the sqlite memory driver (-M). Skipping \Illuminate\Support\Facades\Password.
PDOException: could not find driver
Please configure your database connection correctly, or use the sqlite memory driver (-M). Skipping \Illuminate\Support\Facades\Schema.
A new helper file was written to _ide_helper.php```

**Comment by thomthom** [comment]
I see the same as @tswestendorp - even with the `-M` argument I get these errors.

**Comment by r34ch** [comment]
I also see the same as @tswestendorp and @thomthom with laravel 5.1. Thoughts @barryvdh ?

**Comment by barryvdh** [comment]
Not sure, but it still generates, right:

**Comment by progmars** [comment]
I guess, we'll have to live with this, right? Because of the way how PHP PDO classes are built, it seems impossible to generate IDE helper with PDO classes included without trying to connect to the database, because connection attempt is built into PDO constructor, if I remember correctly.

I am against PHP / PDO  team for such decision. In my opinion, it's not a good idea to do such a heavy task right in the constructor of an object. A dedicated `connect()` method would be better approach.

**Comment by thomthom** [comment]
But shouldn't the error go away with the `-M` option?

**Comment by tswestendorp** [comment]
Finally found what was causing the issue for me

```$ php artisan ide-helper:generate -vvv
PDOException: SQLSTATE[HY000] [2002] No such file or directory
Please configure your database connection correctly, or use the sqlite memory driver (-M). Skipping \Illuminate\Support\Facades\Schema.
A new helper file was written to _ide_helper.php```

```$ php artisan ide-helper:generate -M -vvv
PDOException: could not find driver
Please configure your database connection correctly, or use the sqlite memory driver (-M). Skipping \Illuminate\Support\Facades\Schema.
A new helper file was written to _ide_helper.php```

After installing ```php5-sqlite``` the Exception went away:

```$ php artisan ide-helper:generate -M -vvv
A new helper file was written to _ide_helper.php```
