### ISSUE TITLE
Composer Update & Laravel Socialite

### ISSUE THREAD

**Issue by shehi** [barryvdh/laravel-ide-helper#199]
After adding the Socialite package to composer.json and into conf/app.php, ```composer update``` command yields following output:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Exception: Target [Laravel\Socialite\Contracts\Factory] is not instantiable.
Skipping \Laravel\Socialite\Facades\Socialite.
A new helper file was written to _ide_helper.php
Generating optimized class loader
```
I haven't set any parameters specific to any social login platform in conf.services.php. Any ideas why this error happens? Is this issue related to #159?

P.S.: My composer.json https://github.com/AudithSoftworks/Basis/blob/auth/composer.json - I add Socialite in this branch (added version isn't in Github of course).

**Comment by AndyWendt** [comment]
It sounds like you may have forgotten to add the Socialite Service Provider. Typically when you get not instantiable it means you are missing a binding in the service container.

**Comment by shehi** [comment]
Nah, I had it added.
