### ISSUE TITLE
Unable to run ide-helper:models --dir="app/Http/Models" after composer dump-autoload

### ISSUE THREAD

**Issue by shellprog** [barryvdh/laravel-ide-helper#200]
I am unable to specify the --dir option to models after running 

```
composer dump-autoload

php artisan ide-helper:models --dir="app/Http/Models"
```

**Comment by FractalizeR** [comment]
What does it mean "unable"? What happens if you specify it?

**Comment by bvcvb** [comment]
I have the same problem. file is null.

**Comment by shellprog** [comment]
It works now in new update

**Comment by shehi** [comment]
Models have nothing to do with Http btw :) Thought I should mention.

**Comment by mfn** [comment]
OP mentioned already it's working https://github.com/barryvdh/laravel-ide-helper/issues/200#issuecomment-150904671

@barryvdh issue can be closed :}
