### ISSUE TITLE
Do you plan to release branch for lumen?

### ISSUE THREAD

**Issue by likerRr** [barryvdh/laravel-ide-helper#202]
Hi, Barry, I very like ide-helper and it would be cool to have a branch for lumen, that ready to work out of the box, or may be some manual of how to migrate with current version

**Comment by likerRr** [comment]
Any updates?

**Comment by barryvdh** [comment]
Not yet, sorry

**Comment by likerRr** [comment]
No one will do it better then you, hope it will happen soon, thx

**Comment by paunin** [comment]
:+1:

**Comment by Quagh** [comment]
+1

**Comment by davidsielert** [comment]
anybody even tried it with lumen ? or is it using missing providers/helpers ?

**Comment by Quagh** [comment]
Yep, tried it. Same case as with all other packages that don't work with Lumen: requires some specific Laravel classes which are not present in Lumen.

**Comment by davidsielert** [comment]
k, had to ask :)   I dont imagine it shoudl be a huge hinderance to port this over though .. hard to say

**Comment by Quagh** [comment]
I imagine it will, actually :p The Lumen flow and structure is quite different from Laravel. Though I know nothing about the code of this package.

**Comment by plexnum** [comment]
+1

**Comment by artisaninweb** [comment]
+1

**Comment by kitensei** [comment]
+1

**Comment by matiux** [comment]
+1

**Comment by mmikulski** [comment]
+1

**Comment by frankcarey** [comment]
To be more specific about the issue, I tried adding this to bootstrap/app.php
`$app->register(Illuminate\Foundation\Providers\ArtisanServiceProvider::class);`

But then I get an error when I run `php artisan`:
```
[ReflectionException]
  Class path.config does not exist
```

**Comment by 20TRIES** [comment]
+1

**Comment by lokielse** [comment]
+4

**Comment by webkenny** [comment]
:+1: - Totally with you on this. I would love to see this happen too. Doesn't seem it would be too difficult to do if someone just stripped out the irrelevant packages for Lumen. I might give that a shot in the example generated file and let you know what happens.

**Comment by barryvdh** [comment]
The packages are automatic, it's about the helpers and missing methods for the ServiceProvider mostly.

**Comment by adrian7** [comment]
@webkenny have you tried it?

**Comment by webkenny** [comment]
Not yet but I will report back when I get a chance to.

**Comment by claygorman** [comment]
+1

**Comment by moradgholi** [comment]
+1

**Comment by ffsantos92** [comment]
+1

**Comment by spajz** [comment]
+1

**Comment by juanpborda** [comment]
+1

**Comment by KarimGeiger** [comment]
+1

**Comment by jeremy-bruns** [comment]
+1

**Comment by cuthbert** [comment]
+1

**Comment by rto-pub** [comment]
+1

**Comment by lEx0** [comment]
+1

**Comment by bkuhl** [comment]
:+1:

**Comment by nnnikolay** [comment]
+1

**Comment by shehi** [comment]
+1

**Comment by Fender123** [comment]
+1

**Comment by destronije** [comment]
+1

**Comment by neochief** [comment]
Here's a workaround.

Add `illuminate/filesystem` to your composer requirements:

```
composer require illuminate/filesystem
```

Then, add this before `return $app;` in your `bootstrap/app.php`:

```
if (!function_exists('config_path')) {
    function config_path()
    {
        return base_path() . '/config';
    }
}
$app->register(Illuminate\Filesystem\FilesystemServiceProvider::class);
class_alias('Illuminate\Support\Facades\File', 'File');
```

After this, you can run regular ide-helper artisan commands.

**Comment by barryvdh** [comment]
So, I've added a check for the config_path helper. So the ServiceProvider runs.
Also injected the Filesystem in the Models command, so that runs fine now.

But Lumen doesn't have a AliasLoader, so don't know yet how to get all the used facades.

**Comment by neochief** [comment]
Here's a workaround.

Add `illuminate/filesystem` to your composer requirements:

```
composer require illuminate/filesystem
```

Then, add this before `return $app;` in your `bootstrap/app.php`:

```
if (!function_exists('config_path')) {
    function config_path()
    {
        return base_path() . '/config';
    }
}
class_alias('Illuminate\Support\Facades\File', 'File');
$app->register(Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
```

After this, you can run regular ide-helper artisan commands.

**Comment by neochief** [comment]
Oh, looks like while I've been searching for workaround, @barryvdh fixed almost all the issues :)

**Comment by barryvdh** [comment]
So should be fixed by https://github.com/barryvdh/laravel-ide-helper/commit/0d13a51ff5171a9744be862f477b6747b83b1ac2
No auto-detecting of the Facades, but at least you get the default facades :)

**Comment by barryvdh** [comment]
And for all the lazy people, here is the default gist: https://gist.github.com/barryvdh/be17164b0ad51f832f20

**Comment by likerRr** [comment]
Thank you, Barry! But may be it is possible to have a way to inject (if no way to gather them from lumen) own facades to ide-helper to generate them after?

**Comment by barryvdh** [comment]
Sure, could be a config or something. Submit a PR and I'll review.

But for Lumen, I would suggest to just not use Facades.

**Comment by barryvdh** [comment]
2.1.0 is tagged with Lumen support.

**Comment by danrichards** [comment]
What a guy! Way to go Barry, Thanks!

**Comment by jeremy-bruns** [comment]
Awesome thx!

**Comment by shehi** [comment]
@barryvdh , first of all: God bless your soul for such an awesome tool.

Second, is my question: is there any way for us to generate PHPStorm meta file? Thanks.

**Comment by likerRr** [comment]
@shehi what do you mean about phpstorm meta file?

**Comment by barryvdh** [comment]
Should work the same as in Lumen, just 'php artisan ide-helper:meta'.

https://github.com/barryvdh/laravel-ide-helper/blob/master/readme.md#new-phpstorm-meta-for-container-instances

**Comment by shehi** [comment]
@likerRr : Check the new README file in the package.

@barryvdh : That small piece of command should be included in Readme, IMHO. Or is it there and I missed it?

**Comment by barryvdh** [comment]
It's there, but it was in the same codeblock as the example. Clarified the readme a bit.

**Comment by nnnikolay** [comment]
Sorry, should it help to navigate in this case ?
```
$validator = Validator::make($this->attributes, $rules, $this->messages);
..
if ($validator->passes()) return true;
```

I click on `->passes` method but can't reach defenition

**Comment by xiphiaz** [comment]
@barryvdh I can't get the helper to work at all for Lumen - am I doing something wrong? https://github.com/spira/spira/pull/158 The file builds fine, and it looks the same as your static gist, but checking Facades like `Cache::` and `Config::` seem to do nothing.

PHPStorm 9.0 if that helps.

**Comment by Redjik** [comment]
@barryvdh, I will try to describe what's the problem.
https://gist.github.com/barryvdh/be17164b0ad51f832f20 this is the file you provided.
Compare it to the laravel's.
Facades shouldn't be wrapped into namespace. They should be in a global scope.

**Comment by shehi** [comment]
I'd recommend first re-indexing your project: FILE > INVALIDATE CACHES / 
RESTART.

**Comment by xiphiaz** [comment]
@shehi thanks for the suggestion, but it did not work. I think @Redjik is on the money, as the structure appears to be different for the lumen gist.

**Comment by barryvdh** [comment]
You are right, Facades and real classes are swapped.

**Comment by barryvdh** [comment]
Can you try the new gist?

**Comment by xiphiaz** [comment]
@barryvdh yep just tried it, no dice :( Do I need to be registering it in the composer.json file somewhere?

**Comment by JoshZA** [comment]
+1
