### ISSUE TITLE
Packagist outdated

### ISSUE THREAD

**Issue by bdreesen** [barryvdh/laravel-ide-helper#204]
A few days ago support for laravel 5.1 was added but the commit is still not available on packagist.
Packagist points to previous commit and i'm unable to load the package on 5.1

dev-master / 2.0.x-dev reference: dac46a0

**Comment by barryvdh** [comment]
I've force-updated the packagist listing. Should now point to https://github.com/barryvdh/laravel-ide-helper/commit/b1dedc3ee63c82388311dfc9de28b88e81bb1396
