### ISSUE TITLE
The columns of eloquent db objects are not recognized in phpstorm

### ISSUE THREAD

**Issue by iarief** [barryvdh/laravel-ide-helper#209]
Hi, i'm having quite a peculiar problem here, the ide-helper:model did generate the new file called _ide_helper_models.php but phpstorm doesn't seem to read from those. 

i.e.

$article = Article::find(1);
$article->(Ctrl + space)

in the second i believe that i should expect the columns of the object Articles to exist in the autocomplete suggestion list, but it doesn't. i had some column on that class (body, title, published_at) and they exist in _ide_helper_models.php file but for some reason it's still not working. the Article::find did get auto completed though.

**Comment by Komayo** [comment]
As i know, it happens also with other situations. for example.

$user = User::where(xyz...), where method is also not detected.

For example also, in $message parameter of a Mail::send method,

$message->to, to is also not reconized!

And theres a few more.

I did some tests, and i know that for example at Sublime Text 3, the autocomplete works 100% fine, even with this methods.

Just happens in Phpstorm...

**Comment by funsterisdafunniest** [comment]
@Komayo but did sublime 3 able to provide the auto completion for columns in the objects?
i already extend the Eloquent facade and created the model helper but still can't get it to work.

**Comment by Komayo** [comment]
@funsterisdafunniest yes it provides auto completion for columns.

for example my user table has "username, password, activated, etc"

$user->activated (perfectly fine with autocomplete)

**Comment by funsterisdafunniest** [comment]
@Komayo  hmm. that's strange.. it doesn't work for me even while i'm using sublime with code intel. did you write the php doc in the object or did you write them to the external file?

**Comment by Komayo** [comment]
I am using the generated ide_helper.php. Works fine. But not on phpstorm.

**Comment by aledmb** [comment]
@Komayo how do you deal with "where" and a few other methods not passing inspection? do you suppress those warnings on all your files?

**Comment by akmumu** [comment]
so do i
![image](https://cloud.githubusercontent.com/assets/3242526/10018173/318aea04-6167-11e5-89b5-94b9d6d38bd0.png)

**Comment by ruuter** [comment]
IMHO the best workaround I've found so far is to downgrade severity if __magic methods are present in class. PhpStorm has this exact option in inspections settings. [Check my answer at SO](http://stackoverflow.com/a/35347256/1296104)

**Comment by zuhairtaha** [comment]
I faced this problem. Finally I solved it by following the structures under **Automatic phpDocs for models** in laravel-ide-helper.

https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-for-models

Before I had applying only the first part of installation.
Now everything is OK.

**Comment by mfn** [comment]
@barryvdh this definitely works (I also just tried it, using the `_ide_helper_models.php` instead of writing them back to the model), issue can be closed :}
