### ISSUE TITLE
Schema class not generated without database connection

### ISSUE THREAD

**Issue by JeroenNoten** [barryvdh/laravel-ide-helper#210]
If there is no working database connection, the `Schema` class is not added to the helper file. Why is that?

I have only a working database connection within my Homestead box, and I discovered this issue when I ran the generate command on my machine vs on Homestead. In the first case, the helper file did not include a `Schema` class, and in the second case it did include the class. I am wondering why this difference is there and maybe the situation could be improved.

**Comment by barryvdh** [comment]
Because instantation of the class/facade fails without a valid database config, and I can't parse the class.
An error is shown when the classes are skipped. It's possible to use a `-M` flag to use an in-memory sqlite db instead.

**Comment by JeroenNoten** [comment]
Thanks! Sorry, I see it now in the Readme also, I had to read that better.
