### ISSUE TITLE
ide-helper:meta throws Exception

### ISSUE THREAD

**Issue by mitiaj2** [barryvdh/laravel-ide-helper#213]
Running this command exception is thrown

![selection_040](https://cloud.githubusercontent.com/assets/5555280/7765854/be9b4496-006b-11e5-850d-3007b5d41083.png)

It happens when I try to register aliases in AppServiceProvider.php

AppServiceProvider@register:
![selection_041](https://cloud.githubusercontent.com/assets/5555280/7765877/0358114a-006c-11e5-8327-a76efbed8bc2.png)

It may look strange that I try to add namespace as an alias, but this prevents laravel from creating new instance in method injection. When using facade (in current context) - instance is always returned by key and its singleton. Using method injection laravel omits that and looks for namespace in container and creates new instance where namespace is key. This alias helps to find right service.
I am not expert in laravel, and I not rule out of the fact that this alias registration may be done incorrectly, but it works just fine.

Removing "$this->app->alias(.." line of code solves a problem for ide-helper.

**Comment by shehi** [comment]
@barryvdh better close this one, OP didn't even bother to search for the actual error on web and discover that it's XDebug related.
