### ISSUE TITLE
Laravel Ide helper

### ISSUE THREAD

**Issue by binalfew** [barryvdh/laravel-ide-helper#214]
The ide helper skips my custom Facades. Any idea?

**Comment by LukeNZ** [comment]
Same issue here, despite defining them in the aliases array in app.php.

**Comment by days85** [comment]
:+1: 
I know that this issue is old. 
I Have this issue on L5.4 and had on L5.3 any ideas?

**Comment by mfn** [comment]
@barryvdh none of the mentioned Laravel versions are supported and custom facades do work, as long they're properly registered; I vote for closing the issue :}
