### ISSUE TITLE
ide-helper:generate not working in composer post-update-cmd

### ISSUE THREAD

**Issue by refear99** [barryvdh/laravel-ide-helper#216]
```
"post-update-cmd": [
      "php artisan clear-compiled",
      "php artisan ide-helper:generate",
      "php artisan optimize"
    ],
```

I use this to generate ide-helper file, bug the generated file missing some methd, such as "Cache::put"

but when I use "artisan ide-helper:generate" in Terminal, it's OK. Why is that?

thanks

**Comment by BlueManLine** [comment]
Same to me - after creating my custom command which run all the ide-helper commands
```php
    public function handle()
    {
        $this->call('ide-helper:generate');
        $this->call('ide-helper:meta');
        $this->call('ide-helper:models', ['--nowrite' => 'yes']);
    }
```
BUT... when I commit any line (or more :P) than this is working... .

![screenshot - 30 06 2015 - 11 34 06](https://cloud.githubusercontent.com/assets/3807650/8428029/f1737496-1f1b-11e5-9765-b16d98c7097f.png)

**Comment by mfn** [comment]
Seems there are different issues mixed here:
- working, but not generating everything
- not working when used within another command (though unclear what "commit any line") means

@refear99 @BlueManLine is this still an issue, can you try with latest laravel/ide-helper?

**Comment by bluemanos** [comment]
@mfn cant confirm right now, but a years ago I found a solution. You have to switch order of the commands and everything is working fine.

```php
    public function fire()
    {
        $this->call('ide-helper:generate');
        $this->call('ide-helper:models', ['--nowrite' => 'No']);
        $this->call('ide-helper:meta');
    }
```

**Comment by mfn** [comment]
@bluemanos thanks for getting back!

Also apologies from my side, I really didn't realize what the reason for the code in https://github.com/barryvdh/laravel-ide-helper/issues/216#issuecomment-117087352 was fore but re-reading it and your recent comment it's clear now.

I tried both variants in the latest ide-helper, to the best I can see both work correctly already.

@barryvdh I don't think there's an open issue here, I vote for closing :}
