### ISSUE TITLE
References to wrong class generated

### ISSUE THREAD

**Issue by TommyC81** [barryvdh/laravel-ide-helper#218]
Since recently getting wrong class references generated. ExamHandler is used via a Facade (resolved as a singleton) and configured accordingly in config/app.php.

File "ExamHandler.php":

```
use App\Entities\Exam as ExamEntity;

/**
     * Generates an exam.
     *
     * @param ExamEntity $exam
     * @return bool
     * @throws ExamHandlerException
     */
    public function generate(ExamEntity $exam){
        // Stuff
    }
```

File "_ide_helper.php":

```
/**
         * Generates an exam.
         *
         * @param \App\Services\ExamHandler\ExamEntity $exam
         * @return bool 
         * @static 
         */
        public static function generate($exam){
            return \App\Services\ExamHandler\ExamHandler::generate($exam);
        }
```

File "Test.php", outcome from usage:

![PhpStorm warning](https://cloud.githubusercontent.com/assets/1904092/7888750/d2409736-064b-11e5-8e55-d23cc8d14c3a.png)

Edit: Dealt with by enabling FQCN DocBlocks in PhpStorm, however, not sure if the change in behavior experienced was intended?

**Comment by jbussemaker** [comment]
+1, would be nice if the IDE helper would output FQCN's by itself :)

**Comment by barryvdh** [comment]
It should do that for classes/methods it generates.
