### ISSUE TITLE
Meta & L5.1

### ISSUE THREAD

**Issue by Shhu** [barryvdh/laravel-ide-helper#220]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory' not found

i **dont** use 
- composer require symfony/psr-http-message-bridge
- composer require zendframework/zend-diactoros

**Comment by barryvdh** [comment]
I've tried a new way to catch those errors, does that work for you?

**Comment by Shhu** [comment]
it work thx !

For information :
Cannot make 'Psr\Http\Message\ServerRequestInterface': Class 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory' not found.
Cannot make 'filesystem.cloud': Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found.
Cannot make 'Illuminate\Contracts\Broadcasting\Broadcaster': Class 'Pusher' not found.
A new meta file was written to .phpstorm.meta.php
