### ISSUE TITLE
Classes not loading.

### ISSUE THREAD

**Issue by uibar** [barryvdh/laravel-ide-helper#224]
I get the errors in terminal after running:
```php
php artisan ide-helper:meta

results in:

Cannot make 'Psr\Http\Message\ServerRequestInterface': Class 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory' not found.
Cannot make 'filesystem.cloud': Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found.
Cannot make 'Illuminate\Contracts\Broadcasting\Broadcaster': Class 'Pusher' not found.
Cannot make 'redis': Class 'Predis\Client' not found.

A new meta file was written to .phpstorm.meta.php
```

Am I doing something wrong? Or it is a bug. I need to mention that I recive this error only after the laravel 5.1 update. I also get it on new Laravel 5.1 install too.

**Comment by barryvdh** [comment]
No it's fine, just a warning that those are skipped.

**Comment by zanematthew** [comment]
Is there a reason those are skipped? I'm currently using Laravel and the Filesystem.
