### ISSUE TITLE
Generation of file halted in middle

### ISSUE THREAD

**Issue by conway-chris** [barryvdh/laravel-ide-helper#225]
When I run "php artisan ide-helper:generate" a bunch of the code is outputted but the generation of the file is halted in the middle with the last line being: 

"class Input extends \Illuminate\Support\Facades\Input{"

Does this show a problem with my setup or anything you've seen before?

Thank you!

**Comment by mfn** [comment]
@barryvdh not much information to act on, 5 years old etc.; I vote for closing this :}
