### ISSUE TITLE
Meta file: app()->make('events') works, but app('events') does not

### ISSUE THREAD

**Issue by JeroenNoten** [barryvdh/laravel-ide-helper#226]
Hi, after running `ide-helper:meta`, then `app()->make('events')` provides nice autocompletion, but `app('events')` does not. Any ideas why?

**Comment by barryvdh** [comment]
Because the meta completion isn't perfect :(
Did you try with latest dev version and latest Phpstorm (9 public beta or something)?

**Comment by barryvdh** [comment]
This: http://blog.jetbrains.com/phpstorm/2015/06/phpstorm-9-eap-141-1619/

**Comment by JeroenNoten** [comment]
Thank you.
Yes, I am using the latest EAP version at the moment.

**Comment by barryvdh** [comment]
See https://youtrack.jetbrains.com/issue/WI-27712
Should hopefully be fixed in upcoming EAP

**Comment by JeroenNoten** [comment]
Good work! Let's hope indeed.

**Comment by barryvdh** [comment]
Should be fixed in http://blog.jetbrains.com/phpstorm/2015/06/phpstorm-9-eap-141-1717/

Also `app('MyClass')` should now automatically complete `MyClass` if you update to latest EAP + 2.0.6

**Comment by JeroenNoten** [comment]
Yep, confirmed!

Thank you.
