### ISSUE TITLE
Dev mode generation failed from composer update script

### ISSUE THREAD

**Issue by alexglue** [barryvdh/laravel-ide-helper#229]
I got /local/app.php with ide-helper provider in it (like in this manual https://github.com/chiraggude/larabase/wiki/Development-Environments-and-Configuration-in-Laravel)

```
<?php
/// /var/www/site/config/local/app.php
return [

    'providers' => append_config([
        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
    ])
];
```

```
composer.json:
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "barryvdh/laravel-ide-helper": "^2.0",
        "doctrine/dbal": "~2.3"
    },
scripts:{
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ],
}
```

Now, when i run composer update (or composer install) i got this:

```
  [InvalidArgumentException]                                    
  There are no commands defined in the "ide-helper" namespace.                                                            
Script php artisan ide-helper:generate handling the post-update-cmd event returned with an error
  [RuntimeException]  
  Error Output:       
```

Also, i got 

```
$ php artisan ide-helper:generate                                 
  [InvalidArgumentException]                                    
  There are no commands defined in the "ide-helper" namespace. 
```

Everything is ok when i put that provider to app.php, but i do not want to load it on production!

**Comment by barryvdh** [comment]
Are you on the correct environment? Try php artisan env

**Comment by alexglue** [comment]
@barryvdh yes, env is correct:
```
$ art env
Current application environment: local
$ art -V
Laravel Framework version 5.1.3 (LTS)
```
there's no other plugins/modules/etc except your module;
i've just install clear version of framework and ran ```laravel new projectname```

**Comment by umutyerebakmaz** [comment]
I have a same problem and cant fix. Still stack here.

**Comment by HopeGroundskyova** [comment]
How to fix this problem ?

**Comment by bebnev** [comment]
@alexglue, as I can see, you are using Laravel version 5.1.3.
Laravel from version 5.* starts using DotEnv library, so you can control the main config options through .env files and you can have different versions of them for different environments.
Config in local folder nowadays really do nothing except for creating a new config key 'loca.app' in your case, and they are not merged with original app config.
As for different providers for different environments you can use AppServiceProvider (app/Providers/) to load them.
Something like this
```php
public function register()
    {
        if ('local' == app()->environment()) {
            app()->register(
                IdeHelperServiceProvider::class
            );
        }
    }
```

**Comment by Rolice** [comment]
How did you managed to run conditional composer `post-update-cmd` commands?

**Comment by Rolice** [comment]
I have made a workaround solution with one extra , simple command that checks for installed and enabled package and verifies the environment.

See: https://gist.github.com/Rolice/6c6bcc4fedc12f369691d40cf259a41a

With this approach you should add the command above in your `App\Console\Commands` folder, first. Then you will have to register it in `App\Console\Kernel` like:

```php
    protected $commands = [
        // Your previous registered commands...
        IdeHelperHandler::class,
    ];
```

At last you will have to modify the `composer.json` file to execute it with the post install/update commands (example below).

```json
 "post-install-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postInstall",
      "php artisan optimize",
      "php artisan ide-helper:handle"
    ],
    "post-update-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postUpdate",
      "php artisan optimize",
      "php artisan ide-helper:handle"
    ]
```

**Comment by Rolice** [comment]
Happy to help!

Yes indeed, I agree with you. 

I think this a bit tricky issue, since if the package is not installed there will be no code to check. On the other hand, composer executes commands straight forward and there is no room for any conditional logic.

Thus it has to be outside the package and most appropriate place is not in package at all, but in the application itself.

**Comment by mfn** [comment]
Since the introduction of auto-discovery this shouldn't be an issue anymore, because if the ide-helper package isn't installed in production, the serviceprovider won't be registered and nothing bad will happen.

As for manual registering the service provider: I don't so much _this package_ can do if you're in an environment _the package will not be installed in_ 💥 

If someone insists on manual registration _and_ not installing dev dependencies in production, there's no other way than handling this in a custom way; there's 0 this package can do and this problem would apply to any dev-only package

@barryvdh I vote for closing this :}
