### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by Nextt1** [barryvdh/laravel-ide-helper#230]
I added the package is mentioned in the docs.

i added the 

Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
line in app.php file.

Now when I executed this commnad

php artisan ide-helper:generate

following error occured.

[Symfony\Component\Debug\Exception\FatalErrorException]
class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found

Im using laravel 5.1.4

**Comment by ceesco53** [comment]
Try adding <code>Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider</code> instead of <code> Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class</code> to the providers array in <code>config/app.php</code>.

**Comment by Nextt1** [comment]
Not working

**Comment by bequadrat** [comment]
Removing ::class I was able to run php artisan ide-helper:generate in the first place. It also generates a _ide_helper.php file in my project's root. But PhpStorm 9 doesn't seem to make any use of it - autocompletion still doesn't work and PhpStorm still show me most namespaces and classes as "undefined".

**Comment by mfn** [comment]
@barryvdh registration problems on a 5 year old issue  => I vote for closing as this is certainly a basic thing which we know works :}
