### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by bequadrat** [barryvdh/laravel-ide-helper#234]
I required the package with composer, but it's not working at all for me. 

If I add "Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class" to my config/app.php providers array, php artisan always gives me a FatalErrorException "Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class' not found". 

If I remove the "::class" from the service provider, php artisan ide-helper:generate creates a _ide_helper.php in the root directory of my project, and it also looks fine, but PhpStorm doesn't seem to make any use of it. Auto-completion doesn't work and all the facades used by my app show up as warnings / errors inside PhpStorm. 

PhpStorm also doesn't seem to be able to resolve vendor namespaces (e.g. in \Illuminate\Support\Facades\App the "Facades" show up in red, a tooltip says "Undefined namespace Facades", and additionally "App" show up with a yellowish background, a tooltip says "Undefined class App").

I'm using Laravel 5.0.33 with PHP 5.6.9 and PhpStorm 9.0. I'd be very grateful if someone could help.

**Comment by barryvdh** [comment]
Of you use the class notation, don't use quotes around it.

Did you index your vendor folder also?

**Comment by shehi** [comment]
@barryvdh I believe you should close issues after certain time period when we don't receive any input. They clutter issue-base and are hard to manage really. Wasting time going over useless issues really.

**Comment by mfn** [comment]
@barryvdh also one of this old "serviceprovider registration" problems => I vote for closing :}
