### ISSUE TITLE
Adding support for specifying which database connection to use

### ISSUE THREAD

**Issue by tylercrompton** [barryvdh/laravel-ide-helper#235]
All of the `migrate` sub-commands support both `--database=[DATABASE]` and `--env[=ENVIRONMENT]`. However, the `ide-helper` sub-commands do not support the `--database=[DATABASE]` option. This option is used to specify which database connection to use.

The current workaround is to create an entirely new environment or to temporarily change the database username and the database password in the current environment. The former is difficult in that one would have to maintain duplicate settings that would otherwise not change between environments. The latter is just annoying and takes up time.

I propose adding a `--database=[DATABASE]` option to solve this issue. This will allow for easier changing of database connections with the `ide-helper` sub-commands. Additionally, this will add consistency with Artisan's builtin commands. If this is a feature that would be desired, I'll be more than glad to make the changes and submit a pull request.

The primary use case that I can conceive is having a database user for the web application itself and another database user for administrative/developmental purposes.

**Comment by barryvdh** [comment]
For the ide helper, it doesn't matter, because the only difference is the database driver (mysql etc).

For the models, it should probably check the database specified for that model.

Your dev and production should be in sync anyways, and usually they are both different servers.

**Comment by tylercrompton** [comment]
>Your dev and production should be in sync anyways, and usually they are both different servers.

On my development machine, I could be using different databases to test different things. I'm not sure what you mean by "in sync." Do you mean in regard to the configuration, schema, or data?

Additionally, I would hope that people shouldn't be in a situation in which they need Laravel IDE Helper on a production (or even a staging) machine. What I'm getting at with that last statement is that I'm not considering production servers with this feature request.

>For the ide helper, it doesn't matter, because the only difference is the database driver (mysql etc).
>
>For the models, it should probably check the database specified for that model.

Do you mind elaborating on that bit? I don't think I follow what you're trying to say.

**Comment by barryvdh** [comment]
I'm just a bit confused why you would need to set the database.

- `ide-helper:generate`: only uses the database connection to show the actual driver in the manager class, but doesn't do anything else with the database.
- `ide-helper:meta`:  doesn't use the db.
- `ide-helper:models`: Can use Doctrine to load table information, but this should just use the database connection as it's defined in the model.

So what do you expect to get from defining the database?

**Comment by tylercrompton** [comment]
>Can use Doctrine to load table information, but this should just use the database connection as it's defined in the model.

Do you mind elaborating on this bit (particularly the latter half)?

**Comment by mfn** [comment]
> Can use Doctrine to load table information, but this should just use the database connection as it's defined in the model.

Any model can specify a custom connection name via `\Illuminate\Database\Eloquent\Model::$connection` which correctly is used by ide-helper.

Otherwise how would your model know (by itself), which of your many database connections it should connect to? Are you dynamically changing them at runtime?

> The primary use case that I can conceive is having a database user for the web application itself and another database user for administrative/developmental purposes.

"can conceive" as in "can _think_ of" or …?

Does this mean you want to re-use your model for different database connections, i.e. one model might either point to database A or database B, depending on context?

If so, this is the first and only time (AFAICS in the issue search) this ever come up; not sure if it's worth the added complexity to support this scenario?
