### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by A-David** [barryvdh/laravel-ide-helper#238]
Doesn't seem to do anything.

Installed, it's in composer.json, dependencies are there. Ran the artisan command to generate ide-helper too. All went smoothly, no errors.

I think this might be why though:

![Image](http://puu.sh/jccfv/806e980a95.png)

Most the stuff in here says "Multiple references available"

**Comment by MCH-David** [comment]
Fixed that multiple definitions problem, PhpStorm had an include path referencing a previous Laravel installation, but I'm still having problems.

![Image](http://puu.sh/jccsR/cbb292e14b.png)

Even if that warning is fine, it's still not working.

**Comment by MCH-David** [comment]
Just to leave some more stuff.

Request::all() says it shouldn't be called statically, no code completion either.

$request = new Request;
$request->all;
No errors, code completion ^

**Comment by vukasin0** [comment]
PHP Storm 9 - doesn't work at all :(

**Comment by mfn** [comment]
- the images don't work anymore
- I just tested it, the facade `Request::all()` works as expected for me (technically and with auto-complete)
- the last example is confusing, `new Request` is certainly not going to work as it needs to be injected correctly

@barryvdh don't think there's anything actionable, I vote for closing this issue :}
