### ISSUE TITLE
ide-helper:models --dir="app/Models" generates two docblocks

### ISSUE THREAD

**Issue by tzfrs** [barryvdh/laravel-ide-helper#240]
I have a class, that looks like this

    <?php
    namespace FBFeedParser\Models;
    
    class FacebookPostData extends BaseModel
    {
        /**
         * The table name of this class, since the AI of Laravel would add an s to the end of this class
         * @var string
         */
        protected $table = 'facebook_post_data';
    
        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'facebook_post_id', 'shares', 'likes', 'comments', 'total_count'
        ];
    
        protected $parentMapper = [
            'facebook_post_id'  => 'id',
            'shares',
            'likes',
            'comments',
            'total_count'
        ];

        /**
         * Saves a new FacebookPostData entry into the database via values from a FacebookPost object
         *
         * @param FacebookPost $facebookPost
         */
        public function saveFromFacebookPost(FacebookPost $facebookPost)
        {
            parent::saveFromParentObject($facebookPost);
        }
    }

Now, when trying to generate the phpdocblock with `php artisan ide-helper:models --dir="app/Models"` and typing in yes to overvwrite existing model files I'm getting this output

>Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/BaseModel.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookCategory.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPage.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPageData.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPost.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPostData.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/User.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/BaseModel.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookCategory.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPage.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPageData.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPost.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/FacebookPostData.php
Written new phpDocBlock to /home/vagrant/work/FBFeedParser/app/Models/User.php

As you can see, all models are there two times. And then, the phpdocblock looks like this

    /**
     * FBFeedParser\Models\FacebookPostData
     *
     * @property integer $id 
     * @property integer $facebook_post_id 
     * @property integer $shares 
     * @property integer $likes 
     * @property integer $comments 
     * @property integer $total_count 
     * @property \Carbon\Carbon $created_at 
     * @property \Carbon\Carbon $updated_at 
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereId($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereFacebookPostId($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereShares($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereLikes($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereComments($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereTotalCount($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereCreatedAt($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereUpdatedAt($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\BaseModel today()
     */
    /**
     * FBFeedParser\Models\FacebookPostData
     *
     * @property integer $id 
     * @property integer $facebook_post_id 
     * @property integer $shares 
     * @property integer $likes 
     * @property integer $comments 
     * @property integer $total_count 
     * @property \Carbon\Carbon $created_at 
     * @property \Carbon\Carbon $updated_at 
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereId($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereFacebookPostId($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereShares($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereLikes($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereComments($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereTotalCount($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereCreatedAt($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\FacebookPostData whereUpdatedAt($value)
     * @method static \Illuminate\Database\Query\Builder|\FBFeedParser\Models\BaseModel today()
     */

Why is everything generated twice?

**Comment by bebnev** [comment]
Doc blocks are generated twice because you set --dir option with the folder that already in app folder (that is parsed automatically and is set in config), so the models are parsed from app folder and then from inner folder app/Models and that is why there are duplicates. As a workaround I add every parsed model to ignore list, so they will not be parsed twice.

**Comment by barryvdh** [comment]
So, #242 is merged, this is fixed?
