### ISSUE TITLE
Chained method not supported?

### ISSUE THREAD

**Issue by justinmoh** [barryvdh/laravel-ide-helper#241]
I installed laravel-ide-helper and following some tutorials on Laracast. Very soon I find this:
![screen shot 2015-07-29 at 2 16 24 am](https://cloud.githubusercontent.com/assets/11174621/8939676/652da87e-3598-11e5-80cf-3d0a977887d7.png)
![screen shot 2015-07-29 at 2 16 46 am](https://cloud.githubusercontent.com/assets/11174621/8939675/6477714e-3598-11e5-87e3-b8e0ccc8b30d.png)

It refers chained method "->nullable()" as undefined. Then I look through other pages, find that another chained method "->unique()" resulting the same.

Did I miss out some steps or this is the limitation of the ide-helper?

**Comment by barryvdh** [comment]
Limitation
