### ISSUE TITLE
Exception: Unknown database type geography requested

### ISSUE THREAD

**Issue by ahmadazimi** [barryvdh/laravel-ide-helper#244]
Hi there,

I've recently try using **PostGIS** in my project. So some of my project models have _geographical_ filelds like Point, Polygon and etc.

Now when I run `ide-helper:models` command, the following error occures:

```
Exception: Unknown database type geography requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
Could not analyze class W3group\Framework\Models\Province.
```

**Comment by wstoettinger** [comment]
+1

is there any way to make the generator ignore this field as a workaround?

**Comment by hohl** [comment]
Any success so far? Or at lest getting laravel-ide-helper to ignore the PostGIS fields?

**Comment by ahmadazimi** [comment]
I'm still waiting for an update...

**Comment by barryvdh** [comment]
Can't that be fixed with config?
https://github.com/barryvdh/laravel-ide-helper/blob/22612733a2c3beddce6f801587926bfceb4440d8/config/ide-helper.php#L89-L117

**Comment by hohl** [comment]
The following config does at least suppress the error message for me:

```    'custom_db_types' => array(
        'postgresql' => array(
            'geography' => 'array',
        ),
    ),```

**Comment by barryvdh** [comment]
So can be closed?

**Comment by hohl** [comment]
I guess so.

**Comment by ahmadazimi** [comment]
@hohl me too!

**Comment by mfn** [comment]
@barryvdh the proposed solution to manually map unkown types is the correct one, issue can be closed :}
