### ISSUE TITLE
Using in production version

### ISSUE THREAD

**Issue by miladrahimi** [barryvdh/laravel-ide-helper#246]
Does it take a so significant resource or else that persuade us to remove it in the server and production version of our Laravel application?

**Comment by gmsantosxl** [comment]
Because it is useless in production. Why you need a IDE helper on production server ?

**Comment by miladrahimi** [comment]
It's time consuming to remove it, and if we don't consider it, syncing with server is so easier, but with it, syncing is mmm shit!

**Comment by gmsantosxl** [comment]
One can simply add the file path to .gitignore and done.

**Comment by barryvdh** [comment]
The file itself does nothing, it's just a file that your ide indexes. It's not loaded.
You service provider is just loading a few commands, so almost no impact.

**Comment by miladrahimi** [comment]
yeah, the created file _id_helper.php is fine and I'm talking about the service, so it's a only few commands you say, no problem, do confirm again?

**Comment by barryvdh** [comment]
It's not a big problem. The service provider should be deferred so only loaded when actually called.

**Comment by miladrahimi** [comment]
Oh, so it seems good, thanks a lot.
