### ISSUE TITLE
error in phpstorm.meta file

### ISSUE THREAD

**Issue by apps4u** [barryvdh/laravel-ide-helper#247]
HI Im getting a error in my phpStorm meta file that stops it from working . e.g.:

`app('')('') => [`

after looking at the contents of the file I noticed that its getting double parentheses and its happens on all version of App.

PhpStrom 9 
build 141.1912 
Laravel 5.0 
php version  5.5.27

os x 10.10

**Comment by barryvdh** [comment]
Did you publish the views to your own dir? If so, can you remove/refresh them?

**Comment by mfn** [comment]
@barryvdh all information here is outdated and the current phpstorm meta works, also the format has changed since then etc. => I vote for closing the issue :}
