### ISSUE TITLE
Model::findOrFail

### ISSUE THREAD

**Issue by miladrahimi** [barryvdh/laravel-ide-helper#248]
It doesn't support this method (findOrFail) and some other methods like Model::save().

I'm using Laravel 5.0 and "barryvdh/laravel-ide-helper": "^2.0".

If there is a simple way to add it myself please explain.

**Comment by Radau** [comment]
As far as findOrFail goes I've had luck using `class CLASSNAME extends \Eloquent` instead of `class CLASSNAME extends Model` within your Model. This workaround will cause it to use the helper file, so I believe you will need to deploy WITH the ide-helper file, but I'm not certain.

That will get most of them working it seems, however I'm still having issues getting `where` to work within my Model, not sure if it has to do with how I'm calling it `$query->where(...`, but using \Eloquent seems to fix most of the methods.

**Comment by miladrahimi** [comment]
Definitely I don't want use \Eloquent instead of Model cause it's the Laravel recommendation,
But It's seems it's not hard to extend this helper. how can I do it?

**Comment by barryvdh** [comment]
It's the same thing, Eloquent is an alias of Model. But because it's an alias, we can use the ide helper for it.

**Comment by miladrahimi** [comment]
So if I use Eloquent (Laravel >= 5), It supports more. ok.

**Comment by pahan35** [comment]
I faced with similar problem today.

I fixed it by adding `|static[]|static|null` to return signature for class `class Eloquent extends \Illuminate\Database\Eloquent\Model` method ` public static function findOrFail($id, $columns = array())` in **_ide_helper.php**

Before
```
            /**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array $columns
             * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
             * @static 
             */ 
            public static function findOrFail($id, $columns = array())
            {    
                return \Illuminate\Database\Eloquent\Builder::findOrFail($id, $columns);
            }

```

After
```
            /**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array $columns
             * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static[]|static|null
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
             * @static 
             */ 
            public static function findOrFail($id, $columns = array())
            {    
                return \Illuminate\Database\Eloquent\Builder::findOrFail($id, $columns);
            }
```

Has anyone any idea how to fix it on generation? Maybe we should add this to phpDoc  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:317 ?
