### ISSUE TITLE
Does not seems to work with Laravel 5.1 and Phpstorm 9.0.0

### ISSUE THREAD

**Issue by gholol** [barryvdh/laravel-ide-helper#249]
I've successfully installed ide-helper via composer, then I executed these commands

`php artisan clean-compiled`
`php artisan ide-helper:generate`
`php artisan optimize`

Restarted IDE, tried to invalidate cache,  it still doesnt work, it looks like _ide_helper file is just ignored.

![fff](http://i.imgur.com/13pZseK.png)

**Comment by barryvdh** [comment]
Why did you close this? Was it fixed?

**Comment by bebnev** [comment]
I think the problem was in using facade namespace, because it it the first that is suggested by phpstorm.

**Comment by mcanaves** [comment]
Could you tell me how you fix this issue? because I have the same problem. Thanks.

**Comment by bebnev** [comment]
In your namespace block use class aliase instead of full path to the facade.
For example:
```php
use DB;
```
instead of 
```php
use Illuminate\Support\Facades\DB;
```

**Comment by karmendra** [comment]
That didn't help. PhpStorm8 with default PasswordController

>use Illuminate\Support\Facades\Password;

and I override `postEmail` in `PasswordController` to add captcha validation

![image](https://cloud.githubusercontent.com/assets/11293052/9993529/ef0223c2-6095-11e5-9896-d17425a6e206.png)

It resolves the Password Facade but not the member function that is actually defined in `\Illuminate\Auth\Passwords\PasswordBroker`. I expected that Password Facade will resolve to ide_helper that has the reference to sendResetLink function.

Any help appreciated.

**Comment by gholol** [comment]
@barryvdh Yes, All i have to do was remove full paths to the facades, just like @bebnev  said.
