### ISSUE TITLE
phpcs Find Error | Whitespace found at end of line

### ISSUE THREAD

**Issue by mahmutbayri** [barryvdh/laravel-ide-helper#251]
Hello,

When i generate model docs ide-helper add an extra space to @property and @property-read line. In this case `phpcs` dedects errors.

Command is : 
``
php artisan ide-helper:models App\Models\UserStatus
``
Generated comment on top of the model class

```
/**
 * App\Models\UserStatus
 *
 * @property boolean $id 
 * @property string $name 
 * @property-read \Illuminate\Database\Eloquent\Collection|\User[] $user 
 * @method static \Illuminate\Database\Query\Builder|\App\Models\UserStatus whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\UserStatus whereName($value)
 */
```

phpcs results
``
phpcs:
    [phpcs]
    [phpcs] FILE: Model path\UserStatus.php
    [phpcs] ----------------------------------------------------------------------
    [phpcs] FOUND 3 ERRORS AFFECTING 3 LINES
    [phpcs] ----------------------------------------------------------------------
    [phpcs]  12 | ERROR | [x] Whitespace found at end of line
    [phpcs]  13 | ERROR | [x] Whitespace found at end of line
    [phpcs]  14 | ERROR | [x] Whitespace found at end of line
    [phpcs] ----------------------------------------------------------------------
    [phpcs] PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    [phpcs] ----------------------------------------------------------------------
    [phpcs]
    [phpcs] Time: 91ms; Memory: 2.75Mb
    [phpcs]
    [phpcs] Result: 1
``

Thanks

**Comment by barryvdh** [comment]
I guess this is fixed with https://github.com/barryvdh/laravel-ide-helper/pull/252 ?
