### ISSUE TITLE
could not analyze model extended from pivot 

### ISSUE THREAD

**Issue by hamidzmi** [barryvdh/laravel-ide-helper#253]
i have a pivot table who have relationship to other table.
after run 
php artisan ide-helper:models
says could not analyze the class how extended from pivot

**Comment by barryvdh** [comment]
Can you paste your relevant code?

**Comment by hamidzamani** [comment]
my code is this: http://stackoverflow.com/questions/32033235/laravel-eloquent-one-to-many-relationship-in-custom-pivot-not-works

**Comment by mpyw** [comment]
Same problem, +1

**Comment by WickedSik** [comment]
I have the same problem +1

@barryvdh I do not have any suggestions as how to fix this.

What I have seen is that the subclass isn't registered correctly (I think). By changing the test a little, I've seen this:

**Changed (src/Console/ModelsCommand.php:184) :**

```
if (!$reflectionClass->isSubclassOf('Illuminate\Database\Eloquent\Model')
        || $reflectionClass->isSubclassOf('Illuminate\Database\Eloquent\Relations\Pivot')) {

    if ($this->output->getVerbosity() >= OutputInterface::VERBOSITY_VERBOSE) {
        $this->comment("Model '$name' is no valid Model or Pivot: " . print_r($reflectionClass->getParentClass(), true));
    }

    continue;
}
```

**Relevant output:**

```
Model 'App\Models\Personal\Consumation\Scholarship' is no valid Model or Pivot: ReflectionClass Object
(
    [name] => Illuminate\Database\Eloquent\Relations\Pivot
)
```

**Comment by WickedSik** [comment]
Now that I read this. Isn't it the problem that there's a missing `!` in front of the second check?

**Comment by barryvdh** [comment]
Looks like it indeed.

**Comment by 4n70w4** [comment]
The same problem

**Comment by 4n70w4** [comment]
The fast solution for `_ide_helper.php`

replace:

`class Eloquent extends \Illuminate\Database\Eloquent\Model {`

to:

`class Eloquent extends \Illuminate\Database\Eloquent\Relations\Pivot {`
