### ISSUE TITLE
Branch 1.1 not fully compatible with Laravel 4.2 and PHPStorm 9

### ISSUE THREAD

**Issue by mechanicious** [barryvdh/laravel-ide-helper#255]
This gist: https://gist.github.com/barryvdh/bb6ffc5d11e0a75dba67 provides auto-completion for e.g. `app('events')` (IoC bindings), but not for `Event` (Facade aliases).

This gist: https://gist.github.com/barryvdh/5227822/f8082a17dfad6f01d6544194b347601dc048fc2a provides auto-completion for Facade aliases but not for IoC bindings.

Note: using both at the same time doesn't work either. Only Facade aliases auto-completion persists.

**Comment by shehi** [comment]
That's why using Facades isn't a good idea if you care about IDE resolutions.

**Comment by mfn** [comment]
@barryvdh can be closed, L4.* isn't relevant anymore
