### ISSUE TITLE
SublimeText 3 Support

### ISSUE THREAD

**Issue by esinanturan** [barryvdh/laravel-ide-helper#256]
Does this helper support sublime-text 3 , ıt says yes but i couldn't integrate , could you explain how to work with this helper on sublime text , thanks

**Comment by phillipmadsen** [comment]
I  would also like to find out how to make this work please

**Comment by royduin** [comment]
I'm interested too.

**Comment by churiart** [comment]
Any answer on this issue is really appreciated.

**Comment by barryvdh** [comment]
I don't know, don't use it. There used to be a codeintel package, not sure what it does now.
It doesn't doe anything specific for any ide, so if Sublime supports phpdocs from other files, it should be good..

**Comment by acccounttest** [comment]
I fully generated a file of 419 ko using the switch --sublime in generate command but codeintel seems to not works with the file ?

**Comment by yuceltoluyag** [comment]
++

**Comment by mfn** [comment]
Sublime code generation has been marked as "DEPRECATED". Since 7 years 🤷‍♀️. And the flag even doesn't do anything.

Except one file, everything generated is "IDE agnostic" so it's up to the IDEs to support this

@barryvdh I vote for closing this :}
