### ISSUE TITLE
Cartalyst Sentinel compatibility

### ISSUE THREAD

**Issue by henriale** [barryvdh/laravel-ide-helper#257]
laravel-ide-helper can not find Sentinel's functions!
It says "Method 'register' not found in class Cartalyst\Sentinel\Laravel\Facades\Sentinel" everywhere I use it.

I've looked around for something similar, but I couldn't find anything.
Is there any generated configuration about it?

I'm running Laravel 5.1 and using phpStorm as editor

**Comment by bebnev** [comment]
Hello.
The first problem is that you are using the namespace of the Sentinel Facade and not Sentinel class alias.
I mean:
```php
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

// something here

public function index()
{
  Sentinel::register();
}
```
But it should be:
```php
use Sentinel; // or whateever alias that you have set in the app.php as a sentinel facade resolver

// something here

public function index()
{
  Sentinel::register();
}
```
And secondly, have a look at the issue [250](https://github.com/barryvdh/laravel-ide-helper/issues/250#issuecomment-129533678) where I have described how to add Sentinel "magic" methods to the autocompletion.

**Comment by mfn** [comment]
@barryvdh this is similar to https://github.com/barryvdh/laravel-ide-helper/issues/250 and https://github.com/barryvdh/laravel-ide-helper/issues/330 , there are workarounds available if the 3rd party provided package does not have proper clas phpdoc method annotations for this; not much we can do here => I vote for closing this issue :}
