### ISSUE TITLE
How to check _ide_helper.php file is working or not??

### ISSUE THREAD

**Issue by sks1990** [barryvdh/laravel-ide-helper#258]
Hello Barryvdh,

I am newbie in laravel framework.I have not identify the ide_helper.php file  is working or not.

I have  moved All code new  server then code is not running proper and not show the any error.

please help me.

**Comment by bebnev** [comment]
Hello. 
_ide_helper.php or any ather generated file from the package has no impact on the work of the laravel application, of cource if you installed everything accordingly to the given instruction in [readme.md](https://github.com/barryvdh/laravel-ide-helper/blob/master/readme.md).

**Comment by sks1990** [comment]
Thanks Bebnew for replay.

**Comment by mfn** [comment]
@barryvdh looks like a support issue, IMHO can be closed :}
