### ISSUE TITLE
app('db') vs \Db facade

### ISSUE THREAD

**Issue by shehi** [barryvdh/laravel-ide-helper#260]
Whereas code such as:
```
\Db::table('reminders')->where('user_id', '=', 1)->value('code');
```
works (i.e. IDE resolves successfully), its non-facade, resolved counterpart:
```
app('db')->table('reminders')->where('user_id', '=', 1)->value('code');
```
doesn't (code itself works, but IDE can't resolve). Error given is "method ```table()``` not found". All other Facade resolutions such as ```app('events')``` etc successfully work in IDE, but for some reason ```app('db')``` doesn't. Any ideas how to fix this?

**Comment by barryvdh** [comment]
Yes, use the Phpstorm meta file.

**Comment by shehi** [comment]
I am :) That's why everything works honkie-dorie, except ```app('db')``` :)

**Comment by bebnev** [comment]
`app('db')` returns instance of `Illuminate\Database\DatabaseManager` which doesn't have method `table` (for example). All that methods are resolved via `__call` and via `DatabaseManager connection` method.
So, to see autocompletion, you can use such workaround:
```php
app('db')->connection()->table();
```
which is the same to 
```php
app('db')->table();
```

**Comment by shehi** [comment]
I know all that @bebnev , I wasn't asking for help :) I was just pointing out a behaviour/"bug" which isn't quite aligned with the purpose of this package.

**Comment by shehi** [comment]
@barryvdh , do you see any way to make IDE think ```app('db')``` is equivalent to ```app('db')->connection()``` ?

**Comment by shehi** [comment]
Changing line 438 in PHPStorm meta file from 
```'db' instanceof \Illuminate\Database\DatabaseManager,```
TO
```'db' instanceof \Illuminate\Database\Connection,```
fixes the issue. Since I don't know the intricacies of this tool and Laravel's Db component, I can't provide any better solutions. Using ```\Db``` facade works fine, but that is totally different topic as facades work through ```_ide_helper.php``` file, not ```phpstorm.meta.php```.

**Comment by shehi** [comment]
@barryvdh , is there *anything* planned in this regard, or shall I just close this issue and forget about it? :) I don't really want it clutter your Issues list.

**Comment by barryvdh** [comment]
One alternative would be to generate the list based on Facades, not actual implementations, but that would be kind of ugly. Not sure if there is any syntax to add 2 classes to 1 entry.

**Comment by shehi** [comment]
Ok, closing this for now, let it remain as a record for those who end up here via search.
