### ISSUE TITLE
Autocomplete shows incorrect syntax for Input request

### ISSUE THREAD

**Issue by battlesteel** [barryvdh/laravel-ide-helper#263]
I found a bug when i was writing code to rename an uploaded file before saving in a dir. I noticed the autocomplete shows me 2 "move". As you can see in screenshot 1. After selecting the second "move", it shows me something else, as you can see in screenshot 2.

Screenshot 1
![screenshot_1](https://cloud.githubusercontent.com/assets/10210396/10120536/d3e0453a-6494-11e5-944c-2e635fb438fe.png)

Screenshot 2
![screenshot_2](https://cloud.githubusercontent.com/assets/10210396/10120537/d3e32250-6494-11e5-920e-a805b8d7fc3e.png)

**Comment by mfn** [comment]
I don't see the relation to this package, what am I missing?

I can barely see that the referenced class is "Requests\BannerRequest"??

This seems to reference a concrete class and not a facade so this isn't directly subject to anything this package provides?

Rather it looks like a confused auto-complete.

@barryvdh looks like an old support issue, I vote for closing :}
