### ISSUE TITLE
Problem with generated ide_helper namespace in Laravel 4.2.x

### ISSUE THREAD

**Issue by anandabudi** [barryvdh/laravel-ide-helper#264]
I have a problem with namespace after generating the `ide_helper` for my `facade` class. The problem is, it looks like the generator couldn't recognize the namespace from the `use` statement in the beginning of the main class (`YUtilities`).

I used these chain of commands when generating the ide_helper
- `composer dump-autoload`
- `php artisan dump-autoload`
- `php artisan ide-helper:generate`
### The main class (YUtilities)

```
<?php namespace App\Libraries\Utilities;

use App\Models\Translation\Language;

class YUtilities
{

    /**
     * Count sentence unit (character or word)
     *
     * @param String   $sentence      Source sentence
     * @param Language $languageModel Language Model

     * @return int
     */
    public static function countUnit($sentence, Language $languageModel)
    {
        $unitCount = 0;

        return $unitCount;
    }
}
```
### Language class

```
<?php namespace App\Models\Translation;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    ....
}
```
### Generated _ide_helper class

```
/**
 * Count sentence unit (character or word)
 *
 * @param String $sentence Source sentence
 * @param \App\Libraries\Utilities\Language $languageModel Language Model
 * @return int 
 * @static 
 */
public static function countUnit($sentence, $languageModel){
    return \App\Libraries\Utilities\YUtilities::countUnit($sentence, $languageModel);
}
```

As you can see from the snippet, the doc from the generated `ide_helper` file produced the wrong namespace for the `Language` model. Instead of `App\Models\Translation\Language`, the generator took the root namespace of the main `YUtilities` class (`App\Libraries\Utilities`).

I tried to use the full `namespace` of `Language` model inside `countUnit()` function's parameter, and it solved the problem, but my IDE throws a warning, because I shouldn't use a full namespace inside the parameter.

```
public static function countUnit($sentence, App\ModelsTranslation\Language $languageModel) {
......
}
```

So, is this a bug with the current version of `ide_helper` ? I'm sorry if the answer/solution for this problem is quite obvious, I already tried to find similar issue in the internet, but couldn't find similar issue with me.

Thanks for your help. 

Cheers !

**Comment by mfn** [comment]
@barryvdh this can be closed as duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/627 :}

**Comment by mfn** [comment]
Closing per my comment https://github.com/barryvdh/laravel-ide-helper/issues/264#issuecomment-650617865
