### ISSUE TITLE
on L5.1 ide-helper:models  Modelname > no phpdoc generated

### ISSUE THREAD

**Issue by zofe** [barryvdh/laravel-ide-helper#265]
I'm on L 5.1.19 
running:
`php artisan ide-helper:models User`
generate an empty file _ide_helper_models.php  (except for top generic comment block "An helper..")

II've tried also with --write  but models seems untouched,  no phpdoc  is generated

I've  "doctrine/dbal": "~2.3" on require-dev  and 
`php artisan ide-helper:generate` seems to work correctly

**Comment by brazenvoid** [comment]
+1

**Comment by shehi** [comment]
If your models are not located inside ```app/``` directory, you should provide a location for them. Additionally, you will have to provide FQNamespace for your models as well:

```./artisan ide-helper:models --dir='app/Models' \App\Models\User```

**Comment by zofe** [comment]
Thanks all @shehi  adding full namespace solved the issue 
php artisan ide-helper:models "\App\Curriculum"

I think I can close,  @barryvdh already documented on readme to use full namespace, so my mistake.

**Comment by johlton** [comment]
Sorry to reopen/hijack this.

This problem persists on my machine in Laravel 5.3.24 and PHPStorm 2016.2.2 (Build #PS-162.2380.11, built on October 24, 2016). My models sit in app\Models. 

`php artisan ide-helper:generate` & `php artisan ide-helper:meta` ran smoothly. 

When running `php artisan ide-helper:models`: No error, but nothing written.
When running `php artisan ide-helper:models User`: No error, but nothing written.
When running `php artisan ide-helper:models --dir="app\Models"`: No error, but nothing written.
When running `php artisan ide-helper:models "\App\Models\User"`: Error "Exception: could not find driver. Could not analyze class \App\Models\User."

Any help would be highly appreciated.

**Comment by apoca** [comment]
I have the same issue: php artisan ide-helper:models --dir="app/Models" --dir="\App\Models"

only runs for a few Models (11) and have more than 40 Models ...
