### ISSUE TITLE
No support for strict_types on PHP 7

### ISSUE THREAD

**Issue by igorsantos07** [barryvdh/laravel-ide-helper#267]
Current implementation complains about unknown `declare` for strict_types. Also, if that line is commented, it further complains that default values with classes typehint should always be null, in a code like `test(string $var = '') { }`

**Comment by shehi** [comment]
Laravel 5.1 itself isn't PHP 7 ready at the moment. Right now IDE-helper has more important problems with PHP 5.x side of things, I don't think PHP 7 should have higher priority for early future.

**Comment by igorsantos07** [comment]
Well, I've started using Laravel 5.1 with PHP7 and it didn't show any problems for now - but my project is still in its early stages. Also, Homestead have released support for PHP7 as well. So I guess it is, indeed, PHP7 ready.

Meanwhile, I do understand your point about this project. I don't think PHP7 should indeed have higher priority, but it's still a big issue nonetheless, that should be seen when the time arrive :)

**Comment by Namoshek** [comment]
I'd like to revive this issue as the `_ide_helper.php` file generated with `php artisan ide-helper:generate` copies `declare(strict_types=1);` from source files specified in `config/ide-helper.php` within the `helper_files` array. This leads to multiple declarations in the helper file, which isn't allowed by the PHP spec and therefore IDEs complain quite a bit.

It would probably be enough to also replace `declare(strict_types=1);` at the same time as `<?php` when including helper files here:
https://github.com/barryvdh/laravel-ide-helper/blob/32df0a3bc641aa225f7ec988c1d5a95509f20e28/src/Console/GeneratorCommand.php#L102-L108
It should be noted that there can be different notations (like `declare(strict_types = 1);`, which makes replacement by regex more suitable.

**Comment by mfn** [comment]
I can confirm this, but:

What is the real use-case for having the helper files define in here?

For me, PhpStorm already properly autocompletes this even without this in `_ide_helper.php`, simply because any `vendor/` file is available for autocomplete anyway.
