### ISSUE TITLE
ide-helper generate Mail and Password facades are skipped

### ISSUE THREAD

**Issue by jimmck** [barryvdh/laravel-ide-helper#272]
When a queue is NOT running and you generate a helper file, the Mail and Password Laravel Facades are skipped with a Connection Refused error.  Seems related to Mailer ???

See Trace.

Jamess-MacBook-Pro:laravel5 jimm$ art ide-helper:generate
#0 /Users/jimm/GitHub/laravel5/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(195): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 /Users/jimm/GitHub/laravel5/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(179): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 /Users/jimm/GitHub/laravel5/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(41): PhpAmqpLib\Connection\AbstractConnection->__construct('guest', 'guest', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#3 /Users/jimm/GitHub/laravel5/vendor/fintech-fab/laravel-queue-rabbitmq/src/FintechFab/LaravelQueueRabbitMQ/Queue/Connectors/RabbitMQConnector.php(20): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('127.0.0.1', 5672, 'guest', 'guest', '/')
#4 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(133): FintechFab\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector->connect(Array)
#5 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(113): Illuminate\Queue\QueueManager->resolve('rabbitmq')
#6 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php(68): Illuminate\Queue\QueueManager->connection()
#7 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): Illuminate\Queue\QueueServiceProvider->Illuminate\Queue{closure}(Object(Illuminate\Foundation\Application), Array)
#8 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build(Object(Closure), Array)
#9 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('queue.connectio...', Array)
#10 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(1159): Illuminate\Foundation\Application->make('queue.connectio...')
#11 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(78): Illuminate\Container\Container->offsetGet('queue.connectio...')
#12 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(34): Illuminate\Mail\MailServiceProvider->setMailerDependencies(Object(Illuminate\Mail\Mailer), Object(Illuminate\Foundation\Application))
#13 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): Illuminate\Mail\MailServiceProvider->Illuminate\Mail{closure}(Object(Illuminate\Foundation\Application), Array)
#14 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build(Object(Closure), Array)
#15 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('mailer', Array)
#16 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(1159): Illuminate\Foundation\Application->make('mailer')
#17 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(155): Illuminate\Container\Container->offsetGet('mailer')
#18 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(118): Illuminate\Support\Facades\Facade::resolveFacadeInstance('mailer')
#19 /Users/jimm/GitHub/laravel5/vendor/barryvdh/laravel-ide-helper/src/Alias.php(189): Illuminate\Support\Facades\Facade::getFacadeRoot()
#20 /Users/jimm/GitHub/laravel5/vendor/barryvdh/laravel-ide-helper/src/Alias.php(45): Barryvdh\LaravelIdeHelper\Alias->detectRoot()
#21 /Users/jimm/GitHub/laravel5/vendor/barryvdh/laravel-ide-helper/src/Generator.php(176): Barryvdh\LaravelIdeHelper\Alias->__construct('Mail', 'Illuminate\Supp...', Array, Array)
#22 /Users/jimm/GitHub/laravel5/vendor/barryvdh/laravel-ide-helper/src/Generator.php(81): Barryvdh\LaravelIdeHelper\Generator->getNamespaces()
#23 /Users/jimm/GitHub/laravel5/vendor/barryvdh/laravel-ide-helper/src/Generator.php(71): Barryvdh\LaravelIdeHelper\Generator->generatePhpHelper()
#24 /Users/jimm/GitHub/laravel5/vendor/barryvdh/laravel-ide-helper/src/Console/GeneratorCommand.php(113): Barryvdh\LaravelIdeHelper\Generator->generate('php')
#25 [internal function]: Barryvdh\LaravelIdeHelper\Console\GeneratorCommand->fire()
#26 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Container/Container.php(503): call_user_func_array(Array, Array)
#27 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#28 /Users/jimm/GitHub/laravel5/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/jimm/GitHub/laravel5/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /Users/jimm/GitHub/laravel5/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\LaravelIdeHelper\Console\GeneratorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /Users/jimm/GitHub/laravel5/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /Users/jimm/GitHub/laravel5/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Users/jimm/GitHub/laravel5/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}

Exception: Error Connecting to server (61): Connection refused
Sk

**Comment by mfn** [comment]
This is the same as https://github.com/barryvdh/laravel-ide-helper/issues/237 but with more details 👍 

This happened with Laravel 5 and I happen to use (redis [a]sync) driver and it works generating the Mail facade correct on nowadays Laravel versions even when I shut down redis.

Maybe it's Amqp specific but it's all outdated code versions from the initial report.

I guess "5 years ago" there was something to it but I would only go after this if we get a new report.

@barryvdh same as https://github.com/barryvdh/laravel-ide-helper/issues/237 I vote for closing this :}
