### ISSUE TITLE
Auth::user resolves to wrong type

### ISSUE THREAD

**Issue by tkuijer** [barryvdh/laravel-ide-helper#274]
In my project I have moved the normal `App\User` to `Domain\Models\User` (Residing in the app\Models folder). I also modified my auth configuration file to reflect this change. However the `ide-helper:generate` command doesn't pick up on this change and instead points the `Auth::user()` to the standard App\User model

**Comment by shehi** [comment]
See readme file in repo, read it completely. You are wasting people's time.

**Comment by barryvdh** [comment]
@shehi Relax, nothing wrong with asking a question.

See the config file here: 
https://github.com/barryvdh/laravel-ide-helper/blob/master/config/ide-helper.php#L86

It should replace `\Illuminate\Contracts\Auth\Authenticatable` with `config('auth.model', 'App\User'),`.
If `auth.model` is set, it should use that. But perhaps you have an old published config?

You are talking about the _ide_helper.php file, right?

**Comment by shehi** [comment]
@barryvdh : I never needed all that - just give ```--dir=``` parameter and provide model's FQN, and any model should be mapped. I have Cartalyst's Sentinel running the show in my app, and it needs changing nothing at all, to get doc generation.

**Comment by tkuijer** [comment]
I did find the option in the ide-helper configuration file (after posting
this issue, my fault..) however this should default to looking at the auth
config file, which doesn't appear to be working, so it uses the default
(which I now modified to reflect my project)
Op 22 okt. 2015 12:38 schreef "Şəhriyar İmanov" <notifications@github.com>:

**Comment by barryvdh** [comment]
Could be due to the order of loading the config (or service provider) and/or caching the configs.

**Comment by tkuijer** [comment]
This seems to match my findings while debugging. Looks like the `auth.model` configuration key isn't set at the time it gets requested by the ide-helper config file.

**Comment by barryvdh** [comment]
I guess an option would be to leave our config 'null' and request the Auth model on runtime, then we're sure it's available.

**Comment by tkuijer** [comment]
Sounds like that would be a good solution. Rather than configuring the model in the `ide-helper` configuration file, request it when we're sure it's available.

**Comment by barryvdh** [comment]
Did that in above commit. Doesn't work for people who published their configs though.

**Comment by rickselby** [comment]
For 5.2, this should be auth.providers.users.model. Not sure you can check the version in the config file though?
