### ISSUE TITLE
I dont know why you remove the magic where method in your dev-master

### ISSUE THREAD

**Issue by imvkmark** [barryvdh/laravel-ide-helper#276]
Can you say it?

**Comment by barryvdh** [comment]
Not really convinced of their usefulness, seems a bit 'much' when you have lot of columns.

Was thinking about making it optional.

**Comment by imvkmark** [comment]
I think has another reason . if there is another column named in or not_in and etc, will conflict with default method, thank you for your answer.and my project used more method like where* , so i asked this question
