### ISSUE TITLE
Methods not showing when using FormRequests even though they do work

### ISSUE THREAD

**Issue by jonnywilliamson** [barryvdh/laravel-ide-helper#277]
I have a controller with a method that uses a [FormRequest](http://laravel.com/docs/master/validation#form-request-validation)

In the method I want to get some data from the Request, so I use:

``` php
    public function processForm(RegisterForm $request)
    {
     //snip
        $name = $request->input('name');
      //do stuff
     }
```

This _WORKS_

However, I can't get the `$request->input()` method autocomplete from my IDE even thought it is available to the Request object.

So I took a look and I don't know why it doesn't inherit a _lot_ of methods from the main Request object it extends. This is how I can recreate this issue

Make a new FormRequest:

``` php
`artisan make:request demo`
```

Now open `\App\Http\Requests\demo.php` and you see:

``` php
namespace App\Http\Requests;

use App\Http\Requests\Request;

class demo extends Request
{
      //removed
}

```

Going up the extended chain, we now open `App\Http\Requests\Request` and it shows

``` php
abstract class Request extends FormRequest
{

}
```

Open  `\Illuminate\Foundation\Http\FormRequest`

``` php
class FormRequest extends Request implements ValidatesWhenResolved
{

}
```

Finally we open `\Illuminate\Http\Request` where the Input (and many other) methods are found.

``` php
class Request extends SymfonyRequest implements ArrayAccess
{
    //snip
    /**
     * Retrieve an input item from the request.
     *
     * @param  string  $key
     * @param  string|array|null  $default
     * @return string|array
     */
    public function input($key = null, $default = null)
    {
        $input = $this->getInputSource()->all() + $this->query->all();

        return Arr::get($input, $key, $default);
    }

}
```

Is this a bug or can the IDE-HELPER not inherhit all these methods because the class has been extended so often/much?

At the moment when I try to see what I can autocomplete on the request object I only see these methods:

![image](https://cloud.githubusercontent.com/assets/2513663/11021236/0149f682-8633-11e5-8354-39695a2b933e.png)

Can't thank you enough for this project. It makes such a difference to my workflow. Thank you.

**Comment by mfn** [comment]
@jonnywilliamson how did you get to have `$request`, i.e. how it's supposed to be  a `DemoRequest extends FormRequest` but how did you construct/request it in the context?
