### ISSUE TITLE
An option for not generating static whereColumn methods

### ISSUE THREAD

**Issue by halaei** [barryvdh/laravel-ide-helper#278]
Is there any option for not generating static whereColumn methods in models? This is just a coding style preference we have. We prefer not to use those static methods, and not to have the extra doc blocks.

Thanks for the great packages.

**Comment by isaackearl** [comment]
with laravel 5.2 the package seems to have stopped generating the whereColumn methods...

**Comment by mfn** [comment]
There's now a `write_model_magic_where` config with which this can be turned off

@barryvdh all solved here, issue can be closed :}
