### ISSUE TITLE
in phpstorm8,.phpstorm.meta.php was error,why,??

### ISSUE THREAD

**Issue by buuug7** [barryvdh/laravel-ide-helper#282]
in phpstorm8,.phpstorm.meta.php was error,why,??
![image](https://cloud.githubusercontent.com/assets/12119289/11559829/ccce0dee-99f6-11e5-8d88-5445ddc7ff3b.png)

**Comment by OddGreg** [comment]
This is normal because .phpstorm.meta.php does NOT use valid syntax. Note these comments found in the file as described by JetBrains:
```<?php
// This file is not a CODE, it makes no sense and won't run or validate
// Its AST serves IDE as DATA source to make advanced type inference decisions.
```

See [JetBrains PhpStorm Advanced Metadata](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata)

**Comment by shehi** [comment]
@barryvdh : shelf it? :)
