### ISSUE TITLE
Problem installing IDE helper _Laravel 5_

### ISSUE THREAD

**Issue by elmarssi2015** [barryvdh/laravel-ide-helper#284]
Hello everybody.

I have a problem installing the helper using Composer ; here is the output 

php artisan clear-compiled  
  [UnexpectedValueException]  
  Invalid route action: [App\Http\Controllers]  
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error  
  [RuntimeException]  
  Error Output:  
require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

Anybody can explain to me what's this and give me a solution,because i'm a newbie on Laravel FrameWork so i wanna install this Helper.

**Comment by EselDompteur** [comment]
It's not an error by IDE-HELPER ...

You have an error in your route.php ( a typo I suppose ) ... your should see this error on every artisan-command ... fix your route.php first and try again

**Comment by shehi** [comment]
Yea, and close this issue please.

**Comment by mfn** [comment]
@barryvdh not related to ide-helper, issue can be closed :}
