### ISSUE TITLE
Non-static method, why?

### ISSUE THREAD

**Issue by facebear** [barryvdh/laravel-ide-helper#285]
"require": {
        "barryvdh/laravel-ide-helper": "v2.1.0"
    },

Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

![untitled-3](https://cloud.githubusercontent.com/assets/16147464/11583579/7b7e9758-9a6c-11e5-804d-98487ca53740.png)

**Comment by aphofstede** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/95

**Comment by mfn** [comment]
@barryvdh this is the same as https://github.com/barryvdh/laravel-ide-helper/issues/95 and for the same reason this issue can be closed :}
