### ISSUE TITLE
Exception: Missing argument 1 for Illuminate\Database\Eloquent\Model::morphedByMany()

### ISSUE THREAD

**Issue by catalinux** [barryvdh/laravel-ide-helper#286]
When I run 
`php artisan ide-helper:models`

I get:
Exception: Missing argument 1 for Illuminate\Database\Eloquent\Model::morphedByMany() ... vendor/barryvdh/laravel-ide-helper/src/Conso
le/ModelsCommand.php on line 365 and defined

I am using

```
    "laravel/framework": "5.0.*",
    "illuminate/html": "5.0.*",
```

**Comment by shehi** [comment]
Fix your models?

**Comment by catalinux** [comment]
I would like to, but I do not know how. I do not  have any morphing relation. Actually I get  the error also when I remove my only `hasMany` relation.

**Comment by fpm5022** [comment]
+1

**Comment by lbogdan** [comment]
This might be related to not having the alias 'Eloquent' defined. See https://github.com/barryvdh/laravel-ide-helper/issues/311 .

**Comment by catalinux** [comment]
I'll look into it . Tx

**Comment by mfn** [comment]
`morphedByMany` works and we even have a few tests with this; I this this is just outdated

@barryvdh I vote for closing :}
