### ISSUE TITLE
getDefaultValue fails on variadic params

### ISSUE THREAD

**Issue by miraage** [barryvdh/laravel-ide-helper#287]
https://github.com/barryvdh/laravel-ide-helper/blob/v2.1.0/src/Console/ModelsCommand.php#L533

Here should be a check for `$param->isDefaultValueAvailable()` before `$param->getDefaultValue()`.

**Comment by barryvdh** [comment]
Can you submit a PR?

**Comment by miraage** [comment]
I think I could.

**Comment by miraage** [comment]
Since PR has been merge issue is resolved.
