### ISSUE TITLE
PHP 7 return type hints. PHP Parse error on ide-helper:generate

### ISSUE THREAD

**Issue by martindilling** [barryvdh/laravel-ide-helper#292]
Sorry, I don't really have time to look into it right now, will maybe dig around when I can find the time.
But couldn't find an issue here, so I thought I'd create one :)

I'm using this with Laravel 5.1 running on PHP7, It worked fine until I used return type hinting for a class the generate command tries to generate from.

```
Script php artisan ide-helper:generate handling the post-update-cmd event returned with an error
                                                                                                                     
[RuntimeException]                                                                                                                                                            
Error Output: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in file.php on line 35
```

I've seen this for some time, but now that php7 is released I thought it was worth creating this issue :)

**Comment by barryvdh** [comment]
What is `file.php`?

**Comment by martindilling** [comment]
Sorry, that's just a file in my project using return type hints :)
It's pointing to the first line in this:
```
35: public function createCustomer(string $name, string $email, Address $address): Customer
36: {
37:    // Stuff happens
38: }
```

**Comment by barryvdh** [comment]
And does it work in the rest of your project?

**Comment by barryvdh** [comment]
Is you CLI php version also 7?

**Comment by martindilling** [comment]
It works fine in the project yes.

...well.... sorry to bother you, that was embarrassing xD But thanks for the help :)
\*I'll just back silently out of here now ;)*
