### ISSUE TITLE
No creating @method comments for blocks

### ISSUE THREAD

**Issue by godjen99** [barryvdh/laravel-ide-helper#300]
First, let me say I love and appreciate the project @barryvdh . It's been a real time saver!

Ran into something interesting today. I've recently upgraded my app to Laravel 5.2 (I'm not sure if this had anything to do with it, I just noticed it after upgrading and trying to run the plugin) and now when creating models (or re-generating old models) the @method for each of the fields are not being generated. 

For example:
Previous model (before update)
```
/**
 * App\SomeModel
 *
 * @property integer $id
 * @property string $uuid
 * @property string $first_name
 * @property string $last_name
 * @property string $date_of_birth
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereUuid($value)
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereFirstName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereLastName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereDateOfBirth($value)
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\SomeModel whereUpdatedAt($value)
 */
```
If I delete the comments and re-run the helper, now I get this...
```
/**
 * App\SomeModel
 *
 * @property integer $id
 * @property string $uuid
 * @property string $first_name
 * @property string $last_name
 * @property string $date_of_birth
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
```

**Comment by brazenvoid** [comment]
I am having this issue in 5.1 since some time now, thus we have stopped running the generator reset but that's just a lame workaround.

**Comment by brazenvoid** [comment]
If you want, you can copy the ModelsCommand file from my fork to have a quick fix, well until someone sends a PR here with a more proper solution. 
https://github.com/brazenvoid/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php

**Comment by barryvdh** [comment]
I'll add it back soon.

**Comment by icedfish** [comment]
+1

**Comment by godjen99** [comment]
Good news @barryvdh, thanks!

**Comment by icedfish** [comment]
Hello guys，
  Any updates?

**Comment by mfn** [comment]
For anyone in desperate need of them, this commit removed them: 76f09aaa65121b800c04394bd32dca78c3810b5c

**Comment by icedfish** [comment]
@barryvdh I add an PR https://github.com/barryvdh/laravel-ide-helper/pull/314 for this issue, 
and did a little change:

                    Only add whereXXX() helper function comment to _ide_helper_models.php,
                    keep model file as simple as possible.

Please take the PR if you think it's ok for most situation.

**Comment by mfn** [comment]
I still think it's bad move to remove this feature in a minor version, add it back a few versions later but with *different* semantics :-(

Some may prefer to have it in their model. My suggestion would be to
1. reinstate as it was
2. break that change for a next major version but
3. keep BC with a switch for those who want it

Of course 2. and 3. only it really must be done.

Just my 2c; thx :-)

**Comment by barryvdh** [comment]
Yeah guess I'll add it back.
