### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by brynnb** [barryvdh/laravel-ide-helper#304]
While I appreciate the efforts of this package, it's a bit of a hassle for me to SSH into my VM every time I want to run composer update/install. I removed the requirement from my composer.json file and removed the entry in my config/app.php, but I am still getting a `SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.` when I run `php artisan optimize` which I believe is tied to ide-helper trying to do stuff. I cannot figure out how it is hooking into `php artisan optimize` - any pointers?

Thanks.

**Comment by pietdevries94** [comment]
php artisan optimize is a laravel command. There is something prevent you from connecting with your database, but it's not a ide-helper issue.

**Comment by brynnb** [comment]
@pietdevries94 I could be totally wrong, but I was under the impression that `php artisan optimize` did not normally need a database connection. I thought there was something about laravel-ide-command that tied into this command that required the database connection. Am I wrong?

**Comment by pietdevries94** [comment]
@brynnb Ok, you have a good point. I seems that optimize will indeed touch the database when there is a global script that touches it (like routes).

However, the steps you did should be enough, but I doubt it's ide-helper. Are there any othere packages you added to Laravel which use the database on a "global" level? Maybe you changed a setting. Anything that will touch the database when loading the framework?

**Comment by brynnb** [comment]
@pietdevries94 Could you describe the method or the file name/line number of how ide-helper ties into `php artisan optimize`? It's a bit difficult to "follow the rabbit hole" going through Laravel's code to see where it might be tying in. I am not sure how best to check for what you asked.

I feel bad using the issues here as my own personal helpdesk, especially because this is possibly not ide-helper related at all, but here's my composer.json:

```
 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "intervention/image": "^2.3",
        "laravelcollective/html": "~5.0",
        "league/flysystem-rackspace": "~1.0",
        "intervention/imagecache": "^2.3",
        "algolia/algoliasearch-laravel": "^1.0",
        "rtconner/laravel-tagging": "~2.0",
        "guzzlehttp/guzzle": "~5.3|~6.0",
        "laracasts/flash": "^1.3",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "ext-gd": "*",
        "brynnb/chargify-laravel-v2": "dev-master",
        "brynnb/chargify-laravel": "dev-master",
        "bogardo/mailgun": "dev-use172"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "laravel/homestead": "^2.1"
    },
```

I do not believe any of these other packages would tie into the database on running `php artisan optimize`, but again could be totally wrong. Thanks for your help!

**Comment by brynnb** [comment]
Nevermind, found the issue: 

```
    public function boot()
    {
        $settings = Settings::first();
        view()->share('settings', $settings);
    }
```

inside my `AppServiceProvider.php`. Sorry for wasting your time!
