### ISSUE TITLE
Laravel 5.2 There is no autocomplete for Auth alias

### ISSUE THREAD

**Issue by grinry** [barryvdh/laravel-ide-helper#307]
Helper does not create methods for 'Auth' alias in Laravel 5.2

```
Auth::user()
Auth::check()
Auth::attempt()
```

**Comment by iwex** [comment]
Yes, I have such problem too

**Comment by ellisthedev** [comment]
This is fixed on `dev-master`.

**Comment by mfn** [comment]
@barryvdh all here fixed already, issue can be closed :}
