### ISSUE TITLE
[Lumen] Exception: Missing argument 1 for Illuminate\Database\Eloquent\Model::morphedByMany()

### ISSUE THREAD

**Issue by lbogdan** [barryvdh/laravel-ide-helper#311]
In a Lumen application, running "php artisan ide-helper:models" gives the error "Exception: Missing argument 1 for Illuminate\Database\Eloquent\Model::morphedByMany()".

While trying to debug it, I stumbled upon https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L335 , which does a method_exists() on the alias 'Eloquent', but this is not defined in Lumen. Can 'Eloquent' be changed to '\Illuminate\Database\Eloquent\Model' on that line? If this would break compatibility (although I don't see how), at least check if class 'Eloquent' exists, and give a warning if it doesn't. The error we get now is not at all obvious.

The workaround was to define the 'Eloquent' alias in bootstrap/app.php.

**Comment by jaoued** [comment]
:+1:

**Comment by lbogdan** [comment]
@jaoued:

class_alias(Illuminate\Database\Eloquent\Model::class, 'Eloquent');

Let me know if that works.

**Comment by barryvdh** [comment]
Does above commit fix it for you? I renamed the facade to the actual model class.

**Comment by jaoued** [comment]
Hi @lbogdan , thanks your solution works.
Hi @barryvdh , yes v2.1.4 resolved this issue, thanks a lot :+1:
