### ISSUE TITLE
Why are scope-methods declared static?

### ISSUE THREAD

**Issue by Lambik** [barryvdh/laravel-ide-helper#316]
In my code I have scope-methodes, like `public function scopeActive($query, $value = true)`. However, after running `models` I get this line:  `* @method static \Illuminate\Database\Query\Builder|\Storesquare\Product active($value = true)`

Why has it suddenly become static? PHPStorm now complains that I should call `::active()` instead of `->active()` on my model.

![image](https://cloud.githubusercontent.com/assets/467373/12678505/6220f1c0-c69f-11e5-93b0-e92cf0b99e16.png)

**Comment by barryvdh** [comment]
Because you can also call like `MyModel::active()`

**Comment by Lambik** [comment]
I'm not sure anymore, but I think I meant: could an `@method` line also be created for ->active() instead of just ::active()?

**Comment by delmicio** [comment]
any news about this one? @Lambik @barryvdh

**Comment by astralo** [comment]
If I'll write in Model scope
` @method \Illuminate\Database\Eloquent\Builder|\App\Room byLocation(\App\Models\Locations\CommonLocation $location)`
then scopeByLocation works without static calling
