### ISSUE TITLE
It doesn't generate Storage static calls to default disk

### ISSUE THREAD

**Issue by vedmant** [barryvdh/laravel-ide-helper#317]
It doesn't generate Storage static calls to default disk, like this:

    Storage::exists('file.jpg'); 
    Storage::get('file.jpg');

FilesystemManager redirects all other static calls to default disk:

    /**
     * Dynamically call the default driver instance.
     *
     * @param  string  $method
     * @param  array   $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        return call_user_func_array([$this->disk(), $method], $parameters);
    }

**Comment by barryvdh** [comment]
Can you add a PR to this? Should be something in detectDrivers() here: https://github.com/barryvdh/laravel-ide-helper/blob/f1ebd847aac9a4545325d35108cafc285fe1605f/src/Generator.php#L115-L167
Probably would need to find the default disk and add that as extra class.

**Comment by vedmant** [comment]
Ok, done https://github.com/barryvdh/laravel-ide-helper/pull/327

**Comment by barryvdh** [comment]
Okay merged, let me know if you run into problems :)

**Comment by vedmant** [comment]
Looks like it's working. I think I noticed some errors, it refers old paths for Interfaces in some places, like '\Illuminate\Cache\StoreInterface', now they are in Contracts package '\Illuminate\Contracts\Cache\Store'. It's safer to use \Illuminate\Contracts\Cache\Store::class so it will be visible if path if not correct and also navigate faster there in IDE.
