### ISSUE TITLE
ide-helper commands fatal error

### ISSUE THREAD

**Issue by gokigoks** [barryvdh/laravel-ide-helper#318]
ide-helper:generate throws this error...

 [Symfony\Component\Debug\Exception\FatalErrorException]
 syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION)

while ide-helper throws this..

 [Symfony\Component\Debug\Exception\FatalErrorException]
 syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION)

I did as instructed, clear-compiled, config:clear, cache:clear, clear cache and restart for my phpstorm, then optimized. but still to no avail.
I'm installing doctrine/dbal manually by adding it to my composer.json.. is it required? ill update if it fixes the problem.

**Comment by gokigoks** [comment]
this is my composer.json btw

```
> "require": {
> 		"laravel/framework": "5.0.*",
> 		"nesbot/carbon": "~1.14",
> 		"barryvdh/laravel-ide-helper": "^2.1"
> 	},
> 	"require-dev": {
> 		"fzaninotto/faker": "v1.3.0",
> 		"phpunit/phpunit": "~4.0",
> 		"phpspec/phpspec": "~2.1",
> 		"doctrine/dbal": "~2.3"
> 	},
```

including doctrine/dbal in composer.json didnt fix it.. sigh..

any help would be appreciated.

**Comment by mfn** [comment]
@barryvdh this looks like PHP version mismatch or something, though I vote for closing this old issue :}
