### ISSUE TITLE
Ever since upgrade to laravel 5.2 I no longer get whereColumn methods

### ISSUE THREAD

**Issue by isaackearl** [barryvdh/laravel-ide-helper#325]
After upgrading to 5.2 I no longer get docblocks like this anymore in my models: (so code completion for these are borked now)

```
* @method static \Illuminate\Database\Query\Builder|\Aviago\Models\Trip whereUpdatedAt($value)
```

I have tested using the latest version 2.1.2 as well as the newest commit dev-master.  

I have tried doing it while extending Model and \Eloquent but neither work.  Any help would be greatly appreciated.

**Comment by barryvdh** [comment]
SHould be fixed now.
