### ISSUE TITLE
Facade with magic methods not generating methods

### ISSUE THREAD

**Issue by fosron** [barryvdh/laravel-ide-helper#330]
So i have a object under a facade with `@method` comments, that are "overloaded" with `__call` functionality, and they are not copied over to the `_ide_helper.php`. As i see no PHPDoc blocks that precede a class are copied over. Is this intended?

A small workaround i found is to put  `@method` comments into the facade class, but that's not sufficient enough too as the autocompletion still does not work for the first level of function calls.

Is there a way to have those magic methods generated, or at least the PHPDoc blocks added to `_ide_helper.php`?

**Comment by ethanf22** [comment]
Some of the past issues recommend replacing `extends Model` in your models with `extends \Eloquent`. There's a whole discussion in the Laravel framework repo about this and a bit here in older issues. I'm not sure what the status on a solution with less manual tweaking is though.

**Comment by fosron** [comment]
It's not about the models, i have a custom package created. Sorry not to mention that.

**Comment by mfn** [comment]
@barryvdh IMHO this can be closed because in the meantime the phpdoc `@method` _are_ copied over to the `_ide_helper.php` file, I just checked it :}
