### ISSUE TITLE
phpstorm laravel helpers actions not found

### ISSUE THREAD

**Issue by calvinchoy** [barryvdh/laravel-ide-helper#335]
Hi all,

I followed the steps in the read me, everything is working great in phpstorm. The only problem I got is actions from helpers like: redirect(), view() etc.

The helper class itself is resolved but the corresponding actions not. For example

`redirect()->to(...)` redirect() is class is resolved, but the `to()` action is not found. Ik checked the class, and phpdoc is provided so I expect it to resolve.

Any steps I have to follow to get the helper classes actions recognised?

Thanks

**Comment by jorgeneira** [comment]
Same here, It was working on PhpStorm 10, but after I updated to PhpStorm 2016.1 it is no longer working. 

It also has issues with the meta file, before the update, every time I used` app(MyClass::class) `it was displaying the autocompletion box with all methods and fields, It doesn't work anymore.

**Comment by briedis** [comment]
Can confirm. 

As a temprary workaround, you can put slash before the call: `\redirect()->to();`
This would indicate that the function is in global scope. This  works with `\redirect back()-with(..)`, etc.

It looks like a bug, probably something to do with namespaces. Storm thinks that redirect is in current classes namespace, not in the global scope.

Let's hope JetBrains sorts this out soon, really annoying.

**Comment by briedis** [comment]
Reported a bug on JetBrains, it's easily reproducible: https://youtrack.jetbrains.com/issue/WI-31241

**Comment by calvinchoy** [comment]
Thanks, first I thought maybe I marked the vendor directory incorrectly in phpstorm, but it is indeed a phpstorm and namespacing thing. 

Will wait for the next update and hope the fix will be included.

**Comment by shehi** [comment]
Related to #340 - it's indeed PHPStorm related issue. See links provided in #340.
