### ISSUE TITLE
.phpstorm.meta.php has no effect in PhpStorm 2016.1

### ISSUE THREAD

**Issue by shehi** [barryvdh/laravel-ide-helper#340]
@barryvdh , after a month or so, when I return to my project, for some weird reason, the generated ```.phpstorm.meta.php``` file is missing a lot of lines in it (such as lines for ```app('log')```, ```app('validator')``` etc). My current file looks like this:

https://gist.github.com/shehi/1aeb5d96c5c1b338360474efbd7806f0

Has something changed with package?

**Comment by shehi** [comment]
The project in question is AudithSoftworks/Basis .

**Comment by shehi** [comment]
@barryvdh , I think ```.phpstorm.meta.php``` file has zero effect on my PHPStorm-2016.1... Did they break some compatibility? You have any idea?

**Comment by shehi** [comment]
https://youtrack.jetbrains.com/issue/WI-30660

Yea, it is broken in PHPStorm side. 2016 line of releases are affected I guess.

**Comment by shehi** [comment]
Works perfectly on PS-10. Its PS-2016, I just reinstalled and verified. Closing this one.

**Comment by barryvdh** [comment]
So according to the issue, `\app()` should work? Can you verify?

**Comment by shehi** [comment]
I did. But you also need to replace that everywhere in the code as well, especially if code is namespaced. I believe the issue appeared in PS-2016 when they added new PHP-7 related features. Either way, we can't afford editing our codes and namespace every single global function/helper. Let's wait for a fix.

**Comment by shehi** [comment]
And the party moved to a new location at https://youtrack.jetbrains.com/issue/WI-31102 :D

**Comment by garethlawson** [comment]
Voted for the issue in YouTrack instance for what it's worth...

**Comment by shehi** [comment]
Just did.

**Comment by hackur** [comment]
Fixed! :)... I hated that yellow color.

**Comment by barryvdh** [comment]
What do you mean fixed? No new release yet, right?

**Comment by shehi** [comment]
Nothing so far. What was fixed?

**Comment by hackur** [comment]
I can do `redirect()->to()` and `app('log')`. Both are auto completing with suggestions.

<img width="638" alt="screen shot 2016-05-17 at 1 33 55 am" src="https://cloud.githubusercontent.com/assets/161835/15316043/ddc8679c-1bcf-11e6-9508-21105a4320f1.png">
<img width="697" alt="screen shot 2016-05-17 at 1 35 40 am" src="https://cloud.githubusercontent.com/assets/161835/15316044/ddcb0632-1bcf-11e6-8078-bdc7e945d380.png">

I tried a couple times to see if it was a plugin I installed or updated. I changed a few things in my environment at the same time after this happened a couple days ago. But there were also some updates to a few plugins today.

**A few notes that could be related...**
- I have PHP 7 selected as my "PHP language level" in my PHP Storm settings.
- I'm running my composer commands from within vagrant/homestead which is also using PHP 7.
- I have "Add packages as libraries" checked under Composer in my PHP Storm settings.
- And I did a restart / invalidate cache after installing some new plugins last night. (listed them elow)
- I run my generation commands during composer update so clear-compiled gets run first. Also, I include "--helpers" when I run the generate command.

```javascript 
# composer.json
"post-update-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postUpdate",
      "php artisan clear-compiled",
      "php artisan ide-helper:generate --helpers",
      "php artisan ide-helper:models --reset --no-interaction",
      "php artisan ide-helper:meta --no-interaction",
      "php artisan optimize"
    ]
```

**I also installed a few other PHP-related plugins right after I noticed this issue. I tried disabling them and restarting / invalidating cache. But it still seemed to still work. These are the only plugins that could possibly have something to do with it:**
PHP Toolbox - v0.2.2
PHP Annotations - v3.0.1
Symfony Plugin - v0.12.119
Laravel Plugin - v0.9.1

**Here's my PHP Storm info:**
PhpStorm 2016.1.1
Build #PS-145.970, built on May 3, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by shehi** [comment]
Is your code namespaced?

**Comment by shehi** [comment]
@hackur , your code doesn't seem to be namespaced, as you are using ```Carbon``` in global scope. You can't do that with namespaced code, ```\Carbon``` would be the way.

So, is your code namespaced?

**Comment by hackur** [comment]
Yeah it's a standard Laravel 5.2 application. I ran `php app:name ExampleNamespace` when I first installed it. So that's also configured in my composer.json.

My example screenshots up there were taken from within a class at `ExampleNamespace\ActivationRepository`

I have `use Carbon\Carbon;` at the top of the repository file.

**Comment by shehi** [comment]
Ah ok. As we speak, I have been testing v2016.1.1 to verify if it indeed was fixed. I will let you guys know once I finish doing so.

**Comment by hackur** [comment]
Here are my generated files and my composer.json:
https://gist.github.com/hackur/d4076cd38b01060b16df71cfaa82d759
https://gist.github.com/hackur/2db64c494d4fbf692608b4467b70fbb9
https://gist.github.com/hackur/146fa3e743331cb17dd8fcdeea0549d6

**Comment by shehi** [comment]
Can you try testing ```app('events')->``` and see if Events related methods come up? Such as ```fire()```. I can only see ```app()``` 's methods (without parameter, just ```app()```).

**Comment by shehi** [comment]
Yea, facades do work (I never use them, so not sure if they were before), and shortcut methods such as ```view()```, ```app()``` do work if no parameters have been passed (i.e. ```app('logs')```, app('events')```) which is the same old problem. Not even FQNS'ed ```\app('events')``` does work with current IDE-Helper.

**Comment by shehi** [comment]
Bumping the fact that: Guys, please upvote these issues at Jetbrains:

https://youtrack.jetbrains.com/issue/WI-31102
https://youtrack.jetbrains.com/issue/WI-30660

Thanks.

**Comment by hackur** [comment]
The FQN works for me. It autocompletes the "fire" method using `\app('events')->fi`...

But you're correct `app('events')` doesn't seem to work.

<img width="605" alt="screen shot 2016-05-17 at 2 36 07 am" src="https://cloud.githubusercontent.com/assets/161835/15318013/d27cb952-1bd8-11e6-8e66-83af24386d5c.png">

<img width="1297" alt="screen shot 2016-05-17 at 2 34 44 am" src="https://cloud.githubusercontent.com/assets/161835/15318020/e17bf27e-1bd8-11e6-8d9e-909f6bc882c8.png">
<img width="605" alt="screen shot 2016-05-17 at 2 36 07 am" src="https://cloud.githubusercontent.com/assets/161835/15318021/e18127e4-1bd8-11e6-8de5-fa7dbdfe859a.png">

**Comment by shehi** [comment]
Yea, so overall, it's the same old situation, i.e. not fixed. :)

**Comment by barryvdh** [comment]
Are you on the EAP? Is the file indexed?

**Comment by shehi** [comment]
Wait, didn't this fix come for 2016.1.2?!

**Comment by barryvdh** [comment]
2016.2 is the latest EAP I think.

**Comment by aledmb** [comment]
Hey guys, I'm having issues with PhpStorm not recognizing some methods on Eloquent\Builder (whereNull, orderBy etc.). Is it related to this issue?

**Comment by bburr** [comment]
@aledmb I don't believe that's related, pretty sure that's because those functions are called dynamically via `__call` (they're actually on the `Query\Builder` class: [whereNull](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Query/Builder.php#L1011) and [orderBy](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Query/Builder.php#L1317))

**Comment by aledmb** [comment]
Thank you @bburr !
