### ISSUE TITLE
PhpStorm 2016.1

### ISSUE THREAD

**Issue by OskarD** [barryvdh/laravel-ide-helper#342]
I can't get this to work on PhpStorm 2016.1

I have successfully generated the `.phpstorm.meta.php` and `_ide_helper.php` files in the root directory (Where .env, composer.json etc is) but my IDE does not help with autocompletion for facades.

I have looked inside the files and they seem OK. I have followed the instructions in the readme, including adding the service provider.

What am I doing wrong?

**Comment by shehi** [comment]
You are not searching issues before posting.

**Comment by OskarD** [comment]
@shehi I did try searching, and I browsed through some issues, but I could not find a solution. Maybe you can point me in the right direction?

**Comment by shehi** [comment]
Search for "phpstorm 2016 " in issues? Hint: all issues, not only open ones.

**Comment by shehi** [comment]
short version: there is no solution. go back to PS 10.x until Jetbrains solves the issue.

**Comment by OskarD** [comment]
Oh :( Thank you @shehi
