### ISSUE TITLE
Does this not support Redis autocomplete?

### ISSUE THREAD

**Issue by 9IPHP** [barryvdh/laravel-ide-helper#346]
Does this not support Redis autocomplete? I tried `Cache`, it can autocomplete, but not for `Redis`.

**Comment by shehi** [comment]
Gotta give us more info: what kind of autocompletion do you want? Both ```Redis``` and ```Predis``` are visible within Laravel app, in PhpStorm 10 (due to a Metadata-file related bug, this package can't shine in PS 2016 for the moment, until Jetbrains fixes the issue). I just tested, they work fine, if you have imported them correctly.

**Comment by 9IPHP** [comment]
For example, when I type `Cache::`, it will show :

![2016-05-05 10 54 03](https://cloud.githubusercontent.com/assets/5997084/15040992/5a851476-12eb-11e6-90d4-61b73fe675a9.png)

While when I type `Redis::` there is no tips:

![2016-05-05 10 54 38](https://cloud.githubusercontent.com/assets/5997084/15041005/77c2dbe0-12eb-11e6-9a25-d3e63abc7726.png)

**Comment by shehi** [comment]
Nope. Check your namespacing. It should be ```\Redis``` if you are namespacing:

![image](https://cloud.githubusercontent.com/assets/653569/15041075/ee8db710-12c1-11e6-8437-2c002e78d0ec.png)

**Comment by 9IPHP** [comment]
@shehi It does not work:

![2016-05-10 5 25 43](https://cloud.githubusercontent.com/assets/5997084/15141896/fa39865e-16d4-11e6-8a4c-8056ec9a3cdf.png)

**Comment by barryvdh** [comment]
Does the Redis class exist in the generate ide_helper file?

**Comment by 9IPHP** [comment]
@barryvdh No, I searched for it, but find nothing.

**Comment by barryvdh** [comment]
And does the `Predis\Client` class exists?

See this check here: https://github.com/barryvdh/laravel-ide-helper/blob/e97ed532f09e290b91ff7713b785ed7ab11d0812/src/Generator.php#L188-L191

Does removing that check help?

**Comment by 9IPHP** [comment]
@barryvdh No, that file does not contain anything about [Redis] or [Predis]

**Comment by barryvdh** [comment]
No I meant in your own application. See the referenced lines.

**Comment by 9IPHP** [comment]
If I remove that line, it will return 

```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Fatal error: Class 'Predis\Client' not found  
```

**Comment by shehi** [comment]
Try Invalidating your PhpStorm cache and reindexing.

**Comment by shehi** [comment]
You are not using IDEA IntelliJ with PHP plugins, are you?

**Comment by 9IPHP** [comment]
@shehi  Do you mean this?

![2016-05-10 5 58 25](https://cloud.githubusercontent.com/assets/5997084/15142707/db685b5c-16d8-11e6-9bd6-da62c201e39e.png)

**Comment by 9IPHP** [comment]
I'm using phpStorm 2106.1

**Comment by shehi** [comment]
Okkk, please don't :) Revert back to 10.x as we have standing bug in 2016.*. See #340 . I'd say close this task until it's fixed, but I will let @barryvdh decide that.

**Comment by barryvdh** [comment]
But can you use the Redis class at all then? Don't you need the Predis Client installed to be able to use that?
That is why the check is there.

**Comment by barryvdh** [comment]
https://laravel.com/docs/5.2/redis
> Before using Redis with Laravel, you will need to install the predis/predis package (~1.0) via Composer.

Just to be 100% sure, you did required the predis package?

**Comment by 9IPHP** [comment]
@barryvdh @shehi Sorry for that, I just missed to install predis/predis. Thanks for helping me.

**Comment by dvikas** [comment]
Instead of importing  Redis Like
 `use Illuminate\Support\Facades\Redis;` 
import like following 
`use Redis;`

> Now you will get auto complete

**Comment by levend18** [comment]
as  @dvikas said it's work for me.
i change use Illuminate\Support\Facades\Redis;  to use Redis;
thanks for your help @dvikas
