### ISSUE TITLE
[Doctrine\DBAL\DBALException]                                                                       Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it. 

### ISSUE THREAD

**Issue by mukeshp004** [barryvdh/laravel-ide-helper#347]
after upgarding to laravel 5.2 i am facing the below issue
[Doctrine\DBAL\DBALException]                                                                    
  Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it. 

how to resolve it.

**Comment by shehi** [comment]
Don't use MySQL 5.7 features. Laravel doesn't support them natively, you need to do a lot of workarounds.

**Comment by mukeshp004** [comment]
Ya Done,
Thanks.
