### ISSUE TITLE
Request: Ability to ignore models when generating php docs for models

### ISSUE THREAD

**Issue by abishekrsrikaanth** [barryvdh/laravel-ide-helper#35]
Can a configuration be provided using which some models can be ignored when generating php docs for the models.

My use case is the following:
My application has few models communicating to MongoDB and some to MySQL.
When ide-helper generates the phpdocs, it throws and error 

```
Exception: call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB' does not have a method 'getDoctrineDriver'
Could not analyze class Action.
```

So this just errors out and does not generate the PHP docs.

So if there was a configuration, something like

```
php artisan ide-helper:models ignore-models:Model1,Model2
```

we could ignore the required models.

**Comment by vaishnavmhetre** [comment]
Unfortunately, this getDoctrineDriver issue has raised over User model and seems like it also belongs to MongoDB package, as I'm using jenssegers/mongodb

**Comment by RiccardoManzan** [comment]
Is it possible to get this working setting a mode that ignores database entity schematics but keeps generating phpdocs for scope methods and things like that?
It would be reeeeeally useful.

**Comment by amirhs712** [comment]
> Is it possible to get this working setting a mode that ignores database entity schematics but keeps generating phpdocs for scope methods and things like that?
> It would be reeeeeally useful.

Agreed, It would be nice to have basic phpdocs for mongodb models.
Also, some relationships are supported by `jenssegers/mongodb`.

**Comment by MrHaroldA** [comment]
> > Is it possible to get this working setting a mode that ignores database entity schematics but keeps generating phpdocs for scope methods and things like that?
> > It would be reeeeeally useful.
> 
> Agreed, It would be nice to have basic phpdocs for mongodb models.
> Also, some relationships are supported by `jenssegers/mongodb`.

I'm pretty late to the party, but connectionless Eloquent-like models like `Jenssegers\Model` would fit the Mongo case as well.

**Comment by superhuman62** [comment]
> > Is it possible to get this working setting a mode that ignores database entity schematics but keeps generating phpdocs for scope methods and things like that?
> > It would be reeeeeally useful.
> 
> Agreed, It would be nice to have basic phpdocs for mongodb models. Also, some relationships are supported by `jenssegers/mongodb`.





https://stackdev.space/questions/employing-mongodb-for-data-modeling
