### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by showFocus** [barryvdh/laravel-ide-helper#352]
I'm using a frsh install of Laravel 5.2.36. When I run this command: 

> composer require barryvdh/laravel-ide-helper

I get the following error:

> Your requirements could not be resolved to an installable set of packages.
>   Problem 1
>     - Installation request for phpdocumentor/reflection-docblock (locked at 3.0.2) -> satisfiable by phpdocumentor/reflection-docblock[3.0.2].
>     - barryvdh/laravel-ide-helper v2.1.0 requires phpdocumentor/reflection-docblock 2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
>     - barryvdh/laravel-ide-helper v2.1.1 requires phpdocumentor/reflection-docblock 2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
>     - barryvdh/laravel-ide-helper v2.1.2 requires phpdocumentor/reflection-docblock 2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
>     - barryvdh/laravel-ide-helper v2.1.3 requires phpdocumentor/reflection-docblock ^2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
>     - barryvdh/laravel-ide-helper v2.1.4 requires phpdocumentor/reflection-docblock ^2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
>     - Conclusion: don't install phpdocumentor/reflection-docblock 2.0.4
>     - Installation request for barryvdh/laravel-ide-helper ^2.1 -> satisfiable by barryvdh/laravel-ide-helper[v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4].

**Comment by nueko** [comment]
I have no issue when installing fresh 5.2, but 5.1 yes.
i think the package composer.json should be 
```json
"phpdocumentor/reflection-docblock": "^2.0|^3.0"
```

if you currious, just hit ```composer why phpdocumentor/reflection-docblock```

to fix the issue, i first remove phpdocumentor/reflection-docblock
```
composer rem phpdocumentor/reflection-docblock:^3.0
```
then install the phpdocumentor/reflection-docblock:^2.0
```
composer req phpdocumentor/reflection-docblock:^2.0
```

then install this package

```
composer req barryvdh/laravel-ide-helper
```
hope it helps.

**Comment by barryvdh** [comment]
Can you submit a pr?

**Comment by nueko** [comment]
Done.

**Comment by CbCaio** [comment]
I had the same problem, however I was using laravel 5.2.36 and I "accidentally" ran composer update, only then the phpdocumentor/reflection-docblock updated to 3.0.

**Comment by AmrAlfoly** [comment]
same problem here
i even tried the fix that was suggested by @nueko  but the same error appears when i try to install the ide-helper package

**Comment by VictorLima17** [comment]
Same problem here

**Comment by drtzack** [comment]
Same in here

**Comment by frederik-jacques** [comment]
got the same issue after adding IDE helper to Laravel v5.2.36

**Comment by somuraijoe** [comment]
same :)

**Comment by Carloscentro** [comment]
While this is corrected, simply edit composer.json in Laravel project:   
 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "doctrine/dbal": "~2.3",
        **"barryvdh/laravel-ide-helper": "^2.1"**

Then run `composer update`

This works for me...

**Comment by VictorLima17** [comment]
Worked here @Carloscentro 
Thanks

**Comment by barryvdh** [comment]
Why are you all getting phpDocumentor v3? Is there some new library using that?

**Comment by JoshZA** [comment]
Same issue on fresh install of 5.2

**Comment by barryvdh** [comment]
So what package is conflicting? (So not reflection docblock, but the other package using v3 of reflection docblock)

**Comment by VictorLima17** [comment]
In my case,came together with Laravel

**Comment by ryanvade** [comment]
I cloned a project that is using 5.2.36, ran composer install, and am now getting this error.  The fix @nueko suggested fixes it.

**Comment by coenjacobs** [comment]
`phpspec/prophecy` requires this:
```
"phpdocumentor/reflection-docblock": "^2.0|^3.0.2",
```
via [this pull request](https://github.com/phpspec/prophecy/pull/275). Reasons are some compatibility issue with Symfony 3.1.

**Comment by barryvdh** [comment]
Well, in that case Composer should install ^2.0, not keep 3.x..

**Comment by h4ckth1ssh1t** [comment]
I've used the solution @Carloscentro suggested. Just adding the `"barryvdh/laravel-ide-helper": "^2.1"` line to the `require` object of the `composer.json` file, Composer automatically updates all the required dependencies and installs the desired package.

**Comment by skaisser** [comment]
Just Followed @h4ckth1ssh1t instructions and it worked perfectly here!

**Comment by ozanhazer** [comment]
Hmm `composer require barryvdh/laravel-ide-helper` fails but updating `composer.json` and then installing is fine as @Carloscentro and others mentioned...
Using laravel v5.2 and composer v1.1.2. I feel like this might be some composer bug or something :\

**Comment by barryvdh** [comment]
Yeah if anyone can create a PR for v3, that would be great :)

**Comment by barryvdh** [comment]
In the meanwhile, I updated my fork and used that for ReflectionDocblock.

Can you guys try with laravel-ide-helper v2.2.0?

**Comment by ZamanOof** [comment]
**I try 1.11 & 2.2.0 u mentioned , i have the same error :** 
**composer require barryvdh/laravel-ide-helper ~2.2.0
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/console v5.2.25 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for barryvdh/laravel-ide-helper ~2.2.0 -> satisfiable by barryvdh/laravel-ide-helper[v2.2.0].
    - Conclusion: remove laravel/framework v4.2.19
    - Conclusion: don't install laravel/framework v4.2.19
    - barryvdh/laravel-ide-helper v2.2.0 requires illuminate/console ^5.0,<5.4 -> satisfiable by illuminate/console[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.6, v5.2.7].
    - don't install illuminate/console v5.0.0|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.0.22|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.0.25|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.0.26|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.0.28|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.0.33|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.0.4|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.1|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.13|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.16|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.2|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.20|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.22|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.25|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.28|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.30|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.31|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.6|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.1.8|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.0|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.19|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.21|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.24|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.26|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.27|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.28|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.31|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.32|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.37|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.6|don't install laravel/framework v4.2.19
    - don't install illuminate/console v5.2.7|don't install laravel/framework v4.2.19
    - Installation request for laravel/framework (locked at v4.2.19, required as 4.2.*) -> satisfiable by laravel/framework[v4.2.19].**

** I use composer version : **
<br>
**Composer version 1.1.2 2016-05-31 19:48:11** 
<br>
**and composer.json** 
<br>
`{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "4.2.*",
       		"laracasts/commander": "~1.0"
	},
    "require-dev": {
	"way/generators":"~2.0",
        "codeception/codeception": "~2.0",
	"laracasts/testdummy": "~1.0"
    },
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "stable"
}`

**Comment by barryvdh** [comment]
You are using 4.2?

**Comment by ZamanOof** [comment]
yes, and try 1.11 it was the same error .

**Comment by theWhiteFox** [comment]
"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.1.*",
    "doctrine/dbal": "~2.3",
    "barryvdh/laravel-ide-helper": "2.2.*@dev"
  }

check php.ini file for 
;extension=php_mbstring.dll
;extension=php_fileinfo.dll
;extension=php_openssl.dll
and remove the ;

**then**
composer update 
This worked for me.

**Comment by bishwaskalika** [comment]
plz help me sir i am getting this type of here. i have no idea about this. while installing laravel 5
![screenshot 445](https://cloud.githubusercontent.com/assets/23506220/22395093/32e085ac-e55b-11e6-91ba-655198975c61.png)

**Comment by nueko** [comment]
verify the "Desktop" directory u navigated exists. sorry, are you new to
command line?

**Comment by mfn** [comment]
@barryvdh all versions mentioned / discussed here are no longer supported and we're not aware of current installations issues (except with composer v2 😸 ), therefore I vote for closing this issue :}
