### ISSUE TITLE
Did i can not generate the static function whereSomeField()

### ISSUE THREAD

**Issue by imvkmark** [barryvdh/laravel-ide-helper#354]
if i don't want to generate
`\Illuminate\Database\Query\Builder|\App\Models\PlatformOrder whereOrderId($value)`
this help function 
can i have a configuration in `ide-helper.php`

**Comment by mfn** [comment]
@imvkmark yes, it exists now and is called `write_model_magic_where`

@barryvdh all done here, issue can be closed :}
