### ISSUE TITLE
Can this work with Visual Studio Code?

### ISSUE THREAD

**Issue by ksidibe** [barryvdh/laravel-ide-helper#358]
Hey.
Can this work with Visual Studio Code? If so, how?
Thanks

**Comment by barryvdh** [comment]
If it supports autocomplete, just let it index the generated file.

**Comment by Bodom78** [comment]
I could not get this to work with VSC.

I also tried with the [crane auto complete plugin](https://github.com/HvyIndustries/crane) but no luck.

VSC leaves most functionality up to plugins so I believe one would need to be developed to add the required Laravel Intellisense functionality into the IDE.

**Comment by tlgreg** [comment]
Intellisense extensions should pick it up.
Neither the "PHP Intellisense", nor the "Crane PHP Autocompletion" plugin indexes or understands the _ide_helper file.

For me the [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) extension worked, it indexes for a while and vscode needed a restart (composer classes are picked up without a restart, but the _ide_helper file doesn't), but it works after that. Need more testing though, so I recommend trying it out.

**Comment by javisr** [comment]
@tlgreg did PHP Intelephense finally works well for you? In my case it doesn't show all the options I expected.

**Comment by chemitaxis** [comment]
Same here, not all static methods of Models, for example thanks

**Comment by andreshg112** [comment]
It works for me! However, @mixin doesn't work. It doesn't autocomplete functions like find, findOrFail, updateOrCreate, firstOrCreate.

**Comment by dviluk** [comment]
@andreshg112 Hi, you only need to change 

```php
class User extends Model implements
```
to
```php
class User extends \Eloquent implements
```

that's how it works in VSCode with Intelephense.

**Comment by mfn** [comment]
@barryvdh another IDE problem specific issue; almost everything generated is "IDE agnostic" and it's up to the IDE / plugins to support the features (i.e `@mixin` support is basically required to get proper model completion). I don't see what we can do here and vote for closing :}
