### ISSUE TITLE
generate model phpDocs no property and method

### ISSUE THREAD

**Issue by abinghu** [barryvdh/laravel-ide-helper#359]
I use Laravel v5.2.35，doctrine/dbal v2.5.4, run `php artisan ide-helper:models`.
Get _ide_helper_models.php file like this,
![qq20160623-0](https://cloud.githubusercontent.com/assets/1740452/16298243/fa0b0bd0-3966-11e6-8dda-c8c4372d5d34.jpg)

> namespace App\Modules\Benefit\DB{
> /**
>  *\* App\Modules\Benefit\DB\GoodsItem
>  **
>  **/
>     class GoodsItem extends \Eloquent {}
> }

No properties and method.

**Comment by barryvdh** [comment]
Did you install doctrine?

**Comment by abinghu** [comment]
Yes, I install that, user doctrine/dbal v2.5.4.

**Comment by huang-yi** [comment]
I've had the same problem recently.
My database version is PostgreSQL 9.5.7.

And this is my solution: Add all schemas to search_path.

```sql
ALTER USER username SET search_path = "$user", "public", "custom_schema";
```

**Comment by mfn** [comment]
@barryvdh old issue and all versions are already unsupported. The last comment may be even a different cause / PgSQL specific but user found a fix => I vote for closing :}
