### ISSUE TITLE
Shall 'static' means the child class is better ?

### ISSUE THREAD

**Issue by micln** [barryvdh/laravel-ide-helper#362]
two class here : 

``` php
class base
{
   /**
     * @return static
     */
    public function f()
    {
        //  some code ...
    }
}

class user extends base{}
```

then I get the bellow results

``` php
namespace {
    /**
     * @method static base f()
     */
    class user extends base {}
}
```

Does method 'A()' return the class where defined it ? If yes, it could lead to some problems.

How about return the class who called the method ? It means , classA extends classB's method f(), the result 'static' in f() should not B but A ?

Did I has show my question clearly ? 
Thanks your useful and magical tools !

**Comment by mfn** [comment]
@micln is this still an issue for you?
