### ISSUE TITLE
Feature request: Write PhpDoc directly to Laravel source code

### ISSUE THREAD

**Issue by danilcha** [barryvdh/laravel-ide-helper#366]
While `_ide_helper.php` works in some cases, in other cases it does not (when using absolute class names, such as `use Illuminate\Support\Facades\Auth;`, for instance). 

What if you could modify the source code of Laravel to include the required PhpDoc entries? Like  you are doing now with models. Usually it's bad idea to modify library source code, but here it is not, because (1) we would be doing it automatically and can do it again after library update and (2) we are not influencing library functionality and protocols, and thus don't depend on the changes.

**Comment by barryvdh** [comment]
It's not just phpdocs, it also the method stubs that are useful, because they allow you to click through, which you wouldn't want in the source.

And adding phpdocs therey wouldn't make it work for the Facade aliases, just the full classes, so you'd still need this..
