### ISSUE TITLE
custom helper functions not poped

### ISSUE THREAD

**Issue by macnux** [barryvdh/laravel-ide-helper#367]
already installed phpstorm 2016.1and laravel plugin (latest version) and laravel ide helper (latest) and works very well with me 
now

i create a file app/Helpers/Helper.php and i type on composer.json these lines

```
"autoload": {
"files": [
          "app/Helpers/Helper.php"
      ]
}
```

and i put some functions then i run

`composer dump-autoload`
and i see a reference for my file in vendor/composer/autoload_files.php then i run

`php artisan ide-helper:generate`
and when i try to type of of helper functions found none of them !!

what is wrong here?

**Comment by mfn** [comment]
AFAIK to make this work, you need to enable `include_helpers` and add the path to `helper_files`

@barryvdh I think this can be closed as there's a way to do this :}
