### ISSUE TITLE
Unnecessary fully qualified model name

### ISSUE THREAD

**Issue by danilcha** [barryvdh/laravel-ide-helper#369]
There are such lines in model PhpDoc written by `ide-helper:models --write` into `\App\Models\User`:

```
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereId($value)
```

PhoStorm generates warnings saying, that `\App\Models\User` is unnecessary fully qualified name and that simply `User` would be sufficient.

It probably happens in lines https://github.com/barryvdh/laravel-ide-helper/blob/28af7cd19ca41cc0c63dd1de2b46c2b84d31c463/src/Console/ModelsCommand.php#L296 and/or https://github.com/barryvdh/laravel-ide-helper/blob/28af7cd19ca41cc0c63dd1de2b46c2b84d31c463/src/Console/ModelsCommand.php#L339. 

Probably it should be `(new \ReflectionClass($model))->getShortName()` in both cases. And the slash after word 'Builder' also has to be removed.

**Comment by barryvdh** [comment]
But that only applies when all your models are in the same namespace

**Comment by danilcha** [comment]
Isn't it always the model for which the PhpDoc is generated?

**Comment by barryvdh** [comment]
Oh sorry, the whereX methods are indeed. Just not the relations

**Comment by mfn** [comment]
@barryvdh this is fixed with https://github.com/barryvdh/laravel-ide-helper/pull/954 and can be closed :}
