### ISSUE TITLE
Using laravel-ide-helper in non-laravel project

### ISSUE THREAD

**Issue by Tklaversma** [barryvdh/laravel-ide-helper#370]
I was wondering if I could use this in a non-laravel project, since I'm just using the Eloquent library [`illuminate/database`](https://github.com/illuminate/database).

Just want to know how to use the `_ide_helper.php` file in order for the following to get seen by PhpDoc: `User::query()->where('username', '=', $example)->exists()` in PhpStorm 2016.2.

The problem I'm having is that `exists()` is marked yellow as `method not found in $this`, where `$this` ofcourse refers to `\Illuminate\Database\Eloquent\Builder` and not **also** to `\Illuminate\Database\Query\Builder`.

Any ideas?

Thanks in advance!

**Comment by Tklaversma** [comment]
Anyone?

**Comment by barryvdh** [comment]
Don't think that is really possible.
