### ISSUE TITLE
relations

### ISSUE THREAD

**Issue by bokodi-dev** [barryvdh/laravel-ide-helper#373]
IDE (phpstorm) cannot find the methods for relations.

[screen](http://image.prntscr.com/image/e29645cb593849b39ec3c8f81cd31829.png)

**Comment by bokodi-dev** [comment]
At least a "don't care" response would be nice

**Comment by barryvdh** [comment]
I'm sorry, this library is not magic. I can only provide autocomplete for facades, not existing classes.
