### ISSUE TITLE
generate property's type according to $casts

### ISSUE THREAD

**Issue by leo108** [barryvdh/laravel-ide-helper#374]
If I defined `$casts` like
```
protected $casts = [
    'expired_at' => 'datetime',
];
```
I hope when I execute `php artisan ide-helper:models` it will generate

`@property Datetime $expired_at`

But now is

`@property string $expired_at`

**Comment by barryvdh** [comment]
Good idea, can you submit a PR?

**Comment by keizah7** [comment]
Any updates?
