### ISSUE TITLE
Ability to write int and not integer.

### ISSUE THREAD

**Issue by ellisio** [barryvdh/laravel-ide-helper#376]
Is there a way to write `@property int` and not `@property integer` when running `ide-helper:models` seeing as how the naming convention for Laravel is `int` and not `integer`?

**Comment by ellisio** [comment]
Appears you're forcing a `realType`. I'll open a PR with a potential way to configure this behavior.

**Comment by mfn** [comment]
@barryvdh author provided the actual PR https://github.com/barryvdh/laravel-ide-helper/pull/377 which brought us the `type_overrides` feature => all done here and issue can be closed :}
