### ISSUE TITLE
5.3 support?

### ISSUE THREAD

**Issue by aios** [barryvdh/laravel-ide-helper#379]
```
Declaration of App\Providers\EventServiceProvider::boot(Illuminate\Contracts\Events\Dispatcher $events) should be c
  ompatible with Illuminate\Foundation\Support\Providers\EventServiceProvider::boot() 
```
when update to 5.3

**Comment by barryvdh** [comment]
Not sure what this has to do with the IDE helper? Seems like an error in your own code.
Please follow the Laravel upgrade guide https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0 or ask on the forums.

**Comment by aios** [comment]
Thanks. Already Finded)
