### ISSUE TITLE
models helper uses getCasts() which is >= Laravel 5.2 

### ISSUE THREAD

**Issue by afraca** [barryvdh/laravel-ide-helper#382]
When I accidentally installed the master version of this package, and used ide-helper:models --write , I noticed there were errors about a missing function. 

The function `getCasts` was only introduced in Laravel 5.2 ( [here](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L2790) ), so either the package should require this version, or should check whether this information is available and only then call it.

**Comment by barryvdh** [comment]
Does above commit fix it for you?

**Comment by afraca** [comment]
Yup thanks.
