### ISSUE TITLE
Laravel 5.3 - Broadcast Facade autocompletion missing

### ISSUE THREAD

**Issue by shehi** [barryvdh/laravel-ide-helper#384]
Laravel 5.3 - Broadcast Facade auto-completion is missing...

**Comment by shehi** [comment]
Also, using it like ```app(BroadcastManager::class)->routes();``` works, but again, autocompletion is partial. For instance, ```app(BroadcastManager::class)->channel();``` doesn't get proper autocompletion.

**Comment by edmundluong** [comment]
+1

**Comment by barryvdh** [comment]
Are you generating the file yourself? And have added the facade in your config/app.php?

**Comment by ahuininga** [comment]
Had the same problem. Fixed it with adding 

'Broadcast' => Illuminate\Support\Facades\Broadcast::class,

as an alias in config/app.php and regenerating the file with composer update

**Comment by btaens** [comment]
+1

**Comment by hubertnnn** [comment]
+1

**Comment by felixmind** [comment]
+1

**Comment by mfn** [comment]
This was fixed in Laravel via https://github.com/laravel/framework/pull/24531 in Laravel 5.6, nothing we can do for Laravel 5.5

@barryvdh issue can be closed :}
