### ISSUE TITLE
Lumen install instructions incomplete

### ISSUE THREAD

**Issue by DarkGhostHunter** [barryvdh/laravel-ide-helper#385]
Title

Installing in vanilla latest Lumen user is welcomed in console with:

`[Symfony\Component\Console\Exception\CommandNotFoundException]`
`There are no commands defined in the "ide-helper" namespace.`

To correctly function, the user must go to `bootstrap/app.php` and add to the `Register Service Providers` section:

`if($app->environment() !== 'production') {`
`   $app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);`
`}`

**Comment by barryvdh** [comment]
Can you submit a PR to the readme?

**Comment by DarkGhostHunter** [comment]
Gladly.
