### ISSUE TITLE
Route parameters() breaks generate

### ISSUE THREAD

**Issue by Kampfbereit** [barryvdh/laravel-ide-helper#390]
If I have this in a model, generate breaks;
`$foo = Route::current()->parameters();
`

> # php artisan ide-helper:generate 
> [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Call to a member function parameters() on null

**Comment by barryvdh** [comment]
Where do you have it in your model?

**Comment by Kampfbereit** [comment]
In the constructor. I tried moving it to initialize as a service provider using boot() to no avail.

**Comment by mfn** [comment]
@Kampfbereit is this still an issue for you, can you try with the latest version?

**Comment by Kampfbereit** [comment]
project moved to java så it's archived :(
