### ISSUE TITLE
Gate facade not generated in Lumen

### ISSUE THREAD

**Issue by 4026** [barryvdh/laravel-ide-helper#395]
My helper file (generated in Lumen 5.3.1) doesn't include the definitions for the `Gate` facade. The definitions for it are generated correctly in a Laravel 5.3.18 project.

The facade itself works fine in my Lumen application. I've tried creating a `config/app.php` file with the following contents:

``` php
<?php
return [
    'aliases' => [
        'Gate' => Illuminate\Support\Facades\Gate::class
    ]
];
```

...but the helper definitions still don't get generated. What am I doing wrong?

**Comment by ellisio** [comment]
I am having a similar problem with Lumen 5.4 and the JWTAuth facades. Nothing is being written to `_ide_helper.php`.

```
<?php

return [
    /*
     * These are for the ide-helper generation. Look in bootstrap/app.php the actual registration.
     */
    'aliases' => [
        'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
        'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class,
    ]
];
```

**Comment by ellisio** [comment]
This was fixed by calling the following right before `return $app` in `bootstrap/app.php`:

```
$app->configure('app');

return $app;
```

Looks like if you want the helper to pick up the custom app config, you need to add that line. Maybe the ServiceProvider can hot load this if it's detected running in a Lumen environment? Dunno.

**Comment by servocoder** [comment]
Seems this is not enough for Lumen 5.5 (or the current plugin version). I solved the custom facades generation issue in this way: https://github.com/barryvdh/laravel-ide-helper/issues/360#issuecomment-353126863
