### ISSUE TITLE
Problem with Laravel 5.3 Models

### ISSUE THREAD

**Issue by blackfyre** [barryvdh/laravel-ide-helper#398]
When running the models function I get the error:

```
Exception: Invalid argument supplied for foreach()
Could not analyze class App\Comment.
```

And here's the Model

``` php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
}
```

The same goes for all the models, `doctrine/dbal` is installed, the service provider is registered.

**Comment by Mohamed-Elwan** [comment]
have you tried `composer dump-autoload` and `php artisan clear-compiled` yet ?

**Comment by barryvdh** [comment]
Is there anything in the logs?

**Comment by blackfyre** [comment]
@Mohamed-Elwan These were the first I went for :smile: 

@barryvdh Sadly the logs are empty

**Comment by blackfyre** [comment]
So, I went into the dark forest, and came out finding that my own stupidity caused this error.
There was an error for the `custom_db_types` settings in my config file.
