### ISSUE TITLE
Feature request: A CLI option to forcibly delete existing Model comments and write afresh

### ISSUE THREAD

**Issue by saifulss** [barryvdh/laravel-ide-helper#399]
E.g.

`php artisan ide-helper:models --force`

Currently I'm manually going to each Eloquent model and deleting the existing doc blocks to make way for ide-helper:models to write doc blocks afresh.

Thanks for the ever so helpful package!

**Comment by Kurre** [comment]
You can use reset switch for that.
`php artisan ide-helper:models -R` will reset (remove) docblocks before writing.

Combine it with write switch (-W) to make process even more fluent.

See help for more info: `php artisan ide-helper -h`

**Comment by barryvdh** [comment]
Indeed, that should do the trick :)
