### ISSUE TITLE
[Request] Parse bootstrap files for defined Macros

### ISSUE THREAD

**Issue by christoferd** [barryvdh/laravel-ide-helper#40]
Hi Barry,

Just a [Request] 

Parse bootstrap files for defined Macros

Example Macro I have in Bootstrap/start.php

```
Html::macro('linkButton', function($url, $label, $buttonType = 'primary', $glyph = '', $size = 'md')
{
    return sprintf('<button type="button" class="btn btn-%s btn-%s"
        onclick="window.open(\'%s\',\'_self\')">
      <span class="glyphicon glyphicon-%s"></span> %s
    </button>',$buttonType,$size,$url,$glyph,$label);
});
```

Thanks,
Chris :-)

**Comment by mikemand** [comment]
I know this is over two years old, but has anyone been able to solve this issue? More and more things are implementing the `Macroable` trait and it is getting increasingly frustrating when my IDE cannot autocomplete or jump to the definition of a macro method.

**Comment by jonnywilliamson** [comment]
@briedis I've a number of collection Macros that I'd love to get to autocomplete.

But I can't seem to get your trick to work in my IDE (phpstorm). How would I get my collection macros to autocomplete when they are currently defined in a `CollectionMacroServiceProvider` class?

Thanks!

**Comment by briedis** [comment]
@jonnywilliamson Can you show me what have you tried (like in my example)?

**Comment by jonnywilliamson** [comment]
Sure.

So here's my `CollectionServiceProvider` where I register all my extra Macros I want to add. I'll reduce it to just one for ease of viewing.

```php
<?php

namespace App\Providers;

use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;

class CollectionServiceProvider extends ServiceProvider
{

    public function register()
    {
        Collection::macro('toAssoc', function () {
            return $this->reduce(function ($assoc, array $keyValuePair) {
                list($key, $value) = $keyValuePair;
                $assoc[$key] = $value;

                return $assoc;
            }, new static);
        });
}
```

So having read your comment above where you added a fake Class Docblock, I thought this might work.

```php
<?php

namespace App\Providers;

use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;

/**
 * Class CollectionServiceProvider
 *
 * @package App\Providers
 * @method Collection toAssoc(callable $callback) To Assoc description and info here.
 */
class CollectionServiceProvider extends ServiceProvider
{
    public function register()
    {
        Collection::macro('toAssoc', function () {
            return $this->reduce(function ($assoc, array $keyValuePair) {
                list($key, $value) = $keyValuePair;
                $assoc[$key] = $value;

                return $assoc;
            }, new static);
        });
}

```

Basically in any other class I create I want to be able to do this:

```php
<?php
namespace App\Providers;
use Illuminate\Support\Collection;

class demo
{

    public function start()
    {
        $demo = collect([1,2,3]);
        $demo->   //At this point autocomplete should show `toAssoc` as a complete option. It does not.
    }
}
```

I generated a new _ide_helper, but that still didn't give me the `toAssoc` option.

So then I tried changing the fake docbloc class name to match the `Illuminate\Support\Collection` class name:

```php
/**
 * Class \Illuminate\Support\Collection
 *
 * @package App\Providers
 * @method Collection toAssoc(callable $callback) To Assoc description and info here.
 */

```

But that didn't work.

So I'm open to suggestions!

**Comment by briedis** [comment]
@jonnywilliamson 

The trick is that you need to create another decalration of Collection class that IS NOT included in the actual code.

Create a file somewhere, and add this content:

![image](https://cloud.githubusercontent.com/assets/500491/18617008/8f96ebea-7dcf-11e6-96e4-c5c4e8ddecfe.png)

You can see, that I try to redefine Collection class. When PhpStorm encounters multiple definitions of the class, it just merges together methods and properties. This is a hack, and can result in IDE warnings about multiple class definitions.

**Comment by jonnywilliamson** [comment]
Ahhh.

Ok, So I actually just stuck this at the top of my `CollectionsServiceProviders` class and it's working! Thanks!

For anyone else following this is what it looks like now:

```php
<?php

namespace Illuminate\Support;
/**
 * @method Collection toAssoc(callable $callback) To Assoc description and info here.
 */
class Collection{};
?>


<?php

namespace App\Providers;

use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;


class CollectionServiceProvider extends ServiceProvider
{
    public function register()
    {
        Collection::macro('toAssoc', function () {
            return $this->reduce(function ($assoc, array $keyValuePair) {
                list($key, $value) = $keyValuePair;
                $assoc[$key] = $value;

                return $assoc;
            }, new static);
        });
}
```


It's ugly, but it works!

Will do nicely for a sticky plaster for a while. Thank you @briedis

**Comment by briedis** [comment]
Your solution will probably generate an error, because you cannot re-declare a class twice. You have to put this hack-code in a separate file, file which will be indexed by IDE, but it will never acutally be included in the running code.

**Comment by jonnywilliamson** [comment]
@briedis Indeed it did. Thank you for the warning.

I've now done what you suggested and it is working well! Really appreciate that.

**Comment by cviebrock** [comment]
Just looking for solutions to this problem and came across this.

My issue (after creating a separate `_ide_macros.php` file with my definitions) is that PHP Storm now complains about "Multiple definitions exist for class XXX" in my code.  Apart from turning that inspection off, is there a solution to this?

**Comment by Gummibeer** [comment]
You can disable this inspection.
```
Settings | Editor | Inspections | PHP | Undefined | Undefined class | Don't report multiple class declaration potential problems
```
Be aware that this disables the inspection everywhere and for everything. So it will also not notify you about really duplicated classes.

All other hacks/settings won't work because they prevent phpstorm from indexing the file and therefore you won't have method completion.

**Comment by mfn** [comment]
- there's a duplicate issue https://github.com/barryvdh/laravel-ide-helper/issues/531
- there was a PR merged some years ago which brought macro support, buy only _within_ Facades => https://github.com/barryvdh/laravel-ide-helper/pull/500

**Comment by mfn** [comment]
I'm closing this in good faith, assuming the recent macro support fixes this => see the release https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.8.1

Since this is a _very old_ issue, I think if anyone here experiences issues with the new feature, please open a new issue with details. Thanks!
