### ISSUE TITLE
Fatal error: Class 'Memcached' not found

### ISSUE THREAD

**Issue by xiaohepan** [barryvdh/laravel-ide-helper#400]
i run  this command "php artisan ide-helper:generate", then throws out this exception 
`
 Fatal error: Class 'Memcached' not found in    /Applications/XAMPP/xamppfiles/htdocs/test/vendor/illuminate/cache/MemcachedConnector.php on  line 74
`
`
[Symfony\Component\Debug\Exception\FatalErrorException]
`
`
Class 'Memcached' not found.
`
i can find Class 'Memcached'。

**Comment by marsvogel** [comment]
Same issue here. I had to install `memcached` for my current php version. Since you are on macOS you can install `php70-memcached` via homebrew. You may need to install `xcode-select`.

**Comment by tembra** [comment]
Run this command inside Homestead that has Memcached installed.

**Comment by servocoder** [comment]
It's an issue.
I don't want to install Memcached just to run "ide-helper:generate" smoothly.

Is there a way to avoid `Class 'Memcached' not found` error without Memcached get actually installed?
I use Lumen 5.4

**Comment by servocoder** [comment]
My problem was in absence of `.env` file.
Once I put it back the error is gone.

**Comment by mfn** [comment]
I suspect this had to do something with cache driver config and memcached not being installed or some eager dependency resolved

@barryvdh it's quite old and one user reported he could fix it and this is the only issue I can find regarding memcache, I therefore vote for closing this :}
