### ISSUE TITLE
static called as dynamic warning on facade returning $this

### ISSUE THREAD

**Issue by miklcct** [barryvdh/laravel-ide-helper#401]
When I try to use a facade function returning $this (which is not the facade itself but an object instead) and chain it, IDE thinks that I am calling a static method on the object (because the IDE helper copies the docblock returning $this, but it is returning a real object instead).

e.g.

`User::inRandomOrder()->first()`

IDE thinks I am calling the static function first() because inRandomOrder() returns "$this" (actually a builder object) and first() exists on the facade (e.g. User::first()) as well. However I am calling first() on the returned object (a Builder instance) rather than on the facade itself.

The return type generated in the IDE helper should be changed from $this to the real class the facade represents instead

**Comment by mfn** [comment]
@barryvdh this works nowadays, likely due to support of `@mixin`; I think we can close it :}
