### ISSUE TITLE
Cannot use ServiceName as ServiceName because the name is already in use

### ISSUE THREAD

**Issue by nsnyder** [barryvdh/laravel-ide-helper#403]
This may not be an actual issue, but I keep getting the following error:
```Cannot use ServiceName as ServiceName because the name is already in use```

It seems to be because I'm using services in other services, so trying to load all the dependencies loads services multiple times. Maybe Laravel isn't supposed to load services into other services, or maybe it's a bug with this? Any thoughts?

Thanks!
Nathan

**Comment by Zwaen91** [comment]
I got the same with a self defined ValidationException

**Comment by tylerseymour** [comment]
Experiencing the exact same issue as nsyder outlined and unable to resolve without a major refactoring of existing code.  Any clarification on this issue would greatly be appreciated!  Thanks!

**Comment by nsnyder** [comment]
I managed to resolve my issues by including all of my facades in services in the following way:
`use App\Facades\MyService as MyServiceFacade;`

Hopefully that can help point others in the right direction. However, you will have to change any uses of those services in the file accordingly.

**Comment by nsnyder** [comment]
If this resolves the problem for others, I'd be happy to close it. My issue is resolved.

**Comment by tylerseymour** [comment]
Thanks Nathan - appreciate you sharing!
