### ISSUE TITLE
Update generated versions

### ISSUE THREAD

**Issue by sangar82** [barryvdh/laravel-ide-helper#408]
Hi

The last time update generated versions was updated:

> Generated for Laravel 5.1.40 (LTS) on 2016-07-18.
     

Can you update generated versions for Laravel 5.3??

**Comment by mfn** [comment]
I guess this is referring to the gist in https://gist.github.com/barryvdh/5227822 , which currently mentions `Generated for Laravel 5.5.13 on 2017-09-28.`

@barryvdh I think we can close this, unless you want to maintain the gist 🤷‍♀️

**Comment by mfn** [comment]
FTR, the gist links have been removed from the readme as they're becoming unusable for different systems/newer versions etc. It's expected, and the goal of this library, to generate them.
