### ISSUE TITLE
Not working service navigation by Ctrl+Click. Error "Cannot find declaration to go to"

### ISSUE THREAD

**Issue by Sorbing** [barryvdh/laravel-ide-helper#409]
Hi. I install the package `laravel-ide-helper` and generate the file `.phpstorm.meta.php`. But I have not working classes navigation by `Ctrl+Click`. I get error `Cannot find declaration to go to`. Although navigation by methods work well..
OS: Ubuntu 16.04, PhpStorm 2016.3 EAP (build #PS-163.7743.39, built on November 16, 2016).
Thanks.

![Cannot find declaration to go to](https://cloud.githubusercontent.com/assets/1755934/20459605/80f5518a-aed0-11e6-9db4-947ebbd5f2f0.png)
![Navigation by methods works fine](https://cloud.githubusercontent.com/assets/1755934/20459616/d7419b48-aed0-11e6-8b2e-62df5ab225a9.png)

**Comment by barryvdh** [comment]
That not something I can fix, you should ask Phpstorm

**Comment by Kurre** [comment]
Works for me. Using Navigate -> Declaration (binded to mouse button).
Have you tried `Invalidate Caches / Restart` ?

![phpstorm-app-make-declaration](https://cloud.githubusercontent.com/assets/1389199/20483839/e974b912-affc-11e6-8814-0e70e4e331d7.jpg)

PhpStorm 2016.3 EAP
Build #PS-163.7743.39, built on November 16, 2016
PhpStorm EAP User
Expiration date: December 16, 2016
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

**Comment by Sorbing** [comment]
@Kurre: Yes, "Navigate » Declaration" is enabled, action `Ctrl+B` and `Ctrl+Button1 Click`, "Invalidate Caches / Restart" - not fixes problem. I send issue to PhpStorm, maybe them help fix problem.. Thanks.

**Comment by Sorbing** [comment]
I publish PhpStorm issue - https://youtrack.jetbrains.com/issue/WI-33980.

**Comment by quantumwebco** [comment]
@barryvdh I am also having this error on newer versions of Laravel. Works ok on older versions but somethings broken for the latest versions 6.x

**Comment by mfn** [comment]
Everything here points that this needs to be fixed elsewhere (phpstorm itself or the laravel plugin)

@barryvdh on top of that, in fact it works for me, `\App::make('router')` correctly goes to `\Illuminate\Routing\Router` for me, I think this issue can be closed :}
