### ISSUE TITLE
"SoftDeletingScope" methods in all Eloquent Models

### ISSUE THREAD

**Issue by Stalinko** [barryvdh/laravel-ide-helper#413]
All Eloquent models which use `SoftDeletes` trait accept methods from `SoftDeletingScope`:

1. forceDelete
2. restore
3. withTrashed
4. withoutTrashed
5. onlyTrashed

Usage example:
`InventoryItem::withTrashed()->where('unit_id', $unit->id)->update(['unit_id' => 1]);`
`Equipment::where('name', 'Stick')->onlyTrashed()->all();`

Currently Laravel doesn't provide any way to typehint these methods in PHPStorm (and other smart IDEs if any...). We can solve this in ide-helper. I have some ideas how to do this, but I want to discuss with you which is better.

1. Explicitly add a blank `Illuminate\Database\Eloquent\Model` class with PHPDoc where these methods described like:

```
namespace Illuminate\Database\Eloquent {
	/**
	 * Class Model
	 *
	 * @package Illuminate\Database\Eloquent
	 * @static \Illuminate\Database\Eloquent\Builder withTrashed()
	 * ... the rest of methods ...
	 */
	abstract class Model {}
}
```

2. Add this PHPDoc before `\Eloquent` generated in `_ide_helper.php` file. Though I don't know if there is a good way if implementing this.

3. Add this PHPDoc with artifical blank trait 

```
namespace Illuminate\Database\Eloquent {
	trait SoftDeletes {}
}
```

What do you think guys and especially @barryvdh ?

**Comment by dmason30** [comment]
+1 @barryvdh

**Comment by UksusoFF** [comment]
Duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/371 but really needed.

**Comment by anasred** [comment]
Any Solution for this

```Exception: Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::withTrashed()
Could not analyze class App\Order.```

**Comment by rogatty** [comment]
The issue is still present on the latest version.

**Comment by ssarljames** [comment]
Any updates?

**Comment by mfn** [comment]
> Add this PHPDoc before `\Eloquent` generated in `_ide_helper.php` file. Though I don't know if there is a good way if implementing this.

I did not look into this in detail but this suggestion make sense to me and AFAIK there's precedence. So, don't take my word for gold, but if it's about a) detecting the trait and b) just adding the static phpdoc method and slap a test on it, would this be a satisfying solution?

I think PRs are welcome 🤷‍♀️

**Comment by miken32** [comment]
For getting the static methods to autocomplete on the model, like `User::withTrashed()->get()`, nothing is needed. The trait [now includes](https://github.com/laravel/framework/commit/7b91285cf7c100b07bf3e277bc0acb3e0598b7aa) the methods in its docblock header.

But using the methods on relationship methods like `$user->posts()->withTrashed()->get()` is still not possible. I've had partial success adding this to `_ide_helper.php`:
```
namespace Illuminate\Database\Relations {
    /**
     * Class Relation
     *
     * @package Illuminate\Database\Eloquent
     * @method \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder withTrashed()
     * @method \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder onlyTrashed()
     * @method \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder withoutTrashed()
     */
    abstract class Relation {}
}
```
This stops the complaints about unknown methods, but it still won't autocomplete them (using PhpStorm.)

**Comment by shehi** [comment]
Any updates? @barryvdh isn't around?

**Comment by barryvdh** [comment]
Any pull requests?

**Comment by Stalinko** [comment]
5 years have passed, I think now I've grown enough to make a good PR, will try to do that in the nearest time 😊

**Comment by CitizenBeta** [comment]
I'm running into this issue on the latest version of everything. Is there something I should be enabling to resolve it?

![Screenshot from 2021-12-30 12-48-51](https://user-images.githubusercontent.com/595049/147776143-ad6a2b9a-76e7-4ea9-900d-159063c6236a.png)

**Comment by shehi** [comment]
Yea, same here. I can comfirm.
