### ISSUE TITLE
Autocompletion is not working

### ISSUE THREAD

**Issue by Starkmann** [barryvdh/laravel-ide-helper#415]
I somehow can not get the autocompetion  running.

Example:
```

use Illuminate\Support\Facades\File;
$file = new File();
$file->

```
Here i get the autocompletion of the facade.

```
$file = new \File();
$file->
```

Here i get the autocompletion of the ide helper, but of course the code is not running.

What am i doing wrong?

**Comment by mfn** [comment]
```php
use Illuminate\Support\Facades\File;
$file = new File();
```
That's now Facades are supposed to be used, please read https://laravel.com/docs/7.x/facades#introduction

@barryvdh old support issue, IMHO can be closed :}
