### ISSUE TITLE
IDE does not recognize Artisan Facade

### ISSUE THREAD

**Issue by tpalts** [barryvdh/laravel-ide-helper#416]
PhpStorm 2016.2.2
Laravel 5.1.45

Autocompletion works fine for Route, Session, View facades. Autocompletion does not work for Artisan facade.

Am I missing something?

**Comment by mfn** [comment]
@barryvdh old issue, outdated versions, works for me locally when I added it to `config/app.php` `aliases` => I vote for closing the issue :}
