### ISSUE TITLE
Not all models are being ran.

### ISSUE THREAD

**Issue by chef-it** [barryvdh/laravel-ide-helper#420]
I can't figure out why, file permissions and ownership, namespacing, etc are all the same, but it is only running on about half of my models. Let me know why information you would like from me.

**Comment by apoca** [comment]
Yes I have exactly same problem.

**Comment by barryvdh** [comment]
Any pattern in the name? Only first half? No spaces etc?

**Comment by chef-it** [comment]
I have compared ones that worked to ones that didn't and can't find anything that sets one apart from the other. All in camel case, some one word, some a couple; Some have setters/getters/scopes, some don't; etc, but nothing correlates to the ones that did work to the ones that didn't. It's also intermixed, not as if it started processing them and just stopped if it works alphabetically.

**Comment by itsabadcode** [comment]
In my experience process breaks when DB table for model don't exist.

**Comment by mfn** [comment]
@barryvdh old support issue, I vote for closing :}
