### ISSUE TITLE
Non static method should not be called statically

### ISSUE THREAD

**Issue by P1llus** [barryvdh/laravel-ide-helper#421]
Using the newest version of phpstorm, ide-helper and the laravel plugin:

After running generate, and meta, restarting phpstorm, i still have problems with facades, for example when using $this->.

Looking at the IDE helper file, i can see errors on most of them, with "Non static method should not be called statically", though i am guessing that is not the cause of the problem.

Here is a few examples:

![image](https://cloud.githubusercontent.com/assets/8027539/21429162/e5f189f4-c85d-11e6-9954-2a341117f569.png)

![image](https://cloud.githubusercontent.com/assets/8027539/21429168/ef0334ca-c85d-11e6-97d2-0578345430f3.png)

IDE Helper file:
![image](https://cloud.githubusercontent.com/assets/8027539/21429198/0c7aa84e-c85e-11e6-810e-168ae72652ac.png)

Is there anything i am missing?

**Comment by eugenevdm** [comment]
See if this post maybe applies to your installation:
https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-317411918

**Comment by mfn** [comment]
@barryvdh I believe this is another thing fixed by `@mixin` support, I derive this also from the linked comment which suggests this as a fix => I believe this issue can be closed :}
