### ISSUE TITLE
There are no commands defined in the "ide-helper" namespace

### ISSUE THREAD

**Issue by fabyo** [barryvdh/laravel-ide-helper#422]
php artisan ide-helper:generate

[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "ide-helper" namespace.

**Comment by devdurbs** [comment]
Getting same error. 
[InvalidArgumentException]
There are no commands defined in the "ide-helper" namespace.

Using:
"post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan clear-compiled",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan ide-helper:models --write",
            "php artisan optimize"
        ],

**Comment by barryvdh** [comment]
Did you register the service provider?

**Comment by marija-bogdanovic** [comment]
Hi, 
I have the same problem, but I registered service provider in config/app.php by adding Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class, into section Providers.

root@marleen:/media/sf_Development/laravel# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating laravel/framework (v5.4.25 => v5.4.27) Downloading: 100%         
  - Updating laravel/passport (v2.0.10 => v2.0.11) Downloading: 100%         
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ide-helper" namespace.    
                                                                  

Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1
You have new mail in /var/mail/root
root@marleen:/media/sf_Development/laravel# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ide-helper" namespace.    
                                                                  

Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1
You have new mail in /var/mail/root
root@marleen:/media/sf_Development/laravel#

**Comment by mfn** [comment]
@barryvdh old support issue, I think we can close it :}

**Comment by bhojkamal** [comment]
I removed this package, still I got this error on my log on every second and my log file is too big size within few hours. I removed it from composer, app.php appserviceprovider, where still this error coming from?? I could not find it.
