### ISSUE TITLE
Having problems with \Illuminate\Support\Fluent\ for nullable, index, unsigned, etc

### ISSUE THREAD

**Issue by mzamoras** [barryvdh/laravel-ide-helper#425]
I was having troubles using the Blueprint Class on migrations, I was constantly having warnings using something like this:

```php
   //after string there is no autocompletion  after string("foo") and warning in nullable
   $table->string("foo")->nullable()->index();

  //after string there is no autocompletion after integer("bar") and warning in unsigned
   $table->integer("bar")->unsigned();
```

I hadn't found any proper solution, some people was saying they didn't had that problem, but based on this link [http://stackoverflow.com/a/32811541](url) I added this to the end of my _ide-helper.php file and every thing started to work.

```php
   namespace Illuminate\Support{
        /**
         * @method Fluent first()
         * @method Fluent after($column)
         * @method Fluent change()
         * @method Fluent nullable()
         * @method Fluent unsigned()
         * @method Fluent unique()
         * @method Fluent index()
         * @method Fluent primary()
         * @method Fluent default($value)
         * @method Fluent onUpdate($value)
         * @method Fluent onDelete($value)
         * @method Fluent references($value)
         * @method Fluent on($value)
         */
        class Fluent {}
    }
```

I think you should add this to the the ide-helper.

Well, hope you find this useful; 
By the way, thanks for this tool, otherwise phpstorm would be a painful collection of warning screams all over the place, and even worst without autocompletion!!!

**Comment by raimaj** [comment]
Same problem here, the solution worked fine

**Comment by barryvdh** [comment]
Did you set `include_fluent` to true in the config?

**Comment by raimaj** [comment]
Oh I see, that definitely fixed it.
My bad, can this be included in the readme?

**Comment by barryvdh** [comment]
Sure, can you create a PR?

**Comment by phiterf** [comment]
How can I do that in a Lumen application? There is no config file.

**Comment by mfn** [comment]
The readme already contains the reference to `include_fluent`.

For lumen, I guess the config has to be copied manually?

@barryvdh the original issue has been resolved, I suggest to close this one :}
