### ISSUE TITLE
Ide helper doesn't work properly

### ISSUE THREAD

**Issue by ketys** [barryvdh/laravel-ide-helper#426]
Hello, I've got a problem with IDE-helper. I've installer everything correctly, but for example, when I insert this command: `Hash::make('pasword')`, it will prints an error and also autocomplete doesn't work (of course)
> Method 'make' not found in Illuminate\Support\Facades\Hash

One possible solution is to change `use Illuminate\Support\Facades\Hash;` to `use \Hash;`, but then it tells me, that 
> Import '\Hash' is never used

Why is it happening and how to fix this issue?

**Comment by mynque** [comment]
We also couldn't make this work without modifying `_ide_helper.php`.

A solution for PhpStorm (and other IDEs, I suppose) would be placing the IDE helper classes into the `Illuminate\Support\Facades` namespace:
```
namespace Illuminate\Support\Facades {
	exit("This file should not be included, only analyzed by your IDE");
...
```
And excluding `vendor/laravel/framework/src/Illuminate/Support/Facades` in Settings | Directories.

**Comment by barryvdh** [comment]
Can you try with the latest dev version (`2.x@dev`)?

**Comment by mfn** [comment]
@barryvdh old support issue, I suggest to close it :}
