### ISSUE TITLE
Exception: Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it

### ISSUE THREAD

**Issue by milsanore** [barryvdh/laravel-ide-helper#427]
Hi, is there a way to map the MySql BIT(1) type to a boolean type?
Thanks,

**Comment by barryvdh** [comment]
You can set custom types in the config.

**Comment by milsanore** [comment]
Is there a user guide / documentation on setting custom types in the config?

**Comment by milsanore** [comment]
Never mind, I solved it myself,

1) run "php artisan vendor:publish" this will generate an ide-helper.php
2) Modify the 'custom_db_types' with the following:

    'custom_db_types' => array(
		'mysql' => [
			'bit' => 'boolean'
		]
    ),

**Comment by brian-lamb-software-engineer** [comment]
This didnt generate the mentioned file, only some views.  Im not able to find the file, nor the custom_db_types entry in my code base.
