### ISSUE TITLE
CMD+Click to Interface method not navigating to resolved class.

### ISSUE THREAD

**Issue by ellisio** [barryvdh/laravel-ide-helper#428]
Hello,

I have added the following to the `config/ide-helper.php`:

```php
'providers' => [
    'App\Contracts\Models\Repositories\NumberVendorRepository',
],
```

When viewing the generated `.phpstorm.meta.php` file it is listed correctly in all three blocks as:

```php
'App\Contracts\Models\Repositories\NumberVendorRepository' instanceof \App\Models\Repositories\NumberVendorRepository,
```

However, when I go to CMD click into the function I am navigated to the interface itself; not the resolved class. Here is a video demonstrating the behavior:

http://d.pr/v/Oq0D

PhpStorm Details:

```
PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016
Licensed to Andrew Ellis
Subscription is active until February 11, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by ellisio** [comment]
Here is another video demonstrating using the string version of the class name in `app()`: http://d.pr/v/Ek4U

**Comment by mfn** [comment]
@ellisio does this still happen?
