### ISSUE TITLE
"artisan ide-helper:models --nowrite" gives "Multiple definitions exist for class ..."

### ISSUE THREAD

**Issue by johnvt** [barryvdh/laravel-ide-helper#430]
First off, thanks for a great package!

After some hassle, I've got the facades and Eloquent/Builder stuff working like a charm.

But I'm struggling a  bit now with the Model helpers. I'd prefer them in the separate _ide_helper_models.php. But if I do so, PhpStorm finds both the original Model and the generated helper. How do I prevent that?

**Comment by barryvdh** [comment]
Write them to the actual models, using the write flag (or should suggest that by default?)

**Comment by barryvdh** [comment]
Or why do you need them seperate?

**Comment by johnvt** [comment]
It seemed a bit cleaner to have it in a separate file. And not clutter up the Model files.

Also, it's really easy to remove the file and regenerate. Just to be sure that it doesn't fail on existing methods or custom stuff. (I encountered one case where an existing method changed in parameters but the helper wasn't updated accordingly)

**Comment by barryvdh** [comment]
You can also use the refresh (-R) option to reset.

**Comment by johnvt** [comment]
Yes, but that removes custom comments.

How is the separate file option supposed to work, regarding the multiple definitions?

**Comment by alberto-bottarini** [comment]
:+1:

**Comment by sebastiaanluca** [comment]
Small annoyance, but would be great to find a solution for this.

**Comment by tucq88** [comment]
+1 for this. Models would look much cleaner.

**Comment by aleixfabra** [comment]
+1

**Comment by Sciscitator** [comment]
+1

**Comment by valeryan** [comment]
I agree that being able to use the separate model meta file is much better than adding the extra meta to the models. My team and I found having the meta in the models to be a little frustrating when they cause conflicts in version control and over bloated our pull request. The only solution I have found to make this usable as an external file is to disable the check for the duplicate declarations. However, this is the head in the sand approach and I don't like that either.  

To turn off this message go to: 
`Settings -> Editor -> Inspections -> PHP -> Undefined -> Undefined class`

Then: 
Uncheck Option -> `[] Don't report multiple class declaration potential problems`

**Comment by tucq88** [comment]
@valeryan But actually uncheck that option will prevent us from knowledge about actual `multiple class declaration potential problems`

**Comment by valeryan** [comment]
@tucq88 yes, I believe I said this is like sticking your head in the sand. I don't like it but it's the only way I can use this tool right now until someone figures out how to get phpstorm to understand that these files are just providing meta about models.

**Comment by Chinese1904** [comment]
I have been using the setting for `Don't report multiple class declaration potential problems` as well, but for the last two days I have been trying to figure out a better solution.

Is there anyone here that has found one already?

**Comment by paishin** [comment]
Anyone managed to resolve this?

**Comment by carbontwelve** [comment]
This is someting that should be fixed on the IDE side as its the IDE displaying the annoyance and there is little ide-helper can do to avoid that, its just how code inspection works.

It should be possible to create a [custom scope](https://www.jetbrains.com/help/phpstorm/settings-scopes.html) that excludes the `_ide_helper_models.php` and `_ide_helper` files. Then have that scope used for the inspection causing the warnings but it doesn't seem to work for me.

**Comment by CitizenBeta** [comment]
Any update to this? I can reproduce this on the latest version of Phpstorm.

**Comment by jamesratcliffe** [comment]
> This is someting that should be fixed on the IDE side as its the IDE displaying the annoyance and there is little ide-helper can do to avoid that, its just how code inspection works.
> 
> It should be possible to create a [custom scope](https://www.jetbrains.com/help/phpstorm/settings-scopes.html) that excludes the `_ide_helper_models.php` and `_ide_helper` files. Then have that scope used for the inspection causing the warnings but it doesn't seem to work for me.

This worked for me! Thanks. I created the scope, then went to the 'Multiple class definitions' inspections and deselected the new scope.

**Comment by ThomasCollignon** [comment]
@jamesratcliffe I'm not convinced it is supposed to work like that. In _Inpections -> Undefined symbols -> Multiple class declarations_ I can use a scope for the sources wherein the inspection applies, but not for where the inspection looks for classes definitions.

**Comment by jamesratcliffe** [comment]
@ThomasCollignon Does that mean that my steps are just effectively disabling the inspection?

**Comment by jamesratcliffe** [comment]
@ThomasCollignon You're right. I tested with the scope it just excludes a random file. The inspection is disabled in other files, but not in that excluded file.

I'm pretty sure this means the only workaround is to not use this option with `ide-helper` or to totally disable the inspection. 😞
