### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by freekmurze** [barryvdh/laravel-ide-helper#431]
Hi,

could you already tag a L5.4 compatible release like you've done with [debugbar](https://github.com/barryvdh/laravel-debugbar)?

**Comment by barryvdh** [comment]
Did you test the latest `^2@dev` version with the current 5.4? Is this good to tag?

**Comment by barryvdh** [comment]
Tagged v2.2.3, let me know if you run into problems!

**Comment by freekmurze** [comment]
Cool, thanks!

**Comment by bionicmaster** [comment]
I'm having this error, with any version:   Call to undefined method Illuminate\Foundation\Application::share()

**Comment by barryvdh** [comment]
Ah we should replace those with singleton (see upgrade docs) 
Can you submit a PR for the service provider?

**Comment by bionicmaster** [comment]
Sure, I will do, thanks

**Comment by barryvdh** [comment]
Actually, I think this should already be fixed and tagged. Are you sure you have the latest version?

**Comment by donnygunawan93** [comment]
how to install in L5.4?
just need to copy https://gist.githubusercontent.com/barryvdh/5227822/raw/e559691e54eb0a5da95d98188d1fa3a27fbfa535/_ide_helper.php ? but I still got error om my facade.

**Comment by barryvdh** [comment]
https://github.com/barryvdh/laravel-ide-helper#install

I'll regenerate the gist when I have the time for L5

**Comment by thoys** [comment]
laravel-ide-helpers doesn't seem to work at all for me with L5.4, I've tried regenerating multiple times, did anyone get it to work? Also the file is full of errors (1100~ `Non-static method 'sendLaterOn' should not be called statically`). Thanks

**Comment by barryvdh** [comment]
What doesn't work? Cause you do get a file? 
Some Php storm linting errors cannot be avoided, but shouldn't impact the functionality

**Comment by thoys** [comment]
![image](https://cloud.githubusercontent.com/assets/607735/22402582/aa3f7990-e5fc-11e6-81e8-c869561e837c.png)

**Comment by thoys** [comment]
I do see this function in the generated file

**Comment by barryvdh** [comment]
Don't import the facade, then it won't work indeed.

**Comment by thoys** [comment]
I'm not sure what you mean, sorry, thanks for the fast response btw 👍

**Comment by barryvdh** [comment]
You're referencing the full path, while for it to work, just use the facade in the global namespace. Eg. Remove the use..

**Comment by TheDeadCode** [comment]
Does the new version suport real-time Facades as shown here? https://laracasts.com/series/whats-new-in-laravel-5-4/episodes/8

**Comment by barryvdh** [comment]
No

**Comment by Brakkar** [comment]
Hello, I have the same kind of problem, what should I replace 

use Illuminate\Support\Facades\Validator;

with ? 

If I replace 'use' with 'namespace' it creates other problems.

Example: https://i.stack.imgur.com/CuzwM.png

**Comment by thoys** [comment]
@barryvdh thanks that helped

@Brakkar what I did to fix it is instead of `use Illuminate\Support\Facades\Validator;` only use the Facade like `use Validator;` , be sure that you do include the facade in the aliases of `config/app.php`

**Comment by Brakkar** [comment]
@thoys Thannks, indeed, this solves the issue. Seems the alias was set already in config/app.php.

**Comment by zedentox** [comment]
@TheDeadCode I discovered this feature today. I will make some tests but in all case I think you will need to specify your facades in config...

**Comment by saifulss** [comment]
@barryvdh Just spun up a new Laravel 5.4 app, generated _ide_helper.php, code-assist for Eloquent models aren't working as previously for my Laravel 5.3 app.

E.g. User::find(1)->    //doesn't show any code-assist

I compared the _ide_helper.php generated for the find method. Screenshots as follows.

Laravel 5.3 - This has correct code-assist.
![image](https://cloud.githubusercontent.com/assets/13928954/22678918/ec2eb620-ed38-11e6-814d-c0f8ef60a5c7.png)

Laravel 5.4 - This doesn't have the code-assist.
![image](https://cloud.githubusercontent.com/assets/13928954/22678937/1b6c3e80-ed39-11e6-884e-c2a28f98e21f.png)

**Comment by jtoler** [comment]
Get this error running ide-helper:^2@dev and laravel 5.4.

`php artisan ide-helper:models`

> PHP Fatal error:  Class name must be a valid object or a string in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php on line 487
> 
>   [Symfony\Component\Debug\Exception\FatalErrorException]
>   Class name must be a valid object or a string

**Comment by zedentox** [comment]
@saifulss After some research I found this https://github.com/laravel/framework/commit/3be29a0851e44a038a020fea0804dce03f01863b and if you read the Laravel API here https://laravel.com/api/5.4/Illuminate/Database/Eloquent/Builder.html#method_find the return type is mixed.

**Comment by paguemaou** [comment]
Hi,
I'm upgrading a L5.1 app with the packadge "toin0u/geocoder-laravel": "^1.0"

I use a **fresh new Lavel 5.4.**

1) add "toin0u/geocoder-laravel": "^1.0" in composer.json
2) composer update (OK....)
3) add Geocoder\Laravel\Providers\GeocoderService::class in app.php
4) composer update => error in Barryvdh ide-helper

```php
post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",           **=> error during this step**
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ]
```

What do you think ? 
Is it coming from Geocoder (maybe not validated with L5.4?) or does this comes from barryvdh/ide-helper ?

Thanks in advance,
Paguemaou

**Comment by zedentox** [comment]
@paguemaou This class exists only in version 2.x of Geocoder. (https://github.com/geocoder-php/Geocoder) What is your version ?

**Comment by paguemaou** [comment]
@zedentox 

The Geocoder's class is called from composer.json of the package.

```json
{
    "name": "toin0u/geocoder-laravel",
    "description": "Geocoder Service Provider for Laravel",
    "keywords": [
        "laravel",
        "geocoder",
        "geocoding"
    ],
    "homepage": "http://geocoder-php.org/",
    "license": "MIT",
    "authors": [
        {
            "name": "Antoine Corcy",
            "email": "contact@sbin.dk",
            "homepage": "http://sbin.dk",
            "role": "Developer"
        },
        {
            "name": "Mike Bronner",
            "email": "hello@genealabs.com",
            "homepage": "https://genealabs.com",
            "role": "developer"
        }
    ],
    "require": {
        "php": ">=5.4",
        "illuminate/support": "~5.0",
        "willdurand/geocoder": "~3.3"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "doctrine/dbal": "^2.5",
        "laravel/laravel": "^5.3",
        "phploc/phploc": "^3.0",
        "squizlabs/php_codesniffer": "^2.7",
        "phpmd/phpmd": "^2.4",
        "pdepend/pdepend": "^2.2",
        "sebastian/phpcpd": "^2.0",
        "jakub-onderka/php-parallel-lint": "^0.9.2"
    },
    "autoload": {
        "psr-4": {
            "Geocoder\\Laravel\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\": "vendor/laravel/laravel/app/",
            "Geocoder\\Laravel\\Tests\\": "tests/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.0-dev"
        }
    }
}
```
Thanks for your reply
Paguemaou

**Comment by zedentox** [comment]
@paguemaou Your problem is not related to laravel-ide-helper. I continue the conversation here https://github.com/geocoder-php/GeocoderLaravel/issues/66.

**Comment by jonnywilliamson** [comment]
@saifulss 

https://github.com/laravel/framework/pull/18625

Should be back soon!!

**Comment by NickCoolii** [comment]
For Laravel 5.4 in manual better use "doctrine/dbal": "~2.3 < 2.6", because dbal 2.6 requiers php ^7.1

**Comment by barryvdh** [comment]
If you're on php7.0 it should skip those version automatically.

**Comment by ratm54** [comment]
Hello @barryvdh,

Since i migrated from laravel 5.2 to laravel 5.4 the command :
  php -cli artisan ide-helper:models -W

output this error :                                                    
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Trait 'Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers' not found 

In composer.json i have : 
  "require-dev" : {
    "barryvdh/laravel-ide-helper": "^2.4",

Whats wrong ?

Tanhks in advance for response.

**Comment by shehi** [comment]
Make sure you have the class, and then run composer dump

**Comment by ratm54** [comment]
the class AuthenticatesAndRegistersUsers does not exist aymore in my project. I thiink it's a modification between laravel 5.2 and laravel 5.3 : 
https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0
