### ISSUE TITLE
IDE Helper for Laravel Dusk Browser instance

### ISSUE THREAD

**Issue by adityapurwa** [barryvdh/laravel-ide-helper#434]
Currently the `$browser` and `Browser` does not have any auto completion.

    $this->browse(function (Browser $browser) {
            $browser->visit('/')
                ->assertSee('Laravel');
        });

So typing `$browser->` above would not pop any suggestion.
Expecting to see suggestion for Laravel Dusk browser.

**Comment by approached** [comment]
+1

**Comment by slava-vishnyakov** [comment]
https://gist.github.com/slava-vishnyakov/5eb90352fc97702f53a41888e5bae27a

**Comment by adityapurwa** [comment]
@slava-vishnyakov referenced is your implementation? Submitting a pull request?

**Comment by slava-vishnyakov** [comment]
@adityapurwa I don't think I can do a pull request, since ide-helpers generates the files dynamically, this is just a way to get auto-complete before the official solution. 

Actually, the problem is not in ide helpers, but in PHPStorm (see my link for PHPStorm's bug).

**Comment by jonnywilliamson** [comment]
@slava-vishnyakov Thanks for that.

Just adding this link for a similar issue I had with wanting some collection macros to be visible to the IDE and how I managed to get that to work.

I'll be using your text in my file too, it might help someone else: https://github.com/spatie/laravel-collection-macros/issues/16#issuecomment-286467543

**Comment by dmitry-ivanov** [comment]
Hey, guys! :)

So, for now, the problem is fixed in PHPStorm 2017.3 and Browser methods do have autocomplete.
But what about custom component or page methods referenced at the same Browser's `_call` magic method?

```

**Comment by carltondickson** [comment]
@dmitry-ivanov, use slava's _browser_ide_helper.php he linked to.

Works fine once you add your own functions, the only issue I get now is a message saying multiple class definitions exist for Browser.

**Comment by dmitry-ivanov** [comment]
@carltondickson For my project I've created `./tests/Browser/_ide_helper_dusk.php` with the following code:

```
<?php

namespace Laravel\Dusk;

/**
 * @method Browser assertOnPage()
 * @method Browser assertElementEnabled($selector)
 * @method Browser assertElementDisabled($selector)
 * @method Browser assertSeeConfirm($text, $ok = 'OK', $cancel = 'Cancel')
 * ... and so on ...
 */
class Browser
{
}
```

So, I'm just specifying which custom methods were added in my base and specific page classes.
This file is not included anywhere, it just created for IDE. And yes, you can disable "multiple class definitions" warning in PHPStorm too (just by clicking on the "lamp" icon near it).

Anyways, it would be cool to have that as a part of `laravel-ide-helper`.

**Comment by alistairreynolds** [comment]
It isn't quite laravel and means a bit of overriding, but I extend the default dusk browser and add any additional methods in there, stored as traits for tidyness.

This means that they'll be available on every test page, so I prefix each method with the page to prevent confusion

It's not the perfect solution, but works for me

### Extended Browser class
```
namespace Tests\Browser;

use Tests\Browser\Traits\MapMethods;

class Browser extends \Laravel\Dusk\Browser
{
    
    use MapMethods;
```


### Trait
```
trait MapMethods
{

    /**
     * Searches for the passed item
     *
     * @param                        $search
     * @param int                    $pauseSeconds
     *
     * @return $this
     */
    public function mapSearch($search, $pauseSeconds = 500)
    {
```

### Test
```
use Tests\Browser\Browser;
use Tests\DuskTestCase;


class MapPageTest extends DuskTestCase
{


    /**
     * @throws \Throwable
     */
    public function testCanOpenMap()
    {
        $this->browse(function (Browser $browser) {
```
