### ISSUE TITLE
MS SQL issues

### ISSUE THREAD

**Issue by vedmant** [barryvdh/laravel-ide-helper#435]
Hi, I wanted to use "ide-helper:models" with "sqlsrv" driver, I run MS Sql server for my database. But I get following error for each model:

Exception: SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute
Could not analyze class App\SomeModel

**Comment by tucq88** [comment]
Yeah, got same trouble. My new project needs to work with MSSQL, if this package could support model generation for MSSQL, that would be awesome.

**Comment by barryvdh** [comment]
Sorry don't have MSSQL. I'm using Doctrine to generate it. If you can submit a PR that would be great.

**Comment by tucq88** [comment]
Thanks for let us know. I'll take a look about how it works in raw first then will try to make a PR. Great package btw

**Comment by supernaut** [comment]
Any work being done on this issue? I'm also on MSSQL and can't generate phpdocs for models.

**Comment by DarthMuto** [comment]
The problem is a bit deeper (DBAL, it's own descendants of PDO etc). It also crushes DBAL-based model generators.
For me the solution was enabling persistent connections, basic PDO is used then.

config/database.php:

    'connections' => [
        'sqlsrv' => [
            'driver' => 'sqlsrv',
            // ...
            'options' => [\PDO::ATTR_PERSISTENT => true],
        ],
    ],

Can be done for local environment only if necessary:

    $pdoOptions = [];
    if (env('APP_ENV') == 'local') {
        $pdoOptions[\PDO::ATTR_PERSISTENT] = true;
    }
    // ...
    return [
        'connections' => [
            'sqlsrv' => [
                'driver' => 'sqlsrv',
                // ...
                'options' => $pdoOptions,
            ],
        ],
    ];

**Comment by tucq88** [comment]
@DarthMuto Did you manage to make it work?

**Comment by DarthMuto** [comment]
Yep, works fine.

**Comment by yifei3212** [comment]
Is this issue solved? I tried @DarthMuto 's method, but got this exception: 
`Exception: SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS cannot be used with persistent PDO instances`

**Comment by georanma** [comment]
> The problem is a bit deeper (DBAL, it's own descendants of PDO etc). It also crushes DBAL-based model generators.
> For me the solution was enabling persistent connections, basic PDO is used then.
> 
> config/database.php:
> 
> ```
> 'connections' => [
>     'sqlsrv' => [
>         'driver' => 'sqlsrv',
>         // ...
>         'options' => [\PDO::ATTR_PERSISTENT => true],
>     ],
> ],
> ```
> 
> Can be done for local environment only if necessary:
> 
> ```
> $pdoOptions = [];
> if (env('APP_ENV') == 'local') {
>     $pdoOptions[\PDO::ATTR_PERSISTENT] = true;
> }
> // ...
> return [
>     'connections' => [
>         'sqlsrv' => [
>             'driver' => 'sqlsrv',
>             // ...
>             'options' => $pdoOptions,
>         ],
>     ],
> ];
> ```

Still seeing this issue, and the above patch was not a fix for me.
