### ISSUE TITLE
IDE Helper caused a weird unit test malfunction in Laravel 5.3

### ISSUE THREAD

**Issue by zxz054321** [barryvdh/laravel-ide-helper#439]
Failed to run Laravel 5.3 unit test after requiring `barryvdh/laravel-ide-helper` in composer.json.

Travis CI report(**Laravel 5.2** with `barryvdh/laravel-ide-helper`)
**_Nothing goes wrong._**
https://travis-ci.org/zxz054321/laravel4china/builds/195412053

Travis CI report(**before** requiring `barryvdh/laravel-ide-helper`)
**_Nothing goes wrong._**
https://travis-ci.org/zxz054321/laravel4china/builds/197570800

Travis CI report(**after** requiring `barryvdh/laravel-ide-helper`)
**_Failed._**
https://travis-ci.org/zxz054321/laravel4china/builds/197572164

Error message:
> PHP Fatal error:  Call to undefined method Illuminate\Console\Application::forgetBootstrappers() in /home/travis/build/zxz054321/laravel4china/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php on line 151

**Comment by barryvdh** [comment]
Not really sure why this happens. Is it just with installing, or after adding the service provider?

**Comment by zxz054321** [comment]
Just with installing. Didn't add a service provider or change the `config/app.php`.

To reproduce this bug, just install a new Laravel 5.3, composer require `barryvdh/laravel-ide-helper`, run `phpunit`(or run it in Travis), and you'll see the error message.

https://travis-ci.org/zxz054321/laravel4china/builds/202480241
https://github.com/zxz054321/laravel4china/blob/fix-phpunit-issues/app/Providers/AppServiceProvider.php
https://github.com/zxz054321/laravel4china/blob/fix-phpunit-issues/config/app.php#L167

**Comment by zxz054321** [comment]
Would it be a problem of package version conflict?

**Comment by mfn** [comment]
@barryvdh old/outdated versions, I suggest to close this issue :}
