### ISSUE TITLE
Fatal  Error running with codeception

### ISSUE THREAD

**Issue by timbroder** [barryvdh/laravel-ide-helper#440]
```PHP Fatal error:  Cannot redeclare class App in ~/workspace/kidfund/web/_ide_helper.php on line 1098```

Looking around to see if I can somehow exclude thison codeception's end

The exclusion code is still at the top:

```
namespace {
    exit("This file should not be included, only analyzed by your IDE");
```

**Comment by barryvdh** [comment]
What if we put a return statement above the exit?

**Comment by timbroder** [comment]
negative

**Comment by barryvdh** [comment]
Then I guess you should exclude it somehow in codeception. 
Not sure why it's included in the first place

**Comment by timbroder** [comment]
[trying](https://github.com/Codeception/Codeception/issues/3990 "trying") 😄 

I'll let you know what I come up with

**Comment by timbroder** [comment]
[Solved!](https://github.com/Codeception/Codeception/issues/3990#issuecomment-277378105 "Solved!")
