### ISSUE TITLE
note on whereKey 5.4

### ISSUE THREAD

**Issue by dhonions** [barryvdh/laravel-ide-helper#442]
Not an issue just a note for 5.4

Not a good idea to use 'key' as a table column name while using the model helper methods generated by ide-helper:models since they introduced 'whereKey' method in 5.4  as it returns null.

 * @method static \Illuminate\Database\Query\Builder|\App\Http\MyApp\Model\MyModel whereKey($value)

ie. 
<=5.3 returns row
MyModel::whereKey($name)->first();

5.4 returns null
MyModel::whereKey($name)->first();

Use instead
MyModel::where('key','=',$name)->first();

Took me a little while to work out why nothing worked as expected.

**Comment by MladenJanjetovic** [comment]
same here, I just can't use my `key` column like `$m->whereKey($my_key_name)`

**Comment by LukasLt** [comment]
There is a new whereKey method in Eloquent\Builder class.

```php
    # Illuminate\Database\Eloquent\Builder
    /**
     * Add a where clause on the primary key to the query.
     *
     * @param  mixed  $id
     * @return $this
     */
    public function whereKey($id)
    {
        if (is_array($id) || $id instanceof Arrayable) {
            $this->query->whereIn($this->model->getQualifiedKeyName(), $id);

            return $this;
        }

        return $this->where($this->model->getQualifiedKeyName(), '=', $id);
    }
```

so instead of selecting by `key` column, it selects by tables `primary key`. 
In other words - we have a naming conflict preventing shortcut for actual key column.

-----------------
**Is it possible to somehow mark `whereKey` method as dangerous, or at least mark it as `not working as expected`?**

**Comment by mfn** [comment]
What is the actual issue?

Is it that, if there's a column `key` that it generates `whereKey` shadowing the actual `\Illuminate\Database\Eloquent\Builder::whereKey` ?
