### ISSUE TITLE
Cannot install, composer gives strange error.

### ISSUE THREAD

**Issue by JacobCZ** [barryvdh/laravel-ide-helper#444]
I've just tried to install this using composer and I'm getting this error:

``` [ErrorException]
  Argument 1 passed to Composer\Autoload\ClassLoader::addClassMap() must be of the type array, integer given, called in phar:///vagrant/tracker/composer.phar/src/Compose
  r/Autoload/AutoloadGenerator.php on line 755 and defined
```

(Laravel 5.4.11)

**Comment by errogaht** [comment]
+1

**Comment by JacobCZ** [comment]
@errogaht I've come to a temporary solution! Delete the contents of your vendor directory and give it 777 permissions. It works but it's not ideal...

This problem doesn't occur in windows because of the very different way Windows handle file permissions.

**Comment by mfn** [comment]
@barryvdh old issue, seems unrelated to the package itself, vote for closing :}
