### ISSUE TITLE
[Feature] Add meta data for routes/views etc

### ISSUE THREAD

**Issue by barryvdh** [barryvdh/laravel-ide-helper#447]
In theory more classes, besides the IoC container, could benefit from the meta file for phpstorm. 

- [ ] Views
- [ ] Routes
- [ ] Config
- [ ] Translation

Only problem it would have to be generated every time..

**Comment by evgeniy-n** [comment]
@barryvdh There are plugin for phpstorm which already handle this.
Check it: https://plugins.jetbrains.com/plugin/7532-laravel-plugin
It's very cool, but it break work of .meta.php so I just recompile it without some features :)
