### ISSUE TITLE
All static methods on model broken

### ISSUE THREAD

**Issue by chancezeus** [barryvdh/laravel-ide-helper#448]
I (just) updated ide-helper to the newest version and regenerated the _ide_helper.php file. This however results in code-completion in IntelliJ to become completely broken for all models, it somehow cannot find any normal model methods anymore (static::{event} inside boot, $this->{relationshipType}, etc). Removing the _ide_helper.php file makes these work again (but of course no more completion on facades/fluent/etc)...

It looks like an issue related to the generation of a (facade) interpretation of "Illuminate\Database\Eloquent\Model" (since IntelliJ complains about duplicate definitions for this file)...

**Comment by barryvdh** [comment]
Should we remove the Eloquent facade from completion?

Can you remove the Eloquent facade from your config and regenerate the file? (You can then put it back if you use the Eloquent facade). Does that help?

**Comment by chancezeus** [comment]
That does indeed fix the auto-completion issues but this results in the "\Eloquent" mixin comment not working anymore (and of course the magic ide-helper extras linking it to the Eloquent\Builder and Query\Builder)...

I think instead of removing/disabling the facade the fqn should not be used for models...

**Comment by chancezeus** [comment]
It might be (have not yet noticed it yet) that the new functionality breaks other classes too (in intellij)... maybe it should be a configurable opt-in/-out...

**Comment by barryvdh** [comment]
Yeah but eloquent is special,you don't extend other facades.

**Comment by pinepain** [comment]
Same here. On default settings ide helper is barely usable after v2.2.3, had to downgrade.

**Comment by barryvdh** [comment]
Can you try with https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.3.2 ? Should be able to complete when extending `Eloquent` or using `@mixin \Eloquent`

**Comment by pinepain** [comment]
@barryvdh it seems to work nicely at first look. Thanks a lot!

**Comment by mfn** [comment]
@barryvdh issue is solved per user feedback, issue can be closed :}
