### ISSUE TITLE
Eloquent\Model multiple implementation

### ISSUE THREAD

**Issue by iboldurev** [barryvdh/laravel-ide-helper#451]
Hi, autocomplete models in phpstorm not work.

Laravel 5.4.12
Ide-Helper v2.3.0

If delete a file _ide_helper.php that autocomplete in model file work.

![2017-02-19 16 52 43](https://cloud.githubusercontent.com/assets/17103170/23103443/035e2df0-f6c4-11e6-820b-483c02688d23.png)

**Comment by iboldurev** [comment]
If delete a file _ide_helper.php that autocomplete in model file work.

**Comment by rokde** [comment]
Version 2.2.3 is correct. 2.3.0 same error like shown.

**Comment by barryvdh** [comment]
It's not an error, it's a warning. But doesn't it work now then?

**Comment by barryvdh** [comment]
Can you try with https://github.com/barryvdh/laravel-ide-helper/commit/25c8de637ddf79567d721c1856616be01db7b960 ?

**Comment by rokde** [comment]
Yes, that works! ;)

**Comment by iboldurev** [comment]
@barryvdh Thanks, it works

**Comment by barryvdh** [comment]
Can you try with https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.3.2 ? Should be able to complete when extending `Eloquent` or using `@mixin \Eloquent`

**Comment by cviebrock** [comment]
I'm using 2.3.2 in a new Laravel 5.4 project.  I've also used

```sh
php artisan ide-helper:models --nowrite
```

to put the annotations in a separate file.  Naturally, this means I get the warning from PHPStorm: "Other declaration of class User exist at User.php" for my models.

Is there a solution to this when using a separate `_ide_helper_models.php` file?
