### ISSUE TITLE
Wrong facades namespace

### ISSUE THREAD

**Issue by pinepain** [barryvdh/laravel-ide-helper#455]
In laravel-ide-helper v2.3.1 (actually, after v2.2.3) when namespaced facade alias defined, in generated helper it still imported into root namespace (though, in advance to the right namespace).

**Comment by pinepain** [comment]
Closed because of misconfiguration, though we faces with facades duplication =(

**Comment by barryvdh** [comment]
Yes, facades are duplicated, but otherwise we can't provide any autocompletion.

**Comment by pinepain** [comment]
It should be a separate issue, though I haven't yet figured out the cause, but in brief, in service provider I have

```php
public function boot() {
        $loader = AliasLoader::getInstance();

        $loader->alias('My\Remove', My\Awesome\Pacakge\Has\Remote\Facade::class);
}
```

which later doesn't aliased in project app.php, but in ide helper it get imported to root namesapce as Remote, which is not right and which conflict with Laravel's Remote facade which also in a root namespace. And I see not Remote in ide helper under My namespace which is also a bit disappointing. At this time I stay on 2.3.1, but will try to find some time to dig what went wrong in latest versions (haven't checked the diffs yet). If you have something in mind - please suggest.

**Comment by barryvdh** [comment]
Ping @zedentox ideas?

**Comment by pinepain** [comment]
At this time can confirm that issue introduced in 525733122ee14eceabcc60815fcf2b16a7f53d85.

**Comment by pinepain** [comment]
The issue (obviously?) came from https://github.com/barryvdh/laravel-ide-helper/blob/e82de98cef0d6597b1b686be0b5813a3a4bb53c5/resources/views/helper.php#L40-L63 where we assume that all aliases come from root namespace, which is in my case is not.

**Comment by zedentox** [comment]
@pinepain Can you give us the code actually generated in `_ide_helper.php` and your aliases in `app.php` ? It's the first time I see someone using a namespaced alias so I never tested this. 😄 
It's a problem for sure. I will fix it.

**Comment by pinepain** [comment]
@zedentox Not sure about original ide helper as it a private project, but I'll create some small reproducible demo now.

**Comment by zedentox** [comment]
@pinepain Yes of course I only want the wrong parts and what is attended. You can obfuscate all other things.

**Comment by pinepain** [comment]
@zedentox here is the commit which adds namespaced alias and generates ide helper - https://github.com/pinepain/ide-helper-facades/commit/2e2754254ce30389ef782b6d1bf6c56b7eadec0d. The whole repo is bare laravel 5.4 with laravel-ide-helper installed. Notice that `TestIdeHelper` lies in a root namespace while it's under `App` ns initially. I created `test` artisan command to demonstrate that aliased facade works as expected, to test that run `php artisan test`. Thanks for you help and sorry for not looking into it myself.

**Comment by zedentox** [comment]
Your ide-helper config is missing ? The alias must be defined somewhere in config and not only on runtime.

**Comment by barryvdh** [comment]
I think it can be defined in runtime, as we ask the AliasLoader for all aliases.

**Comment by zedentox** [comment]
Ok I see. I'm working on it.

**Comment by pinepain** [comment]
@zedentox calling `AliasLoader:alias()` is the same as specifying aliases in `app.aliases`, under the hood that config array get set to `AliasLoader::$aliases` , and `AliasLoader:alias()` adds items there one by one, so it mostly doesn't matter, the result still the same.

**Comment by zedentox** [comment]
@pinepain Can you try this one ? zedentox/laravel-ide-helper@3f2f0bf2ce6df5f220d04aa891a56703dfd5256b

**Comment by pinepain** [comment]
@zedentox seems to be working like a charm, thanks a lot! Will wait to get it merged and patch version released.
