### ISSUE TITLE
Can you please help with functionality in VS Code?

### ISSUE THREAD

**Issue by neeravp** [barryvdh/laravel-ide-helper#457]
I have used laravel-ide-helper earlier with phpstorm without any issues and find it to be extremely useful. However it doesn't work with VS Code.   
Can you please help to make it work with VS Code?

**Comment by barryvdh** [comment]
What does need to change for VS code?

**Comment by neeravp** [comment]
Excuse me for the delayed response.   
I have absolutely no idea regarding what needs to be done. The thing is that laravel-ide-helper with phpstorm gives intellisense for blade directives as well as the facades, while even after installing laravel-ide-helper and generating the file, in vs code it has no effects. Doesn't help get intellisense for Facades and Blade directives in vs code.  
Can you help me with pointers as to what should I explore to get the desired intellisense with laravel-ide-helper in vs code?  
Thanks for your response and eagerly awaiting ...

**Comment by mfn** [comment]
@barryvdh as was established elsewhere, the generated files are mostly IDE agnostic. As there's nothing specific here for improvement, I vote for closing this issue :}
