### ISSUE TITLE
.phpstorm.meta.php has no effect in EAP PhpStorm 2017.1

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [barryvdh/laravel-ide-helper#460]
No autocomplition on this and similar...
```
app('events')->f
\app('events')->f
```
http://joxi.ru/L21lbV3TbPLBmX?d=1
http://joxi.ru/zAN4VvQik4KWm9?d=1

.phpstorm.meta.php generated, PHPStorm restarted, etc.

may be they removed [Depricated](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata#PhpStormAdvancedMetadata-Deprecated:Legacymetadataformat(2016.1andearlier)) format? 

tried the same project in older PhpStorm 9.0.2  - autocomplete works [fine](http://joxi.ru/Vm6z7VkHaw1zmZ?d=1).

**Comment by dustingraham** [comment]
As a note, I am using 2017.1 and app('events')->f autocompletes with a fresh phpstorm.meta and laravel 5.4

```
PhpStorm 2017.1
Build #PS-171.3780.104, built on March 21, 2017
JRE: 1.8.0_112-release-736-b13 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 8.1 6.3
```

**Comment by Vasiliy-Bondarenko** [comment]
@dustingraham, autocompletes with correct fire() method? or other trash like factory()?

**Comment by dustingraham** [comment]
@Vasiliy-Bondarenko Oops, you're right. Trash like factory(). Sorry. Was rushing to get this set up.

So yes, this is a problem in mine too.

**Comment by jonnywilliamson** [comment]
@Vasiliy-Bondarenko @dustingraham 

This appears to be fixed now in the latest release of 0.14.1

https://github.com/barryvdh/laravel-ide-helper/issues/473

**Comment by dustingraham** [comment]
@jonnywilliamson Version `0.14.1` of what? I did a composer update, and php artisan ide-helper:meta and generated a new .phpstorm.meta.php but app('events')->f still shows "factory" rather than "fire"

app(' does show "events" as a suggested app('.. autocomplete, but then the methods available are not being offered.

**Comment by jonnywilliamson** [comment]
@dustingraham 

1) Do `File->Invalidate caches` in phpstorm and restart. That fixed an issue for me.

If that does not work, 
2) install the laravel plugin (using phpstorm plugin menu). The source is from here: https://github.com/Haehnchen/idea-php-laravel-plugin but you use phpstorm to install it.

**Comment by dustingraham** [comment]
After File->Invalid Cache and restart, it prompted me up update from 0.14 to 0.14.1 for the laravel plugin. After that, I did file->invalid cache and restart a second time, and now app('events')->fi shows "fire" as an option. ( @Vasiliy-Bondarenko )

Thanks Jonny.

**Comment by Vasiliy-Bondarenko** [comment]
yep. working fine. thanx.
