### ISSUE TITLE
Missing query grammar references  (PhpStorm 2017.1)

### ISSUE THREAD

**Issue by FrancoisH** [barryvdh/laravel-ide-helper#461]
When building a new query and using `Illuminate\Database\Query\Grammars\Grammar` methods like whereYear, whereMonth, i get warning for missing method usage in the editor.

It already happened in PHPStorm 2016 for a few methods here and there.

Maybe am I using this wrongly. Maybe could you pinpoint to me what I'm doing wrong if it's my fault :)

**Comment by mfn** [comment]
`<Mode>::whereYear` etc. is correctly autocompleted as well as `<Model>::where()->whereYear()`

I'm not exactly sure how the `Grammar` is involved here, as usually it's either `Query\Builder` or `Eloquent\Builder` being involved here.

@FrancoisH do you still have the issue with the latest version?
