### ISSUE TITLE
published config file not working in lumen

### ISSUE THREAD

**Issue by 00madz** [barryvdh/laravel-ide-helper#465]
I'm new to laravel/lumen so appologies if this is my mistake, but I followed the lumen instructions in the readme then (using laravelista/lumen-vendor-publish) published the config file so I could overwrite `'include_fluent' => true` however I found the published config file was not being used. I needed to add `$this->app->configure('ide-helper');`, I'm not sure whether everyone just knows to do this in lumen and why it isn't required in laravel? or whether it's a bug and there should be a call to this in the register() method of the IdeHelperServiceProvider class? 
Maybe it's something I should be reporting over on laravelista/lumen-vendor-publish?

**Comment by ZiperRom1** [comment]
Works well thx
