### ISSUE TITLE
Model docblock generation does not take declared return type into account.

### ISSUE THREAD

**Issue by miklcct** [barryvdh/laravel-ide-helper#468]
Take the following PHP code as an example:

````
class Foo extends Model {
    public function getTypeAttribute() : int {
        return 0;
    }
}
````

If I generate the doc for this model, the $type attribute is shown up as mixed but not int.

**Comment by mfn** [comment]
Run into the same thing. It seems currently only the phpdoc is evaluated. If you change it to:
```php
/**
 * @return int
 */
public function getTypeAttribute() : int {
    return 0;
}
```
it will be correctly generated.

**Comment by mfn** [comment]
@barryvdh this was fixed with https://github.com/barryvdh/laravel-ide-helper/pull/906 , issue can be closed :}
