### ISSUE TITLE
phpstorm.meta.php can now be a folder-name containing multiple files!

### ISSUE THREAD

**Issue by jonnywilliamson** [barryvdh/laravel-ide-helper#469]
@barryvdh 

Over the last 2 weeks I came across an article online that described a new feature of phpstorm with regards processing of the `.phpstorm.meta.php` file.

Alas I can not for the life of me find that article, but it explained the following:

`.phpstorm.meta.php` can now be the name of a FOLDER in your project. Inside the folder you can now have MULTIPLE `php` files that contain custom data.

I have just tested this out and it seems to be working really well. The only thing you MUST do after creating the `.phpstorm.meta.php` **FOLDER** and moving any metadata **FILES** into it, is _RESTART_ the IDE. It won't pick up those files until the IDE has been restarted.

I was wondering if you might be interested in either
1) provide a config option to create the folder `.phpstorm.meta.php` instead of only the file `.phpstorm.meta.php`
2) make the folder the new default method when generated with this package?

I would attempt to send a PR if I knew what option you leaned more towards.

This then allows anyone to add their own files into the project to be used AS WELL as the one generated by this repository. Currently, because only 1 file is being read by the IDE at the moment it's hard to customise or add to this package's `.phpstorm.meta.php` file because it keeps getting overwritten relatively frequently and destroying any manual additions...

Here's an example of a previous issue: https://github.com/barryvdh/laravel-ide-helper/issues/337#issue-143846792

**Comment by jonnywilliamson** [comment]
Of course as soon as I posted this I found the article online. 

https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata#PhpStormAdvancedMetadata-Deprecated:Legacymetadataformat(2016.1andearlier)

![image](https://cloud.githubusercontent.com/assets/2513663/24322747/44c96346-1162-11e7-9c8c-0a0b9f3ce717.png)

**Comment by jonnywilliamson** [comment]
Do you have any thoughts on this @barryvdh ? Positive or negative! :)

**Comment by barryvdh** [comment]
> By using example metadata below It can reside anywhere, but we recommend using .phpstorm.meta.php file in project root.

So should already work?

**Comment by jonnywilliamson** [comment]
@barryvdh 

Evening, so I did some testing this evening and these were the results.

- If there is a `.phpstorm.meta.php` file, phpstorm will only read meta data from that file. ie, if you create `another.meta.php` file in the root folder, and put valid data in it, it does not get parsed.

- If you create a folder called `.phpstorm.meta.php` you can then put as many files in that folder, with whatever filename you want and they will ALL get parsed.

![image](https://cloud.githubusercontent.com/assets/2513663/24630471/c7494dd2-18b4-11e7-8a7f-f0bddd2ea6de.png)


Technically, I could use this project to create a `.phpstorm.meta.php` FILE, and then rename it and place it in a `.phpstorm.meta.php` FOLDER. That would then allow anyone to add more files to the folder for some custom meta data that would help with autocomplete. However this seems quite a tedious workflow.

How do you feel about having the meta file generated by this project, saved to a `.phpstorm.meta.php` FOLDER with the name `ide-helper.meta.php` for example?

**Comment by barryvdh** [comment]
I think that does make sense, only worried that it might be BC break.

**Comment by jonnywilliamson** [comment]
Yes, I think you could be right. 😞 

Perhaps leaving the file name AND folder as `.phpstorm.meta.php` for this project would be a way to avoid that?

![image](https://cloud.githubusercontent.com/assets/2513663/24631730/57b0beba-18b9-11e7-8b8e-0db0d7493327.png)


(This works, I've just checked)

**Comment by jonnywilliamson** [comment]
At the moment I just use the following command in my composer.json file to save the generated `.phpstorm.meta.php` into a folder. This allows me to add other files into the folder and phpstorm can then read them all:

```
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta --filename='.phpstorm.meta.php/phpstorm.php'",
            "php artisan optimize"
        ]

```

IMHO, I think this should be the default setting for this package, but as it's an easy work around I'll leave that for @barryvdh to decide!
