### ISSUE TITLE
System fails if the main laravel app does not implement the PhpEngine renderer.

### ISSUE THREAD

**Issue by theMadness** [barryvdh/laravel-ide-helper#474]
See topic.

    $ php artisan ide-helper:meta
                                 
      [InvalidArgumentException]  
      View [meta] not found.

**Comment by theMadness** [comment]
Issued PR #475 that fixed the issue locally, it's hastily put together, but I think it's overall an improvement.

**Comment by mfn** [comment]
@barryvdh above PR was merged, issue can be closed :}
