### ISSUE TITLE
Running artisan commands yields error after Laravel-ide-helper installed

### ISSUE THREAD

**Issue by joeizang** [barryvdh/laravel-ide-helper#477]
hi,

thanks for making this cool project. I installed your package on a fresh laravel 5.4 install and when I tried to run php artisan clear-compiled I get the following error:

`[Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found`

so I can't even run php artisan ide-helper:generate or any of the relevant commands.

please help.

**Comment by mfn** [comment]
The trait by this name doesn't exist anymore:
- t was renamed => https://github.com/laravel/framework/commit/a742b7971686f543cb58af53ee9a144f78c347e3
- there's a closed issue with the new name => https://github.com/barryvdh/laravel-ide-helper/issues/909 => user closed it itself so I assume it's non-issue

@barryvdh IMHO this issue can be closed
