### ISSUE TITLE
New syntax for PhpStorm Advanced Metadata file

### ISSUE THREAD

**Issue by jonnywilliamson** [barryvdh/laravel-ide-helper#478]
It appears that Phpstorm has created a newer syntax for the `.phpstorm.meta.php` file that can be created using this package.

https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

One of the lines in the sample of the newer syntax says:
![image](https://cloud.githubusercontent.com/assets/2513663/24591593/fde49684-17fc-11e7-9453-37303e3eb22a.png)

Which just led me to wonder:

- Would using the new syntax make creating the `.phpstorm.meta.php` file easier (for this package to do)?
- Are there any significant benefits for using the new syntax. I can only follow the "code" somewhat but don't see anything massive that jumps out at me for using the new syntax.
- Is there any risk that in the near future if this package isn't able to produce the new format code, that the ability to use the meta file might be lost. Would it be sensible to start moving towards the new syntax.

No doubt you've probably already seen this and maybe made a decision, but I just thought I'd bring it up here as I couldn't find any other issue about it.

Thanks.

**Comment by barryvdh** [comment]
I did see it and gave it a try, but didn't really get it to work. Might need to try on the latest version again.

**Comment by jonnywilliamson** [comment]
Implemented with https://github.com/barryvdh/laravel-ide-helper/pull/523
