### ISSUE TITLE
Missing argument 1 for Illuminate\Support\Manager::createDriver()

### ISSUE THREAD

**Issue by G-Rath** [barryvdh/laravel-ide-helper#479]
Today I tried installing [Laravel-FCM](https://github.com/brozot/Laravel-FCM), and generating the _ide_helper code for it's Facades, but got this error:

```
Exception: Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and defined
Skipping \LaravelFCM\Facades\FCM.
Exception: Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and defined
Skipping \LaravelFCM\Facades\FCMGroup.
A new helper file was written to _ide_helper.php
```

Looking at other facades the FCM facade seems the same, but I don't know Laravel enough to come up with an explanation. 

I'm not sure if this is an issue with the library, or with laravel-ide-helper, so any assistance on this matter would be greatly welcomed. 

Right now I'm resorting to actually adding the helper code by hand, since it's only for a couple of methods.

**Comment by G-Rath** [comment]
It seems I made this issue in haste: I got the same error when trying to actually use the class. While any advice would still be welcomed, I'm confident that this issue isn't related to laravel-ide-helper.

**Comment by G-Rath** [comment]
Horribly silly of me - I had forgotten to run `php artisan vendor:publish`

**Comment by Cphil31** [comment]
don't work a have "Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /home/philippe/Documents/exos/cecilephilippedeveloppeur/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 88 and defined"
