### ISSUE TITLE
TINYINT database column identified as bool by Automatic phpDocs for models

### ISSUE THREAD

**Issue by komirad** [barryvdh/laravel-ide-helper#480]
Using `php artisan ide-helper:models`, a `TINYINT` column is documented as `bool`.

While `TINYINT` is commonly used to represent `bool`, I am using it to map to a small amount of model states.

And while I do not know what's the best way to differentiate the two, the length of the column can be used to at least rule out `bool` if it's `>1`. i.e. `TINYINT(2)` can never be `bool`.

**Comment by barryvdh** [comment]
Makes sense, can you make a Pr?

**Comment by komirad** [comment]
@barryvdh  I only just had a brief look at the source code. If you look [here](https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L356), it looks like there's no reference to tinyInt. So I am guessing this is a doctrine issue?

**Comment by komirad** [comment]
Could be related: https://github.com/doctrine/dbal/issues/1205
