### ISSUE TITLE
Exception: Undefined property

### ISSUE THREAD

**Issue by devonblzx** [barryvdh/laravel-ide-helper#484]
For some reason, the ide-helper:models command is unable to evaluate a relationship I have defined in my model.

```
Loading model 'App\ReportCrew'
Exception: Undefined property: App\ReportCrew::$country
Could not analyze class App\ReportCrew.
```

Nevermind:  Issue caused because the relationship was named the same as the field.  You can ignore this as an issue.

**Comment by nielslucas** [comment]
Thanks for your update. I have the same problem, at least I know why it happens now.

**Comment by matt-allan** [comment]
Thanks for the pointer @devonblzx. This appears to be an issue with Laravel itself so I opened an issue over there: https://github.com/laravel/framework/issues/31098
