### ISSUE TITLE
ide-helper:models -I --ignore is not working

### ISSUE THREAD

**Issue by str** [barryvdh/laravel-ide-helper#486]
Generating the docblocks for the models does not work in my case. It's trying to generate the docblock for a model where I define a specific __construct, so I tryied adding the model to the --ignore list, but it always tries to include that model. This is how I'm calling the command:

```bash
 php artisan ide-helper:models -D app/ -N  --ignore=app/Library/Reports/CRWordReport.php
```

I think it should allow not only to ignore a specific model but also to ignore a full dir, but that's another issue.

**Comment by mfn** [comment]
You need to provide the class name not the filename

@barryvdh issue can be closed :}

**Comment by str** [comment]
Wow, yea, it took a while I ended changing IDE, latest Laravel does not use facades, nor magic classes.  But thank you :)
