### ISSUE TITLE
run 'php artisan ide-helper:models' seed this

### ISSUE THREAD

**Issue by lxtac** [barryvdh/laravel-ide-helper#488]
`[Symfony\Component\Debug\Exception\FatalErrorException]  
  parse error, expecting `';'' or `'{''    `

**Comment by rohithmeethal** [comment]
This kind of errors usually happens when there is error in your code.

**Comment by lxtac** [comment]
`<?php
	
	namespace App\Http\Controllers\Web;
	
	use App\Model\User;
	use Illuminate\Http\Request;
	use App\Http\Controllers\Controller;
	use EasyWeChat\Foundation\Application;
	
	class TestController extends Controller
	{
		public function __construct(Application $wechat)
		{
			parent::__construct($wechat);
		}
		
		public function index(Request $request)
		{
			$user = User::find(12);
			dd($user);
		}
	}
`

**Comment by lxtac** [comment]
`
<?php
	
	namespace App\Http\Controllers\Web;
	
	use App\Model\User;
	use Illuminate\Http\Request;
	use App\Http\Controllers\Controller;
	use EasyWeChat\Foundation\Application;
	
	class TestController extends Controller
	{
		public function __construct(Application $wechat)
		{
			parent::__construct($wechat);
		}
		
		public function index(Request $request)
		{
			$user = User::find(12);
			dd($user);
		}
	}

`

**Comment by lxtac** [comment]
`<?php
	
	namespace App\Http\Controllers\Web;
	
	use App\Model\User;
	use Illuminate\Http\Request;
	use App\Http\Controllers\Controller;
	use EasyWeChat\Foundation\Application;
	
	class TestController extends Controller
	{
		public function __construct(Application $wechat)
		{
			parent::__construct($wechat);
		}
		
		public function index(Request $request)
		{
			$user = User::find(12);
			dd($user);
		}
	}
`

you can see,it`s have no error in my code!
