### ISSUE TITLE
New version (2.3.2) breaks custom facades

### ISSUE THREAD

**Issue by devanes** [barryvdh/laravel-ide-helper#494]
Hello,

I have custom models (non-eloquent) for which I have created Facades. My models methods are now highlighted if I use the facades. If I use the models directly, there's no problem.

`class Domain extends \App\Models\Domain {}`

`namespace App\Models {

    class Domain {
        
    }         
}`

This class \App\Models Domain has it's own (mostly static) methods. It also extends another class (which is not reflected in the _ide_helper.php as shown above) which contains more methods (static and otherwise). All of these now produce errors.

Do I need to do something specific to get these methods recognized?

**Comment by mfn** [comment]
custom non-eloquent models with facades? 🤔

Sounds very… special.

Do you still experience this problem?

**Comment by devanes** [comment]
I created those at the time to be able to approach data from an API as if they were simply eloquent database models.

But this issue is over 3 years old and the application I used it for it no longer in use (actually the whole company doesn't exist anymore). So I have no way of telling whether the problem would still occur. I'll just close the issue.
