### ISSUE TITLE
Models does not recognize "bit" as a type for MySQL

### ISSUE THREAD

**Issue by mikepmtl** [barryvdh/laravel-ide-helper#496]
When trying to run "php artisan ide-helper:models" with a model that has a MySQL field of type "bit" the following error is received.

Exception: Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it. Could not analyze class App\Contact.

**Comment by rohithmeethal** [comment]
@mikepmtl You can add custom data types in ide-helper config file, please check custom_db_types part of the config,

```
'custom_db_types' => array(
        'mysql'=>[
            'bit'=>'boolean'
        ]
    ),
```

**Comment by mfn** [comment]
@barryvdh issue is solved and can be closed :}
