### ISSUE TITLE
Add sofa/eloquence support

### ISSUE THREAD

**Issue by ebbbang** [barryvdh/laravel-ide-helper#498]
There is currently no sofa/eloquence support.

The IDE says method not found on search() method, it can be fixed by adding 
```php
* @method static \Sofa\Eloquence\Builder search($query, $columns = null, $fulltext = true, $threshold = null)
```
to Model's doc block which uses the following trait
```php
Sofa\Eloquence\Eloquence
```

However, I don't know how that can be done by laravel-ide-helper.
So if you would be so kind to add that OR point me in the right direction, so that I can solve it and create a PR.

Regards,
Ebrahim

**Comment by rohithmeethal** [comment]
@ebbbang this is one possible way to make it work I guess (not tested)
Publish config's [php artisan vendor:publish] and check ide-helper configuration array 

```
    'extra' => array(
        'Eloquent' => array('Illuminate\Database\Eloquent\Builder', 'Illuminate\Database\Query\Builder'),
        'Session' => array('Illuminate\Session\Store'),
    ),
```
I think by modifying the Eloquent part you could achieve the result.

**Comment by mfn** [comment]
I think this is as much as this package can do.

Also the library seems abandoned, almost 2 years without update, no support for Laravel 7 => probably not much traction

@barryvdh IMHO same as https://github.com/barryvdh/laravel-ide-helper/issues/90#issuecomment-649426199 , I vote for closing this :}
