### ISSUE TITLE
User fields not found in Illuminate\Contracts\Auth\Authenticatable|null

### ISSUE THREAD

**Issue by morawcik** [barryvdh/laravel-ide-helper#501]
When I try use auth()->user()->name I got "error" in PhpStorm

> Field 'name' not found in Illuminate\Contracts\Auth\Authenticatable|null

Yes I generated models helper and helper has this property.
Yes I set inluce_fluent to true

**Comment by Sorbing** [comment]
Same problem.. I'm trying to generate PhpDoc for completion `App\Models\user` instead `Illuminate\Contracts\Auth\Authenticatable` interface. I don't add the method `Illuminate\Contracts\Auth\Guard::user()` with the ide-helper.
Need to add into `_ide_helper.php` something like this:
```
namespace Illuminate\Contracts\Auth {
    interface Guard2 {
        /**
         * Get the currently authenticated user.
         * @return \Illuminate\Contracts\Auth\Authenticatable|\App\Models\User|null
         */
        public function user();
    }
}
```

**Comment by UksusoFF** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/274#issuecomment-150174132 
But now it's not work.

**Comment by apintocr** [comment]
Any workaround for this?

**Comment by dont-panic-42** [comment]
Is this really still not working, or am I doing something wrong?  

I have generated `_ide_helper.php` and `ide_helper_models.php`, and `ide_helper_models.php` includes info for `App\User`, including:

```
namespace App{
/**
 * App\User
 *
 * @property int $id
 * @property string $name
 ...
*/
	class User extends \Eloquent {}
}
```

But in PHPStorm `Auth::user()->name` still shows me the error:

> Property 'name' not found in \Illuminate\Contracts\Auth\Authenticatable|null 

I am new to PHPStorm, maybe I have something misconfigured?

**Comment by jadamec** [comment]
+1

**Comment by jadamec** [comment]
Anything new about this issue?

**Comment by safjammed** [comment]
hey bros, really need this working man. I have been juggling so many projects. this thing would boost my productivity...

is there any update about this issue?

**Comment by morawcik** [comment]
> hey bros, really need this working man. I have been juggling so many projects. this thing would boost my productivity...
> 
> is there any update about this issue?

Unfortunately no...
I have workaround for myself - in helpers file I added another helper layer
```
function user() : User|Authenticatable|null
{
    /** @var App\Models\User $user */
    return auth()->user();
}
```

**Comment by Chf-Shuvo** [comment]
Auth::user()->getAttributeValue('name')

solves the issue!

**Comment by yusufalper** [comment]
> Auth::user()->getAttributeValue('name')
> 
> solves the issue!

I don't think this is a good use case for just this issue. 

Has anyone solved this problem?
