### ISSUE TITLE
Morph relations fields are undefined

### ISSUE THREAD

**Issue by meness** [barryvdh/laravel-ide-helper#502]
Hi,

Those relations which are not morphed works perfectly but, what about morph relations?

```php
/**
     * @Relations
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function requestable(): MorphTo {

        return $this->morphTo();
    }
```

this packages creates following doc
```php
/**
 * @property-read \Illuminate\Database\Eloquent\Model|\Eloquent $requestable
/*
```

And I'm using like this `$this->request->requestable->project->id` but `project->id` is undefined.

**Comment by greatwitenorth** [comment]
Any progress on reading morphed relations?

**Comment by martov1** [comment]
Workaround.

Define your relation manually on phpdoc.

```php
/**
 * 
 * Class description 
 * @property Post|Video|OtherClass $commentable
 */
class comment .....
```

**Comment by nelson6e65** [comment]
My morphTo relation produces the same model as return type for the property:

```php
/**
 * Website.
 * [...]
 * @property-read \App\Entities\Website $owner
 */
class Website extends EntityBase
{
    
    /**
     *
     * @return MorphTo
     */
    public function owner(): MorphTo
    {
        return $this->morphTo();
    }
}
```

Is there a way to ignore these relations in order to not been overridden by `ide-helper:models` command? Or set them default to be `mixed` type?

**Comment by amcsi** [comment]
I'm having the same issue. What's the recommendation?

**Comment by MatanYadaev** [comment]
@barryvdh Can you please re-open this issue? It's still relevant
