### ISSUE TITLE
Cookie Queue class mismatch with real function

### ISSUE THREAD

**Issue by Daviex** [barryvdh/laravel-ide-helper#504]
Hello.

I'm here to report this bug: when I access the Cookie::queue method in class Cookie, it automatically bring me to CookieJar::queue, that accepts a params type (...$parameters), BUT, when the _ide_helper.php is created, this parameter request become a simple $parameters, and the PHPDoc is signed as an array type, so there's a Mismatch and a warning when using this function.

Personally, I fixed it into the _ide_helper.php directly by adding the dots before the variable, but I hope you can fix this directly into your code.
```php
<?php
        /**
         * Queue a cookie to send with the next response.
         *
         * @param array $parameters
         * @return void 
         * @static 
         */
        public static function queue(...$parameters)
        {
            \Illuminate\Cookie\CookieJar::queue($parameters);
        }
?>
```

Thanks

ps. Hope I wrote it comprensible

**Comment by Daviex** [comment]
Added a request for the pull with the fix:
https://github.com/barryvdh/laravel-ide-helper/pull/505

**Comment by mfn** [comment]
The referenced PR wasn't merged because at this point I commented there, the feature was already present 😄

This already works now, this is generated in `_ide_helper.php`:
```php
        /**
         * Queue a cookie to send with the next response.
         *
         * @param array $parameters
         * @return void 
         * @static 
         */ 
        public static function queue(...$parameters)
        {
                        /** @var \Illuminate\Cookie\CookieJar $instance */
                        $instance->queue(...$parameters);
        }
```

@barryvdh issue can be closed :}
