### ISSUE TITLE
Does not work in api.php but works fine in web.php 

### ISSUE THREAD

**Issue by ahmadbadpey** [barryvdh/laravel-ide-helper#507]
After Installation I found that I can not navigate to controller methods by `ctrl+click` on the name of controller only in `api.php` file.  while that works fine in `web.php` routes file.

Of course I'm using [dingo laravel package](https://github.com/dingo/api)  and all defined routes are like this : 

```
	$api = app('Dingo\Api\Routing\Router');

	$api->version('v1', ['prefix' => 'v1', 'namespace' => 'App\Http\Controllers'], function ($api) {
		$api->post('Profile', ['as' => 'Profile', 'uses' => 'UserController@showProfile']);
		$api->post('getEditProfile', ['uses' => 'loginController@getEditProfile']);
		$api->post('UpdateProfile', ['uses' => 'loginController@UpdateProfile']);
        });
```
Could this be problematic?

**Comment by mfn** [comment]
`$api = app('Dingo\Api\Routing\Router');`

This should work in phpstorm due to the `.phpstorm.meta.php` file; but maybe `Dingo\Api\Routing\Router::class`?

Is this still an issue?
