### ISSUE TITLE
Method not found when use model create function

### ISSUE THREAD

**Issue by morawcik** [barryvdh/laravel-ide-helper#509]
When I create new model:
` $user = User::create($attributes);`
and next I want call function from user (`$user->addRole($role)`)
I got 
>  Method 'addRole' not found in \Illuminate\Database\Eloquent\Model

**Comment by rohithmeethal** [comment]
@morawcik I dont think this issue is relevant to this package, I am assuming you are using some Roles and Permission package, in that case I think you forgot to include the trait provided by the package in your user model. I suggest you read the respective package documentation carefully.

**Comment by morawcik** [comment]
Nope, It's method in User model.

**Comment by minhphuc429** [comment]
me too

> Method 'addRole' not found in \App\User

```
User::create([
    'name' => $data['name'],
    'email' => $data['email'],
    'password' => bcrypt($data['password']),
]);
```

**Comment by delmicio** [comment]
@morawcik have you fixed this?

**Comment by morawcik** [comment]
@delmicio Nope, I left it

**Comment by hashemsh** [comment]
i have that problem with User::create($userData) .. 
Method 'create' not found in \App\User

but it's work , all data store in DB

**Comment by cyberha4** [comment]
> i have that problem with User::create($userData) ..
> Method 'create' not found in \App\User
> 
> but it's work , all data store in DB

I have the same

**Comment by mfn** [comment]
Two different issues are mixed:
- the initial reported one regarding `->addRole()` => this isn't related to this package (I commented already in https://github.com/barryvdh/laravel-ide-helper/issues/509#issuecomment-304506148 )
- the others are about `::create`
  But I just tested this, it definitely works

I suggested someone with the latter problem test with the latest version and search existing issue or create new ones with more details.

@barryvdh Original issue is not related to the package, I suggest to close issue :}

**Comment by morawcik** [comment]
@mfn How it isn't related? I have method in User model and PhpStorm can't recognize it in this way
```
$user = User::create($attributes);
$user->addRole($role);
```
Which should be done with Laravel IDE Helper. And no - in latest version still "method not found"

**Comment by mfn** [comment]
@morawcik where is `addRole` defined, where this it come from? Can you show the code?

**Comment by morawcik** [comment]
Like I said 2 times - it's method in User model
```
class User extends Authenticatable implements HasMedia
{
    use Notifiable,
        InteractsWithMedia;
    
    public function addRole(Role $role)
    {
        // 
    }

    // 
}
```

**Comment by mfn** [comment]
Which version of Laravel? Which version of ide-helper? What version of PhpStorm?

What command did you use from ide-helper _exactly_ ?

**Comment by gilvaju** [comment]
> Which version of Laravel? Which version of ide-helper? What version of PhpStorm?
> 
> What command did you use from ide-helper _exactly_ ?

Command: php artisan ide-helper:generate
PHP: 7.4.13
PHPStorm: 2020.2
Laravel: 8.15

![image](https://user-images.githubusercontent.com/677039/102699908-5d376000-4227-11eb-8d29-b8c39ca9b2e1.png)

**Comment by mfn** [comment]
Works for me, same versions:
![image](https://user-images.githubusercontent.com/87493/102725446-15900180-4317-11eb-9957-528f6244294b.png)

Did you create `_ide_helper.php`?

**Comment by gilvaju** [comment]
> Works for me, same versions:
> ![image](https://user-images.githubusercontent.com/87493/102725446-15900180-4317-11eb-9957-528f6244294b.png)
> 
> Did you create `_ide_helper.php`?

Yes, with: php artisan ide-helper:generate. Others methods is the same issues to. Like relationship methods.

**Comment by gilvaju** [comment]
> Works for me, same versions:
> ![image](https://user-images.githubusercontent.com/87493/102725446-15900180-4317-11eb-9957-528f6244294b.png)
> 
> Did you create `_ide_helper.php`?

Yes, with: php artisan ide-helper:generate. Others methods is the same issues to. Like relationship methods.

**Comment by PaVel-58** [comment]
> i have that problem with User::create($userData) ..
> Method 'create' not found in \App\User
> 
> but it's work , all data store in DB

Did you manage to solve this problem?

**Comment by Collinsboss18** [comment]
I think the issue is coming from the Model extended class

**Comment by TermoTheBavarian** [comment]
> I think the issue is coming from the Model extended class

Me too, but my user Model extends Autehnticable that also extends Model, so something is happening in between
