### ISSUE TITLE
Wrong return type on JsValidatorFacade from proengsoft/laravel-jsvalidation

### ISSUE THREAD

**Issue by alexgmin** [barryvdh/laravel-ide-helper#511]
The return type on the methods of this Facade is wrong.
_ide_helper.php
![image](https://cloud.githubusercontent.com/assets/8340441/26636113/020efa04-461c-11e7-8a24-bb379b676064.png)
[JsValidatorFactory](https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidatorFactory.php#L61)
![image](https://cloud.githubusercontent.com/assets/8340441/26636074/e706253e-461b-11e7-9f09-facf9ea174e6.png)
[Use on JsValidatorFactory](https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidatorFactory.php#L12)
![image](https://cloud.githubusercontent.com/assets/8340441/26636089/f15d507a-461b-11e7-8359-1b022623e10f.png)

I know it's probably an issue on the [package](https://github.com/proengsoft/laravel-jsvalidation), but I can't find why the generated return is `\Proengsoft\JsValidation\JavascriptValidator` instead of `\Proengsoft\JsValidation\Javascript\JavascriptValidator`

**Comment by LEI** [comment]
I can confirm this is still happening.

I tried to add the full namespace to the `@return` annotations in [JsValidatorFactory](https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidatorFactory.php) and the helper is correctly generated.

I guess the generator doesn't parse the `use` statements and just prepends the `namespace` to the relative classes found in doc blocks. I would gladly try to fix this but no idea where to start.
