### ISSUE TITLE
Multiple definitions exist for class Schema

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [barryvdh/laravel-ide-helper#516]
Not sure if there's anything that can be done for this, but I'm getting `Multiple definitions exist for class Schema` in PhpStorm.

Commenting out `use Illuminate\Support\Facades\Schema;` seems to stop the error, but I don't know if that's advisable.

**Comment by daniel-de-wit** [comment]
I usually disable the inspection for it:
![image](https://user-images.githubusercontent.com/3015394/27696523-2252b78c-5cf2-11e7-9f0f-184e5dcb65af.png)

You can find it at PHP -> Code Style -> Unnecessary fully qualified name

**Comment by teamgimb** [comment]
For people looking for an updated answer to this you can view it here:
https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-355268633

**Comment by greatwitenorth** [comment]
For people looking for an updated answer to this you can view it here:
https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-355268633
