### ISSUE TITLE
Eloquent class not created in _ide_helper.php

### ISSUE THREAD

**Issue by mrbirne** [barryvdh/laravel-ide-helper#517]
Hey, first I like your Projekt and what you are doing. But when I'm running ```php artisan ide-helper:generate``` the Eloquent class is not created in the _ide_helper.php file. I'm using Lumen 5.4 and version 2.3 of your Project.

I've downloaded the generated _ide_helper.php file so it works but the generation process should work also.

**Comment by ZiperRom1** [comment]
Try to remove your vendors and rerun `composer install`, it fixes the issue for me idk why ...

**Comment by tank-chan** [comment]
You need to set aliases in `config/app.php`, like
```
return [
    'aliases' => [
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
    ]
];
```
then run `php artisan ide-helper:generate` again

**Comment by mfn** [comment]
@barryvdh I think the last comment is correct & the solution, and this feature is known to work => I vote for closing this issue :}
