### ISSUE TITLE
Redis autocomplete not work?

### ISSUE THREAD

**Issue by mugennsou** [barryvdh/laravel-ide-helper#519]
It's a new Laravel application and I'm required predis/predis.

But the generated _ide_helper.php only has two Redis method.

like this

```
......

 class Redis {
        
        /**
         * Get a Redis connection by name.
         *
         * @param string|null $name
         * @return \Illuminate\Redis\Connections\Connection 
         * @static 
         */
        public static function connection($name = null)
        {
            return \Illuminate\Redis\RedisManager::connection($name);
        }
        
        /**
         * Resolve the given connection by name.
         *
         * @param string|null $name
         * @return \Illuminate\Redis\Connections\Connection 
         * @throws \InvalidArgumentException
         * @static 
         */
        public static function resolve($name = null)
        {
            return \Illuminate\Redis\RedisManager::resolve($name);
        }
        
    }

.....

```

Should I do other things to make it work?
Thx

**Comment by mortenscheel** [comment]
I struggled with the same, and I've come up with this little hack that seems to do the trick.

Add a DocBlock to the abstract class Illuminate\Redis\Connections\Connection:
```
/**
 * @mixin \Predis\Client
 */
abstract class Connection
```

Now if you resolve a client instance with `Redis::resolve()` PhpStorm will be able to autocomplete the methods.

![image](https://user-images.githubusercontent.com/6514342/27386515-67ba3bae-5696-11e7-81d3-fe90ecb68baf.png)

**Comment by tucq88** [comment]
@mortenscheel that seems too tricky, so I gonna need to edit vendor files to make ide-helper works :(

**Comment by AidasK** [comment]
Any solution for this?

**Comment by lokielse** [comment]
I DON'T THINK `laravel-ide-helper`, this version,  can autocomplete `Redis` commands like `Redis::set()`. 

As a result, all commands such as `get`,`get` exist in php-docs in  `Predis\ClientInterface`

There are approaches:

- In phpstorm, use `Redis::set()` and disable IDE inspection warning for "Non-static method 'set' should not be called statically.
- Use `Redis::connection()->set()`
- Create a global function named `redis()` which return `Redis::connection()`, now you can use `redis()->set()`
- Create a [`_ide_helper_redis.php`](https://gist.github.com/lokielse/6cefae42e71a06f24b15fc6e82f3f5cf) and add all methods for commands of redis.

**Comment by CloudyCity** [comment]
I just write a _ide_helper_redis.php like @lokielse said, and change all function to static. It works :)
`
<?php

namespace Illuminate\Support\Facades;

class Redis
{
      public static function psetex( ) {}
      ...
}
`

**Comment by tucq88** [comment]
Could you share it with us @CloudyCity ?

**Comment by judahnator** [comment]
Any updates on this? Autocomplete is not working on my end.
 * Library v2.6.2
 * Laravel v5.8.16
 * predis/predis v1.1.1
 * PHP 7.3.4

**Comment by 4n70w4** [comment]
The same problem! `Redis::throttle()` don't suggested!

**Comment by faridmovsumov** [comment]
I found this as the best solution

`Cache::store('redis')->set($cacheKey, $data, 3600);`

**Comment by ellermister** [comment]
@faridmovsumov 

I tried your way and it doesn't work.

This is the best I think so far.

```
/**
 * Get redis cache instance
 *
 * @return \Illuminate\Contracts\Cache\Repository
 */
function cache_redis(): \Illuminate\Contracts\Cache\Repository
{
    return Cache::store('redis');
}


/**
 * Get redis instance
 *
 * @return mixed|Redis
 */
function redis()
{
    return \Illuminate\Support\Facades\Redis::connection()->client();
}

```
