### ISSUE TITLE
Documentation error: "With the --reset (-R) option, the existing phpdocs are ignored"

### ISSUE THREAD

**Issue by JackWH** [barryvdh/laravel-ide-helper#527]
The documentation in `readme.md` states:

> With the --reset (-R) option, the existing phpdocs are ignored, and only the newly found columns/relations are saved as phpdocs.

I don't think this is correct. When I tested this, using the `--write` and `--reset` flags completely removed and replaced the entire model's docblock. I tried adding a couple of my own random properties to it, they were removed and overridden with the actual database columns.

Additionally, calling `php artisan ide-helper:models --help` indicates:

```
Options:
  ...
  -R, --reset                Remove the original phpdocs instead of appending
```

\- which contradicts what's stated in the documentation.

I'd make a pull request to correct this, but I wanted to check I'm not missing something or misinterpreting this somehow - thanks in advance!

**Comment by barryvdh** [comment]
I mean it's ignoring them and just writing new ones (so removing), but I can understand that's not totally clear. I'll accept a PR for this

**Comment by Blizzke** [comment]
I would personally prefer it to leave the description etc intact (basically everything that does not start with `@`)

I really love the functionality, especially during development, but this also means I have the blocks rewritten regularly (i don't like that the order is messed up when I append).
Unfortunately this means that I use my descriptions every time.

**Comment by barryvdh** [comment]
I'll accept a PR for this.
