### ISSUE TITLE
How to help with Trait methods?

### ISSUE THREAD

**Issue by kickthemooon** [barryvdh/laravel-ide-helper#529]
So I am using a Spatie package for roles and permissions.
I am using a trait on my User model and a trait HasRoles.
I moved my models to "App\Models" and used following commands:

```
php artisan clear-compiled
php artisan ide-helper:generate
php artisan optimize
php artisan ide-helper:models "App\Models\User" -N
```

It gives me autocompletion for, e.g. User::create but unfortunately it doesn't give me autocompletion for
$user->assignRole() which is located in the trait.

**Comment by barryvdh** [comment]
It shouldn't have to autocomplete existing methods? phpstorm can figure those out with ide-helper.

**Comment by delmicio** [comment]
@kickthemooon have you fixed this?

**Comment by forwells** [comment]
Model Traits not work in Vscode.

**Comment by Kassim-exe** [comment]
Was a solution ever found for this?
