### ISSUE TITLE
Help needed, ide-helper models

### ISSUE THREAD

**Issue by pardmeister** [barryvdh/laravel-ide-helper#530]
Hi

I have attached an image of the problem I am having below.

![screen shot 2017-06-26 at 14 15 46](https://user-images.githubusercontent.com/6696083/27538889-7570dc66-5a7a-11e7-94a2-0b8c4216ad45.png)

It seems PhpStorm is getting back \Illuminate\Database\Eloquent\Model instead of \App\Models\Client\Client. This also means that I cannot call the methods that I've created within the client model because create does not return a client. Is there something that I have done wrong?

Thanks
Pard

**Comment by crhg** [comment]
I also encounterd a similar problem about findOrFail method and I noticed that it is defined in _ide_helper.php as follows:

```php
            /**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array $columns
             * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection 
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
             * @static 
             */ 
            public static function findOrFail($id, $columns = array())
            {    
                return \Illuminate\Database\Eloquent\Builder::findOrFail($id, $columns);
            }
```

It says that findOrfail returns \Illuminate\Database\Eloquent\Model (or \Illuminate\Database\Eloquent\Collection in case of $columns is specified). But actually it returns the model class that extends \Illuminate\Database\Eloquent\Model, so I think @return line should by like this using `static`:

```php
            /**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array $columns
             * @return static|\Illuminate\Database\Eloquent\Collection 
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
             * @static 
             */ 
            public static function findOrFail($id, $columns = array())
            {    
                return \Illuminate\Database\Eloquent\Builder::findOrFail($id, $columns);
            }
```

I tried this fix and it seems to work fine.

**Comment by pardmeister** [comment]
Sorry for the delayed response, static works. Does this need to be done with all definitions?

**Comment by pablorsk** [comment]
For now, we have only one solution:

```php
/** @var Client */
$client = Client::findOrFail($some_id);
```

I try to add on Model definition, a `@method` php doc, but don't work. Any one has a better solution? My solution require write that phpdoc on every `findOrFail` with error. Also, developers can make mistakes forcing var type.

**Comment by mfn** [comment]
I think the problem was that PhpStorm didn't understand `@return static` in the past?

@barryvdh nowadays this certainly works, I vote for closing this :}

**Comment by mfn** [comment]
Closing per my comment https://github.com/barryvdh/laravel-ide-helper/issues/530#issuecomment-650160933
