### ISSUE TITLE
Wrong scope detection?

### ISSUE THREAD

**Issue by Omranic** [barryvdh/laravel-ide-helper#533]
When generating docblocks for models using `Kalnoy\Nestedset\NodeTrait` it generates a strange un-existing method doc: 
```php
* @method static \Illuminate\Database\Eloquent\Builder d()
```

After tracing, I discovered the reason here:
https://github.com/lazychaser/laravel-nestedset/blob/v4/src/NodeTrait.php#L729

It treats all methods starting with `scope` as a scope, while that may not be true in the `/lazychaser/laravel-nestedset` package. Any thoughts?

**Comment by mfn** [comment]
That's a pity, because Laravel clearly documents that methods prefixed with `scope` are supposed to be, well local scopes for models.

Even if ide-helper would not ad this, I bet you could call `->d` (or `::d`) on the model and it would _try_ to call it?
