### ISSUE TITLE
Static methods registered by factory (docblock) Not Generated

### ISSUE THREAD

**Issue by aios** [barryvdh/laravel-ide-helper#538]
Hi. I am contributor of SleepingOwlAdmin.

So this nice history:
We have some littlebit static methods like
`AdminColumn::link(params)`

That AdminColumn is alias of SleepingOwl\Admin\Display\TableColumn
Having that:
![image](https://user-images.githubusercontent.com/737550/28151325-a478e2b2-67a2-11e7-92e8-cb0d0958d1a7.png)

So registering in factory

![image](https://user-images.githubusercontent.com/737550/28151346-c7ec7588-67a2-11e7-8f83-c877c5ab0a3d.png)

Have docblock, have registry

But after call `php artisan ide-helper:generate`
We have all generated facades section 
![image](https://user-images.githubusercontent.com/737550/28151376-eb923c84-67a2-11e7-9e14-879a1e44f7f8.png)
![image](https://user-images.githubusercontent.com/737550/28151390-fd18966a-67a2-11e7-92d2-3cfbb82fd242.png)
And show must go on.
![image](https://user-images.githubusercontent.com/737550/28151408-10b2f33c-67a3-11e7-872e-50b4574d5a17.png)

that worked some time ago (3-4 month)
how i can resolve that?

**Comment by aios** [comment]
So manually i can fix that by remove all generated section from ide_helper.php
![image](https://user-images.githubusercontent.com/737550/28151556-fcce74bc-67a3-11e7-93cf-2e3debb93641.png)
like that

and all works fine
![image](https://user-images.githubusercontent.com/737550/28151577-11defa52-67a4-11e7-969f-d7e5ebc5118e.png)

**Comment by mfn** [comment]
Is this still an issue?
