### ISSUE TITLE
Overriding 'include_fluent' config value on application level

### ISSUE THREAD

**Issue by zomberg** [barryvdh/laravel-ide-helper#546]
If I understood correctly to change any setting in config I need change this directly in vendor/barryvdh/laravel-ide-helper/config/ide-helper.php.

I created my own {project_root_directory}/config/ide_helper.php file to override this setting:
```php
<?php

return [
    'include_fluent' => true,
];
```

But it is not working because in IdeHelperServiceProvider my setting was overridden by setting from vendor/barryvdh/laravel-ide-helper/config/ide-helper.php:
```php
$configPath = __DIR__ . '/../config/ide-helper.php';
$this->mergeConfigFrom($configPath, 'ide-helper');
```

Is there a way to override this setting on application level without modification original config file (vendor/barryvdh/laravel-ide-helper/config/ide-helper.php)?

**Comment by barryvdh** [comment]
Are you using a dash or underscore?

**Comment by zomberg** [comment]
Oh, it was underscore. With dash all is working great. Thank you so much for help!
