### ISSUE TITLE
phpstorm declaration navigation

### ISSUE THREAD

**Issue by devdurbs** [barryvdh/laravel-ide-helper#549]
The ide-helper is working fine for autocomplete, warnings etc.

However, one MAJOR issue is the declaration navigation in PHPStorm (Cntrl Click) does not navigate to the model method but instead to the _ide_helper_models file.

When setting the USE option two 'versions' of the model class are offered, presumably the model class and the ide-helper file (not that you can tell which is which) however both options end up pointing to the ide file.

How do I get the declaration navigation to point to the model class?

Using the latest release of ide-helper (July 2017) and Laravel 5.4. The ide_helper_models is set to create a file not place the contents within the models themselves.

Thanks

**Comment by Artistan** [comment]
Did you write the model docs?  The model writer is a separate method.

[Automatic phpDocs for models](https://github.com/barryvdh/laravel-ide-helper#automatic-phpdocs-for-models)

**Comment by devdurbs** [comment]
If you are referring to the ide-helper:models, yes. I use this in the post-update-cmd:
"php artisan ide-helper:models --nowrite"

**Comment by Artistan** [comment]
`--no-write` will write the docs to `_ide_helper_models.php`.
If you want them to reference the model itself, you need to write the docs to the model.
Otherwise it is just a helper in the `_ide_helper_models.php` file.

**Comment by devdurbs** [comment]
Thanks @Artistan, pity about that, really didn't want all that clutter in the models.

**Comment by Artistan** [comment]
At least those comments are collapsible in PhpStorm. :)

**Comment by carlituxman** [comment]
When I go to declaration then open _ide_helper instead the model. How solve this?

**Comment by mfn** [comment]
There is no way to "solve" this from this package ATM.

The whole concept builds on the premise that we've a "fake PHP file" (`_ide_helper.php`)  documenting additional properties for classes etc. so things "just work". The IDEs parse this and provide this additional information _in the correct_ context but to the IDEs, these files are not special but naturally they get linked.

@barryvdh to the best of our knowledge this is currently out-of-scope, I vote for closing :}
