### ISSUE TITLE
Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found

### ISSUE THREAD

**Issue by sulfo** [barryvdh/laravel-ide-helper#55]
Hi. I've tried to find my mistake, but I can't. I've been following the "Automatic phpDoc generation for Laravel Facades" guide, but i fails.

Running MAMP PRO with php 5.4.10.

After adding `'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider',` to the app/config/app.php this error is appearing:

Symfony \ Component \ Debug \ Exception \ FatalErrorException
Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found in
/Users/x/Sites/laravel/todo/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php line 158

If I run the `php artisan ide-helper:generate`` it generates this error

`PHP Fatal error:  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found in /Users/michaelsoerensen/Sites/laravel/todo/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 158
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider' not found","file":"\/Users\/michaelsoerensen\/Sites\/laravel\/todo\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":158}}{"error":{"type":"Symfony\\Component\\Debug\\Excep [something more I can't see....)``

The php error log have this:
`PHP Fatal error:  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found in /Users/michaelsoerensen/Sites/laravel/todo/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 158`

Any help is much much appreciated

Thanks :-)

**Comment by WindBridges** [comment]
Hi, I found this thread by googling "Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class' not found". It was my real problem which I was unable to solve. I checked my composer.json file twice, it was ok, but error still occured. Right before uninstalling this package I decided to try to remove "::class" from provider definition in app.php. And it works! 

Documentation says:
> After updating composer, add the service provider to the providers array in config/app.php
> Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

And it didn't work for me. When I replaced it to
> Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider

it works fine. And IDE recognizes all classes correctly now. 
I hope it helps to somebody with similar problem.

**Comment by pietdevries94** [comment]
Did you put quotes around `Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class`? That would break it.

**Comment by WindBridges** [comment]
Yes, of course )

**Comment by WindBridges** [comment]
Hmm, I didn't even thought that it may work without quotes, so I wrapped it without hesitation. Thank you for hint.

**Comment by pietdevries94** [comment]
`::class` is a Scope Resolution Operator. http://php.net/manual/en/language.oop5.paamayim-nekudotayim.php It returns the class which returns the same string as the quoted part.

**Comment by WindBridges** [comment]
Yes, I know about `::`, but combination with `class` keyword confuses me.

**Comment by pneal-vital** [comment]
Well done, thanks guys

**Comment by zahraMHD** [comment]
I have this problem I update my composer.json and add Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class, in my app.php in providers array but when run php artisan ide-helper:generate command I got this error " Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found " is any thing that I did not check?

**Comment by pneal-vital** [comment]
zahraMHD

 

Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' is used to enable PHPStorm to find classes. When you have “use \Request;” in your php file, PHPStorm cannot find the source file this refers to. Google/search Laravel Ide Helper in github and you will see how 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' can be used.

 

Before you try to deploy your code, comment out 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' in composer.json.

 

Hope this helps

Paul

**Comment by andrefigueira93** [comment]
pneal-vital Saving my job 363 Days after his post

**Comment by karyubi** [comment]
Hi, I am new in Laravel. I am using Netbeans 10 on Windows 10 and xampp. I dont have a folder vendor/barryvdh/laravel-ide-helper, from where could I download it or ...

**Comment by chaerf** [comment]
my case had APP_ENV=prod instead of APP_ENV=production

**Comment by Radiergummi** [comment]
This might also happen if you install composer `require` dependencies only and omit `require-dev` dependencies, as might be configured for production environments:
```php
composer install --no-dev
```

In that case, the package isn't installed during runtime, and the class reference `Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class` can't be resolved to a class, hence the error is thrown.  
If you would like to keep it this way, or can't influence it, you should follow the advice above and use the string variant of the class name (`'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider '`) instead, even if it feels dirty :)

**Comment by samhk222** [comment]
In my case was because the package was in *require-dev* and in my *AppServiceProvider* i had 

`if ($this->app->isLocal()) {
            $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
        }`

And in composer.json i had 

`"post-update-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postUpdate",
      "@php artisan ide-helper:generate",
      "@php artisan ide-helper:meta"
    ]`

So when i run any deploy, the post-update-cmd was triggering, and raising a error
