### ISSUE TITLE
Fails when using relation+where+Auth::user()->id

### ISSUE THREAD

**Issue by mushketer888** [barryvdh/laravel-ide-helper#551]
Fails to generate model helper when there is function with relation+where like:
```
class Record extends Model{...
    public function mystatus()
    {
        return $this->hasOne('App\Status')->where('user_id', '=', Auth::user()->id);
    }
```
Maybe it is bad practice to use Eloquent in such way. If so please say advice :)
Maybe just use return App\Status::where(...)->first()

But i wanted to use ::with('mystatus') eager loading

P.S. this model is not User. Status is like many to many through table\model Status
Status has record_id and user_id

**Comment by arisanguinetti** [comment]
Same here...

**Comment by mfn** [comment]
I fail to properly understand _where_ the problem is exactly?

Is this still relevant with latest version of Laravel/ide-helper/Your IDE?

**Comment by mfn** [comment]
Closing due to lack of feedback on years old issue
