### ISSUE TITLE
Field type mysql5.7 that does not seem to support JSON

### ISSUE THREAD

**Issue by zongmi** [barryvdh/laravel-ide-helper#552]
Field type mysql5.7 that does not seem to support JSON

Exception: Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

**Comment by zongmi** [comment]
Mongodb doesn't seem to support either
Exception: call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getDoctrineDriver'

**Comment by linxbin** [comment]
I also found this problem

**Comment by linxbin** [comment]
> I also found this problem

Add the following code in the `custom_db_types` field of the ide-helper.php file,

```
'custom_db_types' => array(
        'mysql' => [
            'json' => 'json_array',
        ]
    ),
```
JSON can be supported

**Comment by mfn** [comment]
@barryvdh the last comment is the correct solution, issue can be closed :}
