### ISSUE TITLE
Ignoring custom model properties (or database columns)

### ISSUE THREAD

**Issue by shaahin** [barryvdh/laravel-ide-helper#555]
I'm using a column for saving geo location as POINT SQL datatype and I understand that neither laravel nor ide_helper supports this data type but I don't want to miss the great model doc generation for this model.
It would be great if we could ignore some data types or column names in the process of creating doc for models.

**Comment by shaahin** [comment]
I have bypassed the issue by adding `'mysql' => [
            'point' => 'text'
        ]` into `custom_db_types` array in `ide-helper.php` config file. But it would be great if we can specify some properties/columns to ignore.

**Comment by mikerogne** [comment]
@shaahin Thanks! Helpful workout :)

**Comment by mfn** [comment]
@barryvdh the second to last comment is the correct solution, issue can be closed :}
