### ISSUE TITLE
Update the plugin will be something wrong

### ISSUE THREAD

**Issue by lxtac** [barryvdh/laravel-ide-helper#556]
When I update the Laravel-Plugins,if you use some static method exm "User::find($id)" will waring to " Non-static method User::find() should not be called statically",this very bad!

**Comment by Artistan** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/541#issuecomment-322265795

**Comment by mfn** [comment]
@barryvdh another issue fixed since `@mixin` support, can be closed :}
