### ISSUE TITLE
How to handle 'meta' generation on Service Provider that does not function without HTTP request

### ISSUE THREAD

**Issue by SirLamer** [barryvdh/laravel-ide-helper#557]
Referencing this issue report on another package here:
https://github.com/cloudcreativity/laravel-json-api/issues/88

...can anyone suggest a good way to prevent the meta generation from not failing when hitting this package?

The author suggests they will throw an exception from the service provider top-level to indicate that there is no inbound request. (https://github.com/cloudcreativity/laravel-json-api/issues/88#issuecomment-322101118)

**Comment by lindyhopchris** [comment]
Hi! I'm the author of the mentioned package.

This is more a question about a service binding that throws an Exception under some circumstances. It just happens to be that in this case, the service binding is throwing an Exception if it has not been invoked during an active HTTP request.

**Comment by SirLamer** [comment]
Note this was corrected by throwing a ```RuntimeExpception``` instead of allowing the fatal error.
