### ISSUE TITLE
Question: does this package get auto-discovered and registered in production?

### ISSUE THREAD

**Issue by erikbelusic** [barryvdh/laravel-ide-helper#558]

**Comment by Blizzke** [comment]
I depends on you. The auto discovery is there, but if you add the package as a dev package, the discovery only works when you install the dev-dependencies. If you don't do that on your production environment, it won't generate errors. 
If you do, it will be auto-discovered unless you add the `dont-discover` to your `composer.json`
(See [Taylors' article](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518) about it for the info)

**Comment by mfn** [comment]
See also https://github.com/barryvdh/laravel-ide-helper/issues/229#issuecomment-649582371

@barryvdh the last comment and my linked comment explain everything, issue can be closed :}
