### ISSUE TITLE
The "Route" methods coming from "RouteRegistrar" class not auto-completed

### ISSUE THREAD

**Issue by aik099** [barryvdh/laravel-ide-helper#559]
In the `routes/api.php` there is a code like this:

```php
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

On it the `middleware` method is indicated as non-existing. Debugging the stuff revealed that:

1. `Route` is an alias to the `\Illuminate\Support\Facades\Route` class
2. the `\Illuminate\Support\Facades\Route` class is a facade linked to `router` class in service container
3. the `router` alias in service container is mapped to the `\Illuminate\Routing\Router` class
4. the `\Illuminate\Routing\Router` class on the call to non-existing record is creating the `\Illuminate\Routing\RouteRegistrar` class and calling `attribute` method on it
5. the allowed attributes are located in `\Illuminate\Routing\RouteRegistrar::$allowedAttributes` property

Maybe they can be added to auto-complete as well the same way as was done with magic Eloquent query building methods?

**Comment by caiocutrim** [comment]
There is some glue of it? I am new on laravel and phpstorm. I really like this helper file

**Comment by mfn** [comment]
This works with latest Laravel/ide-helper, I just tested it:
![image](https://user-images.githubusercontent.com/87493/85899613-9b1a7500-b7fe-11ea-8840-c32ba53ab8de.png)

If it would not work, it would look like this:
![image](https://user-images.githubusercontent.com/87493/85899644-a79ecd80-b7fe-11ea-9d33-5a8ea0f48aa8.png)

@barryvdh works nowadays, issue can be closed :}
