### ISSUE TITLE
php version issue

### ISSUE THREAD

**Issue by moiz2050** [barryvdh/laravel-ide-helper#561]
Hi 

i am using php version 7.0.2 when i am installing it this is giving me this error

`doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.2) does not satisfy that requirement`

as i see on packagist requirement is 5.6+, why it is giving me this error of version 7.1 ??

**Comment by rap2hpoutre** [comment]
Doctrine now requires php >= `7.1` (since `2.6` which is accepted by `laravel-ide-helper` in its `composer.json`)

@barryvdh Do you think we should fix doctrine to a version < `2.6` OR set the PHP version of `laravel-ide-helper` to `7.1`?

**Comment by barryvdh** [comment]
It usually shouldn't install any packages that don't work for it. Not sure why it does in this case.

**Comment by moiz2050** [comment]
yes @barryvdh it acting weird because i have 2 projects in one it was already installed and i didnt get any error when i usually update it via composer, but recently in my new project when i am adding it , it is giving me this error on installation. so finally i have to update my php version for using this.. i cant ignore it anyways. 🥇

**Comment by mfn** [comment]
@barryvdh this is dealing with outdated versions, nowadays PHP 7.2 is the minimum required version; issue can be closed :}
