### ISSUE TITLE
Simplify full namespaces for already included resources

### ISSUE THREAD

**Issue by webmake** [barryvdh/laravel-ide-helper#565]
Hello,

by using phpstorm, there is an option `Simplify FQN`. Is it possible, that `ide-helper:models` command would do that?

I'm not talking about whole file modification, that automatically write `use Carbon\Carbon;` and then in php docblock would be only ` * @property Carbon|null $created_at`,
*but at least if class already has such includes.*

For example:
```
namespace Module\Sample;

/**
 * Class SampleClass
 *
 * @package Module\Sample
 * @property int $id
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\Module\Sample\SampleClass whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Module\Sample\SampleClass whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Module\Sample\SampleClass whereId($value)
 * @mixin \Eloquent
 */
class SampleClass extends Model
```
Should be (if Carbon included and SampleClass itself, but Builder not)

```
namespace Module\Sample;

/**
 * Class SampleClass
 *
 * @package Module\Sample
 * @property int $id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|SampleClass whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|SampleClass whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|SampleClass whereId($value)
 * @mixin \Eloquent
 */
class SampleClass extends Model
```

**Comment by nelson6e65** [comment]
I agree. Lines using FQN, when the class is already imported with `use`, becomes unnecessarily long.

**Comment by ad-mos** [comment]
Issue is popped up again on Laravel 8 with `\Database\Factories\` classes.

![image](https://user-images.githubusercontent.com/22893424/143765054-3324b404-904a-45b3-945f-172cbf22c349.png)
