### ISSUE TITLE
withTimestamps

### ISSUE THREAD

**Issue by pix2D** [barryvdh/laravel-ide-helper#569]
If a model has a relation like this:

    /**
     * Get all of the posts that are assigned this tag.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function posts()
    {
        return $this->morphedByMany('App\Post', 'taggable')->withTimestamps();
    }

PhpStorm complains with the following:

> Return value is expected to be '\Illuminate\Database\Eloquent\Relations\MorphToMany', '\Illuminate\Database\Eloquent\Relations\BelongsToMany' returned

Works fine without ```withTimestamps()```.

**Comment by mfn** [comment]
This works nowadays because the phpdoc for `withTimestamps` has `@return $this`:
```php
    /**
     * Specify that the pivot table has creation and update timestamps.
     *
     * @param  mixed  $createdAt
     * @param  mixed  $updatedAt
     * @return $this
     */
    public function withTimestamps($createdAt = null, $updatedAt = null)
    {
        $this->withTimestamps = true;

        $this->pivotCreatedAt = $createdAt;
        $this->pivotUpdatedAt = $updatedAt;

        return $this->withPivot($this->createdAt(), $this->updatedAt());
    }

```
This was fixed in Laravel with https://github.com/laravel/framework/pull/25314

@barryvdh it's working, issue can be closed :}
