### ISSUE TITLE
php artisan migrate error

### ISSUE THREAD

**Issue by diazardian** [barryvdh/laravel-ide-helper#575]
`Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Too few arguments to function Illuminate\Cache\Console\ClearCommand::__construct(), 1 passed in C:\xampp\htdocs\bukang\vendor\laravel\framework\src\Illuminate\Foundation\P
  roviders\ArtisanServiceProvider.php on line 217 and exactly 2 expected
`

i don't know what is wrong?

**Comment by mfn** [comment]
This… rather seems like a problem within the Laravel framework?

Also pretty sure, this dating back to 2017 that it was based on versions we're not supporting anymore

@barryvdh without more info I suggest to close this issue :}
