### ISSUE TITLE
Unexpected no document

### ISSUE THREAD

**Issue by wayne5w** [barryvdh/laravel-ide-helper#578]
This started happening a few weeks ago, can't figure out why or how to correct.

php artisan ide-helper:generate
Unexpected no document on Illuminate\Database\Eloquent\Model
Content did not change <?php

namespace Illuminate\Database\Eloquent;

use Exception;
use ArrayAccess;
use JsonSerializable;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Contracts\Support\Jsonable;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Contracts\Routing\UrlRoutable;
use Illuminate\Contracts\Queue\QueueableEntity;

**Comment by Kurre** [comment]
I debugged this issue a bit a while ago, and IIRC this happens because some command can't find class docblock in Model class.

Docblock was removed in this commit: https://github.com/laravel/framework/commit/6f518a8a534702da9166ef2fc5e297a06ed5cc18

**Comment by kmark** [comment]
I just reverted back to the latest stable release.

**Comment by wayne5w** [comment]
I migrated to Laravel 5.5 ad it’s fine now.

**Comment by szepeviktor** [comment]
Any news on this one or merging #584 (with modification)?

**Comment by lsfiege** [comment]
Still happening on Laravel 5.5.34

**Comment by spont4e** [comment]
I have the same problem
**NOW** with Laravel Framework **5.5.34**

**Comment by akalongman** [comment]
Same issue with Laravel 5.5.34

**Comment by LCD344** [comment]
Same issue laravel 5.6.0

**Comment by karlkras** [comment]
Hate to pile on... but yep, here too.

**Comment by irakliOrbis** [comment]
+1

**Comment by Yahav** [comment]
+1
Whats going on with this

**Comment by crabovwik** [comment]
+1

**Comment by tucq88** [comment]
+1 on 5.6

**Comment by tkrause** [comment]
Still an issue on Laravel 5.6

![image](https://user-images.githubusercontent.com/1427628/40439524-03f183b0-5e70-11e8-9077-ecb71268345a.png)

**Comment by yurik94** [comment]
+1 on 5.6.23

**Comment by augz** [comment]
+1 on 5.6.24

**Comment by eComEvo** [comment]
Rolling back to ide-helper 2.4.3 on Laravel 5.5.40, then running `ide-helper:models` then running `ide-helper:generate` fixed the issue for me.

**Comment by SDekkers** [comment]
+1 on 5.6.32

**Comment by HoseinGhanbari** [comment]
+1 on 5.7 dev-develop

**Comment by brentkozjak** [comment]
Just got this on 5.6.38

**Comment by amcsi** [comment]
I'm getting this on Laravel `5.7.13`. Fixed this by rolling back to ide-helper `~2.4` with thanks to @eComEvo.

**Comment by amcsi** [comment]
@barryvdh any plans on fixing this? Not to be demanding, but this package currently cannot be used with the latest Laravel out of the box without hacks.

**Comment by mfn** [comment]
IMHO this was fixed with https://github.com/barryvdh/laravel-ide-helper/pull/700

If there's anyone having troubles with _recent_ version I suggest to open a dedicated ticket with more details

@barryvdh IMHO original issue has been solved long time ago, vote for closing this issue :}

**Comment by amcsi** [comment]
I think it's fine by now. I don't remember this issue coming up for a while.
