### ISSUE TITLE
Methond 'on' not found

### ISSUE THREAD

**Issue by MartijnBastiaansen** [barryvdh/laravel-ide-helper#586]
Hello,

I'm using PhpStorm 2017.1 and Laravel framework 5.5. I ran the following already:

"php artisan ide-helper:generate",
"php artisan ide-helper:meta",
"php artisan ide-helper:models --write"

But still the $join->on is giving me the 'method not found' warning:

![methodonnotfound](https://user-images.githubusercontent.com/32897569/31713558-ea138630-b3fe-11e7-9e0e-48f9ad7abadd.png)

Can someone help me out?

Best Regards,

Martijn Bastiaansen

**Comment by mfn** [comment]
This is expected and unrelated to ide-helper => `function ($join)` => how could anyone know what `$join` is? You would need to add a typehint on your own, e.g. `\Illuminate\Database\Query\JoinClause` is probably appropriate. YMMV.

@barryvdh unrelated to ide-helper, issue can be closed :}
