### ISSUE TITLE
Package assumes relationship methods do not have parameters

### ISSUE THREAD

**Issue by ryantbrown** [barryvdh/laravel-ide-helper#587]
I have a method in my `User` model with the signature:

```php
/**
 * Return the related network by id or name
 *
 * @param  int|string $network
 * @return \Illuminate\Database\Eloquent\Relations\HasOne
 */
 public function network($network)
```

Depending on the network the method returns the related model:

```php
$this->hasOne('App\Models\Networks\\'.ucfirst(strtolower($network)), 'user_id')->first();
```

When I run `php artisan ide-helper:models` I get `Too few arguments to function App\Models\User::network()`

The `getPropertiesFromMethods` method in the `ModelCommand.php` class grabs the related class using `$relationObj = $model->$method();` without checking for parameters.

The only way to fix this is to add a default value to the method signature. This shows intent for default values when none exist.

**Comment by mfn** [comment]
@barryvdh this was fixed with https://github.com/barryvdh/laravel-ide-helper/pull/664 , issue can be closed :}
