### ISSUE TITLE
  [Symfony\Component\Debug\Exception\FatalThrowableError]

### ISSUE THREAD

**Issue by fawel11** [barryvdh/laravel-ide-helper#588]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Erp\Forms\AcademicQualificationFormTranslation' not found
when run: 

> `$ php artisan ide-helper:models
> 
>  Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead? (Yes/No):
>   (yes/no) [no]:
>  > yes

`

any suggestion? 

return back()->withSuccess('Successfully Deleted'),
withSuccess(), withErrors() not found error
why can't i get intelligence for thsoe?

**Comment by michaellatman** [comment]
+1

**Comment by mfn** [comment]
Is this sill an issue?
