### ISSUE TITLE
PhpStorm - Multiple definitions exist for class DB

### ISSUE THREAD

**Issue by sonnysavage** [barryvdh/laravel-ide-helper#592]
When using the DB facade, I get this warning in PhpStorm:

![image](https://user-images.githubusercontent.com/5487663/33077432-d33eb20e-ce9d-11e7-9277-6a933fddef68.png)

PhpStorm is finding both the facade in the Laravel's vendor path and the `_ide_helper.php` file:

![image](https://user-images.githubusercontent.com/5487663/33077553-1e3711de-ce9e-11e7-9805-6d5ab58a7736.png)

My Google searches haven't turned up a way to resolve this warning. Is this something that should be ignored, or is there a way to resolve it?

**Comment by roballport** [comment]
Same here, sure I never got this in the past. Guess it's something to do with me upgrading to Laravel 5.5.22 and PHP Storm 2017.3 :/ It used to be caused by definitions being fetched from the _ide_helper_models.php file, PHP Storm now reports the duplicated file is _ide_helper.php.

**Comment by math-designer** [comment]
Same here too, I resolved by follwing this: 

**Settings/Preferences | Editor | Inspections | Undefined | Undefined class | Don't report multiple class declaration potential problems**

It was taken from this link: 
https://stackoverflow.com/questions/23066665/multiple-definitions-exist-for-class

**Comment by bluec** [comment]
Would be good to see this re-opened and dealt with.

**Comment by dinoluck** [comment]
Years are passing by and this is still an issue. Will it ever be fixed by the author? It is real shame because the package really does great work until it doesn't.

**Comment by rpounder** [comment]
> Years are passing by and this is still an issue. Will it ever be fixed by the author? It is real shame because the package really does great work until it doesn't.

I don't think there is a solution, aside from JetBrains updating PHPStorm to facilitate Laravel, which personally I think it should.

**Comment by sonnysavage** [comment]
I have finally found a workaround. Instead of this:

```
use Illuminate\Support\Facades\DB;
```

...use this:

```
use DB;
```

The warnings go away.

**Comment by LauLogisch** [comment]
okay it took me some research time, but I found the solution:

Make sure your app name is App or change is it with `php artisan app:name App`. Then exclude the folder "storage": right click on the folder _storage_ then _Make Directory As_ > _Excluded_
Restart PhpStorm.

**Comment by rpounder** [comment]
> okay it took me some research time, but I found the solution:
> 
> Make sure your app name is App or change is it with `php artisan app:name App`. Then exclude the folder "storage": right click on the folder _storage_ then _Make Directory As_ > _Excluded_.
> Now restart PhpStorm.

this isn't a solution, it's a workaround...

**Comment by LauLogisch** [comment]
> > okay it took me some research time, but I found the solution:
> > Make sure your app name is App or change is it with `php artisan app:name App`. Then exclude the folder "storage": right click on the folder _storage_ then _Make Directory As_ > _Excluded_.
> > Now restart PhpStorm.
> 
> this isn't a solution, it's a workaround...

Yes it is. All the other workaround didn't work for me because I had an customized App name. So I thought it was worth mentioning.

**Comment by rpounder** [comment]
> > > okay it took me some research time, but I found the solution:
> > > Make sure your app name is App or change is it with `php artisan app:name App`. Then exclude the folder "storage": right click on the folder _storage_ then _Make Directory As_ > _Excluded_.
> > > Now restart PhpStorm.
> > 
> > 
> > this isn't a solution, it's a workaround...
> 
> Yes it is. All the other workaround didn't work for me because I had an customized App name. So I thought it was worth mentioning.

Changing the name of your app is a workaround by definition /facepalm

**Comment by trollfalgar** [comment]
> 
> 
> okay it took me some research time, but I found a workaround:
> 
> Make sure your app name is App or change is it with `php artisan app:name App`. Then exclude the folder "storage": right click on the folder _storage_ then _Make Directory As_ > _Excluded_.
> Now restart PhpStorm.

This doesn't work for me!

**Comment by mfn** [comment]
There is currently no known way to "fix" this for Facades because the "duplicate generation" is what enabled the _advanced_ autocomplete in the first place, because ide-helper pretends there's a second class by the same name and modern IDE just merge those.

Models, and people insisting writing to `_ide_helper_models.php`, have the same issue but it's different case because Models are in your "app" (and no in vendor) and there's a promising PR => https://github.com/barryvdh/laravel-ide-helper/pull/764

But as mentioned, that's a different scenario but maybe it spurs the creativity of someone to find a way for Facades et al too 🤷‍♀️

**Comment by CaliforniaMountainSnake** [comment]
> Same here too, I resolved by follwing this:
> 
> **Settings/Preferences | Editor | Inspections | Undefined | Undefined class | Don't report multiple class declaration potential problems**

If someone can't find this config: https://stackoverflow.com/a/64302768/10452175

![Screenshot_79](https://user-images.githubusercontent.com/44233829/95675760-3246e500-0bc2-11eb-8a1f-af9e23ea1ca7.png)

**Comment by jadamec** [comment]
I've the same issue...

**Comment by jdecode** [comment]
Issue still persists as of latest versions as writing this comment (April 9, 2021)
PhpStorm - 2021.1
Laravel IDE helper - ^2.9

**Comment by jdecode** [comment]
> > Same here too, I resolved by follwing this:
> > **Settings/Preferences | Editor | Inspections | Undefined | Undefined class | Don't report multiple class declaration potential problems**
> 
> If someone can't find this config: https://stackoverflow.com/a/64302768/10452175
> 
> ![Screenshot_79](https://user-images.githubusercontent.com/44233829/95675760-3246e500-0bc2-11eb-8a1f-af9e23ea1ca7.png)

There is a better setting now - keeping "undefined class" and "multiple declarations" separate from each other.

![Screenshot from 2021-04-09 09-44-23](https://user-images.githubusercontent.com/37613346/114127695-59376700-9918-11eb-9f4d-30de77e9b5fc.png)

**Comment by dyaskur** [comment]
If you don't want to  disable/ignore multiple declarations inspection to all file just add below line to the file:
```
/** @noinspection PhpMultipleClassDeclarationsInspection */
```
Or you can pres `option/alt+enter` then choose `suppress for file` like below screenshot:

<img width="855" alt="Screen Shot 2022-02-15 at 7 09 52 PANGERAN" src="https://user-images.githubusercontent.com/9539970/153968017-4797a0b1-cb31-4f91-88c0-1efdb4682340.png">

**Comment by trig79** [comment]
So I'm using Laravel and the warning clashes with my `_ide_helper_models.php`.

The problem with turning off the warning is that if you want to navigate to that file by holding down cmd and left-clicking, you will be presented with 2 file locations.

![image](https://github.com/barryvdh/laravel-ide-helper/assets/65402006/982c775f-d065-4c3b-91b9-e6c0d005dc2f)

Personally, I do not feel this is the best approach,  I prefer to exclude the file from IDE inspection. 
If you go to setting then directories, you can list single files in the input box:
![image](https://github.com/barryvdh/laravel-ide-helper/assets/65402006/06005ff7-fffa-4fbb-8d97-f998f6edfeec)

By doing this you aren't suppressing the warning for the whole project.

**Comment by Muetze42** [comment]
Strange problem. It was quiet the whole time. Today I updated PhpStorm and it occurs again

**Comment by BeingTomGreen** [comment]
So there's just no solution to this?

Somebody recently updated the [inertia-laravel package](https://github.com/inertiajs/inertia-laravel/pull/625) and added a duplicate Illuminate\Http\Request class, which causes issues in every IDE I have installed...

If I install this package, does it even resolve the issue?

**Comment by BeingTomGreen** [comment]
Installing `barryvdh/laravel-ide-helper` and then generating the various files does resolve the issue, although resolve is perhaps not the right word.

So I assume that makes `barryvdh/laravel-ide-helper` a requirement of any package using `_ide_helper*`?

**Comment by happyDemon** [comment]
For this fixed it in the latest version of PHPStorm:

Go to Settings > Editor > Inspections

then use the search bar to look for "Multiple class declarations" and disable the inspection.

**Comment by BeingTomGreen** [comment]
Disabling the inspector isn't a fix, obviously.

**Comment by lofye** [comment]
The point of using laravel-ide-helper is increased productivity. If we ignore the _ide_helper_models.php file, then we don't get the autocompletes from it, which makes us less productive. Same if we tell it to ignore undefined class, or multiple declarations, or multiple declarations in same file. That means we can't click on classes to go right to the class definition without choosing which class definition we're trying to go to. None of the things above are fixes, and all of them decrease our productivity. Not good.

**Comment by SocolaDaiCa** [comment]
we can use @see to extend autocomplete method like that https://github.com/laravel/framework/blob/d100d1cee3916c21cf341e11dbb2619b2940d454/src/Illuminate/Support/Facades/App.php#L146C3-L146C43

but we need add @see to all class need autocomplete method

**Comment by techieoriname** [comment]
read all the messages here hoping for the best 🥹
