### ISSUE TITLE
morphedByMany relations ignored by artisan ide-helper:models

### ISSUE THREAD

**Issue by IlCallo** [barryvdh/laravel-ide-helper#593]
As the title says, everything works fine, but all morphedByMany relations are ignored.
Any explanation for this behaviour? Is it a known problem? A quick search on issues did not provide any hint.

I'm using v2.4.1 with Laravel 5.4.

**Comment by mfn** [comment]
@barryvdh this was fixed by https://github.com/barryvdh/laravel-ide-helper/pull/632 , issue can be closed :}
