### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content.

### ISSUE THREAD

**Issue by LuChungHeng** [barryvdh/laravel-ide-helper#594]
i want  composer require tcg/voyager ,but.............................who can help me plz
 Problem 1
    - Conclusion: remove laravel/framework v5.3.31
    - Conclusion: don't install laravel/framework v5.3.31
    - tcg/voyager v1.0.0 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.1 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.2 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.3 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.4 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.5 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.6 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - tcg/voyager v1.0.7 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.3.31
    - Installation request for laravel/framework (locked at v5.3.31, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.31].
    - Installation request for tcg/voyager ^1.0 -> satisfiable by tcg/voyager[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7].

**Comment by fyhring** [comment]
I get the somewhat the same result when installing on a clean laravel 5.5 installation.
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/laravel[dev-master, v5.5.22].
    - Can only install one of: laravel/laravel[v5.5.22, dev-master].
    - Can only install one of: laravel/laravel[v5.5.22, dev-master].
    - Installation request for laravel/laravel dev-master -> satisfiable by laravel/laravel[dev-master].
    - Installation request for laravel/laravel == 5.5.22.0 -> satisfiable by laravel/laravel[v5.5.22].
```

**Comment by chandnitin** [comment]
please solve this problem

**Comment by irfan-mirza686** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gloudemans/shoppingcart ^2.5 -> satisfiable by gloudemans/shoppingcart[2.5.0].
    - Conclusion: remove laravel/framework v5.7.16
    - Conclusion: don't install laravel/framework v5.7.16
    - gloudemans/shoppingcart 2.5.0 requires illuminate/events 5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/events[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/events 5.1.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/events 5.2.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/events 5.3.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/events 5.4.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/events 5.5.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/events 5.6.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.1|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.13|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.16|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.2|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.20|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.22|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.25|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.28|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.30|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.31|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.41|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.6|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.1.8|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.0|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.19|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.21|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.24|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.25|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.26|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.27|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.28|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.31|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.32|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.37|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.43|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.45|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.6|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.2.7|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.3.0|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.3.16|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.3.23|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.3.4|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.0|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.13|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.17|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.19|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.27|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.36|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.4.9|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.0|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.16|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.17|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.2|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.28|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.33|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.34|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.35|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.36|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.37|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.39|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.40|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.41|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.43|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.5.44|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.0|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.1|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.10|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.11|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.12|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.13|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.14|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.15|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.16|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.17|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.19|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.2|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.20|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.21|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.22|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.23|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.24|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.25|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.26|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.27|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.28|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.29|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.3|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.30|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.31|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.32|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.33|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.34|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.35|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.36|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.37|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.38|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.39|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.4|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.5|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.6|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.7|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.8|don't install laravel/framework v5.7.16
    - don't install illuminate/events v5.6.9|don't install laravel/framework v5.7.16
    - Installation request for laravel/framework (locked at v5.7.16, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.16].


Installation failed, reverting ./composer.json to its original content.

**Comment by irfan-mirza686** [comment]
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for gloudemans/shoppingcart ^2.5 -> satisfiable by gloudemans/shoppingcart[2.5.0].
> - Conclusion: remove laravel/framework v5.7.16
> - Conclusion: don't install laravel/framework v5.7.16
> - gloudemans/shoppingcart 2.5.0 requires illuminate/events 5.1._|5.2._|5.3._|5.4._|5.5._|5.6._ -> satisfiable by illuminate/events[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
> - don't install illuminate/events 5.1.x-dev|don't install laravel/framework v5.7.16
> - don't install illuminate/events 5.2.x-dev|don't install laravel/framework v5.7.16
> - don't install illuminate/events 5.3.x-dev|don't install laravel/framework v5.7.16
> - don't install illuminate/events 5.4.x-dev|don't install laravel/framework v5.7.16
> - don't install illuminate/events 5.5.x-dev|don't install laravel/framework v5.7.16
> - don't install illuminate/events 5.6.x-dev|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.1|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.13|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.16|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.2|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.20|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.22|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.25|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.28|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.30|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.31|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.41|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.6|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.1.8|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.0|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.19|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.21|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.24|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.25|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.26|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.27|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.28|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.31|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.32|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.37|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.43|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.45|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.6|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.2.7|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.3.0|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.3.16|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.3.23|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.3.4|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.0|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.13|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.17|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.19|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.27|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.36|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.4.9|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.0|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.16|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.17|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.2|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.28|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.33|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.34|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.35|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.36|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.37|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.39|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.40|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.41|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.43|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.5.44|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.0|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.1|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.10|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.11|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.12|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.13|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.14|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.15|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.16|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.17|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.19|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.2|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.20|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.21|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.22|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.23|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.24|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.25|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.26|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.27|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.28|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.29|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.3|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.30|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.31|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.32|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.33|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.34|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.35|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.36|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.37|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.38|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.39|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.4|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.5|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.6|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.7|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.8|don't install laravel/framework v5.7.16
> - don't install illuminate/events v5.6.9|don't install laravel/framework v5.7.16
> - Installation request for laravel/framework (locked at v5.7.16, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.16].
> 
> Installation failed, reverting ./composer.json to its original content.

how can I resolve this issue .. anyone please tell me

**Comment by mfn** [comment]
@barryvdh installation on 5.5 works ( https://github.com/barryvdh/laravel-ide-helper/issues/539#issuecomment-649519846 ), all other versions mentioned here are not supported anymore => issue can be closed :}
