### ISSUE TITLE
can not create helper define when there is a custom get mutator to id

### ISSUE THREAD

**Issue by steve3d** [barryvdh/laravel-ide-helper#595]
I'm using the optimized uuid as primary key, which need to convert from text to binary and vice versa, so I created a trait including the `setIdAttribute` and  `getIdAttribute`, when the `getIdAttribute` function exists, this package tell me this:

```
Exception: Undefined index: id
Could not analyze class App\ClassXXX.
```
but if i remove the `getIdAttribute`, it works fine.

**Comment by jblotus** [comment]
same issue here

**Comment by sirikkoster** [comment]
Same here

**Comment by mfn** [comment]
Is this still an issue?

**Comment by steve3d** [comment]
I think you can close this now, because use uuid as primary key with mysql always a huge pain.

I've already abandoned this idea.
