### ISSUE TITLE
Custom Models: Multiple Implemenations

### ISSUE THREAD

**Issue by floflock** [barryvdh/laravel-ide-helper#597]
Hello!

I have a namespace  ```App\Models``` and phpStorm shows Multiple implementations on that custom models in that namespace.

Is there a solution? :)

![image](https://user-images.githubusercontent.com/3831745/33809180-1a4bc222-ddf3-11e7-9549-1e5498cfeb29.png)

**Comment by alexkearns** [comment]
This is an issue that has been seen before (#430), afaik there's no current workaround (short of disabling the warning in PhpStorm) if you want to keep writing the meta to a separate file. If you write the meta to the model file itself - use the `-W` option when generating meta like `php artisan ide-helper:models -W` the error gets resolved.

**Comment by mfn** [comment]
@barryvdh last comment is the solution (either live with it or write it to the models), issue can be closed :}
