### ISSUE TITLE
Generating models with artisan ide-helper:models fails

### ISSUE THREAD

**Issue by Alexander--** [barryvdh/laravel-ide-helper#598]
I am trying to get the IDE helper to work on new machine. It used to work on a different machine, but when I run it here, it emits errors like this (with `-vvv` option):

````
Loading model 'App\User'
Exception: SQLSTATE[HY000] [2002] No such file or directory
Could not analyze class App\User.
Loading model 'App\Models\Pages'
Exception: SQLSTATE[HY000] [2002] No such file or directory
Could not analyze class App\Models\Pages.
````

The same error is printed for every other model class, resulting in empty `_ide_helper_models.php`.
I have a working database connection configured in Laravel config, as well as in MySQL's `my.cnf`. The Laravel app can use database successfully.

In case that matters, I am using Laravel 5.5 (but when the project was using a previous version, the issue also occured).

**Comment by benyaminl** [comment]
> I am trying to get the IDE helper to work on new machine. It used to work on a different machine, but when I run it here, it emits errors like this (with `-vvv` option):
> 
> ```
> Loading model 'App\User'
> Exception: SQLSTATE[HY000] [2002] No such file or directory
> Could not analyze class App\User.
> Loading model 'App\Models\Pages'
> Exception: SQLSTATE[HY000] [2002] No such file or directory
> Could not analyze class App\Models\Pages.
> ```
> 
> The same error is printed for every other model class, resulting in empty `_ide_helper_models.php`.
> I have a working database connection configured in Laravel config, as well as in MySQL's `my.cnf`. The Laravel app can use database successfully.
> 
> In case that matters, I am using Laravel 5.5 (but when the project was using a previous version, the issue also occured).

This mean your connection is broken. It's PDO error

**Comment by mfn** [comment]
@barryvdh old support issue with a db connection problem, issue can be closed :}
