### ISSUE TITLE
Using with VIM

### ISSUE THREAD

**Issue by Anan5a** [barryvdh/laravel-ide-helper#601]
How to configure it for using with VIM & spf13-vim ?

**Comment by FatBoyXPC** [comment]
Found this issue in a google search, providing a friendly bump :smile:

**Comment by yaegassy** [comment]
Using phpcd.vim.

Only Facade is usable.

The feature of phpDocs for models is a command so you can use it.

Unfortunately PhpStorm Meta file can not be used.

### plugin

https://github.com/lvht/phpcd.vim

### Usage setting (Facade)

https://github.com/lvht/phpcd.vim/wiki/Laravel-Facade-Support

**Comment by FatBoyXPC** [comment]
PHPCD is great!
How does PHPCD get the info for Facades if the meta file cannot be usd?

**Comment by yaegassy** [comment]
The feature using `.phpstorm.meta.php` can not be used.

**Comment by FatBoyXPC** [comment]
I'm asking - how do we get the Facade info to show up in VIM?

**Comment by mfn** [comment]
The comment in https://github.com/barryvdh/laravel-ide-helper/issues/601#issuecomment-370948147 already sums it up

@barryvdh there's not else to do, IDE agnostic files are generated where applicable, IMHO this issue can be closed :}

**Comment by FatBoyXPC** [comment]
I agree, this can be closed. My bump on this was before I understood how vim's autocomplete worked :)
