### ISSUE TITLE
Cannot declare class Redis

### ISSUE THREAD

**Issue by szepeviktor** [barryvdh/laravel-ide-helper#603]
Untouched Laravel 5.5.12 + predis:

> PHP Fatal error:  Cannot declare class Redis, because the name is already in use in _ide_helper.php on line 14394

I think the Redis class is already declared in Illuminate/Support/Facades/Redis.php

**Comment by barryvdh** [comment]
Are you including the file in your code?

**Comment by szepeviktor** [comment]
This is a theoretical research with phpstan without any custom code.

I've installed laravel/laravel and added

```json
"predis/predis": "~1.0",
"barryvdh/laravel-ide-helper": "dev-master"
```

After running `artisan ide-helper:generate` `_ide_helper.php` is created, then I've ran phpstan.

**Comment by szepeviktor** [comment]
Then phpstan reported the duplicated class declaration.

**Comment by barryvdh** [comment]
Yeah it's not actually used code, so nothing to worry about.
