### ISSUE TITLE
Issue with generating ide helper after Laravel Plugin update

### ISSUE THREAD

**Issue by dcaldessa** [barryvdh/laravel-ide-helper#605]
Laravel Plugin was just updated I installed the update and ran 

php artisan ide-helper:generate as per the update and getting this result . 

artisan ide-helper:generate

In ControllerActionNameComposer.php line 15:
                                                 
  Call to a member function getAction() on null  
                                                 

Process finished with exit code 1 at 21:32:36.
Execution time: 264 ms

I tracked the name to AuthServiceProvider.php 

this is what the file has 
 /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        view()->composer('*', 'dracanon\Http\Composers\ControllerActionNameComposer');
        //
    }

not sure what to do at this point , as I am still new to laravel , have not had any issues until this point.
any help would be appreciated . 

Thanks 
D

**Comment by mfn** [comment]
> I tracked the name to AuthServiceProvider.php

Maybe related to introspection for the Auth Facade, but that's just a guess.

Is this still an issue?

**Comment by mfn** [comment]
> I tracked the name to AuthServiceProvider.php

Maybe related to introspection for the Auth Facade, but that's just a guess.

Is this still an issue?
