### ISSUE TITLE
Schema::connection should be mapped to DatabaseManager::connection

### ISSUE THREAD

**Issue by simonschaufi** [barryvdh/laravel-ide-helper#607]
This piece of code is currently not analyzed correctly.
```php
/* @var Illuminate\Database\Schema\MySqlBuilder $builder */
$builder = Schema::connection('myconnectionstring');
```
when I debug it, I end up in `\Illuminate\Database\DatabaseManager->connection`

**Comment by mfn** [comment]
Note to myself: this doesn't work because static methods directly on the Facade are not considered.

It "works" if you use the Facade directly: `\Illuminate\Support\Facades\Schema`; since quite some phpdocs have been added to many Laravel Facades, this mostly works well too.

**Comment by simonschaufi** [comment]
ping

**Comment by mfn** [comment]
🏓
