### ISSUE TITLE
Validate method not found in Illuminate\Http\Request

### ISSUE THREAD

**Issue by golubkovden** [barryvdh/laravel-ide-helper#608]
laravel 5.5.28
ide-helper 2.4.1

Will ide-helper support this validate method in [request](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php#L38)?

**Comment by jonnywilliamson** [comment]
A hack to make this work:

Create a file somewhere in your project and add this to it:

//IDEAutoCompleteHelp.php
```php
<?php
namespace Illuminate\Http;

/**
 * @method bool validate(array $rules, ...$params) Validate the given request with the given rules.
 */
class Request
{
}
```

**Comment by andreich1980** [comment]
I'd add one more line here
```
/**
 * @method bool validate(array $rules, ...$params) Validate the given request with the given rules.
 * @method array validated() Get the validated data from the request.
 */
```

**Comment by Mapteg34** [comment]
+1

**Comment by Nothing-Works** [comment]
This is what I do create `IDEAutoCompleteHelp.php` at root folder.
```sh
<?php

namespace Illuminate\Http;

/**
 * @method bool|array|null validate(array $rules, ...$params) Validate the given request with the given rules.
 * @method array           validated()                        Get the validated data from the request.
 */
class Request
{
}

```

**Comment by Nothing-Works** [comment]
also set `'write_eloquent_model_mixins'` option to `true`

**Comment by HenkPoley** [comment]
At least with Laravel 6.4.0 and laravel-ide-helper 2.6.5, setting `'write_eloquent_model_mixins' => true,` doesn't write the `@method .. validate(..)` annotation to the appropriate place(s) by itself.

The mentioned `IDEAutoCompleteHelp.php` file with contents is still required.

**Comment by ultrono** [comment]
For anyone interested, the mentioned `IDEAutoCompleteHelp.php` method works for macros too. Here's a small example for a few basic macros I created on Laravel's `RedirectResponse` class:

`
namespace Illuminate\Http;

/**
 * @method \Illuminate\Http\RedirectResponse created($message = null)
 * @method \Illuminate\Http\RedirectResponse deleted($message = null)
 * @method \Illuminate\Http\RedirectResponse updated($message = null)
 * @method \Illuminate\Http\RedirectResponse error($message = null)
 * @method \Illuminate\Http\RedirectResponse unAuthorized($message = null)
*/
class RedirectResponse {}
`

**Comment by mfn** [comment]
I believe this fixed with the latest release https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.8.1
> Add support for macros of all macroable classes #1006 

If I'm mistaken, please add a comment or preferable open a new issue with details, thank you!
