### ISSUE TITLE
$query->where() - Method not found for query local scopes

### ISSUE THREAD

**Issue by StatiS** [barryvdh/laravel-ide-helper#610]
When trying to define a new query local scope method in a model, like so:
`public function scopeTest($query)
    {
        return $query->where('test', 0);
    }`
phpstorm gives the following error 

> Method 'where' not found in 
Referenced method is not found in subject 

Of course, not limited to the where() method, autoRecommend doesn't know what to treat the $query as.

Using the latest release of the laravel-ide-helper, and have the \Eloquent mix in.

**Comment by zzpwestlife** [comment]
Any solutions?

**Comment by Ferhnir** [comment]
...
use Illuminate\Database\Eloquent\Builder;
...

 /**
 * @param $query
 *
 * @return Builder
 */
public function scopeTest(Builder $query): Builder
{
     return $query->where('test', 0);
}
