### ISSUE TITLE
@mixin \Eloquent not working on Lumen

### ISSUE THREAD

**Issue by westphalen** [barryvdh/laravel-ide-helper#611]
I have followed every trick and suggestion out there, but PhpStorm still doesn't properly recognize the static methods (`create`, `findOrfail`, etc.) on models in Lumen 5.5.

I have added `@mixin \Eloquent` and `@mixin \Illuminate\Database\Eloquent\Builder` to my model.

But since \Eloquent doesn't actually exist, I also tried setting `config/app.php`:

```php
return [
    'aliases' => [
        'Eloquent' => \App\Models\Model::class,
    ],
];
```

and enabling `$app->withFacades();` and `$app->configure('app');`.

This looks like a hole in Lumen support, or did I miss a step somewhere?

**Comment by ihipop** [comment]
`app/Providers/AppServiceProvider.php:boot()`

```php
if ($app->environment() !== 'production') {
            app('config')->set('app.aliases', [
                'Validator' => 'Illuminate\Support\Facades\Validator',
                'Eloquent'=>'\Illuminate\Database\Eloquent\Model'
            ]);
            $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
}
```

this is just enough

**Comment by SolveSoul** [comment]
@ihipop can you elaborate a bit? In the `boot` function of `AppServiceProvider` I have no variable known as `$app`. I do have this variable in `app.php`. I tried putting the code in the `app.php` file but and regenerating the ide-helper file but I still have the same issue.

**Comment by ihipop** [comment]
@SolveSoul Edited.
Change `$app` -> `$this->app`
