### ISSUE TITLE
Using a lot of memory and not doing anything 

### ISSUE THREAD

**Issue by DrowningElysium** [barryvdh/laravel-ide-helper#613]
I am getting the next issue when doing the command `php artisan ide-helper:models`

```
$ php artisan ide-helper:models

 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead? (Yes/No):  (yes/no) [no]:
 > no

PHP Fatal error:  Allowed memory size of 4026531840 bytes exhausted (tried to allocate 20480 bytes) in C:\Code\reaweb\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 904
PHP Fatal error:  Allowed memory size of 4026531840 bytes exhausted (tried to allocate 32768 bytes) in C:\Code\reaweb\vendor\symfony\debug\Exception\FatalErrorException.php on line 1
```

So my guess is that it has a loop that keeps repeating. I just don't know how to debug this.

**Comment by andrii-trush** [comment]
Are there any progress?

**Comment by DrowningElysium** [comment]
Nop, the issue is still there and haven't found what causes it

**Comment by andrii-trush** [comment]
@DrowningElysium I found. One of the my model crashed, but I don't know why ) I add it to ignore and all works fine

**Comment by andrii-trush** [comment]
I found a reason of crash. I have created a relation with the same name as teble column and it crashed at 468 (`$relationObj = $model->$method();`) in ModelsCommand.php

**Comment by DrowningElysium** [comment]
I have checked all my. Models. I don't have a u relations with the same name as the model they are in

**Comment by andrii-trush** [comment]
Try debug step by step generator )))
It helps me

**Comment by Soulriser** [comment]
I was having the same problem as well. xDebug was my savior, since it stops execution after a certain level of recursion is reached and outputs a trace log. The issue for me was that I had overridden `Model::getAttribute()` in such a way that caused an infinite recursive loop. I was able to fix it with the info I gleaned from xdebug.

**Comment by mfn** [comment]
@DrowningElysium is this still an issue?

**Comment by DrowningElysium** [comment]
Haven't tried this since anymore. Currently not working on any projects or having access to.

**Comment by adibemohamed** [comment]
> I was having the same problem as well. xDebug was my savior, since it stops execution after a certain level of recursion is reached and outputs a trace log. The issue for me was that I had overridden `Model::getAttribute()` in such a way that caused an infinite recursive loop. I was able to fix it with the info I gleaned from xdebug.

 infinite recursive loop 🔥
