### ISSUE TITLE
Phpstorm show the message，how to fix it ？

### ISSUE THREAD

**Issue by pndx** [barryvdh/laravel-ide-helper#620]
EV: phpstorm2017.3.4, laravel5.6
```
        Schema::create(/**
         * @param Blueprint $table
         */
            'users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
```

> Method 'unique' not found in Illuminate\Support\Fluent less... (Ctrl+F1) 
> Referenced method is not found in subject class.

**Comment by pndx** [comment]
solve from the document.

### Automatic phpDocs generation for Laravel Fluent methods
If you need phpDocs support for Fluent methods in migration, for example
`$table->string("somestring")->nullable()->index();`
After publishing vendor, simply change the include_fluent line your config/ide-helper.php file into:
`'include_fluent' => true,`
And then run php artisan ide-helper:generate , you will now see all of the Fluent methods are recognized by your IDE.

**Comment by mfn** [comment]
@barryvdh OP solved it, issue can be closed :}
