### ISSUE TITLE
Option to disable ide-helper:eloquent when doing ide-helper:generate

### ISSUE THREAD

**Issue by ionesculiviucristian** [barryvdh/laravel-ide-helper#628]
The command is confusing the IDE with "non-static methods being called statically" warnings. I had no problems just adding the mixin of Eloquent on my Models. Adding extra mixins seems to be causing the problem. It will be nice to have an option to turn that off.

**Comment by mfn** [comment]
@barryvdh nowadays this works as expected, issue can be closed :}
