### ISSUE TITLE
VS Code support

### ISSUE THREAD

**Issue by delta1186** [barryvdh/laravel-ide-helper#631]
It would be awesomely to see this supported for Visual Studio Code too.

**Comment by mludi** [comment]
I use it with VS Code, what's not working for you?

Currently I use the `_ide_helper.php`.
Only I had to change was my models from

`class Invite extends Model` to `class Invite extends \Eloquent`

**Comment by 3Descape** [comment]
@mludi what package did you use? do I need to configure anything?

**Comment by mludi** [comment]
I use this package https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client That works out of the box.

**Comment by 3Descape** [comment]
@mludi thx.. Will check it out!

**Comment by andreshg112** [comment]
For me, it works without extending `\Eloquent`. However, `@mixin` doesn't work. It doesn't autocomplete functions like find, findOrFail, updateOrCreate, firstOrCreate.

**Comment by diazgilberto** [comment]
Just `wget _ide_helper.php` in the root of the project?

**Comment by andreshg112** [comment]
@diazgilberto , yeah! It doesn't autocomplete request()->validate(). I don't know why.

**Comment by skyrpex** [comment]
AFAIK, the `validate` method is added as a macro (magic methods). I'm not sure if those magic methods can be autocompleted. I'd love Laravel to get rid of those, to be honest.

**Comment by zaczy** [comment]
And what about blade templates autocompletion?

I use enums module, in Controller when I type MyEnumType:: it proposes constants used in enum class, in blade templates \App\Enums\MyEnumType:: autocompletions proposals seems to be "global" - not related to specific class

**Comment by sohel1999** [comment]
> I use it with VS Code, what's not working for you?
> 
> Currently I use the `_ide_helper.php`.
> The only change I've done was my models extending from
> 
> `class Invite extends Model` to `class Invite extends \Eloquent`
how?

**Comment by mludi** [comment]
> I use it with VS Code, what's not working for you?
> 
> Currently I use the `_ide_helper.php`.
> The only change I've done was my models extending from
> 
> `class Invite extends Model` to `class Invite extends \Eloquent`
> how?

How what @sohel1999 ?

**Comment by mfn** [comment]
See https://github.com/barryvdh/laravel-ide-helper/issues/457#issuecomment-649807945

@barryvdh as was established elsewhere, the generated files are mostly IDE agnostic. As there's nothing specific here for improvement, I vote for closing this issue :}

**Comment by josegus** [comment]
Doesn't work with VS code

**Comment by JMitnik** [comment]
+1
