### ISSUE TITLE
Factory methods for Models

### ISSUE THREAD

**Issue by catalinux** [barryvdh/laravel-ide-helper#634]
Is there a way of adding auto complete for model objects created with factory helper method?

For example:

`factory(Model::class)->create()` whould have `Model` type and

`factory(Offer::class,3)->create()` should have `Collection` type

**Comment by mikerogne** [comment]
Any related issues I'm not seeing? Or any plans for this? :)

**Comment by jblotus** [comment]
https://github.com/barryvdh/laravel-ide-helper/pull/758

**Comment by mfn** [comment]
@barryvdh last comment referenced the PR which fixed this, issue can be closed :}
