### ISSUE TITLE
Laravel 5.6 error (and a small documentation fix)

### ISSUE THREAD

**Issue by SturmB** [barryvdh/laravel-ide-helper#637]
First, references to the `php artisan optimize` command should be removed from documentation since it was deprecated in Laravel 5.5 (and did nothing in that version) and finally removed in Laravel 5.6. Any attempt to run this command generates an error now.

Second, it might be a good idea to mention in the `README` that adding the Service Provider is only required on Laravel 5.4 and below. Laravel 5.5 and up have Package Auto-Discovery and, thus, don't require the user edit `config/app.php` to add the Service Provider to it anymore.

Lastly, according to the docs, I added:
```
    "post-update-cmd": [
      "Illuminate\\Foundation\\ComposerScripts::postUpdate",
      "php artisan ide-helper:generate",
      "php artisan ide-helper:meta"
    ]
```
to the `"scripts"` section of the `composer.json` file, but when that runs, I am given an error:
```
[...]
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate

Parse error: parse error in /Users/username/Sites/acs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233
Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 255

Process finished with exit code 255 at 10:25:48.
Execution time: 24,372 ms.
```
I find this odd because I can run `php artisan ide-helper:generate` by itself without any issues.

**Comment by tomzx** [comment]
Do you happen to have multiple versions of php installed on your computer? Sometimes due to how your PATH is configured, you might have a PHP version in your shell, but a different one used when running from within the script.

I suggest that because line 233 on branch 5.6 is ` return app('cache')->get($arguments[0], $arguments[1] ?? null);`, where the null coalescing operator is used, which means the executed php is pre-7.0.

**Comment by SturmB** [comment]
That sounds very likely, @tomzx. I recently installed PHP 7.2.2 for working with Laravel 5.6.5, but I am certain I have 7.1.x installed somewhere. I wouldn't be surprised if there was a pre-7.0 version also installed somewhere. The only thing is that I don't know how to uninstall them _cleanly_ without disturbing my 7.2.2 installation, which was done with Homebrew. Do you happen to have a link or two to some instructions on that?

**Comment by tomzx** [comment]
I think you could maybe diagnose that by adding a line in your scripts section of your `composer.json`, something like `which php`, which should tell you which php is being executed. I don't know how your php is currently installed, and I don't believe there's any guide on how to cleanly uninstall php. Normally it should be as simply as deleting the whole directory (php is self-contained).

**Comment by SturmB** [comment]
Sounds good. I'll give that a try; thanks!

**Comment by mfn** [comment]
@barryvdh all issues are solved (readme was updated in the meantime) and technical problem was likely an older PHP version shaking things up, I vote for closing this issue :}
