### ISSUE TITLE
[Request] Auth::user() use model from auth config as return type

### ISSUE THREAD

**Issue by zhuston** [barryvdh/laravel-ide-helper#64]
I am not sure if other setups exist but it seems Auth::user() always returns null or an instance of the model defined in the auth config. It would be nice if ide_helper included that model class in the return type, so autocomplete on Auth::user() would include methods from the user class.

I looked through the code a little but it wasn't clear to me if there was an easy way to make this happen.

**Comment by matiaslauriti** [comment]
@barryvdh Hi ! Sorry for opening a really old but related feature.

I was trying to use `$request->user()` when using the injected `\Illuminate\Http\Request` but I can't understand how this works. It should return `\App\User` as `Auth::user()` is doing, but it is returning `mixed`, so I have to PHPDoc type hint it... can I configure something on the `ide-helper`'s config or is this a `Laravel` problem or this package ?

Thanks !

**Comment by gigabites19** [comment]
> @barryvdh Hi ! Sorry for opening a really old but related feature.
> 
> I was trying to use `$request->user()` when using the injected `\Illuminate\Http\Request` but I can't understand how this works. It should return `\App\User` as `Auth::user()` is doing, but it is returning `mixed`, so I have to PHPDoc type hint it... can I configure something on the `ide-helper`'s config or is this a `Laravel` problem or this package ?
> 
> Should I request `Laravel` repo to change PHPDoc `@return` for `Request->user()` from `mixed` to same as `Auth::user()` and that should fix it when running `ide:gen` or `ide:meta` ?
> 
> Thanks !

Facing same issue
