### ISSUE TITLE
ide-helper:generate does not respect merged app.alias defined in ServiceProviders using mergeConfigFrom (L5.5)

### ISSUE THREAD

**Issue by nonsapiens** [barryvdh/laravel-ide-helper#646]
So, ide-helper works wonderfully in allowing my Facades to be IDE accessible, so long as they're defined in app.php's alias array.  I'd like to say thanks for such a wonderful tool!

But I do seem to be running into a problem.
Specifically, if you have aliases defined elsewhere, such as in ServiceProviders, using mergeConfigFrom, then these aren't picked up.

For example, in my one registered service provider, I have this:

`$this->mergeConfigFrom( realpath( dirname( __FILE__ ) . '/../../config/aliases.php' ), 'app.aliases' );`

Running like this, the aliases defined in my config/aliases.php don't get picked up by your Generator.  And I think I know why.

In your **Generator.php**, line 244, you have this:

```
 protected function getAliases()
    {

        // For Laravel, use the AliasLoader
        if (class_exists('Illuminate\Foundation\AliasLoader')) {
            return AliasLoader::getInstance()->getAliases();
        }
``` 

That `AliasLoader` simply does not acknowledge the merged config `app.php`.  If I were to replace this simply with (as you have lower down), `config('app.aliases')`, then all works.

Is there either something I'm doing wrong for `AliasLoader` not to see my merged app.php, or is this perhaps a bug?

**Comment by mfn** [comment]
Seems similar to https://github.com/barryvdh/laravel-ide-helper/issues/208

Can you check https://github.com/barryvdh/laravel-ide-helper/issues/208#issuecomment-649570555 ?

Do you still have to issue or where you able to fix/overcome it?
