### ISSUE TITLE
Why do you prefer slug case for naming _ide_helper.php?

### ISSUE THREAD

**Issue by neyaoz** [barryvdh/laravel-ide-helper#648]
Hi, I am really wondering about it, as a person who has Obsessive-Compulsive Disorder (OCD). Why do you prefer slug case for naming `_ide_helper.php`? `.phpstorm.meta.php` seems pretty good, just like all other dot prefixed files. What I expect is `.idehelper.php`.

Thanks for understanding.

**Comment by barryvdh** [comment]
Meh I don't really care. It was based on how existing solutions did it. Phpstorm is based on their docs as suggested name.
