### ISSUE TITLE
Handle PHP7 fatal errors over \Exception

### ISSUE THREAD

**Issue by afk11** [barryvdh/laravel-ide-helper#649]
Hi Barry!

I'm trying to generate stubs for a project where we are not using the laravel Auth service provider. It looks like this line leads to a fatal error on PHP7, https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Generator.php#L135

Wanted to quickly open an issue and as if you'd accept a PR catching \Error instead of \Exception? Looks like in this case, replacing the one instance is enough for me, but I can target the rest too if you think it's helpful.

**Comment by mfn** [comment]
@barryvdh this was fixed recently with https://github.com/barryvdh/laravel-ide-helper/pull/946 , issue can be closed :}
