### ISSUE TITLE
Please add custom config for filename of ide_helper_models.php.

### ISSUE THREAD

**Issue by DesmondPang** [barryvdh/laravel-ide-helper#650]
There are only filename configs for _ide_helper.php and .phpstorm.meta.php but not _ide_helper_models.php. I know it can do that by adding `-F path/filename_models.php` to the end of command  to generate a separate model helper file. Would you mind to add the custom config option in config files?

**Comment by mfn** [comment]
I'd say PRs are welcome 🤷‍♀️

**Comment by barryvdh** [comment]
Yes

**Comment by mfn** [comment]
🤦‍♂️ <- me after already starting a PR

This is already possible with the `--filename` option 😄:
```
$ ./artisan ide-helper:models --filename yolo.php
Model information was written to yolo.php
$ wc -l yolo.php
3180 yolo.php
```

@barryvdh nothing to be done 💪 , issue can be closed
