### ISSUE TITLE
MsSql issue

### ISSUE THREAD

**Issue by BenaddiRar** [barryvdh/laravel-ide-helper#652]
Hello,

I have Mssql installed with docker, and i have two Laravel project.

The first project with L5.1  and the " php artisan ide-helper:models " work fine 

but the new one with L5.4 i have an Exception: 
## SQLSTATE[IM001]: Driver does not support this function: driver does not support getting attributes ##

**Comment by mfn** [comment]
Duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/435

@barryvdh this issue doesn't bring more information to the table, I vote for closing (in favour of the other) :}
