### ISSUE TITLE
Switch return type of Eloquent's firstOr methods to static?

### ISSUE THREAD

**Issue by mortenscheel** [barryvdh/laravel-ide-helper#653]
PhpStorm doesn't pick up the return type of methods like `MyModel::firstOrCreate()`.

My _ide_helper.php file defines the return types as `@return \Illuminate\Database\Eloquent\Model `

Changing the return types to `@return static` seems to help, but I'm not sure if this has any side effects.

**Comment by mfn** [comment]
@barryvdh this was fixed in Laravel with https://github.com/laravel/framework/pull/24526 , issue can be closed

(also means Laravel 5.5 won't have this fix as it was made for 5.7 onward 🤷‍♀️)
