### ISSUE TITLE
Autocompletion works with "Generated version for L5", but not with a new generated one in Netbeans IDE 8.2.

### ISSUE THREAD

**Issue by timuradilev** [barryvdh/laravel-ide-helper#654]
Hello.

I installed this component.
Run "php artisan ide-helper:generate"
_ide_helper.php was generated. 
It not worked.
Switched the file to  "Generated version for L5" https://gist.github.com/barryvdh/5227822
and it works!
Switched back to a new generated one and it doesn't work!
So there is an issue with new version of Laravel.

Netbeans version - 8.2
Laravel - 5.6.17

**Comment by tomzx** [comment]
Can you share the generated _ide_helper.php file?

**Comment by d3no** [comment]
I've the same proble,? Any solution for this?

**Comment by mfn** [comment]
This file is IDE agnostic and it's up to the IDE to support this; unless there's some specific bug to point out, this should be taken to the IDE bendor

@barryvdh I vote for closing this issue :}
