### ISSUE TITLE
Not working in Eclipse

### ISSUE THREAD

**Issue by pursehouse** [barryvdh/laravel-ide-helper#655]
I was able to install/setup/run all the setups
this is the output I get from running `php artisan ide-helper:generate`
results:
```
A new helper file was written to _ide_helper.php
Tag Exists: @mixin \Eloquent in Illuminate\Database\Eloquent\Model
Tag Exists: @mixin \Illuminate\Database\Eloquent\Builder in Illuminate\Database\Eloquent\Model
Tag Exists: @mixin \Illuminate\Database\Query\Builder in Illuminate\Database\Eloquent\Model
```
the file is full of classes listed. but no amount of refreshes/cleans in Eclipse is giving the IDE knowledge of which Facade I am trying to reference. In my case I'm currently using the "Cache" facade.

I also tried adding the `post-update-cmd` into the config and running `composer update -a`. Still no good.

any ideas? thanks!

**Comment by TheM1984** [comment]
I was also having issue with Eclipse.

The workaround that is working for me is:
* Generate the file or use created files that can be downloaded
* mv the file to a folder outside the project
* add the file as a linked resource:

* Goto File -> New -> Folder
* Click on Advanced
* Choose **Link to alternate location (Linked Folder)**
* Click on Browse, and go to the folder where the ide_helper now lives
* Click on finish

![image](https://user-images.githubusercontent.com/13640063/39705667-5a31e778-520f-11e8-91a1-b662e1b95b35.png)

**Comment by pursehouse** [comment]
thanks i'll try that out, you should PR those instructions into the README.MD

**Comment by Jonathan57500** [comment]
Hello, does not work for me as I can't save any file out of the project.
I'm running Eclipse Oxygen 3.

**Comment by TheM1984** [comment]
@pursehouse I don't know if it is the right way this should work.

@Jonathan57500 after generating I moved the file manually

**Comment by zulus** [comment]
Hi, I'm Eclipse PDT Project Leader, could someone explain me what problem you have and how we can simplify this? 

I'm using Symfony only so I might be wrong: As I see command prepare _ide_helper.php file. I'm afraid file is created outside build path (composer class path). Easiest way will be probably move/link to "src" (or any classpath dir). As an alternative you can create dir "_ide_helper" and add it to build path  (project right click ->  php -> source paths -> build path).

There is also an enhancement request to introduce something similar to PHPStorm meta file (https://bugs.eclipse.org/bugs/show_bug.cgi?id=463110). If you have idea how this file should look, please but it here.

**Comment by TheM1984** [comment]
@zulus the issue I was having that putting the file in the base path of the project, the build process of Eclipse was not taking it into account.

As stated above it worked for me to flag the file as a linked resource.
Putting the file in the vendor folder is tricky since I tend to clean that folder at some times. Although I know that is not how it should work.

**Comment by pursehouse** [comment]
@zulus well if you add composer to a project, it clears any pre-set build paths... so even if you move this file into a folder, and add it to the built path... then add ( or re-add, cuz the composer support setting vanishes on projects all the time for me ), the hand made build path is gone.. so that's I dunno, blocker issues I guess

**Comment by zulus** [comment]
@pursehouse couple releases ago we modified way how composer plugin clean-up build paths. If they are outside vendor and autoload/autoload-dev, rules remain untouched. So if you prepare subdir in project (for example .ide_mapping) with generated file, and add it to buildpath everything should work fine.

**Comment by zulus** [comment]
See details about composer management: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512032

**Comment by pursehouse** [comment]
@zulus I'm in the latest photon and this happened 3 days ago

**Comment by zulus** [comment]
Have you standard laravel composer.json or did you change something in autoload* ?

**Comment by pursehouse** [comment]
@zulus I'm not sure which project it was... but possibly yeah, just more psr-4 paths, which still shouldn't make the buildpath lose entries. I'll keep an eye out for the next time it happens

**Comment by kronzeuge** [comment]
I had the same problem with Eclipse 2018-09 (4.9.0) and solved the problem with an external library. I have documented it on [Stackoverflow](https://stackoverflow.com/questions/48909532/laravel-and-eclipse-how-to-avoid-errors-in-default-code-of-laravel-5-5/53801905#53801905).

**Comment by mfn** [comment]
@barryvdh this is Eclipse PHP IDE specific and nothing actionable for ide-helper; the last comment even documents how to get it working _in_ eclipse => IMHO this issue can be closed :}
