### ISSUE TITLE
Parameter of `nullable` of Fluent

### ISSUE THREAD

**Issue by jyhsu2000** [barryvdh/laravel-ide-helper#656]
In `_ide_helper.php`, section of Fluent,
there is a line of `nullable`,
```
@method Fluent nullable() Add the nullable modifier
```
But in the document of Laravel (5.5+), 
[Column Modifiers](https://laravel.com/docs/5.6/migrations#column-modifiers) describes that `nullable` can be used with a boolean parameter

|Modifier|Description|
|---|---|
|`->nullable($value = true)`|Allows (by default) NULL values to be inserted into the column|

When I use nullable with parameter (like `->nullable(false)`), IDE shows the following warning
```
Method call uses 1 parameters, but method signature uses 0 parameters
```

![screenshot_20180420_174435](https://user-images.githubusercontent.com/6276648/39044588-3304299e-44c3-11e8-86f6-13a3fcdf99d7.png)

Could you make it add the parameter to `nullable`?
(when generating `_ide_helper.php` using `ide-helper:generate`)

**Comment by mfn** [comment]
@barryvdh this was fixed in https://github.com/barryvdh/laravel-ide-helper/commit/1a3d32f0d1bcd4aa21063e1680c6042d0e6b055b , issue can be closed :}
