### ISSUE TITLE
Bug - ide-helper:generate fails when a macro's definition uses an object method as callback

### ISSUE THREAD

**Issue by ghobaty** [barryvdh/laravel-ide-helper#657]
When using an object method as a callback, `ide-helper:generate` fails with the following error thrown:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: ReflectionFunction::__construct() expects parameter 1 to be string, array given
```

at

https://github.com/barryvdh/laravel-ide-helper/blob/98d6087a1ef57088ed63ef19363d65ed26eb6438/src/Alias.php#L334

To reproduce, add the following code to `AppServiceProvider`, and then run `php artisan ide-helper:generate`
```
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        \Request::macro('test', [$this, 'test']);
    }

    /**
     * @return bool
     */
    public function test(): bool
    {
        return true;
    }
```

**Comment by mfn** [comment]
@barryvdh this was fixed with https://github.com/barryvdh/laravel-ide-helper/pull/621 , issue can be closed :}
