### ISSUE TITLE
Can I use this helper in a slim + eloquent project ?

### ISSUE THREAD

**Issue by imageslr** [barryvdh/laravel-ide-helper#658]
Now I'm developing a project with slim and eloquent, yet phpstorm doesn't support eloquent method hinting. Except changing to Laravel or Lumen, can I use this helper in a slim + eloquent project ? If you could give me a document link or some suggestions, I would be very grateful. Thank you!

**Comment by mfn** [comment]
Yes, it's possible with some work => please see https://github.com/barryvdh/laravel-ide-helper/issues/756

@barryvdh I vote for closing this issue, as the referenced issue has more details and would be more appropriate for specific questions IMHO
