### ISSUE TITLE
Native iterable type gets namespaced

### ISSUE THREAD

**Issue by sebastiaanluca** [barryvdh/laravel-ide-helper#673]
When `_ide-helper.php` is generated, the native `iterable` pseudo-type gets namespaced as part of the class it's used in.

Laravel example result (`_ide-helper.php`):

```php
/**
 * Determine if all of the given abilities should be granted for the current user.
 *
 * @param \Illuminate\Auth\Access\iterable|string $abilities
 * @param array|mixed $arguments
 * @return bool
 * @static
 */
public static function check($abilities, $arguments = array())
{
    return \Illuminate\Auth\Access\Gate::check($abilities, $arguments);
}
```

Note the following incorrectly generated PHPDoc:

```
@param \Illuminate\Auth\Access\iterable|string $abilities
```

And the source code:

```php
 /**
 * Determine if all of the given abilities should be granted for the current user.
 *
 * @param  iterable|string  $abilities
 * @param  array|mixed  $arguments
 * @return bool
 */
public function check($abilities, $arguments = [])
{
    return collect($abilities)->every(function ($ability) use ($arguments) {
        try {
            return (bool) $this->raw($ability, $arguments);
        } catch (AuthorizationException $e) {
            return false;
        }
    });
}
```

Where `@param  iterable|string  $abilities` is correct.

If someone can point me in the right direction to resolve this, I'd be willing to try and fix this in a PR.

### References

Perhaps related to https://github.com/barryvdh/laravel-ide-helper/issues/344.

**Comment by tdgroot** [comment]
@barryvdh could you give a lead on where to fix it? I'd like to fix this issue.

**Comment by mfn** [comment]
@barryvdh this is a duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/627 hence I vote for closing this issue

**Comment by mfn** [comment]
Closing per my comment https://github.com/barryvdh/laravel-ide-helper/issues/673#issuecomment-650431529
