### ISSUE TITLE
Class 'mixin' not found when called from another command

### ISSUE THREAD

**Issue by benfreke** [barryvdh/laravel-ide-helper#676]
Hi

I wrote a "helper" command to make it easy to copy information between projects. This is the `handle` method.

```php
    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        if (\App::environment() === 'local' && class_exists('Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider')) {
            $this->call('ide-helper:generate');
            $this->call('ide-helper:meta');
            $this->call(
                'ide-helper:models',
                [
                    '--write' => true,
                    '--reset' => true,
                    '--no-interaction' => true,
                ]
            );
        } else {
            $this->info('Helper files not generated. They will only generate when developing locally.');
        }
    }
```

When I run this, the following exception is shown. 

```
Exception: Class 'mixin' not found.
Could not analyze class App\User.
```

If I run the command manually, `php artisan ide-helper:models --write --reset --no-interaction` everything works as I'd expect it to and I get the output written to the models PHPDoc and I get the clean auto complete I'd expect.

This worked on a previous project, but not on the latest project which I'm using Vessel for. 

What else can I try to get this working? The obvious solution to me is to run each of these commands individually instead of as one command (in the composer post-autoload-dump script) but I was wondering what it is that I'm misunderstanding to get this error when attempting to run all 3 at one time.

Edit: Generate and Meta work without any issues, either directly or as part of this command

**Comment by ShahinSorkh** [comment]
Any update on this?

**Comment by markokeeffe** [comment]
I ran into this issue and resolved it by not calling `$this->call('ide-helper:meta');`

**Comment by benfreke** [comment]
@markokeeffe That's great. Can you outline your solution to calling one of the commands from another command?

**Comment by markokeeffe** [comment]
Nothing special I’m afraid, I just called the ‘generate’ and ‘models’ commands and left out the ‘meta’ one.

**Comment by Shonetow** [comment]
Or call `ide-helper:meta` after `ide-helper:models`.

**Comment by mfn** [comment]
There's a similar issue where I did test this and any order worked => https://github.com/barryvdh/laravel-ide-helper/issues/216

Does this problem still exists?
