### ISSUE TITLE
Route::view() is duplicated

### ISSUE THREAD

**Issue by andreshg112** [barryvdh/laravel-ide-helper#682]
![image](https://user-images.githubusercontent.com/15859884/43295286-8f0795d6-9109-11e8-81fe-6c961ee8cd7a.png)

![image](https://user-images.githubusercontent.com/15859884/43295291-9657db5c-9109-11e8-91a0-64feaaa722e9.png)

![image](https://user-images.githubusercontent.com/15859884/43295305-ae162848-9109-11e8-94eb-fcb68567d007.png)

![image](https://user-images.githubusercontent.com/15859884/43295310-bb1834e6-9109-11e8-8305-7a7c6b473458.png)

**Comment by mfn** [comment]
I don't this in the latest version of ide-helper/PhpStorm, is this still an issue for you?
