### ISSUE TITLE
Laravel route action autocompletion not working!

### ISSUE THREAD

**Issue by amirpiri** [barryvdh/laravel-ide-helper#683]
For example:
Route::post('sendOtp', 'App\Http\Controllers\Api\Auth\V1\AuthController@sendOtp');

not autocomplete the @sendOtp part!

**Comment by mfn** [comment]
This out of the scope of a package like ide-helper, it's simply technically not possible as the IDE would need real-time auto-complete information which can only be given by a plugin (I think https://plugins.jetbrains.com/plugin/7532-laravel does this).

If you want some auto-complete without a plugin, you _could_ use single action controllers, if you route to `App\Http\Controllers\Yolo::class` then it's `__invoke` method gets called => but when using the `::class` syntax you've auto-complete.

@barryvdh out-of-scope and workaround suggested, issue can be closed :}
