### ISSUE TITLE
ide-helper:models does not generate phpDoc

### ISSUE THREAD

**Issue by JmRy** [barryvdh/laravel-ide-helper#688]
Hello,

The result of this command is always a failure. Result No phpDoc generated ...
**php artisan ide-helper:models** 
with or without these options --dir='_models directory_',  -W,  -R, _[modelName]_, etc..

 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead? (Yes/No):  (yes/no) [no]:
 > no = empty file _ide_helper_models.php 
> yes = no generation in model files

My config 
 "php": ">=7.2.0",
"laravel/framework": "^5.6",
"doctrine/dbal": "^2.8",
"laravelcollective/html": "^5.6",
"barryvdh/laravel-ide-helper": "^2.4",

I do not understand why?

Thank you for your help :)

**Comment by iPaat** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/697#issuecomment-418754764

**Comment by AraneaDev** [comment]
I just had the same problem. It's related to doctrine somehow. For me changing "doctrine/dbal": "^2.8", to "doctrine/dbal": "~2.3", and then running composer again fixed the issue.

**Comment by JmRy** [comment]
Fine :+1:

**Comment by hotrush** [comment]
Finally found that passing `--dir="app/Models"` doesn't work, need to publish config and edit `model_locations` array.

**Comment by cpiggott** [comment]
Is there a reason that a specific version of dbal is required?

**Comment by jovanialferez** [comment]
I think the `--dir` option is meant to NOT work with specific model/s. It's for all models in that directory unless listed as ignored (`--ignore`). For specific model not in default directory (`app/`), you should specify full namespace (with `\\`) e.g. `php artisan ide-helper:models --write App\\Models\\User`

**Comment by Erutan409** [comment]
@delmicio YUP.  This was the fix for me without going through the extra steps outlined above.

**Comment by Tklaversma** [comment]
@hotrush @delmicio 

The following worked for me:

1. Run ```php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config```

2. Edit ```model_locations``` in ```app/config/ide-helper.php``` to ```'app/Models'```

3. Change ```localhost``` to ```127.0.0.1``` in ```.env``` and in ```app/config/database.php```

4. Edit ```composer.json```:
```
    "scripts" : {
        ...
        "post-update-cmd" : [
            ...
            "@php artisan ide-helper:generate",
            "@php artisan ide-helper:models --nowrite",
            "@php artisan ide-helper:meta"
        ]
    }
```
5. Run ```php artisan clear-compiled```

6. Run ```composer update```

That's it!

**Comment by mfn** [comment]
@barryvdh this was likely a problem with connecting to the database properly, I vote for closing this issue :}

**Comment by okellojohnsilas** [comment]
[Windows] In my case, the issue was I did not run the xampp (which I believe holds the database) and was only relying on <code>php artisan serve</code> while running the command  <code>php artisan ide-helper: models</code> meaning it was not accessing the database.. So the simple solution(in my opinion) is running whatever server stack (WAMPP or XAMPP) alongside the <code>php artisan serve</code> command.

**Comment by zanderwar** [comment]
In my case, I had not ran the migrations yet, so the tables didn't exist so it couldn't inspect the columns
