### ISSUE TITLE
Unexpected no document on Illuminate\Database\Eloquent\Model

### ISSUE THREAD

**Issue by wzsxjy** [barryvdh/laravel-ide-helper#689]
"barryvdh/laravel-ide-helper" : "^2.4"
"laravel/framework" : "5.6.*"

exec "php artisan ide-helper:generate"

output : 
"A new helper file was written to _ide_helper.php
Unexpected no document on Illuminate\Database\Eloquent\Model
Wrote expected docblock to D:\www\game_applet\vendor\laravel\framework\src\Illum
inate\Database\Eloquent\Model.php"

**Comment by iPaat** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/697#issuecomment-418754764

**Comment by mfn** [comment]
@barryvdh pretty sure this was fixed with https://github.com/barryvdh/laravel-ide-helper/pull/624 and no recent reports => vote for closing :}
