### ISSUE TITLE
Error on ide-helper:generate on Laravel 5.7 with v2.5.0 

### ISSUE THREAD

**Issue by maarten00** [barryvdh/laravel-ide-helper#697]
When trying to generate a helper file I get the following output:

```php artisan ide-helper:generate
A new helper file was written to _ide_helper.php
Unexpected no document on Illuminate\Database\Eloquent\Model
Content did not change <?php

namespace Illuminate\Database\Eloquent;

use Exception;
use ArrayAccess;
use JsonSerializable;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Contracts\Support\Jsonable;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Support\Traits\ForwardsCalls;
use Illuminate\Contracts\Routing\UrlRoutable;
use Illuminate\Contracts\Queue\QueueableEntity;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Contracts\Queue\QueueableCollection;
use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Database\ConnectionResolverInterface as Resolver;

abstract class Model implements ArrayAccess, Arrayable, Jsonable, JsonSerializable, QueueableEntity, UrlRoutable
```
(cut output, full output here:https://pastebin.com/M3dDzQ51)

**Comment by drbyte** [comment]
Same as #695 and #689

**Comment by Jimbolino** [comment]
I think the code from this fix has been removed:
https://github.com/barryvdh/laravel-ide-helper/issues/623

**Comment by drbyte** [comment]
Yup. Brand new fresh L5.7 or L5.6 install, adding this package and running `ide-helper:generate` throws up the big red error.

<img width="571" alt="screen shot 2018-09-04 at 11 15 47 am" src="https://user-images.githubusercontent.com/404472/45040410-f2e95a00-b033-11e8-9f89-7c87277a95a9.png">

**Comment by poseso** [comment]
Yeah i had to revert to 2.4.3

**Comment by edh72** [comment]
+1 on Laravel 5.7 and 2.5.0
reverting to 2.4.3 didn't help

**Comment by drbyte** [comment]
It’s not unique to 5.7 though. 

Three options:
- remove the :generate command from composer.json and any other scripts (forfeiting it’s use)
- roll back to older Laravel version where the docblock was removed from the Model class
- use an older version of this pkg where the Model docblock was briefly ignored

**Comment by SjorsO** [comment]
https://github.com/barryvdh/laravel-ide-helper/issues/623#issuecomment-363728595 explains that this error happens because `Model` does not have a docblock.

Until we have a proper solution, a temporary fix is manually adding a docblock to `Illuminate\Database\Eloquent\Model`, like this:
```php

/**
 * Class Model
 *
 * @package Illuminate\Database\Eloquent 
 */
abstract class Model implements ArrayAccess, Arrayable, Jsonable, JsonSerializable, QueueableEntity, UrlRoutable
{
```

**Comment by iPaat** [comment]
I tried to fix this with https://github.com/barryvdh/laravel-ide-helper/pull/624 but it got reverted with https://github.com/barryvdh/laravel-ide-helper/pull/626. Someone could make a Fork to make this package at least work again... I understand that you don't want Composer packages to change other packages, but there is no other way atm.

**Comment by poseso** [comment]
I'm on 5.6.38 . and reverted to 2.4.3 and it's working:

"barryvdh/laravel-ide-helper": "2.4.3",

**Comment by iPaat** [comment]
I'm done with this stuff. I've created a fork.  
It can be used as follows:

Add the new repository to your `composer.json` file:
```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/iPaat/laravel-ide-helper"
    }
]
```

Change dependency to:
```json
"require-dev": {
    "barryvdh/laravel-ide-helper": "dev-fixed",
}
```

**Comment by gordonzero** [comment]
@iPaat would you please do a pull request for your branch. I have tested it and it does appear to fix this issue.

hopefully @barryvdh can merge it in soon.

**Comment by ItaloBC** [comment]
Writing something into the vendor folder should be avoided at all costs. Even if it's a comment.

**Comment by SjorsO** [comment]
It feels like not writing to vendor files makes sense, but what are actual reasons not to do it? As far as i can tell writing a docblock to a vendor file is helpful and harmless

**Comment by ItaloBC** [comment]
Hold my beer:

`composer update`

![image](https://user-images.githubusercontent.com/26698421/45320304-a2cd3480-b518-11e8-82ef-7cf447555e60.png)

It's a matter of principles. If you never used composer update, cool, but again, vendor folder is inmutable. This should be fixed inside the package, and avoid any modification to other packages.

**Comment by amcsi** [comment]
@SjorsO because if you do a composer update and the file within the vendor folder changes, it would overwrite your changes.

**Comment by mfn** [comment]
@barryvdh pretty sure this was fixed with https://github.com/barryvdh/laravel-ide-helper/pull/624 and no recent reports => vote for closing :}
