### ISSUE TITLE
lumen: ide-helper:generate terminates with error 'Class App does not exist'

### ISSUE THREAD

**Issue by crhg** [barryvdh/laravel-ide-helper#698]
# PROBLEM

When I run `ide-helper:generate` on lumen project, it ended with the following error and it does not generate `_ide_helper.php`.

```terminal
% php artisan ide-helper:generate

In Alias.php line 69:

  Class App does not exist
```

The versions are as follows:

laravel/lumen-framework: v5.6.4
barryvdh/laravel-ide-helper: v2.5.0

# STEP TO REPRODUCE

## create lumen project

```
composer create-project --prefer-dist laravel/lumen foo
```

## require laravel-ide-helper

```
composer require barryvdh/laravel-ide-helper
```

## modify `bootstrap/app.php`

Uncomment the following two lines.

```php
$app->withFacades();
```

```php
$app->register(App\Providers\AppServiceProvider::class);
```

## modify `app/Providers/AppServiceProvider.php`

Register `IdeHelperServiceProvider` in `register()`

```php
    public function register()
    {
        $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
    }
```

## run `ide-helper:generate`

```
php artisan ide-helper:generate
```

**Comment by YWatchman** [comment]
I too have this problem.

    MBP-van-Yvan:cyberfusion-api yvanwatchman$ php artisan ide-helper:generate

    In Alias.php line 69:
                            
        Class App does not exist

**Comment by EmperorArthur** [comment]
Can also confirm.  Same error as YWatchman.

**Comment by iocaste** [comment]
I don't know will someone of contributors of this package fix it but temporary workaround, while this issue is open, would be to add in `app.php` something like this:

```php
class_alias(Illuminate\Support\Facades\App::class, 'App');
class_alias(Illuminate\Support\Facades\Bus::class, 'Bus');
class_alias(Illuminate\Support\Facades\Hash::class, 'Hash');
class_alias(Illuminate\Support\Facades\Request::class, 'Request');
```

**Comment by moazam1** [comment]
I am still having same issue. I am using 2.5.1. @iocaste fix solved my problem.

**Comment by edmundluong88** [comment]
+1 also having this issue.

laravel/lumen-framework: v5.6.4
barryvdh/laravel-ide-helper: v2.5.1

**Comment by bleuscyther** [comment]
I had to apply @iocaste 's fix for every Class missing

**Comment by julioalves** [comment]
+1
same problem with laravel/lumen-framework: v5.6.4

**Comment by cnbattle** [comment]
+1
laravel/lumen-framework: v5.7.1
barryvdh/laravel-ide-helper: v2.5.1

**Comment by Awezome** [comment]
same here 

laravel/lumen-framework: v5.7.1
barryvdh/laravel-ide-helper: v2.5.1

**Comment by j3rrey** [comment]
Having the same issue ```"barryvdh/laravel-ide-helper": "^2.5"```

**Comment by emiliopedrollo** [comment]
I have a similar problem with Laravel 5.7: ide-helper:meta returns:
```
In MetaCommand.php line 138:
                                      
  Class 'CreateMetaTable' not found.  
```
