### ISSUE TITLE
Method with same name already defined in this class

### ISSUE THREAD

**Issue by realmarkcross** [barryvdh/laravel-ide-helper#703]
L5.7.2, LIDEH:2.5.1 
_ide_helper.php produces error in PHPStorm :  'Method with same name already defined in this class'
on many methods.  Never had an issue with 5.6, but this is the first time I'm installing both 5.7 Laravel and 2.5.1 LIDEH.
Screenshot shows the first part of the file with underlined methods that reflect this error.
![image](https://user-images.githubusercontent.com/10559427/45260596-a4ccb180-b3b9-11e8-82be-528566f8496b.png)

**Comment by guice** [comment]
+1 on this. I can't here with this same issue.

**Comment by yutarux** [comment]
Me, three.

Laravel 5.5
Intellij IDEA Ultimate 2018.2.3
ide-helper 2.5.0

**Comment by yutarux** [comment]
Same as #697 ?

**Comment by guice** [comment]
@yutarux No. Our files create successfully. We don't get an error during compose update. Our error is within PhpStorm, complaining about pre-existing methods.

**Comment by Evrimedont** [comment]
+1

Laravel 5.7
PHPStorm 2018.2.3
ide-helper 2.5.1

**Comment by SeagleDub** [comment]
+1

Laravel 5.7
PHPStorm 2018.2.3
ide-helper 2.5.1

**Comment by tnorthcutt** [comment]
Another one here; confirmed that reverting to `2.4.3` fixed it. Not sure what the issue is yet, but [here](https://github.com/barryvdh/laravel-ide-helper/compare/v2.4.3...master) are the commits since `2.4.3`.

**Comment by tnorthcutt** [comment]
Update: the bug appears to be introduced in this commit: https://github.com/barryvdh/laravel-ide-helper/commit/b644e48801edba4ac56f1dee561b72d67f731e06

/cc @barryvdh

**Comment by guyaloni** [comment]
+1

Laravel 5.7.6
PHPStorm 2017.3.6

**Comment by hcancelik** [comment]
+1

Laravel 5.7.9
PHPStorm 2018.2.5

**Comment by iAxel** [comment]
+1

Laravel 5.7.6 
PHPStorm 2017.3.6

**Comment by JeppeKnockaert** [comment]
I've proposed a fix for this issue in #720.

**Comment by iAxel** [comment]
> I've proposed a fix for this issue in #720.

Please explain step by step how to solve this problem...
Grateful...

**Comment by JeppeKnockaert** [comment]
The issue is that methods are both defined in the classes defined in idehelper, as well as in the class docblock.

For example, take this snippet from the idehelper file for the DB class:
```
    /**
     * 
     *
     * @method static \Illuminate\Database\ConnectionInterface connection(string $name = null)
     * @method static string getDefaultConnection()
     * @method static void setDefaultConnection(string $name)
     * @method static \Illuminate\Database\Query\Builder table(string $table)
     * @method static \Illuminate\Database\Query\Expression raw($value)
     * @method static mixed selectOne(string $query, array $bindings = [])
     * @method static array select(string $query, array $bindings = [])
     * @method static bool insert(string $query, array $bindings = [])
     * @method static int update(string $query, array $bindings = [])
     * @method static int delete(string $query, array $bindings = [])
     * @method static bool statement(string $query, array $bindings = [])
     * @method static int affectingStatement(string $query, array $bindings = [])
     * @method static bool unprepared(string $query)
     * @method static array prepareBindings(array $bindings)
     * @method static mixed transaction(\Closure $callback, int $attempts = 1)
     * @method static void beginTransaction()
     * @method static void commit()
     * @method static void rollBack()
     * @method static int transactionLevel()
     * @method static array pretend(\Closure $callback)
     * @see \Illuminate\Database\DatabaseManager
     * @see \Illuminate\Database\Connection
     */ 
    class DB {
        
        /**
         * Get a database connection instance.
         *
         * @param string $name
         * @return \Illuminate\Database\Connection 
         * @static 
         */ 
        public static function connection($name = null)
        {
            return \Illuminate\Database\DatabaseManager::connection($name);
        }
```

You see there's both a method `connection` and an `@method` tag for the connection method in the docblock.

Some versions of PhpStorm (e.g. 2018.3) give an error on this kind of thing: "Method with the same name already defined in this class", causing PhpStorm to ignore the method completely.

In my pull request I detect the `@method` tags for which a real method already exists and leave them out of the docblock, so they wouldn't cause any issues.

When/if the fix gets released, you will just need to update idehelper to the newest version and run `php artisan ide-helper:generate` again to solve the issue.

**Comment by iAxel** [comment]
> The issue is that methods are both defined in the classes defined in idehelper, as well as in the class docblock.
> 
> For example, take this snippet from the idehelper file for the DB class:
> 
> ```
>     /**
>      * 
>      *
>      * @method static \Illuminate\Database\ConnectionInterface connection(string $name = null)
>      * @method static string getDefaultConnection()
>      * @method static void setDefaultConnection(string $name)
>      * @method static \Illuminate\Database\Query\Builder table(string $table)
>      * @method static \Illuminate\Database\Query\Expression raw($value)
>      * @method static mixed selectOne(string $query, array $bindings = [])
>      * @method static array select(string $query, array $bindings = [])
>      * @method static bool insert(string $query, array $bindings = [])
>      * @method static int update(string $query, array $bindings = [])
>      * @method static int delete(string $query, array $bindings = [])
>      * @method static bool statement(string $query, array $bindings = [])
>      * @method static int affectingStatement(string $query, array $bindings = [])
>      * @method static bool unprepared(string $query)
>      * @method static array prepareBindings(array $bindings)
>      * @method static mixed transaction(\Closure $callback, int $attempts = 1)
>      * @method static void beginTransaction()
>      * @method static void commit()
>      * @method static void rollBack()
>      * @method static int transactionLevel()
>      * @method static array pretend(\Closure $callback)
>      * @see \Illuminate\Database\DatabaseManager
>      * @see \Illuminate\Database\Connection
>      */ 
>     class DB {
>         
>         /**
>          * Get a database connection instance.
>          *
>          * @param string $name
>          * @return \Illuminate\Database\Connection 
>          * @static 
>          */ 
>         public static function connection($name = null)
>         {
>             return \Illuminate\Database\DatabaseManager::connection($name);
>         }
> ```
> You see there's both a method `connection` and an `@method` tag for the connection method in the docblock.
> 
> Some versions of PhpStorm (e.g. 2018.3) give an error on this kind of thing: "Method with the same name already defined in this class", causing PhpStorm to ignore the method completely.
> 
> In my pull request I detect the `@method` tags for which a real method already exists and leave them out of the docblock, so they wouldn't cause any issues.
> 
> When/if the fix gets released, you will just need to update idehelper to the newest version and run `php artisan ide-helper:generate` again to solve the issue.

Thank you)

**Comment by fmonts** [comment]
Is the issue fixed? I never worked in Laravel (I work in Symfony where there is a plugin installed in the IDE, much simpler than this...) and I have to do something on a project started by someone else... 

I generate this `_ide_helper.php` file following the PHPStorm instructions [here](https://www.jetbrains.com/help/phpstorm/laravel.html), but if I open it it's full of IDE errors and warnings... For example the class App has a duplicate declaration both here and in _vendor\laravel\...\Illuminate\Support\Facades\App_

What should I do to fix the issue? Ignore a vendor folder? This is very weird...

**Comment by Mapteg34** [comment]
+1
Laravel 5.7.14
PHPStorm 2018.3.2

**Comment by martinresko** [comment]
+1
Lumen (5.7.1) (Laravel Components 5.7.*)
PHPStorm 2018.3.3

**Comment by pks1989** [comment]
Аs mentioned earlier, it is PHPStorm IDE problem, because IDE ispections take into account declaration in _ide_helper.php.
So... i mark this file as plain text, and problem gone :)

I think its best fixing variant because you dont disable this inspection in IDE or change any code.

![Screenshot_20190511_163647](https://user-images.githubusercontent.com/37282764/57568023-bc0de400-740b-11e9-95e9-53d764aa66c4.png)

**Comment by gugglegum** [comment]
@pks1989 Bad solution. If you mark _ide_helper.php as Plain Text you got the same result as removing this (barryvdh/laravel-ide-helper) package at all.

**Comment by pks1989** [comment]
> @pks1989 Bad solution. If you mark _ide_helper.php as Plain Text you got the same result as removing this (barryvdh/laravel-ide-helper) package at all.

ok, my fault.

**Comment by ahait** [comment]
This should not be closed since it's still an issue.

**Comment by olezhkafp** [comment]
I have the same with laravel v9.35.1 and phpstorm 2022.2.1

**Comment by JohnnyWalkerDesign** [comment]
Laravel 9.43 and PHPStorm 2202.2.3

Is there a harmless way to get the IDE to ignore this (assuming it's not actually a problem?).

**Comment by itsserbin** [comment]
+1 
Laravel 10.8

**Comment by stehled** [comment]
+1 Symfony

**Comment by Enterprize-1701** [comment]
+1
Laravel 10.10

**Comment by barryvdh** [comment]
This issue is already closed. Is something changed? Which PR should I look at?

**Comment by Enterprize-1701** [comment]
When i use "barryvdh/laravel-dompdf": "^2.0", in my project in laravell 10.10 I face with this again.
![2023-11-3_03-38-35](https://github.com/barryvdh/laravel-ide-helper/assets/11555427/0a24880d-773f-46a7-89d4-56567a21bd75)

**Comment by efren-corillo** [comment]
@Enterprize-1701 
> When i use "barryvdh/laravel-dompdf": "^2.0", in my project in laravell 10.10 I face with this again. "Another definition with same name exists in this file" for _ide_helper.php in PhpStorm 2023.2.3.

It's 2024 and Still getting this issue. I manually removed the duplicate DomPdf "PDF" vs "pdf", but when doing composer install or update the _ide_helper.php is regenerated and the issue comes back.

**Comment by bantawa04** [comment]
> ed in Laravel (I

Any solution ?

**Comment by GDC-Nirmal** [comment]
This issue still there. :monocle_face: Is there a solution for this ? Its not a work breaking problem. just bit annoying showing error on _ide_helper.php file 😞 . This only happens with "barryvdh/laravel-dompdf" package for me. 

> "message": "Cannot redeclare class/interface 'Barryvdh\\DomPDF\\Facade\\Pdf'"

Laravel version: 10.48.29
Editor: VSCode on Windows 11 OS
