### ISSUE TITLE
Hover info not working in PHPStorm

### ISSUE THREAD

**Issue by azdanov** [barryvdh/laravel-ide-helper#704]
After generating `_ide_helper.php` hover info functionality doesn't seem to work in `PhpStorm 2018.3 EAP`. Here's the generated [`_ide_helper.php`](https://gist.github.com/azdanov/9f6aa5f22c90d6a82a33f415233a75fb) for reference.

<img width="616" alt="screen shot 2018-09-09 at 15 53 48" src="https://user-images.githubusercontent.com/6123841/45264670-e9535e00-b448-11e8-9d71-ad4e524f7344.png">
<img width="597" alt="screen shot 2018-09-09 at 15 54 07" src="https://user-images.githubusercontent.com/6123841/45264671-e9ebf480-b448-11e8-8ec8-04c170b2e1de.png">

As someone just starting out with Laravel I can't find where the issue originates from, either `PHPStorm EAP` or `Laravel 5.7`.

__EDIT:__

Also, some methods do seem to work others not:

<img width="628" alt="screen shot 2018-09-09 at 16 28 05" src="https://user-images.githubusercontent.com/6123841/45264972-68e32c00-b44d-11e8-87f0-c613fd4d864c.png">

__EDIT#2:__

Autocomplete functionality does work. But it's strange that after the method is completed, IDE gets confused.

**Comment by azdanov** [comment]
I've managed to make this working thanks to https://github.com/barryvdh/laravel-ide-helper/issues/708#issuecomment-422837744.

So there are there new changes in `5.7` that break the generated file?

**Comment by KaminoU** [comment]
You are lucky az =)

I still can't navigate from my Route to controller.

I got this weird issue after the updating of PHPStorm to 2018.3, tried the #708 but still nothing here (even after invalidating my cache & restarting my IDE)

**Comment by wensonsmith** [comment]
https://github.com/Haehnchen/idea-php-laravel-plugin/issues/148#issuecomment-484979155

**Comment by mfn** [comment]
The original author ended up editing the description saying it works.

As for the others, I suggest to test again using the latest version and search for existing issues or create new ones for specific problems

@barryvdh I vote for closing this issue :}
