### ISSUE TITLE
Models: Will be good use actual `Carbon` class instead of hardcoded `\Illuminate\Support\Carbon`

### ISSUE THREAD

**Issue by LastDragon-ru** [barryvdh/laravel-ide-helper#705]
Since Larael 5.7 the [`\Illuminate\Support\Carbon`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/Carbon.php) is empty and much better always use a `Carbon\Carbon` :)

**Comment by pverhaert** [comment]
Tested in Laravel 5.8:
```php
'Carbon' => Facades\Carbon\Carbon::class,
```

**Comment by LastDragon-ru** [comment]
I meant that `\Illuminate\Support\Carbon` hardcoded as type for date/datetime 
- https://github.com/barryvdh/laravel-ide-helper/blob/c9132b28a6fab5e76207ac653e842f584eb3759d/src/Console/ModelsCommand.php#L287
- https://github.com/barryvdh/laravel-ide-helper/blob/c9132b28a6fab5e76207ac653e842f584eb3759d/src/Console/ModelsCommand.php#L351

And we always have

```
 * @property \Illuminate\Support\Carbon $created_at
 * @property \Illuminate\Support\Carbon $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
```

When I create this issue I supposed that `\Illuminate\Support\Carbon` will be deleted... As I see now Laravel 5.8 uses `Illuminate\Support\Facades\Date` and `\Illuminate\Support\Carbon` can be overridden -> so seems this issue still actual and imho will be good to use actual class instead of hardcoded `\Illuminate\Support\Carbon`.

**Comment by mfn** [comment]
IMHO that's not entirely correct, there are a few things to consider:

1) You already pointed out: you can use `Date::swap(…)` and get something entirely different, see the examples given in https://github.com/laravel/framework/pull/25320 which implemented this. This means what you get back technically "depends".

2) the defaults in Laravel are to return `\Illuminate\Support\Carbon` so it makes sense the ide helper does that too => nothing to change here.

That said, I don't want to imply that this can't be improved but not by virtue of changing the generated code "hardcoded to something else but the default".

**Comment by mfn** [comment]
@barryvdh this was fixed via https://github.com/barryvdh/laravel-ide-helper/pull/859 , issue can be closed :}
