### ISSUE TITLE
Class 'Composer\Autoload\ClassMapGenerator' not found

### ISSUE THREAD

**Issue by Cysioland** [barryvdh/laravel-ide-helper#709]
When doing `php artisan ide-helper:models` this one pops up

**Comment by Orayi** [comment]
Just had the same issue. After composer update it went.

**Comment by mfn** [comment]
Given the age of the issue, I think it's related to outdated versions of ide-helper / laravel or some other problem

@barryvdh I vote for closing this issue :}

**Comment by ahosker** [comment]
Still an issue in 2022

**Comment by elliottpost** [comment]
I was able to temporarily solve this by editing the problematic file (`LaravelActionsIdeHelperCommand.php`) to replace this line:
`use Composer\Autoload\ClassMapGenerator;`
with this:
`use Barryvdh\LaravelIdeHelper\ClassMapGenerator;`

But it requires also having `barryvdh/laravel-ide-helper` installed.

**Comment by acrolink** [comment]
You might need to do this:
`composer require --dev composer/composer`
