### ISSUE TITLE
Postgres citext column type not supported

### ISSUE THREAD

**Issue by bmesin** [barryvdh/laravel-ide-helper#710]
Postgres database engine does not allow case insensitive table columns so if you need this for e.g. unique keys you need to install a plugin called "citext" (https://www.postgresql.org/docs/9.6/static/citext.html)

Unfortunately ide-helper:models breaks on models/tables where citext is implemented.

**Comment by majna** [comment]
@bmesin You can "publish" plugin config file and map custom types:

```
'custom_db_types' =>[
        'postgresql' =>[
           'citext' => 'string',
      ]
]
```

**Comment by mfn** [comment]
@barryvdh last comment is the correct solution, issue can be closed :}

**Comment by ankurk91** [comment]
@barryvdh 
Would you accept a PR to add this column type to this package itself?

**Comment by mfn** [comment]
@ankurk91 what would it improve compared to the suggested solution in https://github.com/barryvdh/laravel-ide-helper/issues/710#issuecomment-424715288 ?

**Comment by ankurk91** [comment]
I just want this config to be included in package by default
