### ISSUE TITLE
Real methods with the same name but different classes is not added to Facade

### ISSUE THREAD

**Issue by pahan35** [barryvdh/laravel-ide-helper#712]
I was adding Sentinel methods to `magic` array in **config/ide-helper.php** when I noticed that methods with different classes but the same name are not processed correctly.

To reproduce this issue try to add to `'magic'` config field method from different classes but with the same name. The actual methods which I was adding when noticed this problem:
```
'magic' => [
    'Sentinel' => [
        'findRoleById' => 'Cartalyst\Sentinel\Roles\IlluminateRoleRepository::findById',
        'findUserById' => 'Cartalyst\Sentinel\Roles\IlluminateUserRepository::findById',
    ]
],
```

**What is expected behavior?**
I expect to see autocomplete for both `Sentinel::findRoleById()` and `Sentinel::findUserById()`

**What happens instead?**
The only one of those methods added to `__ide_helper.php` and has autocomplete.

The problem caused by next line
![image](https://user-images.githubusercontent.com/13823215/46261291-4303f100-c4fa-11e8-939e-d768410c9ae0.png)

It doesn't allow us to add different Facade methods which use methods with the same name even from different classes.

**Comment by mfn** [comment]
@barryvdh OP submitted a PR and fixed the issue themselves, it can be closed :}
