### ISSUE TITLE
Error generating eloquent file

### ISSUE THREAD

**Issue by amirpiri** [barryvdh/laravel-ide-helper#715]
Currently I have installed Laravel Ide-helper on Laravel 5.7 and got error when issue the command 
`artisan ide-helper:eloquent`
The error returned is:
Unexpected no document on Illuminate\Database\Eloquent\Model
Content did not change

My Laravel installation is raw and installed as a new project.

**Comment by iPaat** [comment]
I've been trying to [tackle this problem](https://github.com/barryvdh/laravel-ide-helper/pull/700). Unfortunately, this optional solution has not yet been evaluated.
