### ISSUE TITLE
Method where not found in App\Model

### ISSUE THREAD

**Issue by quantumwebco** [barryvdh/laravel-ide-helper#716]
```
Model::where()
```
Results in the error "method where not found in App\Model"

Laravel 5.7
laravel-ide-helper ^2.4
php 7.2.8

I tried
```
php artisan clear-compiled
php artisan ide-helper:generate
php artisan ide-helper:meta
```

If I do 
```
Model::query()->where()
```
It works fine

**Comment by iPaat** [comment]
I've been trying to [tackle this problem](https://github.com/barryvdh/laravel-ide-helper/pull/700). Unfortunately, this optional solution has not yet been evaluated.

**Comment by maxsky** [comment]
Same problem in Laravel 5.5.44.

**Comment by fifths** [comment]
same problem

**Comment by abordage** [comment]
+1

**Comment by Nicksxs** [comment]
+1

**Comment by linslin** [comment]
+1

**Comment by Epistol** [comment]
+1

**Comment by iPaat** [comment]
Does this help?  
https://github.com/barryvdh/laravel-ide-helper/pull/700#issuecomment-451943526

**Comment by WIttyJudge** [comment]
After the commands you wrote you should write **php artisan ide-helper:models** as well.
It helped me.

**Comment by mfn** [comment]
This works nowadays, it certainly does for me. Also other things mentioned, like local scopes, are supported too.

If there's anything not working as expected, I suggest to search for existing issues or create new ones for each dedicated problem encountered.

@barryvdh I vote for closing this issue :}

**Comment by kaibox-git** [comment]
File "composer.lock": "name": "barryvdh/laravel-ide-helper", "version": "v2.7.0",

File "App\Http\Controllers\Auth\RegisterController.php":

protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);
    }

ide-helper: "Method 'create' not found in \App\User."

Application runs without errors.

**Comment by mfn** [comment]
Did `php artisan ide-helper:generate` generate `_ide_helper.php` and do you have in your project?

What's the content of the file?

There should be an entry like this to make this work:
![image](https://user-images.githubusercontent.com/87493/87775488-78401700-c826-11ea-8a47-d29760056b26.png)

**Comment by mfn** [comment]
> Model::all() is found

Because it's a true static method on the model => `\Illuminate\Database\Eloquent\Model::all`

**Comment by mfn** [comment]
To given an idea how this works in practice:
```
$ ./artisan ide-helper:generate
A new helper file was written to _ide_helper.php

$ wc -l _ide_helper.php
13493 _ide_helper.php
```

**Comment by kaibox-git** [comment]
_ide_helper.php already contains it:
/**
             * Save a new model and return the instance.
             *
             * @param array $attributes
             * @return \Illuminate\Database\Eloquent\Model|$this 
             * @static 
             */ 
            public static function create($attributes = [])
            {
                                /** @var \Illuminate\Database\Eloquent\Builder $instance */
                                return $instance->create($attributes);
            }
         
How to attach the screenshot?

**Comment by mfn** [comment]
@kaibox-git what IDE are you using? 

> How to attach the screenshot?

Just pasting into the next field (assuming your screenshot tool copied the image to the clipboard).

Also, you can use triple ``` to enclose code blocks (place them at the beginning of a line, like this:
![image](https://user-images.githubusercontent.com/87493/87782928-bee83e00-c833-11ea-9b76-93bcc02947a6.png)

**Comment by kaibox-git** [comment]
PHPStorm 2020 and all packages installed locally this month as a new project.  I did:
composer create-project --prefer-dist laravel/laravel project.local
composer require --dev barryvdh/laravel-ide-helper
In config/app.php added
Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,

In composer.json added
"post-update-cmd": [
        "Illuminate\\Foundation\\ComposerScripts::postUpdate",
        "@php artisan ide-helper:generate",
        "@php artisan ide-helper:meta"
    ]

php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config

config/ide-helper.php file into:
'include_fluent' => true,

composer update
(.phpstorm.meta.php и _ide_helper.php appear)

composer require laravel/ui
php artisan ui vue --auth

Then open file "App\Http\Controllers\Auth\RegisterController.php", find create() method, string 
return User::create([
and **ide-helper:** "Method 'create' not found in \App\User."

**Comment by mfn** [comment]
Thanks, detailed protocol helps to understand your problem!

You did not generate the modes, i.e. `php artisan ide-helper:models`

Because this command will write `_ide_helper_models.php`, will write a shallow duplicate of your model with phpdoc attached to the (duplicate|shallow) class. One of those phpdocs is `@mixin \Eloquent`.

Maybe you just forgot to run this command or don't want to, you can also add the mixin manually, then it works:
```php
/**
 * @mixin \Eloquent
 */
class User extends Authenticatable
```

PS: I recommend to use `php artisan ide-helper:models --write` to write that meta data _directly_ onto your models.


Guess it would be helpful to have Github "Discussions" for this project.

And maybe the readme needs some clarifications in this direction too 🤷‍♀️

@barryvdh as mentioned in https://github.com/barryvdh/laravel-ide-helper/issues/716#issuecomment-650489296, this particular issue can definitely be closed.

**Comment by kaibox-git** [comment]
Yes, it helped. I missed that because I thought It is optional and I dont like PHPDocs.
Thank you very much!

**Comment by kaibox-git** [comment]
Is it possible to include to helper Illuminate\Foundation\Auth\User ?
The same behavior:
User::find() not found
User::all() found

**Comment by mfn** [comment]
>  User::all() found

See https://github.com/barryvdh/laravel-ide-helper/issues/716#issuecomment-660016342 , this is unrelated to ide-helper

>  User::find() not found

Works for me?
![image](https://user-images.githubusercontent.com/87493/87807957-38465780-c859-11ea-992c-35dd6ab09027.png)

What is the full code you're using?

**Comment by kaibox-git** [comment]
> What is the full code you're using?

https://github.com/laravel/ideas/issues/1632#issuecomment-575903992

 public function verify(Request $request)
    {
        $user = **User::findOrFail**($request->route('id'));

Method 'findOrFail' not found in \Illuminate\Foundation\Auth\User

**Comment by mfn** [comment]
I think this is https://github.com/barryvdh/laravel-ide-helper/issues/501 and not supported ATM.

**Comment by kaibox-git** [comment]
> And maybe the readme needs some clarifications in this direction too
Yes. Most users who want to install ide-helper prefer one command or at least one window with a list of commands as here https://getcomposer.org/download/. And they want the ide-helper to work everywhere in the project, isn't it? The current readme contains many words and many options (Installation starts with "If for some reason you want ...", "If you want to manually..." and so on) that make the user stuck on the page for a long time. As a result, most users have incorrect installation and subsequent problems.
Thank you.

**Comment by BrobichoDev** [comment]
> PS: I recommend to use `php artisan ide-helper:models --write` to write that meta data _directly_ onto your models.


This was the solution for me ! Thank you !

**Comment by ivnlabs** [comment]
`php artisan ide-helper:models --write` 

This code makes my PHP Storm works and stops complaining about not finding the extend Model functions...
What I did not like too much is that in my Model files now I got a lot of lines that make the connection to make this work... so I might find a solution to move these generated lines of code to another file HIDDEN like a trace or something like that, but so far that code was the only way to make this works, THANKS

testing I saw that `php artisan ide-helper:models` this code ask later if you want to write the code, so if you prompt YES then is the same as the code above the --write , also works and make this stuff to really run the way it should , thanks Mr.Barry if you could make this to be encapsulated inside another file that is called by the model WOW that would be great!
