### ISSUE TITLE
PhpStorm auto completion Request::validate + Input::only etc.

### ISSUE THREAD

**Issue by tka-demon** [barryvdh/laravel-ide-helper#721]
Greetings!

First of all - thanks for providing this ide helper!

I'm new to Laravel. I followed JB's guide to Laravel in PhpStorm here: https://confluence.jetbrains.com/display/PhpStorm/Laravel+Development+using+PhpStorm

However unfortunately auto completion only seem to work partially. For instance basic methods like Input::only or Input::has cannot be autocompleted. Is this a known issue? (or perhaps the JB guide i simply outdated).

Thanks!

Friendly Regards,
/T

**Comment by mfn** [comment]
@barryvdh there's no `Input` facade anymore, was removed for Laravel 6 ( https://laravel.com/docs/6.x/upgrade#the-input-facade ) , this issue can be closed :}
