### ISSUE TITLE
Lumen Fresh Install - Class 'League\Flysystem\Adapter\Local' not found

### ISSUE THREAD

**Issue by dciancu** [barryvdh/laravel-ide-helper#723]
Hello,

I get this error with a fresh install of Lumen (latest version - 5.7.4):
```
> php artisan ide-helper:generate
In FilesystemManager.php line 160:
  Class 'League\Flysystem\Adapter\Local' not found
```

Any idea why?
No filesystem config options are set.

If I install `league/flysystem` package then this comes up:
```
> php artisan ide-helper:generate
In Alias.php line 69:
  Class App does not exist
```

**Comment by rjpounder** [comment]
I know this sounds silly, but have you composer installed lol

**Comment by dciancu** [comment]
@rjpounder `php artisan` doesn't work without deps installed

**Comment by rjpounder** [comment]
Before your edit; it could of been a dependency that didn't install correctly and you just missed the message, what happens when you try to tinker? if you can tinker can you `new Illuminate\Foundation\Application`

**Comment by dciancu** [comment]
Try for yourself:
```
composer create-project --prefer-dist laravel/lumen lumen-test && cd lumen-test && composer require --dev barryvdh/laravel-ide-helper && sed -i '' '19i\
\
$app->register(Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider::class);
' artisan && php artisan ide-helper:generate
```

**Comment by chukkynze** [comment]
I got the same error. Solved it by first running:

`composer require league/flysystem`

Seeing that the error was for aliases, I applied the portion of the docs that referenced aliases and added a `config\app.php` file that looks like this:
```
<?php
return [
    'aliases' => [
        'App' => Illuminate\Support\Facades\App::class,
    ]
];
```

works!

**Comment by dciancu** [comment]
Thanks for the solution.
Dunno which package changed, but requiring `league/flysystem` package now seems to work:
```
composer create-project --prefer-dist laravel/lumen lumen-test && cd lumen-test && composer require --dev barryvdh/laravel-ide-helper league/flysystem && sed -i '' '19i\
\
$app->register(Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider::class);
' artisan && php artisan ide-helper:generate
```
Still an issue, though, you should not have to require another package only for this to work.

**Comment by ricklambrechts** [comment]
Thanks. 

Still an issue.
But  `composer require league/flysystem` still works.

**Comment by MagicShoebox** [comment]
Same initial error, but workaround leads to
```
In AuthManager.php line 97:
  Auth driver [api] for guard [api] is not defined.  
```

**Comment by mfn** [comment]
> I'm guessing the ide-helper assumes Auth classes have been registered rather than checking first.

Maybe unrelated, but I generally see this particular error when I've some kind of error in the code (shouldn't happen, but does). Like a syntax error in one of the many files or forget to register something correctly.

**Comment by judgej** [comment]
Lumen 5.8 does not seem to come with flysystem as a default dependency, so needs to be added separately. The local file logging, local file caching, local sessions, I guess don't use flysystem but just go directly to the local filesystem. This is in contract to laravel.

**Comment by sandcore-dev** [comment]
I got the same issue on a Lumen 5.7 project, `composer require league/flysystem --dev` fixed it.

I think adding Flysystem to the laravel-ide-helper composer.json would be sufficient, since the package is only used as a development dependency anyway.

**Comment by mfn** [comment]
But this package doesn't need it for Laravel so IMHO it shouldn't.

Another train of thought: if it's _required_ for Lumen, add it to the Lumen section in the readme. I think in general Lumen users are aware they need to jump through hoops. Support in 3rd party libraries compatible with Lumen will always lack a certain compatibility level because, as of today and to my knowledge, there's no way to properly test it (orchestra/testbench only targets Laravel and, though Lumen comes up every now and then, no concrete plans are happening).

**Comment by sandcore-dev** [comment]
> But this package doesn't need it for Laravel so IMHO it shouldn't.

That is because Laravel already has League\Flysystem as a dependency.

You are right that it is not specifically developed for Lumen, although I think my solution is pretty elegant. I'm OK with a mention in the readme though.

**Comment by mfn** [comment]
> But this package doesn't need it for Laravel so IMHO it shouldn't.

Actually, I'm not sure I'm right on this.

Of course this package "somehow" depends on it. It makes use of the Filesystem driver but we don't have an explicit dependency on the 3rd party `Local` driver.

So _maybe_ actually expressing this dependency somehow makes sense. Though I'm not sure what the proper solution is.

- `laravel/framework` has the explicit dependency on league/flysystem`
  - but lumen does not => it only depends on illuminate/filesystem => https://github.com/laravel/lumen-framework/blob/7372a1518dd129705fe46c4f4c1e91828f5a0601/composer.json#L29
- Packages don't depend on the framework but it's individual components
-  ide-helper itself correctly depends on `illuminate/filesystem`
  - and this one _has a suggests_ for `league/flysystem`

🤷‍♀️

**Comment by Alluuu** [comment]
I did the require league/flysystem and then just receive a next error:

In Repository.php line 636:
  Call to undefined method Illuminate\Cache\FileStore::refreshEventDispatcher()

**Comment by mfn** [comment]
@Alluuu Maybe I miss something, but you can elaborate how this related to ide-helper?

**Comment by Alluuu** [comment]
Hey @mfn  it was a follow-up to the previous issues, I too am on a fresh lumen install, tried getting ide-helper working, did the league/flysystem require and then after trying to run artisan ide-gelper:generate this was the next new error I received.

**Comment by mfn** [comment]
Ok, thanks for clarifying. I just found it odd this happens in some `Repository.php` 🤷‍♀️ That's why it felt unrelated…

**Comment by moltam** [comment]
Since 2.0 came out for `league/flysystem`, you need to require `1.x` version to access the missing adapter:
`composer require --dev league/flysystem ^1.0`.

**Comment by kamleshwebtech** [comment]
What is solution for Lumen 8.0 version for the same? Please suggest. Thanks a lot.

**Comment by developh** [comment]
thanks @moltam it works on lumen 8.2.3. @kamleshwebtech please try @moltam solution.

**Comment by pnhuyduy** [comment]
thanks @moltam it works like a charm.

**Comment by iamFoxx** [comment]
just run: **composer require league/flysystem ^1.1**

**Comment by PolisssCz** [comment]
**Polisss** _greets you_,
I took the liberty to prepare for you a complete tutorial on how to generate the **ide-helper.php** file.

### Creating a Lumen app called: MYlumen
```
composer create-project --prefer-dist laravel/lumen MYlumen
```
### Permission of facades
In the file: **bootstrap/app.php**

#### *In the section: Create The Application
### Uncomment:
* $app->withFacades(); 
* $app->withEloquent();

#### *In the section: Register Service Providers
#### Add code:
```
// Defined "ide-helper" namespace.
if ($app->environment() !== 'production') {
    $app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
}
```
### Uncomment:
* $app->register(App\Providers\AppServiceProvider::class);
* $app->register(App\Providers\AuthServiceProvider::class);

### Generating ide-helper
1)
```
composer require --dev barryvdh/laravel-ide-helper
```
2)
```
composer require league/flysystem ^1.1
```
3)
```
php artisan ide-helper:generate
```
## DONE! Have a good day :)

**Comment by summerKK** [comment]
> composer require --dev league/flysystem ^1.0

composer require --dev "league/flysystem:^1.0"
