### ISSUE TITLE
version 2.5.2 + latest laravel 5.7.13 generates code which is not valid for phpstan

### ISSUE THREAD

**Issue by victor-ivanov** [barryvdh/laravel-ide-helper#726]
I've created new project with
`composer create-project laravel/laravel blog`

added latest `ide-helper`
```
cd blog
composer require barryvdh/laravel-ide-helper
```
getting following code generated for `Request` facade `validate` and `hasValidSignature` methods
```
/**
 * 
 *
 * @static 
 */ 
public static function validate($rules, $params = null)
{
    return \Illuminate\Http\Request::Illuminate\Foundation\Providers\{closure}($rules, $params);
}

/**
 * 
 *
 * @static 
 */ 
public static function hasValidSignature($absolute = true)
{
    return \Illuminate\Http\Request::Illuminate\Foundation\Providers\{closure}($absolute);
}
```

phpstan fails to validate such code with error 
```
PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR), expecting ';' in .../_ide_helper.php
```

**Workaround**
It generates proper code with previous version of `laravel-ide-helper` `2.5.1`

```
public static function validate($rules, $params = null)
{
    return \Illuminate\Http\Request::validate($rules, $params);
}
public static function hasValidSignature($absolute = true)
{
    return \Illuminate\Http\Request::hasValidSignature($absolute);
}
```

**Comment by STayinloves** [comment]
Shared the same issue using ide-helper on dev-master

**Comment by adampatterson** [comment]
I just noticed that I can't click through on route class names to methods, or to the view file.

Also using IDE Helper version 2.5.2, latest laravel 5.7.13

I had previously tried IDE Helper 2.4.* and updated because it was not working.

**Comment by ondrejmirtes** [comment]
I recommend switching to Larastan.

**Comment by xlstefan** [comment]
@victor-ivanov can you test this with the v2.5.3?
I think this issue could be solved with new release.

**Comment by victor-ivanov** [comment]
Thanks guys! version `2.5.3` works for me
