### ISSUE TITLE
ide helper models wrong with gis field

### ISSUE THREAD

**Issue by Insua** [barryvdh/laravel-ide-helper#727]
Exception: Unknown database type point requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
Could not analyze class

**Comment by Davion-xiao** [comment]
I use MySQL57 and its connection is normal

**Comment by mfn** [comment]
You need to use `custom_db_types` for such cases

@barryvdh already supported, issue can be closed

**Comment by Insua** [comment]
> You need to use `custom_db_types` for such cases
> 
> @barryvdh already supported, issue can be closed

how to use custom_db_types?

**Comment by mfn** [comment]
@Insua please read the comment in the config file for `custom_db_types`; if you haven't updated/republished the configuration in a while, it may be missing.

Here's an example from a project of mine:
```php
    'custom_db_types' => [
        'postgresql' => [
            'jsonb' => 'string',
            '_int4' => 'array', //Map postgres "array of ints" type to array
        ],
```

I guess this config never made it into the README thus hard to discover.
