### ISSUE TITLE
Go To not working in route if group method uses as

### ISSUE THREAD

**Issue by sahnb** [barryvdh/laravel-ide-helper#729]
Go to not working by clt+b or clt+ click only in route file.
    //admin manage orders menu
  Route::get('orders', [
    'uses' => 'OrderController@orderListsContent',
    'as'   => 'admin.shop_orders_list'
  ])->middleware('verifyLoginPage', 'admin', 'sufficientPermission');

Note: in controller and view work perfectly.

**Comment by mfn** [comment]
Works for me, can click on `::get` and `->middleware`

Do you still have this issue?
