### ISSUE TITLE
Invalid _ide_helper.php generated after upgrade to v2.5.2

### ISSUE THREAD

**Issue by mikepsinn** [barryvdh/laravel-ide-helper#734]
```
        /**
         * 
         *
         * @static 
         */ 
        public static function validate($rules, $params = null)
        {
            return \Illuminate\Http\Request::Illuminate\Foundation\Providers\{closure}($rules, $params);
        }
        
        /**
         * 
         *
         * @static 
         */ 
        public static function hasValidSignature($absolute = true)
        {
            return \Illuminate\Http\Request::Illuminate\Foundation\Providers\{closure}($absolute);
        }
         
```

I use:
"barryvdh/laravel-ide-helper": "2.5.2",
"laravel/framework": "5.7.16"

I can verify that this bug was introduced in https://github.com/barryvdh/laravel-ide-helper/commit/981ff45b43e0cf808af0a5a5f40f6369e0e29499 as 2.5.1 works.  

(However, 2.5.1 has the "already defined" warnings in PHPStorm.)

**Comment by xlstefan** [comment]
@mikepsinn can you test this with the v2.5.3?
I think this issue is solved.

**Comment by mikepsinn** [comment]
@xlstefan Yes, it works great now!  Thanks so much!  :D
