### ISSUE TITLE
Click to view or controller is not working.

### ISSUE THREAD

**Issue by adampatterson** [barryvdh/laravel-ide-helper#737]
After updating to Laravel 5.7 Click through to view or controller does not work.

I have tried reinstalling, confirming the installation steps, I am using IDE Helper ^2.5

Click to Controller from s route is **not working** .
```
Route::post('/path', 'Controller@index');
```

Click to view from a controller is **not working**.
```
return \View::make('path.to.view');
```

Click to view from within a view **is working**.
```
@include('path.to.view')
```

**Comment by adampatterson** [comment]
@xlstefan Thanks so much!

**Comment by xlstefan** [comment]
You are welcome @adampatterson 😄 
Should this issue be closed now or when new release is released? @barryvdh

**Comment by adampatterson** [comment]
I was going to close it but since it was referenced I left it open.

**Comment by mfn** [comment]
@barryvdh fix was already released, issue can be closed :}

**Comment by adampatterson** [comment]
Sad, I Googled the same issue and found my old Issue.
