### ISSUE TITLE
PhpStorm, IDE helper does not recognize model methods

### ISSUE THREAD

**Issue by Dunrar** [barryvdh/laravel-ide-helper#738]
The IDE helper does not recognize method calls on models. For example, if I get a user via find or fail, like 
`$employee = User::findOrFail($id);` and then call a Method, like `$expiringQualifications = $employee->expiringQualifications()->pluck('name', 'id');`, the IDE helper does not recognize the expiringQualifications() Method. It tells me:

> Method 'expiringQualifications' not found in \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model

**Comment by MarkWisselink** [comment]
had the same issue; fixed it by replacing the class definition of 'Eloquent extends \Illuminate\Database\Eloquent\Model' with 'class Eloquent extends \Illuminate\Database\Eloquent\Model {}'
into it's own namespace, and then moving the old definition inside a new namespace block like:
`namespace Illuminate\Database\Eloquent {
    class Model {
        //the class definition
    }
}`
obviously this is a static fix; and should be fixed properly in the parser

**Comment by mfn** [comment]
Works for me in PhpStorm with the latest version:

![image](https://user-images.githubusercontent.com/87493/71750230-19addf80-2e78-11ea-9cb7-fc382cf42305.png)

`findOrFail` is generated as:
```php
            /**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array $columns
             * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static|static[] 
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
             * @static 
             */ 
            public static function findOrFail($id, $columns = [])
```

The `static` makes this work.
