### ISSUE TITLE
Syntax errors in _ide_helper.php

### ISSUE THREAD

**Issue by xlstefan** [barryvdh/laravel-ide-helper#739]
This pull request (https://github.com/barryvdh/laravel-ide-helper/pull/736) fixed most of the syntax errors but not all.
There are still syntax errors bellow you can see details.
Commit hash: https://github.com/barryvdh/laravel-ide-helper/commit/99226c92b72b02bf60d9b339fdf9f446d5d9921d
Possible related issues: #734 , #726 

Error message: **Method with this name already defined in this class**
Only in these 4 methods it's shown.

Some more details about packages which I am using:

>     "require": {
>         "php": "^7.1.3",
>         "backpack/crud": "^3.5",
>         "bensampo/laravel-enum": "^1.16",
>         "beyondcode/laravel-self-diagnosis": "1.0.2",
>         "doctrine/dbal": "^2.5",
>         "fideloper/proxy": "^4.0",
>         "laravel/framework": "5.7.*",
>         "laravel/horizon": "^1.4",
>         "laravel/telescope": "^1.0",
>         "laravel/tinker": "^1.0",
>         "laravelcollective/html": "^5.4.0",
>         "predis/predis": "^1.1",
>         "ext-json": "*"
>     },
>     "require-dev": {
>         "backpack/generators": "^1.2",
>         "barryvdh/laravel-debugbar": "^3.2",
>         "barryvdh/laravel-ide-helper": "dev-master#99226c9",
>         "filp/whoops": "^2.0",
>         "fzaninotto/faker": "^1.4",
>         "laracasts/generators": "dev-master",
>         "laravel/homestead": "v7.12.0",
>         "mockery/mockery": "^1.0",
>         "nunomaduro/collision": "^2.0",
>         "phpunit/phpunit": "^7.0"
>     }

```
         /**
         * Get an array of all files in a directory.
         *
         * @param string $directory
         * @param bool $hidden
         * @return \Symfony\Component\Finder\SplFileInfo[] 
         * @static 
         */ 
        public static function files($directory, $hidden = false)
        {
            return \Illuminate\Filesystem\Filesystem::files($directory, $hidden);
        }
        
        /**
         * Get all of the files from the given directory (recursive).
         *
         * @param string $directory
         * @param bool $hidden
         * @return \Symfony\Component\Finder\SplFileInfo[] 
         * @static 
         */ 
        public static function allFiles($directory, $hidden = false)
        {
            return \Illuminate\Filesystem\Filesystem::allFiles($directory, $hidden);
        }

        /**
         * 
         *
         * @static 
         */ 
        public static function validate($rules, $params = null)
        {
            return \Illuminate\Http\Request::validate($rules, $params);
        }
        
        /**
         * 
         *
         * @static 
         */ 
        public static function hasValidSignature($absolute = true)
        {
            return \Illuminate\Http\Request::hasValidSignature($absolute);
        }

```

**Comment by xlstefan** [comment]
#740 solved syntax errors just for methods **validate** and **hasValidSignature** .

**Comment by JeppeKnockaert** [comment]
The problem with files and allFiles is linked to an issue in reflection-docblock, I will do a pull request there to fix these functions too.

**Comment by xlstefan** [comment]
Great @JeppeKnockaert, thanks for support and quick replies!

**Comment by barryvdh** [comment]
Can you try with the latest version?

**Comment by xlstefan** [comment]
I already introduced those changes manually (by editing vendor files with changes from the PRs) and it worked correctly.
Now I tested latest release, updated the package version to the latest and **it works as expected**.

*Since this issue is solved I will also close the issue.*
Thanks for quick replies! @barryvdh @JeppeKnockaert
