### ISSUE TITLE
Model::find and Model::findOrfail

### ISSUE THREAD

**Issue by moradgholi** [barryvdh/laravel-ide-helper#74]
Hi,

This project is amazing ! 
but today i realized there is no auto suggestions for these two : 
Model::find and Model::findOrfail

Can i add them manually ?

**Comment by abderrahmane-tj** [comment]
hi there. They are not working for me in Laravel 5. I had to manually add :

     * @method static \Illuminate\Database\Query\Builder|\App\Article findOrFail
to my Article Model to make sure PHPStorm recognized it in my controller when I do this : 

    $article = Article::findOrFail($id);
    $input = Request::all();
    $article->update($input);

**Comment by ababkov** [comment]
@abderrahmane-tj Try getting your model to extend the \Eloquent alias instead.

@barryvdh It _might_ be nice if the model helpers generated Eloquent\Builder method stubs for models that extend Illuminate\Database\Eloquent\Model.

**Comment by paslandau** [comment]
Extending `\Eloquent` does the trick, although I feel a little uncomfortable to use this workaround as it couples my models to a "helper" package. 

@barryvdh , any update on

    @barryvdh It might be nice if the model helpers generated Eloquent\Builder method stubs for models that extend Illuminate\Database\Eloquent\Model.
?

Cheers
Pascal

**Comment by mborges-ptc** [comment]
same issue here
