### ISSUE TITLE
request()->validate(); Not found

### ISSUE THREAD

**Issue by awais-vteams** [barryvdh/laravel-ide-helper#744]
request()->validate(); is not handling in latest Laravel 5.7.15. It's showing undefined.

**Comment by apintocr** [comment]
I can also confirm this.
Using latest Laravel on a fresh setup.

**Comment by SalemCode8** [comment]
use $this->validate($request, $rule);

in the controller instead

**Comment by apintocr** [comment]
Thank you.
I understand the workarounds, I was only reporting an issue :)

ᐧ

**Comment by hackel** [comment]
Dupe of #608.

**Comment by mfn** [comment]
This works since Laravel 6 because it was added in the framework phpdoc => https://github.com/laravel/framework/pull/30975

@barryvdh issue can be closed :}
