### ISSUE TITLE
Support for splat operator

### ISSUE THREAD

**Issue by TivoSoho** [barryvdh/laravel-ide-helper#747]
Currently splat operator has to be fixed manually every time it runs as "..$param" gets turned into "$param = null"

**Comment by lkloon123** [comment]
anyone has idea how this can be implement?

**Comment by ngmy** [comment]
@TivoSoho @lkloon123 

Hi,

I implemented it in pull request #860.
And the merged stable version [v2.6.7](https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.6.7) has been released.

**Comment by mfn** [comment]
@barryvdh last comment is correct, this was already fixed => issue can be closed :}
