### ISSUE TITLE
Exception: Facade does not implement getFacadeAccessor method

### ISSUE THREAD

**Issue by ddmo** [barryvdh/laravel-ide-helper#750]
Hi, I got this error running artisan ide-helper:generate.
The error is on a custom Facade class.
This my app.php:

'aliases' => [
...
        'Util'          => App\Facades\Util::class,
...
]

Whats wrong?
Thanks
Stefano

**Comment by mfn** [comment]
The exception comes from `\Illuminate\Support\Facades\Facade::getFacadeAccessor`, your code isn't correct because you didn't implement `getFacadeAccessor` in your own Facade, as the exception says.

This is unrelated to this package

@barryvdh bug in the user code, issue can be closed :}
