### ISSUE TITLE
PHPStorm - can't install from Manage Composer Dependencies

### ISSUE THREAD

**Issue by ejblom** [barryvdh/laravel-ide-helper#752]
Dear developers,

After some years of working with Sublime I've purchased IntelliJ Ultimate. I installed PHP for Windows, set the ini file, installed some plugins (Laravel/PHP) in IntelliJ and imported my Laravel 5.4 with Spark integration. 

Via Tools/Composer/Manage Dependencies I tried to installed the barryvdh/laravel-ide-helper but I can't get it installed:

     Failed to install barryvdh/laravel-ide-helper

The show output tells me:

     [InvalidArgumentException]
     Could not find package barryvdh/laravel-ide-helper in a version matchin 2.6-dev
     require - lots of options

I tried several versions although i was just recently told I should use 2.x since the higher versions are for Laravel 5.5. Is there something I didn't set properly in IntelliJ?

**Comment by barryvdh** [comment]
Can you install it with the command line? Composer require barryvdh/laravel-ide-helper:2.x

**Comment by ejblom** [comment]
I installed it on my linux machine which I used for developing:

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Installing symfony/filesystem (v4.2.1): Downloading (100%)
  - Installing seld/phar-utils (1.0.1): Downloading (100%)
  - Installing seld/jsonlint (1.7.1): Downloading (100%)
  - Installing justinrainbow/json-schema (5.2.7): Downloading (100%)
  - Installing composer/xdebug-handler (1.3.1): Downloading (100%)
  - Installing composer/spdx-licenses (1.5.0): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing composer/ca-bundle (1.1.3): Downloading (100%)
  - Installing composer/composer (1.8.0): Downloading (100%)
  - Installing barryvdh/reflection-docblock (v2.0.6): Downloading (100%)
  - Installing barryvdh/laravel-ide-helper (v2.5.3): Downloading (100%)
composer/composer suggests installing ext-zip (Enabling the zip extension allows you to unzip archives)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
barryvdh/laravel-ide-helper suggests installing doctrine/dbal (Load information from the database about models for phpdocs (~2.3))
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: fideloper/proxy
Discovered Package: graham-campbell/flysystem
Discovered Package: intervention/image
Discovered Package: laravel/cashier
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: uxweb/sweet-alert
Package manifest generated successfully.

It has then installed 2.5.3. I commited and pushed the changes and pulled them into my windows machine. Next, I tried installing it:

Failed to update barryvdh/laravel-ide-helper Scripts was cancelled
The dompdf v0.8.2 required ext-gd so I activated that by uncommenting extension=gd2 from php.ini
It was then complaining about curl, fileinfo, soap, 

After that I looked like a regular composer install but it did fail after

Writing lcok file
Generating optimized autoload files


[RuntimeException]
Could not scan for classes inside "database/factories" which does not appear to be a file nor a folder

So I created the database/factories folder (it indeed was not there)

Redid composer thing and it seems to work !!! (ofcourse after an IDE restart!)

Thanks!
