### ISSUE TITLE
auth()->user() does not have methods in User model

### ISSUE THREAD

**Issue by Nothing-Works** [barryvdh/laravel-ide-helper#755]
Hi I have trouble with autocompleting methods in `User` model when I use `auth()->user()`

so I have a method `foo` in `User` model, and when I use `auth()->user()` to get the `login user` instance I do not have the `foo` method show up. 

can some one tell me what congfig I need to do?

**Comment by wvdongen** [comment]
Got the same problem, without a solution so far.

**Comment by HansSchouten** [comment]
I am using `auth()->user()` for checking permissions in combination with spatie/laravel-permissions. `php artisan ide-helper:models` tries to call a member function on `null` in my use case as well.

**Comment by wisemanta** [comment]
I am able to get this working if I edit
`vendor/laravel/framework/src/Illuminate/Support/Facades/Auth.php`
and delete line 9 in the docblock:
` * @method static \Illuminate\Contracts\Auth\Authenticatable|null user()`

Then it pulls out the autocomplete information from the _ide_helper.php
`Class Auth` `function user()` that has a doc block that returns
`\App\Models\User`

**Comment by Nothing-Works** [comment]
@wisemanta  so you mean you changed the Laravel source code?

**Comment by jonnywilliamson** [comment]
Wondering if anyone has a solution that doesn't involve editing a file in the vendor directory

**Comment by p4rse** [comment]
I am using `Auth::user()` for now and it works with the autocompletion...

But I would like to use `auth()->user()`


Hope somebody come with a solution for that!

**Comment by jadamec** [comment]
I've still the same issue... Thanks!

**Comment by Shujee** [comment]
Can still see this problem as of Laravel 8.30.1. Both `auth()->user()` and `Auth::user()` do not show code-completion for User model properties and functions.

I'm using VSCode 1.56.2 and have already generated doc-blocks using IDE Helper package.

**Comment by khanakia** [comment]
Any solutions ?

**Comment by kdlayton** [comment]
I have renamed User to PracticeUser in auth.php
On this statementUnderfined method on Auth->user()->relationMethod on user.
I have renamed User to PracticeUser in auth.php

**Comment by kdlayton** [comment]
I have same problem 'Undefined method'
I have renamed User model to PracticeUser in auth.php

Project uses Laravel 10.13.2 and Inertia/Vue3 1.0.7

Here is an abstraction of my code 
inertia:render('_myroute_', [ '_list_' => Auth:user() ->_relationMethodOnPracticeUserModel_()

The method _relationMethodOnPracticeUserModel_ is flagged as Undefined Method.

I have verified that Auth:user() is an instance of PracticeUser
I have verified that the method  _relationMethodOnPracticeUserModel_ is defined on the PracticeUser model.

Any Solutions?

**Comment by kdlayton** [comment]
I created a comment last week, but no reponse.

Auth::user()->method(), where method() names is the name of a relation
In Laravel Breeze project, Laravel version 101.3.2, 
   - method() is flagged in VS Code as Undefined method.
   - No problem calling the relation method in Tinker on an instance of User model.
In a Laravel project, without Breeze,  Laravel version 9.46.0, method() in VS Code is *not* flagged as Undefined method.

Would appreciate some feedback.

**Comment by bdlowery** [comment]
Yep, same problem here. `auth()->check()` `auth()->user()` etc do not work with any editor other than phpstorm, intelephense throws a undefined method error.
