### ISSUE TITLE
model_locations option does not works with model parameter

### ISSUE THREAD

**Issue by delmicio** [barryvdh/laravel-ide-helper#757]
Hi, thank you for this package. I've found an issue.
`model_locations` option in the ide-helper.php file only works when running all models like
`php artisan ide-helper:models`

but if you want to use it for one model is not consider
`php artisan ide-helper:models Mymodel` DOES NOT WORK as it doesn't use model_locations option
`php artisan ide-helper:models App\Models\Mymodel` WORKS

Expected:
model_locations=App\Models
`php artisan ide-helper:models Mymodel` should work with file App\Models\Mymodel

**Comment by delmicio** [comment]
#688

**Comment by hldh214** [comment]
And there is another issue:

```
app/Models
├── Foo
│   ├── Foo.php
├── Common
│   ├── FooBase.php
│   └── BarBase.php
├── Bar
│   ├── Bar.php
└── Traits
    └── ModelHelper.php
```

`model_locations` is `app` by default and we can use `--dir` option to add another location
the question is: how can i only proceed models file under `app/Models/Foo` directory
but not others?

**Comment by mfn** [comment]
Currently the model requires the FQCN. I don' think this should be change, you could have two models with the same name in different namespace but only mean one of them to be generated.

@barryvdh personal opinion, but I vote for not encouraging to support this :}
