### ISSUE TITLE
[BUG] [ENHANCEMENT] Use `final class`

### ISSUE THREAD

**Issue by ttomdewit** [barryvdh/laravel-ide-helper#766]
When using a `final` statement in a class, the IDE helper will paste it's class DocBlock after the `final` keyword, breaking the code.

I'm assuming that the IDE helper is looking for the `class` keyword, putting that on a new line and then pasting the DocBlock's contents on the previous line.

If that's the case, again I'm assuming, could we opt to include the `final` keyword?

Thank you for your time,

Tom de Wit

PS kind regards to the entire office!

Code example:

```php
final /**
 * Domain\Product\Models\Product
 *
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product query()
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Product extends Model
{
}
```

Desired output:

```php
/**
 * Domain\Product\Models\Product
 *
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product query()
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Domain\Product\Models\Product whereUpdatedAt($value)
 * @mixin \Eloquent
 */
final class Product extends Model
{
}
```

**Comment by Gummibeer** [comment]
Hey all,
I can second this issue and that it still exists.
I will check if I can provide a fix PR.

**Comment by rela589n** [comment]
It is still not working properly

**Comment by Gummibeer** [comment]
@rela589n what's your exactly issue?
Which command and what's the in- and output?

**Comment by rela589n** [comment]
![Screenshot from 2020-06-26 12-21-18](https://user-images.githubusercontent.com/41589422/85842357-46e4a600-b7a8-11ea-9300-99217a5aff3f.png)
![Screenshot from 2020-06-26 12-24-08](https://user-images.githubusercontent.com/41589422/85842365-4815d300-b7a8-11ea-8d0f-c90a76ccb65a.png)
![Screenshot from 2020-06-26 12-24-11](https://user-images.githubusercontent.com/41589422/85842366-48ae6980-b7a8-11ea-917b-d06bfe1771e9.png)

**Comment by ttomdewit** [comment]
@rela589n @Gummibeer Please note there hasn't been a new release since April 22nd.
