### ISSUE TITLE
Exception: stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### ISSUE THREAD

**Issue by andreshg112** [barryvdh/laravel-ide-helper#770]
I'm getting this error with `ide-helper v2.6.0 and v.2.5`,. It was working some hours ago.
![imagen](https://user-images.githubusercontent.com/15859884/53453291-acc4f000-39f1-11e9-88ad-da73b87887f9.png)

**Comment by juliuscaesarnl** [comment]
This exception is given when using PHP 7.3. I use Homestead and solved it by executing
`php7.2 artisan ide-helper:models`

I don't know what your situation is, but either wait for a bugfix or use PHP 7.2.

**Comment by andreshg112** [comment]
@juliuscaesarnl yes, that was the problem. I downgraded to PHP 7.2. Thank you!

**Comment by juliuscaesarnl** [comment]
@andreshg112 You're welcome! I suggest waiting with 7.3 since there are still a bunch of issues when using it with Xdebug, for example.

**Comment by altraWeb** [comment]
For me its working PHP 7.3.2 with Xdebug v2.7.0rc1 on Laravel 5.7

But same setup on Laravel 5.8 it's not working. Is there an issue with Laravel 5.8??

**Comment by starvsion** [comment]
I got it fixed, by editing: Barryvdh\LaravelIdeHelper\Console\ModelsCommand , line 483

Before: 
```php
if (stripos($impl, $type) || stripos($impl, $type) !== false) {

```

After:
```php
if ($type && (stripos($impl, (string)$type) || stripos($impl, $type) !== false)) {
```
