### ISSUE TITLE
PHP 7.3 bugfix

### ISSUE THREAD

**Issue by neoteknic** [barryvdh/laravel-ide-helper#771]
Can you fix php 7.3 bug ? 
#770

**Comment by neoteknic** [comment]
Just add (string) l483 src/Console/ModelsCommand.php to fix
stripos($impl, (string)$type)

**Comment by Nothing-Works** [comment]
same problem

**Comment by mfn** [comment]
@barryvdh this code does not exist in this form anymore and 7.3 works, issue can be closed :}

**Comment by mfn** [comment]
This was PR which fixed it => https://github.com/barryvdh/laravel-ide-helper/pull/774
