### ISSUE TITLE
"composer install --dev barryvdh/laravel-ide-helper" not pulling current version.

### ISSUE THREAD

**Issue by RalphMRivera** [barryvdh/laravel-ide-helper#775]
I'm trying to get the recent fix related to #774. I can see the changes in Github:  

https://github.com/barryvdh/laravel-ide-helper/blob/881f77156c37deea425caef6482783717c466e4f/src/Console/ModelsCommand.php#L483

But they are not in my local package. I deleted my `vendor` folder and purged the composer cache to re-install, but that did not solve the problem.

On my end the line still reads:
```
if (stripos($code, $search) || stripos($impl, $type) !== false) {
```

And I'm still getting the following error:

```
Exception: stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
Could not analyze class App\Models\User.
```

Any thoughts on why this is happening?

**Comment by KillermenBE** [comment]
@RalphMRivera: @barryvdh needs to tag a new release. In the meanwhile, you can use the dev-master to get the new version. Change your composer.json file to this:
`"barryvdh/laravel-ide-helper": "dev-master"`

And `composer update` to fix the issue

**Comment by barryvdh** [comment]
it's tagged.

**Comment by RalphMRivera** [comment]
Thanks so much!
