### ISSUE TITLE
pgsql tablename with schema

### ISSUE THREAD

**Issue by KFan95** [barryvdh/laravel-ide-helper#780]
I use postgresql, and schemas in it.

My table name is 'user' and it in 'main' schema

When i generate models ide-helper cannot generate field, because of table name 'main.user' readed as database name 'main' and table name 'user'

**Comment by mfn** [comment]
Where/how did you specify the schema _and_ the table in your configuration/model?

**Comment by KFan95** [comment]
> Where/how did you specify the schema _and_ the table in your configuration/model?

`class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'main.user';
    protected $primaryKey = 'user_id';
}`

**Comment by mfn** [comment]
Thanks!

**Comment by mfn** [comment]
@KFan95 can you test if https://github.com/barryvdh/laravel-ide-helper/pull/974 works for you?

**Comment by jhjm32087** [comment]
@mfn, This doesn't seem to work with SQL Server(MSSQL). As doctrine expects to have the following format database.table to query the correct database.

Temp fix, but not sure if its working as expected with postgres.
`
$originalTable = $table;
if (strpos($table, '.')) {
          list($database, $table) = explode('.', $table);
}`

SQL Server Issue(SCHEMA_NAME())
This will pull the current default schema, such as dbo which is not the intent
`
SELECT    col.name,
          type.name AS type,
          col.max_length AS length,
          ~col.is_nullable AS notnull,
          def.definition AS [default],
          col.scale,
          col.precision,
          col.is_identity AS autoincrement,
          col.collation_name AS collation,
          CAST(prop.value AS NVARCHAR(MAX)) AS comment -- CAST avoids driver error for sql_variant type
FROM      sys.columns AS col
              JOIN      sys.types AS type
                        ON        col.user_type_id = type.user_type_id
              JOIN      sys.objects AS obj
                        ON        col.object_id = obj.object_id
              JOIN      sys.schemas AS scm
                        ON        obj.schema_id = scm.schema_id
              LEFT JOIN sys.default_constraints def
                        ON        col.default_object_id = def.object_id
                            AND       col.object_id = def.parent_object_id
              LEFT JOIN sys.extended_properties AS prop
                        ON        obj.object_id = prop.major_id
                            AND       col.column_id = prop.minor_id
                            AND       prop.name = 'MS_Description'
WHERE     obj.type = 'U'
  AND       (obj.name = 'sales' AND scm.name = SCHEMA_NAME());`

SQL Server(Temp Fix)
`
SELECT    col.name,
          type.name AS type,
          col.max_length AS length,
          ~col.is_nullable AS notnull,
          def.definition AS [default],
          col.scale,
          col.precision,
          col.is_identity AS autoincrement,
          col.collation_name AS collation,
          CAST(prop.value AS NVARCHAR(MAX)) AS comment -- CAST avoids driver error for sql_variant type
FROM      sys.columns AS col
              JOIN      sys.types AS type
                        ON        col.user_type_id = type.user_type_id
              JOIN      sys.objects AS obj
                        ON        col.object_id = obj.object_id
              JOIN      sys.schemas AS scm
                        ON        obj.schema_id = scm.schema_id
              LEFT JOIN sys.default_constraints def
                        ON        col.default_object_id = def.object_id
                            AND       col.object_id = def.parent_object_id
              LEFT JOIN sys.extended_properties AS prop
                        ON        obj.object_id = prop.major_id
                            AND       col.column_id = prop.minor_id
                            AND       prop.name = 'MS_Description'
WHERE     obj.type = 'U'
  AND       (obj.name = 'sales' AND scm.name = 'core')
`

**Comment by mfn** [comment]
We're back to square one, my PR caused problems I closed it

**Comment by s3huber** [comment]
I'm actually having the exact same problems.

We are using more than one schema with a PostgreSQL database and as such we prefixed the tables with the schema name when defining the table in Eloquent model.
