### ISSUE TITLE
Laravel added aliases for 'Arr' and 'Str' no autocomplete from helper

### ISSUE THREAD

**Issue by dmason30** [barryvdh/laravel-ide-helper#784]
ide-helper version: 2.6.2

In Laravel 5.8.3 aliases were added for the `Arr` and `Str` classes by default: 

https://github.com/laravel/laravel/pull/4951

They are **not added as a `Facade`** though just `alias` of a `class`, **I assume this is the issue**:
```php
'Arr' => Illuminate\Support\Arr::class,
'Str' => Illuminate\Support\Str::class,
```

In `PHPStorm` I am not getting any autcomplete functions for these classes:
![image](https://user-images.githubusercontent.com/20278756/55096035-14359480-50b1-11e9-8e54-d8b3fd35da3f.png)

Do I need to create my own `Facade` for these classes?

---
**ide-helper.php**
The `ide-helper` outputs this in the `ide-helper.php` file:

```php
...
namespace Illuminate\Support { 

    class Arr {
         
    }

    class Str {
         
    }
 
}
...
namespace  { 
    ....

    class Arr extends \Illuminate\Support\Arr {}

    ....

    class Str extends \Illuminate\Support\Str {}

    ....
}
...
```

---

**Temporary solution**
I get autocomplete if I remove this section from the `ide-helper.php` but this file is regenerated often. 

```php
...
namespace Illuminate\Support { 

    class Arr {
         
    }

    class Str {
         
    }
 
}
```

**Comment by cbaconnier** [comment]
I also get errors in PHPstorm due to this issue, I guess.

![PHPstorm error](https://user-images.githubusercontent.com/4738184/57010427-d0c4cd80-6bfc-11e9-821b-64e9635896a5.png)

**Comment by pverhaert** [comment]
Use real-time facades: [https://laravel.com/docs/5.8/facades#real-time-facades](https://laravel.com/docs/5.8/facades#real-time-facades)
Just add **Facades\\** to the path.  
```php
'Arr' => Facades\Illuminate\Support\Arr::class,     
'Str' => Facades\Illuminate\Support\Str::class,
```
<img width="444" alt="Str" src="https://user-images.githubusercontent.com/6221502/57059867-7a689500-6cb7-11e9-880b-e2ddc39ea62e.png">

**Comment by liquid207** [comment]
@pverhaert 
There are some functions that don't work properly with your solution.
e.g.
```
class Arr
{
     public static function forget(&$array, $keys)
    {
     ...
    }
}
```
because `__callStatic` method in `Illuminate\Support\Facades\Facade` cannot pass reference parameters.

**Comment by barryvdh** [comment]
I guess they should only be added if they're a facade. In the case of these classes I would only expect a root class to extend the Support class.

**Comment by tminich** [comment]
> I guess they should only be added if they're a facade. In the case of these classes I would only expect a root class to extend the Support class.

Not quite sure if I understand what you mean, but they should be examined. They are macroable and the helper is able to pick those macros up.

**Comment by mfn** [comment]
With https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.8.1 there was recent improvements regarding macros
> Add support for macros of all macroable classes

But don't know how this works together with such classes which aren't "real" Facades 🤷‍♀️

**Comment by tminich** [comment]
> But don't know how this works together with such classes which aren't "real" Facades 🤷‍♀️

Sorry if I wasn't clear, what I meant that macros are indeed already working with Str and Arr (well, probably, I only have macros for Str). I just wanted to point that out so the helper wouldn't be updated to simply completely ignore them as there is value in examining and adding ide helpers for them despite not actually being Facades.
