### ISSUE TITLE
By default, the models within the app/models are scanned. Describe the error

### ISSUE THREAD

**Issue by chujc** [barryvdh/laravel-ide-helper#795]
Laravel needs to be executed
```bash
    php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config
```
Modify the
```php
      'model_locations' => array(
            'app/Models',
        ),
```
Student: not Lumen

**Comment by mfn** [comment]
Sorry but the description is not clear. What is the issue/error?

**Comment by chujc** [comment]
> Sorry but the description is not clear. What is the issue/error?

There's no problem with the lumen implementation 
```php
php artisan ide-helper:Models
```
Laravel runs into problems with execution，The configuration needs to be modified

**Comment by mfn** [comment]
@barryvdh can you update the issue title to mention Lumen? thanks!
