### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by keeloren** [barryvdh/laravel-ide-helper#796]
- brainmaestro/composer-git-hooks v2.6.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.5) does not satisfy that requirement.
    - brainmaestro/composer-git-hooks v2.6.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.5) does not satisfy that requirement.
    - brainmaestro/composer-git-hooks v2.6.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.5) does not satisfy that requirement.
    - Installation request for brainmaestro/composer-git-hooks (locked at v2.6.0) -> satisfiable by brainmaestro/composer-git-hooks[v2.6.0].

Can you upgrade php version to install success. Many thanks!

**Comment by mfn** [comment]
Did you report this to the wrong repository?

This talks about `brainmaestro/composer-git-hooks` and not `laravel-ide-helper`.

The version constraint of this package is `"php": ">=7"`

**Comment by mfn** [comment]
@barryvdh seems this was reported in the wrong repo, issue can be closed :}
