### ISSUE TITLE
Warning:(40, 57) Qualifier is unnecessary and can be removed

### ISSUE THREAD

**Issue by sergeByishimo** [barryvdh/laravel-ide-helper#800]
The inspection reports on fully qualified class names which can be shortened by adding the 'use' statement.

present value:
* @method static \Illuminate\Database\Eloquent\Builder|\App\Audit whereId($value)

we wish to be:
* @method static Builder|\App\Audit whereId($value)

**Comment by mfn** [comment]
This would mean that the ide-helper suddenly **also** has to mange the `use` imports (and doing that correctly, don't create multiple entries, etc), which may very well be out of scope.

I suggest to simply disable the inspection or ignore it.

I wouldn't count this as feature request unless someone actively wants to implement this.

**Comment by sergeByishimo** [comment]
yep got it thanks!! closing it
