### ISSUE TITLE
Builder::newModelQuery does not exist

### ISSUE THREAD

**Issue by Niksac** [barryvdh/laravel-ide-helper#808]
Hi,

I use Laravel 5.6 and tried to generate a helper file for my models.

`php artisan ide-helper:models App\Coach`

It returns
`Exception: Method Illuminate\Database\Query\Builder::newModelQuery does not exist.
Could not analyze class App\Coach.`

The Class is just a plain Laravel model
`class Coach extends Model {}`

Any hints how i can further examine or fix this?

**Comment by mfn** [comment]
Quick fix: downgrade to 2.6.1; only the latest 2.6.2 contains https://github.com/barryvdh/laravel-ide-helper/pull/782 which is triggering your problem.

**Comment by Niksac** [comment]
Works, thanks.
Is this problem known? Otherwise I will leave this open.

**Comment by mfn** [comment]
Given that per the `composer.json`, Laravel `"^5.5,<5.9",` is supposed to be supported, this issue should be considered a valid bug report.

**Comment by mfn** [comment]
Maybe @brendt can chime in who made https://github.com/barryvdh/laravel-ide-helper/pull/782 ?

**Comment by brendt** [comment]
Are you sure you're extending the Laravel model class?

`newModelQuery` is here: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Model.php#L965

I've been using `2.6.2` for months now, never encountered this problem myself in L5.6

**Comment by Niksac** [comment]
yes, I am extending `Illuminate\Database\Eloquent\Model`
