### ISSUE TITLE
RouteServiceProvider Configs are not loaded

### ISSUE THREAD

**Issue by meshack007** [barryvdh/laravel-ide-helper#809]
For instance if i am getting routes from a different route file and i have assigned a name prefix to the RouteServiceProvider methods for mapping, it fails to obtain the name prefix. It starts directly with names from the routes file.

**Comment by barryvdh** [comment]
Not sure how this is an issue with this library, we don't do anything with routes? Do you mean the phpstorm plugin instead?

**Comment by mfn** [comment]
Closing due to lack of feedback
