### ISSUE TITLE
Blade files show undefined functions

### ISSUE THREAD

**Issue by fbc** [barryvdh/laravel-ide-helper#810]
I can't figure out why no matter what I do, I can't get IDE HELPER working in the blade files as well.
[![by-default-2019-07-26-at-12-08-42-AM.png](https://i.postimg.cc/gcv6Mkwn/by-default-2019-07-26-at-12-08-42-AM.png)](https://postimg.cc/5j20yJSV)

**Comment by fbc** [comment]
Disregard. When I renamed my directory for some reason my composer.json file did not get pointed in phpstorm. So once I did that it all began working properly.. Thanks.. sorry for the confusion.

**Comment by hannanstd** [comment]
hi
i have this problem with function like route, mix, assets , ....
