### ISSUE TITLE
facing problem while deploying to heroku. 

### ISSUE THREAD

**Issue by inderjeet1313** [barryvdh/laravel-ide-helper#813]
remote:
remote:        In ProviderRepository.php line 208:
remote:
remote:          Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found
remote:
remote:
remote:        Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
remote:  !     WARNING: There was a class not found error in your code
remote: 
remote:  !     ERROR: Dependency installation failed!
remote:  !     
remote:  !     The 'composer install' process failed with an error. The cause
remote:  !     may be the download or installation of packages, or a pre- or
remote:  !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
remote:  !     in your 'composer.json'.
remote:  !     
remote:  !     Typical error cases are out-of-date or missing parts of code,
remote:  !     timeouts when making external connections, or memory limits.
remote:  !     
remote:  !     Check the above error output closely to determine the cause of
remote:  !     the problem, ensure the code you're pushing is functioning
remote:  !     properly, and that all local changes are committed correctly.
remote:  !     
remote:  !     For more information on builds for PHP on Heroku, refer to
remote:  !     https://devcenter.heroku.com/articles/php-support
remote:  !     
remote:  !     REMINDER: the following warnings were emitted during the build;
remote:  !     check the details above, as they may be related to this error:
remote:  !     - There was a class not found error in your code
remote:
remote:  !     Push rejected, failed to compile PHP app.
remote:
remote:  !     Push failed

**Comment by mfn** [comment]
This is not a ide-helper issue/bug.

Please tread the link provided by Heroku => https://devcenter.heroku.com/articles/php-support , it says
> Heroku will not install development dependencies from the require-dev section of composer.json

Very likely, and correctly so, you've installed ide-helper as a **dev** dependency and thus it's not available in production.

You have multiple options, if you are not using any ide-helper functionality in production:
1. remove hardcoded reference to the service provider, the latest version of ide helper uses Laravels auto-discovered
2. or only conditionally reference it when `APP_ENV`is not production
3. or move the composer dependency into `require` instead of `require-dev`

This list is weighted from most preferred to least preferred solution IMHO :-)

**Comment by mblarsen** [comment]
I went with a combination of 1 and 2:

In `composer.json`:

```json
    "extra": {
        "laravel": {
            "dont-discover": [
                "barryvdh/laravel-ide-helper"
            ]
        }
    },
```

and then in `AppServiceProvider.php`:

```php
    public function register()
    {
        if ($this->app->environment() !== 'production') {
            $this->app->register(IdeHelperServiceProvider::class);
        }
    }
```

**Comment by mfn** [comment]
@barryvdh solution was provided, there's nothing this package can do if people manually register and and then don't install dependencies, issue can be closed :}

**Comment by fgilio** [comment]
Had this problem as well, the solution was deleting those cache files right before installing composer dependencies and using artisan cache commands:
```bash
- rm ./bootstrap/cache/services.php
- rm ./bootstrap/cache/packages.php
```

**Comment by nsra** [comment]
just `composer update` solved me
