### ISSUE TITLE
Bug while generating with custom getAttribute  mutator

### ISSUE THREAD

**Issue by FondueBug** [barryvdh/laravel-ide-helper#814]
I'm trying to implement magic getter that should return a enumeration.
A sample that does not work:

```php
    public function getEntityTypeAttribute($value): EntityType
    {
        return new EntityType($value);
    }
```

While running ide-helper model generator i'm getting following:

``
Exception: Value '' is not part of the enum School\Shared\Enumeration\EntityType
Could not analyze class School\Shared\Models\User.
``

But when I change getter to :

```php
    public function getEntityTypeAttribute($value)
    {
        return $value;
    }
```

Generator works.
I only experienced this issue on getAttribute.
Any ideas about this issue? Thanks :)

**Comment by mfn** [comment]
The exception is thrown from your own `EntityType` class. Like, if the getter would be called but with no value passed it. 

The code which analyzes the getters is in `\Barryvdh\LaravelIdeHelper\Console\ModelsCommand::getPropertiesFromMethods`:
```php
                    //Magic get<name>Attribute
                    $name = Str::snake(substr($method, 3, -9));
                    if (!empty($name)) {
                        $reflection = new \ReflectionMethod($model, $method);
                        $type = $this->getReturnTypeFromDocBlock($reflection);
                        $this->setProperty($name, $type, true, null);
                    }
```
There's not much going on and I wouldn't see why something like this would happen?

Please re-throw the exception caught in Line 220 of `src/Console/ModelsCommand.php` or use other means to debug _where/how exactly_ this is triggered:
```php
                } catch (\Throwable $e) {
                    // ADD THIS SO IT BUBBLES AND SHOWS THE STACKTRACE TO YOU
                    throw $e;
                    $this->error("Exception: " . $e->getMessage() . "\nCould not analyze class $name.");
                }
```

**Comment by FondueBug** [comment]
Im using following package to manage my [enumerations:](https://github.com/myclabs/php-enum)


I did added throw and I get following:
``

   UnexpectedValueException  : Value '' is not part of the enum School\Shared\Enumeration\EntityType

  at /Users/***/Documents/monorepo/system/vendor/myclabs/php-enum/src/Enum.php:48
    44|             $value = $value->getValue();
    45|         }
    46| 
    47|         if (!$this->isValid($value)) {
  > 48|             throw new \UnexpectedValueException("Value '$value' is not part of the enum " . \get_called_class());
    49|         }
    50| 
    51|         $this->value = $value;
    52|     }

  Exception trace:

  1   MyCLabs\Enum\Enum::__construct()
      /Users/***/Documents/monorepo/packages/shared/src/Models/User.php:89

  2   School\Shared\Models\User::getEntityTypeAttribute()
      /Users/***/Documents/monorepo/system/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:452

  Please use the argument -v to see more details.
MacBook-Pro-van-MacBook:system ****$ 

```

This error is logic because somehow the value that is being passed to the constructor is null.
Thats why the enumeration is throwing error.
However i do not understand why it is a problem in ide-helper.

**Comment by FondueBug** [comment]
I did fix one problem where the $value is nullable by adding default ``entity_type`` 
to model:
```php
 protected $attributes = [
        'entity_type' => EntityType::SCHOOL_WORKER,
    ];
```

The problem that I'm facing now:

```

   ErrorException  : array_key_exists(): The first argument should be either a string or an integer

  at /Users/***/Documents/monorepo/system/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151
    147|         if ($array instanceof ArrayAccess) {
    148|             return $array->offsetExists($key);
    149|         }
    150| 
  > 151|         return array_key_exists($key, $array);
    152|     }
    153| 
    154|     /**
    155|      * Return the first element in an array passing a given truth test.

  Exception trace:

  1   array_key_exists(Object(School\Shared\Enumeration\EntityType), ["School\Shared\Models\School", "School\Shared\Models\SchoolWorker"])
      /Users/***/Documents/monorepo/system/vendor/laravel/framework/src/Illuminate/Support/Arr.php:151

  2   Illuminate\Support\Arr::exists(["School\Shared\Models\School", "School\Shared\Models\SchoolWorker"], Object(School\Shared\Enumeration\EntityType))
      /Users/***/Documents/monorepo/system/vendor/laravel/framework/src/Illuminate/Support/Arr.php:292

  Please use the argument -v to see more details.
```

**Comment by mfn** [comment]
> Please use the argument -v to see more details.

It would be helpful to see more of the trace.

**Comment by mfn** [comment]
@barryvdh due to lack of feedback I suggest to close this one
