### ISSUE TITLE
Laravel v6?

### ISSUE THREAD

**Issue by MatanYadaev** [barryvdh/laravel-ide-helper#815]
I'm using Laravel v6, can't install the package.

**Comment by barryvdh** [comment]
Fixed in https://github.com/barryvdh/laravel-ide-helper/commit/7b4cef1ea424b92c95e5e858007b01228921de52

**Comment by MatanYadaev** [comment]
@barryvdh When do you think you will publish this version?

**Comment by barryvdh** [comment]
When v6 releases probably
