### ISSUE TITLE
Monolog 2.0 compatibility

### ISSUE THREAD

**Issue by kbond** [barryvdh/laravel-ide-helper#818]
In monolog 2.0, the `Monolog\Logger` has removed the `add` prefix from it's logging methods. This causes an issue when running the `ide-helper:generate` command with the default package config:

https://github.com/barryvdh/laravel-ide-helper/blob/1b15d2930b465eb1aec761edc220f122e283ae1a/config/ide-helper.php#L101

The per-project solution is to publish the config and remove the `add` prefix.

I'm not sure what the best solution is for the default package config. We could check the installed version of monolog and change the config based on that... If this is desired, I can make a PR.

**Comment by NikitosGolubev** [comment]
Yeah, I just faced with the same problem. Installed laravel 6, started a new project, but ide-helper:generate dropped me an error.

**Comment by barryvdh** [comment]
Perhaps to just remove these.
