### ISSUE TITLE
php artisan ide-helper:meta not working in Laravel 6

### ISSUE THREAD

**Issue by araeuchle** [barryvdh/laravel-ide-helper#821]
Hey,
just installed a fresh Laravel 6 project. The command php artisan ide-helper:meta always worked nicely, but now it doesnt work. 

i get the following error message:

  Symfony\Component\Debug\Exception\FatalErrorException  : Declaration of Facade\Ignition\Logger\FlareHandler::write(array $report) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void

  at /Users/blackbits/projects/eweb-api/vendor/facade/ignition/src/Logger/FlareHandler.php:12
     8| use Facade\Ignition\Ignition;
     9| use Facade\Ignition\Tabs\Tab;
    10| use Monolog\Handler\AbstractProcessingHandler;
    11| 
  > 12| class FlareHandler extends AbstractProcessingHandler
    13| {
    14|     /** @var \Facade\FlareClient\Flare */
    15|     protected $flare;
    16| 

   Whoops\Exception\ErrorException  : Declaration of Facade\Ignition\Logger\FlareHandler::write(array $report) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void

  at /Users/blackbits/projects/eweb-api/vendor/facade/ignition/src/Logger/FlareHandler.php:12
     8| use Facade\Ignition\Ignition;
     9| use Facade\Ignition\Tabs\Tab;
    10| use Monolog\Handler\AbstractProcessingHandler;
    11| 
  > 12| class FlareHandler extends AbstractProcessingHandler
    13| {
    14|     /** @var \Facade\FlareClient\Flare */
    15|     protected $flare;
    16| 

  Exception trace:

  1   Whoops\Run::handleError("Declaration of Facade\Ignition\Logger\FlareHandler::write(array $report) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void", "/Users/blackbits/projects/eweb-api/vendor/facade/ignition/src/Logger/FlareHandler.php")
      /Users/blackbits/projects/eweb-api/vendor/filp/whoops/src/Whoops/Run.php:433

  2   Whoops\Run::handleShutdown()
      [internal]:0

Can u please have a look at this?

**Comment by barryvdh** [comment]
Is this for my package?

**Comment by mfn** [comment]
IMHO nope, that's related to https://github.com/facade/ignition
