### ISSUE TITLE
Error while installing in Lumen v6.0.2

### ISSUE THREAD

**Issue by K2ouMais** [barryvdh/laravel-ide-helper#829]
Hello,

I followed the installation instructions to install ide-helper in Lumen API, but I am getting an error while trying to generate files.

When trying to run the command "php artisan ide-helper:generate" I get the error " There are no commands defined in the "ide-helper" namespace."

Thanks in advance for your help.

**Comment by benyaminl** [comment]
Have you change the env to debug?

**Comment by MetaiR** [comment]
I have the same problem and env file is set currectly

**Comment by simplenotezy** [comment]
What was the solution @K2ouMais?

**Comment by K2ouMais** [comment]
Back in the time I couldn't fix it.

I used Laravel instead of Lumen.

If you can just use Laravel instead, there is no reason anymore for using Lumen right now. Laravel is quick enough with the latest versions.
