### ISSUE TITLE
add to phpdoc of Eloquent's when() return self

### ISSUE THREAD

**Issue by fey** [barryvdh/laravel-ide-helper#839]
```
            // ..
             * @return self
             * @static
             */
            public static function when()
            {
            }
```

Instead of `* @return mixed`

**Comment by fey** [comment]
![with_self](https://user-images.githubusercontent.com/697178/67571201-c66b3280-f74c-11e9-95b8-85e845705aee.png) - with `@return self` VSCode suggest new methods

![Screenshot_2019-10-25_17-25-40](https://user-images.githubusercontent.com/697178/67571220-db47c600-f74c-11e9-8b32-18826c02a24f.png) - no suggestions

**Comment by fey** [comment]
upd: self or $this

**Comment by barryvdh** [comment]
Open for PR if this can done cleanly. But I think this should be fixed with the phpdoc in Laravel itself.
