### ISSUE TITLE
File permission error when running meta command

### ISSUE THREAD

**Issue by mrkatz** [barryvdh/laravel-ide-helper#843]
receiving this error when running command,

php artisan ide-helper:meta

   ErrorException  : file_put_contents(.phpstorm.meta.php): failed to open stream: Permission denied

  at C:\Programming\Websites\Demo\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:122
    118|      * @return int|bool
    119|      */
    120|     public function put($path, $contents, $lock = false)
    121|     {
  > 122|         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    123|     }
    124|
    125|     /**
    126|      * Write the contents of a file, replacing it atomically if it already exists.

  Exception trace:

  1   file_put_contents(".phpstorm.meta.php", "<?php
// @formatter:off

namespace PHPSTORM_META {

   /**
    * PhpStorm Meta file, to provide autocomplete information for PhpStorm

**Comment by netpok** [comment]
Your php process (or you) don't have permission to write that file.

**Comment by mrkatz** [comment]
manually deleted the files, now work.
thanks
