### ISSUE TITLE
ide-helper:models doesn't generate protected scope() method and attribute() property

### ISSUE THREAD

**Issue by ppc52776** [barryvdh/laravel-ide-helper#845]
ide-helper:models can generate methods and properties for "public" scopes and attributes, but not protected one.

Here is the example model:
```php
class User extends Model
{
    public function scopeBoy() { ... }
    protected function scopeGirl() { ... }
    public function getMidNameAttribute() { ... }
    protected function getLastNameAttribute() { ... }
}
```

ide-helper:models only generate "public" scope and attribute:
```php
/**
 * Class User
 * @property-read string midName
 * @method static User boy()
 */
class User { }
```

**Comment by golonix** [comment]
Why would you like to have non-public methods/attributes added to autocompletion? You cannot access them from the outside, except in child classes (protected methods/attributes), so having that added to the docblock is pointless.

**Comment by ppc52776** [comment]
Model's scope and attribute-related functions can't be called directly. If they are declared as public, IDE tools will auto-complete these functions. Declaring scope-function as 'protected' will prevent this.

**Comment by golonix** [comment]
> Model's scope and attribute-related functions can't be called directly.
Um, why? Besides, local scopes must be declared as public.

**Comment by barryvdh** [comment]
Not sure if it's required, but that is how it's done in the docs. I guess this is an edge-case. 
https://laravel.com/docs/7.x/eloquent#local-scopes
