### ISSUE TITLE
newQuery() is not static

### ISSUE THREAD

**Issue by Jamesking56** [barryvdh/laravel-ide-helper#846]
`php artisan ide-helper:models --write` adds `query()` and `newQuery()` as static methods in the PHPDoc of the model class.

`query()` is static, but `newQuery()` isn't. However, ide-helper marks them both as static.

This normally wouldn't matter too much, until you use strict PHPStan which states that any usages of `newQuery()` should be static. So `$model->newQuery()` fails PHPStan due to the false PHPDoc added by ide-helper.

I hope that makes sense, but basically `newQuery()` shouldn't be marked as static.

**Comment by jpickwell** [comment]
The Method class constructor treats all methods as static.

**Comment by Jamesking56** [comment]
Yes but it shouldn't do, since some methods aren't static.

**Comment by mfn** [comment]
I'd say: PRs welcome 😄

**Comment by barryvdh** [comment]
Closed in favor of #872

**Comment by mfn** [comment]
@barryvdh FTR this is closed in favour of a PR ( https://github.com/barryvdh/laravel-ide-helper/pull/872 ) but there's also a competing PR https://github.com/barryvdh/laravel-ide-helper/pull/897 and neither is merged so the _reported issue_ per se isn't solved yet.

I don't want to override your closing but I think as long as it's not "done" we should keep it open?
