### ISSUE TITLE
How to hide hidden Model columns?

### ISSUE THREAD

**Issue by UksusoFF** [barryvdh/laravel-ide-helper#847]
Any way do this? Or maybe hide this columns from loading database at all?

**Comment by mfn** [comment]
There's no such feature currently.

What's exactly a "hidden" column, do you mean `\Illuminate\Database\Eloquent\Concerns\HidesAttributes::$hidden`? That would be an entirely different thing ($hidden is used for serialization)

What's your use-case?

**Comment by UksusoFF** [comment]
> That would be an entirely different thing ($hidden is used for serialization)

Yep. Seems it's missusage. But in some cases we need hide properties from generator.

**Comment by mfn** [comment]
> But in some cases we need hide properties from generator.

What's your use case for wanting this?

**Comment by UksusoFF** [comment]
I rewrite legacy php application with Laravel. And still use old database scheme. Both app use one db now. 
But some database field not used or not allowed for modify in new app. 
Now I think that's very strange case so perhaps we need close issue.

**Comment by mfn** [comment]
Personally I don't think teaching ide-helper this is the right way. It doesn't protect your from anything, it's like "security through obscurity".

**Comment by UksusoFF** [comment]
For protection I use throw error when try to access to this property.

**Comment by mfn** [comment]
👍 

Seems the appropriate way to me

**Comment by mfn** [comment]
@barryvdh IMHO this is a non-idiomatic use-case, I vote for closing
