### ISSUE TITLE
【Help】`return` is changed from` Mode`l to `Builder`.

### ISSUE THREAD

**Issue by goto-masaya** [barryvdh/laravel-ide-helper#848]
If you update `composer` in a` laravel` project, `Illuminate \ Database \ Eloquent \ Builder` is automatically described instead of the model` eloquent` you created.

This is a repository.
![スクリーンショット 2019-11-24 1 05 47](https://user-images.githubusercontent.com/57246358/69481681-9bacf080-0e56-11ea-9366-981867f389a3.png)

Neither `ip` nor` email` can be supplemented.
It cannot be supplemented in `foreach`.
Although it is purple, it cannot be complemented.

I was able to complement it before.

![スクリーンショット 2019-11-24 1 09 06](https://user-images.githubusercontent.com/57246358/69481736-18d86580-0e57-11ea-95cb-5bff1ddbec15.png)

I don't want to put `model` manually in` return`.
Previously it was added automatically.

I use phpstorm.
If you press enter after `/ **`, it will be generated automatically.

How can I automatically list the `eloquent` of my model?

My `composer.json` is like this.
```
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "barryvdh/laravel-ide-helper": "*",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
```

**Comment by mfn** [comment]
> I was able to complement it before.

Do you might be able to take a screenshot of what autocomplete suggestion you got before, like you did with the newer version after your upgrade? Do you remember which version you had before?
