### ISSUE TITLE
Connection Refused Error when Generating Models

### ISSUE THREAD

**Issue by djallits** [barryvdh/laravel-ide-helper#850]
This following is what I have in my composer.json file:

```
post-update-cmd": [
       "Illuminate\\Foundation\\ComposerScripts::postUpdate",
       "@php artisan ide-helper:generate --memory -vvv",
       "@php artisan ide-helper:meta -vvv",
       "@php artisan ide-helper:models --nowrite -vvv"
 ]
```

The following is the portion of the result in question:
>  @php artisan ide-helper:models --nowrite -vvv
Loading model 'App\Models\User'
Exception: SQLSTATE[HY000] [2002] Connection refused
Could not analyze class App\Models\User.
Model information was written to _ide_helper_models.php

Is this the expected behavior? Note that running the `--memory` flag is not available when executing `ide-helper:models`.

**Comment by mfn** [comment]
Yes, to add phpdoc for models for columns a working database connection is required.

@barryvdh issue can be closed :}
