### ISSUE TITLE
Model phpDoc generation fails when model contains a geometry field

### ISSUE THREAD

**Issue by unlikenesses** [barryvdh/laravel-ide-helper#851]
If a model is associated with a database table containing a `geometry` field, then when running

`php artisan ide-helper:models -W`

this error occurs:

> Exception: Unknown database type geometry requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

(Laravel 5.8, PHP 7.2, MariabDB 10.4.7)

**Comment by faizananwerali** [comment]
+1

**Comment by faizananwerali** [comment]
Did you find any solution yet?

**Comment by faizananwerali** [comment]
I also fails on `point` filed

**Comment by faizananwerali** [comment]
Found a solution.

First publish config file
`php artisan vendor:publish --provider="Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider" --tag=config`

then add these db settings in `config/ide-helper.php`
```
    'custom_db_types' => array(
        'mysql' => [
            'geography' => 'array',
            'point' => 'array',
        ],
    ),
```

**Comment by mfn** [comment]
@barryvdh the proposed solution to manually map unknown types is the correct one, issue can be closed :}
