### ISSUE TITLE
Lumen ^6.0

### ISSUE THREAD

**Issue by valeriy-efimov** [barryvdh/laravel-ide-helper#852]
Fast open controller in web.php not working 
![image](https://user-images.githubusercontent.com/5989188/70137009-bb81b700-1695-11ea-9535-c19462515a51.png)

Enabling Facades ✔
Adding the Service Provider ✔

**Comment by mfn** [comment]
But doesn't auto-complete support in the route string require support for the IDE itself, like https://plugins.jetbrains.com/plugin/7532-laravel
> PHP/Route: Controller completion and goto

Not sure what ide-helper can do here or am I missing something 🤔

**Comment by barryvdh** [comment]
I think

**Comment by fawel11** [comment]
I am facing the same issue for Lumen 7 and "barryvdh/laravel-ide-helper": "^2.8",
