### ISSUE TITLE
Aborted ide-helper:models on windows

### ISSUE THREAD

**Issue by Davidnadejdin** [barryvdh/laravel-ide-helper#855]
`Aborted. at C:\\laragon\\www\\trenings\\vendor\\symfony\\console\\Helper\\QuestionHelper.php:137)
[stacktrace]`
when you try to run ide-helper:models on windows
![image](https://user-images.githubusercontent.com/40993387/70862285-29fb2a80-1f5c-11ea-8325-35ec08121e54.png)

**Comment by ChxGuillaume** [comment]
Still have the same problem at this date.

L6 on Win 10

**Comment by obtoon** [comment]
To fix this just append the --write to the command.
`php artisan ide-helper:models --write`

**Comment by obtoon** [comment]
Discovered the underlying issue has to do with PHP 7.4.0 on certain systems. I upgraded to the latest 7.4.4 and it fixed the issue.
