### ISSUE TITLE
PHP 7.4.0 Exception: Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by pengleelove** [barryvdh/laravel-ide-helper#856]
php artisan ide-helper:models  

this is an error:
Exception: Function ReflectionType::__toString() is deprecated
Could not analyze class App\Models\Company.

**Comment by hailwood** [comment]
@pengleelove the latest version has this fixed.

**Comment by pengleelove** [comment]
> @pengleelove the latest version has this fixed.

thanks !
