### ISSUE TITLE
Move from barryvdh/reflection-docblock to phpdocumentor/reflection-docblock 4.3

### ISSUE THREAD

**Issue by GrahamCampbell** [barryvdh/laravel-ide-helper#858]

**Comment by barryvdh** [comment]
Yeah I forked it and modified it to be able to change the docs instead of just read them. Must check out what changed in the new version.

**Comment by mfn** [comment]
@barryvdh can be as closed as duplicate of your https://github.com/barryvdh/laravel-ide-helper/issues/972 :}

**Comment by GrahamCampbell** [comment]
Actually #972 is a duplicate of this issue?

**Comment by mfn** [comment]
Yeah but a) owner created it himself and b) it's more clear about the current state attempt; this issue isn't as useful IMHO; we only need one for this.

**Comment by mfn** [comment]
Closing per my comment https://github.com/barryvdh/laravel-ide-helper/issues/858#issuecomment-650529380
