### ISSUE TITLE
A small package configure everything automatically.

### ISSUE THREAD

**Issue by Nothing-Works** [barryvdh/laravel-ide-helper#863]
Hi All,
I have a small [package](https://github.com/Nothing-Works/laravel-helper) that configures everything automatically rather than do everything manually,

I am not sure where to put this if this does not fit here, feel free to close this issue.

**Comment by vesper8** [comment]
@Nothing-Works Could you explain what your helper does exactly?

**Comment by Nothing-Works** [comment]
@vesper8  it follows the doc of `laravel-ide-helper`, installs `laravel-ide-helper`, 

php artisan ide-helper:generate
php artisan ide-helper:models
php artisan ide-helper:meta

and modify some config files for your editor to understand some laravel helper methods.

**Comment by vesper8** [comment]
thanks @Nothing-Works, lately I feel like your name a lot ;)

I'm having a lot of trouble with vscode and intelephense.. I have code in custom places.. I use a "modules" system and most of my application code is actually in some folders located in `base_path('modules/vendor/name/src/HERE')`

This code never gets picked up by laravel-ide-helper nor does it get picked up my Intelephense... I was kind of surprised that there's no way to tell laravel-ide-helper to look for code in additional folders. It lets you look for models in specified folders but not general code.. It looks like it only looks in `app` and `vendor` for that

A real head scratcher.. would you have any idea how to make it look for general code in other folders?

**Comment by Nothing-Works** [comment]
@vesper8 maybe turn your code into some packages on packagist? lol

**Comment by mfn** [comment]
@barryvdh I vote for closing this issue :}
