### ISSUE TITLE
How to I can install in Visual Code Studio Windows 10

### ISSUE THREAD

**Issue by mofizul21** [barryvdh/laravel-ide-helper#876]
Hey, how to I can install it in my Windows 10 64bit with Visual Code Studio. I have Intelphense, but I need it to enhance facilities.

**Comment by mfn** [comment]
For installation, please see https://github.com/barryvdh/laravel-ide-helper#install

Whether Visual Code / intelephense can work with ide-helper, I don't know though.

**Comment by mfn** [comment]
@barryvdh same as https://github.com/barryvdh/laravel-ide-helper/issues/631#issuecomment-650419482 and https://github.com/barryvdh/laravel-ide-helper/issues/457#issuecomment-649807945 , I vote for closing :}
