### ISSUE TITLE
no new helper added

### ISSUE THREAD

**Issue by muharremozdemir** [barryvdh/laravel-ide-helper#878]
When I create a new model, even if I apply php artisan ide-helper: models, helpers are not added to the new models?

**Comment by mfn** [comment]
What version of ide-helper are you using?
What version of Laravel / Lumen are you using?
Do you get any error?
What is the exact command you were running (with options)? Preferable with the console output?

**Comment by clouditsoft** [comment]
ide-helper version; ^2.6
laravel version: 5.8
Do you get any error? No
php artisan ide-helper:models

**Comment by mfn** [comment]
What to you answer to the question
> Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead (yes/no)

?

If you don't say yes here, it will write them to `_ide_helper_models.php` instead.

**Comment by clouditsoft** [comment]
Yes, it is now. Currently, the columns do not offer suggestions when creating new objects.
$user = new User();
$user->???

**Comment by mfn** [comment]
> Yes, it is now

I don't understand.

If your problem solved or not?

**Comment by mfn** [comment]
@barryvdh this is a basic feature known to work, due to lack of feedback I suggest to close this issue :}
