### ISSUE TITLE
Does not generate relationship methods

### ISSUE THREAD

**Issue by Putr** [barryvdh/laravel-ide-helper#883]
The `_ide_helper.php` does not include definitions for Laravels relationship methods like `belongsTo`and `hasMany` on the definition for `\Eloquent`.

I'm using it with VSCode/Intelephense (so am not sure if it's picking up and using .phpstorm.meta.php)

**Comment by Putr** [comment]
PS: I've 'solved' this problem by creating an extra `_ide_helper_laravel.php` and added this:

```
namespace Illuminate\Database\Eloquent {
	class Model
	{
		public function belongsTo()
		{
		}
		public function hasMany()
		{
		}
		public function hasOne()
		{
		}
		public function belongsToMany($)
		{
		}
		public function hasOneThrough()
		{
		}
		public function hasManyThrough()
		{
		}
		public function morphTo()
		{
		}
		public function morphOne()
		{
		}
		public function morphMany()
		{
		}
		public function morphToMany()
		{
		}
		public function morphedByMany()
		{
		}
	}
}
```

It's not great, but at least I got rid of the warnings about missing methods.

**Comment by vesper8** [comment]
@putr did you have to do anything to make VSCode Intelephense use it? I've generated the _ide_helper.php but in spite of that the new Intelephense throws warnings about Undefined Type all over the place

**Comment by rdarcy1** [comment]
The methods you've listed are public and belong to `Illuminate\Database\Eloquent\Model` via the trait `HasRelationships` trait. This means they should be picked up by your autocomplete without any need for listing externally.

`_ide_helper.php` generally lists methods that are proxied via the `__call()` magic method, for example the query builder methods like `where()` and `find()`.

I don't use VSCode so afraid I can't help there, but I don't think this is an issue with the package.

**Comment by mfn** [comment]
All I distill here is that VS Code does not handle code introspection / auto-completation well

@barryvdh this is unrelated to ide-helper and can be closed :}
