### ISSUE TITLE
Sorting of models can vary

### ISSUE THREAD

**Issue by carestad** [barryvdh/laravel-ide-helper#885]
I started looking into setting up a regeneration of the helper files using [Github Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions), and I noticed that the sorting of the models in especially `_ide_helper_models.php` ends up being different on Github than on my local machine (or my fellow coworkers machines as well).

For instance, running `artisan ide-helper:models -n -vvv` locally, it will list my `App\Models\ProjectMessage` model last, while in Gitub Actions it lists `App\Models\UserRole` last.

From looking at the code, the list of classes is generated from the composer package `ClassMapGenerator` and more specifically [`ClassMapGenerator::createMap()`](https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L257). I don't see any sorting support there, nor do I know exactly _why_ it sorts differently in this case, but is it perhaps an option to sort the array of models in this package instead to try and make the return more predictable?

**Comment by mfn** [comment]
@carestad please give https://github.com/barryvdh/laravel-ide-helper/pull/982 a try!
