### ISSUE TITLE
Problem with "tymon/jwt-auth"

### ISSUE THREAD

**Issue by PatSpiegel** [barryvdh/laravel-ide-helper#888]
Problem with "tymon/jwt-auth": "1.0.0-rc.5.1"
laravel-ide-helper: 2.6.6
Laravel: 6.14.0
Php: 7.4.1

php artisan ide-helper:generate -M

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Tymon\JWTAuth\Blacklist::__construct() must be an instance of Tymon\JWTAuth\Contracts\Providers\Storage, null given, called in I:\1work\project\vendor\tymon\jwt-auth\src\Providers\AbstractServiceProvider.php on line 288

  at I:\1work\project\vendor\tymon\jwt-auth\src\Blacklist.php:54
    50|      * @param  \Tymon\JWTAuth\Contracts\Providers\Storage  $storage
    51|      *
    52|      * @return void
    53|      */
  > 54|     public function __construct(Storage $storage)
    55|     {
    56|         $this->storage = $storage;
    57|     }
    58|

  Exception trace:

  1   Tymon\JWTAuth\Blacklist::__construct()
      I:\1work\project\vendor\tymon\jwt-auth\src\Providers\AbstractServiceProvider.php:288

  2   Tymon\JWTAuth\Providers\AbstractServiceProvider::Tymon\JWTAuth\Providers\{closure}()
      I:\1work\project\vendor\laravel\framework\src\Illuminate\Container\Container.php:799

**Comment by erkanrua** [comment]
I'm getting the same error
