### ISSUE TITLE
Relations with query not work again

### ISSUE THREAD

**Issue by UksusoFF** [barryvdh/laravel-ide-helper#892]
After #873 we have missed compare all relations types.
Because  $reflection->getReturnType() return type without slash.

`\Illuminate\Database\Eloquent\Relations\MorphToMany` !== `Illuminate\Database\Eloquent\Relations\MorphToMany`

Steps to reproduce described at #760

**Comment by UksusoFF** [comment]
@mfn please take a look here.

**Comment by mfn** [comment]
Ops :-/

I'm quite busy at the moment, so appreciate if someone else can jump in to accelerate a fix!
