### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by martinkolarov** [barryvdh/laravel-ide-helper#896]
Does the package support Laravel 7 as of yet?

Getting following output when trying to install the package:

 Problem 1
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.7
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.6
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.5
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.4
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.3
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.2
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.6.1
    - Installation request for symfony/console (locked at v5.0.5) -> satisfiable by symfony/console[v5.0.5].
    - Conclusion: remove laravel/framework v7.0.2
    - Installation request for barryvdh/laravel-ide-helper ^2.6 -> satisfiable by barryvdh/laravel-ide-helper[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7].
    - Conclusion: don't install laravel/framework v7.0.2
    - barryvdh/laravel-ide-helper v2.6.0 requires illuminate/filesystem ^5.5,<5.9 -> satisfiable by illuminate/filesystem[5.7.17, 5.7.18, 5.7.19, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/filesystem 5.7.17|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem 5.7.18|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem 5.7.19|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.0|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.16|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.17|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.2|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.28|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.33|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.34|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.35|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.36|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.37|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.39|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.40|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.41|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.43|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.5.44|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.0|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.1|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.10|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.11|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.12|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.13|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.14|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.15|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.16|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.17|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.19|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.2|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.20|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.21|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.22|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.23|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.24|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.25|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.26|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.27|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.28|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.29|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.3|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.30|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.31|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.32|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.33|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.34|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.35|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.36|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.37|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.38|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.39|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.4|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.5|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.6|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.7|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.8|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.6.9|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.0|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.1|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.10|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.11|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.15|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.2|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.20|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.21|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.22|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.23|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.26|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.27|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.28|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.3|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.4|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.5|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.6|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.7|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.8|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.7.9|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.0|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.11|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.12|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.14|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.15|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.17|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.18|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.19|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.2|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.20|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.22|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.24|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.27|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.28|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.29|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.3|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.30|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.31|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.32|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.33|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.34|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.35|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.36|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.4|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.8|don't install laravel/framework v7.0.2
    - don't install illuminate/filesystem v5.8.9|don't install laravel/framework v7.0.2
    - Installation request for laravel/framework (locked at v7.0.2, required as ^7.0) -> satisfiable by laravel/framework[v7.0.2].

**Comment by mfn** [comment]
Probably need to bump the version constraint, can you make a PR?

**Comment by martinkolarov** [comment]
@mfn Didn't the version get bumped [here](https://github.com/barryvdh/laravel-ide-helper/commit/edd69c5e0508972c81f1f7173236de2459c45814)?

**Comment by piurafunk** [comment]
This seems be an issue with the `composer/composer: ^1.6` constraint.

```
$ composer require --dev barryvdh/laravel-ide-helper:2.6.7
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-ide-helper 2.6.7 -> satisfiable by barryvdh/laravel-ide-helper[v2.6.7].
    - Conclusion: remove symfony/console v5.0.5
    - Conclusion: don't install symfony/console v5.0.5
    - barryvdh/laravel-ide-helper v2.6.7 requires composer/composer ^1.6 -> satisfiable by composer/composer[1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.9.0, 1.9.1, 1.9.2, 1.9.3].
    - composer/composer 1.6.0 requires symfony/console ^2.7 || ^3.0 || ^4.0 -> satisfiable by symfony/console[v2.7.0, v2.7.1, v2.7 ........
```
`composer/composer 1.6.x` does not support `symfony/console 5.x`, which is required by `laravel/framework 7.x`.

**Comment by barryvdh** [comment]
See https://github.com/composer/composer/pull/8432
It's merged but not yet released. Will see if it's released soon, otherwise I'll see if I can use another classmap generator.

**Comment by stayallive** [comment]
I love finding all these interesting dependencies all kinds of packages I'm using have and I had no idea about, never thought that composer itself is required by multiple packages, makes sense thinking about it...

Thanks for your work @barryvdh, looks like we need a little more patience for composer to catch up to the Symfony 5 train 👍

**Comment by NickJorens** [comment]
> I love finding all these interesting dependencies all kinds of packages I'm using have and I had no idea about, never thought that composer itself is required by multiple packages, makes sense thinking about it...
> 
> Thanks for your work @barryvdh, looks like we need a little more patience for composer to catch up to the Symfony 5 train

This is something I actually don't like. It introduces a lot of dependencies that are preventing you to move forward on your terms. Don't take this as disrespect against this package, because it's still awesome!

**Comment by barryvdh** [comment]
Feel free to open a PR te replace the classmap loader :)

**Comment by NickJorens** [comment]
> Feel free to open a PR te replace the classmap loader :)

I'm sorry, I didn't mean to sound arrogant or disrespectful. It's just something I don't love about the current state of package managers in general. It can sometimes be an endless road of connections.

**Comment by stayallive** [comment]
I'm gonna share my secret here for the impatient ones (like me).

I solved it by adding `composer/composer` to the `require-dev` section of my own `composer.json` file but use the latest version with the Symfony 5 support.

```json
    "require-dev": {
        "barryvdh/laravel-ide-helper": "2.6.*",
        "composer/composer": "^1.10@dev",
        // any other you have
    },
```

_Note: This might not work for you in case there are more than just `composer/composer` that is the issue.`

**Comment by mfn** [comment]
> Feel free to open a PR te replace the classmap loader :)

Oh wow, wasn't even ware of that. Kudos :)

**Comment by barryvdh** [comment]
The new Composer version has been tagged, so let me know if you still have any problems!

**Comment by barryvdh** [comment]
Should be fixed. I've added it to Travis and seems to be fine :)
