### ISSUE TITLE
PhpStorm detecting multiple declarations for models and facades

### ISSUE THREAD

**Issue by Glendog** [barryvdh/laravel-ide-helper#900]
Hello,

Since using ide-helper, I am getting class undefined for my facades and models. When I control click them PhpStorm offers multiple declarations - the framework and the helper file.

https://i.imgur.com/4jwNf9I.png

**Comment by AndresReyesDev** [comment]
Duplicate of #126 #451 #469 #516

**Comment by andytan0727** [comment]
Facing this problem also. So the fastest solution now is just [disable inspection](https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-355268633) if you are using PhpStorm.

**Comment by shirshak55** [comment]
@andytan0727 disable inspection is getting rid of feature not problem.

**Comment by chrisan** [comment]
I use the suggestion here so I don't have to disable it: https://github.com/barryvdh/laravel-ide-helper/issues/592#issuecomment-494107327

**Comment by mfn** [comment]
@barryvdh the other issue has more details and this doesn't bring much new to the table, IMHO this can be closed as duplicated of #592
