### ISSUE TITLE
Removed column and accessor still exist when generating new ide helper

### ISSUE THREAD

**Issue by PanjiNamjaElf** [barryvdh/laravel-ide-helper#902]
I try to create accessor on eloquent model
After that i generate ide-helper for model
and the accessor column display on phpDocs
but when i remove my accessor or rename it to another one and try to generate the ide helper again
my old accessor name still exist in phpDocs
i must delete old phpDocs and re-generate it again..

can you make ability to automatic clear old phpDocs instead manuall delete ?

**Comment by mfn** [comment]
I think you're missing the `--reset` argument for the command, try this:
`php artisan ide-helper:models --write --reset`

**Comment by PanjiNamjaElf** [comment]
Ok its work..
I miss reading the --reset section on ReadMe.md

i have one question again..
how about to generate for specifici model only..

For example i have 'UserActivation' model

i use command like this on readme doc didnt work...

`artisan ide-helper:models UserActivation --env=testing -W -R`

**Comment by mfn** [comment]
The the last one from the output:
```
$ ./artisan ide-helper:models --help
Description:
  Generate autocompletion for models

Usage:
  ide-helper:models [options] [--] [<model>...]

Arguments:
  model                      Which models to include

Options:
  -F, --filename[=FILENAME]  The path to the helper file [default: "_ide_helper_models.php"]
  -D, --dir[=DIR]            The model dir (multiple values allowed)
  -W, --write                Write to Model file
  -N, --nowrite              Don't write to Model file
  -R, --reset                Remove the original phpdocs instead of appending
  -r, --smart-reset          Refresh the properties/methods list, but keep the text
  -I, --ignore[=IGNORE]      Which models to ignore [default: ""]
…
```

**Comment by PanjiNamjaElf** [comment]
Ok thank's
