### ISSUE TITLE
Override return type Laravel 7 custom cast

### ISSUE THREAD

**Issue by tomsix** [barryvdh/laravel-ide-helper#904]
I use the Laravel 7 CastsAttributes interface for type casting. The Caster returns a WebsiteType class but the phpdoc has WebsiteTypeCaster as return type.

`protected $casts= [
        'website_type' => WebsiteTypeCaster::class
    ];`

I wrote this in the confige but it didn't change anything

`'type_overrides' => array(
        'integer' => 'int',
        'boolean' => 'bool',
        WebsiteTypeCaster::class => WebsiteType::class
    ),`

**Comment by mfn** [comment]
Seems legit, ide-helper would need special support for this to properly recognize it.

Do you want to attempt a PR?

**Comment by sandulat** [comment]
@tomsix I believe it should look like this:
```php
'\\'.WebsiteTypeCaster::class => '\\'.WebsiteType::class
```

**Comment by tomsix** [comment]
@sandulat thanks!
