### ISSUE TITLE
Class Barryvdh\LaravelIdeHelper\ModelsCommand located in ./vendor/barryvdh/laravel-ide-helper/src/Barryvdh/LaravelIdeHelper/ModelsCommand.php does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by amfsyn** [barryvdh/laravel-ide-helper#907]
I'm getting this warning during `composer dump-autoload --optimize` with composer v 1.10.1

> Class Barryvdh\LaravelIdeHelper\ModelsCommand located in ./vendor/barryvdh/laravel-ide-helper/src/Barryvdh/LaravelIdeHelper/ModelsCommand.php does not comply with psr-4 autoloading standard.  It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201

Is there anything I can do to fix this?

**Comment by mfn** [comment]
I can't reproduce this (using composer 1.10.1 and 2.6.7).

Are you on the latest version https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.6.7 ?

**Comment by amfsyn** [comment]
Sorry to bug you. Updating to 1.9 fixed the message.

**Comment by mfn** [comment]
Great! Please close the issue, thanks

**Comment by mfn** [comment]
@barryvdh nothing to do here anymore, issue can be closed :}
