### ISSUE TITLE
Undefined class \Illuminate\Support\Facades\Date

### ISSUE THREAD

**Issue by pristinesource** [barryvdh/laravel-ide-helper#911]
There was an update to support the date facade from Laravel 5.8, but that broke Laravel 5.7.  The commit that broke it was:
https://github.com/barryvdh/laravel-ide-helper/commit/0d1dd2182b44221eeb21e8a75ab5a01f884c066c#diff-9c76e55ce4ef570404e58c82d642c1e5 

On line 114 of src/Console/ModelsCommand.php it attempts to determine if the `\Illuminate\Support\Facades\Date` class exists.  It is not possible to use `::class` on a class that does not exist, so if it does not exist there (when trying to use ::class), then an error is produced before class_exists() is called.  It needs to be a string like so: `class_exists('\Illuminate\Support\Facades\Date')`

**Comment by pristinesource** [comment]
It should probably look something like this:

```
$this->dateClass = class_exists('\Illuminate\Support\Facades\Date')
            ? '\\' . get_class(call_user_func('\Illuminate\Support\Facades\Date::now'))
            : '\Illuminate\Support\Carbon';
```

**Comment by pristinesource** [comment]
Nevermind, I was very much mistaken on this.

**Comment by mfn** [comment]
I was pretty sure I tested this with L5/L6. Let me know if there's an issue… (I'm the author of the PR introducing this).
