### ISSUE TITLE
Unregister the custom autoloader that is registered in MetaCommand

### ISSUE THREAD

**Issue by mr-feek** [barryvdh/laravel-ide-helper#915]
The `MetaCommand` registers its own autoloader. It should then unregister this function when it is done with it, so other code executes as expected.

I ran into this here: https://github.com/psalm/psalm-plugin-laravel/pull/41

**Comment by mfn** [comment]
Sounds legit, are you up for a PR?

**Comment by mr-feek** [comment]
I can  probably take a stab at it later this week
