### ISSUE TITLE
Model DocBlock generation works for all but 1 of my models

### ISSUE THREAD

**Issue by chrisan** [barryvdh/laravel-ide-helper#922]
Before you might say check my database configuration... the `php artisan ide-helper:models` command is working for my other models which use the same database (I wouldn't even know how to use a different database)

```
$ php artisan ide-helper:models -v

 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead (yes/no) [no]:
 > yes

Loading model 'App\Listing'
Written new phpDocBlock to /mnt/c/Users/Chris/code/myproject/app/Listing.php
Loading model 'App\Tenant'
Exception: Call to a member function getConnection() on null
Could not analyze class App\Tenant.

Trace:
#0 /mnt/c/Users/Chris/code/myproject/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(220): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->getPropertiesFromTable()
#1 /mnt/c/Users/Chris/code/myproject/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(118): Barryvdh\LaravelIdeHelper\Console\ModelsCommand->generateDocs()
#2 [internal function]: Barryvdh\LaravelIdeHelper\Console\ModelsCommand->handle()
#3 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#4 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#6 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#8 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#9 /mnt/c/Users/Chris/code/myproject/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#10 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#11 /mnt/c/Users/Chris/code/myproject/vendor/symfony/console/Application.php(1001): Illuminate\Console\Command->run()
#12 /mnt/c/Users/Chris/code/myproject/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#13 /mnt/c/Users/Chris/code/myproject/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#14 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#15 /mnt/c/Users/Chris/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run()
#16 /mnt/c/Users/Chris/code/myproject/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#17 {main}
Loading model 'App\User'
Written new phpDocBlock to /mnt/c/Users/Chris/code/myproject/app/User.php
$
```

You can see `Listing` and `User` get docblock generation, but for some reason `Tenant` does not.  All models are in the `app` folder.  Both `Tenant` and `Listing` extend `Model` while `User` extends `Authenticatable`

The migration creates a plural of the name

```
        Schema::create('tenants', function (Blueprint $table) {
            $table->increments('id');
            $table->string('domain');
            $table->boolean('enabled')->default(0);
            $table->string('theme')->default('Default');
            $table->timestamps();
            $table->index(['domain', 'id']);
        });
```

I've just been following along this post https://ollieread.com/articles/laravel-multi-tenancy-avoiding-over-engineering and havent even reached the database separation part (which I don't want to do anyways)

In `php artisan tinker` I can successfully query the first record with `Tenant::first()`

I've also tried `php artisan optimize:clear` and `composer dump-autoload`

What else could I debug to figure out why it can't create a connection to Tenant?

**Comment by mfn** [comment]
Which version of ide-helper are you using?

**Comment by chrisan** [comment]
composer -i shows barryvdh/laravel-ide-helper v2.6.7

**Comment by mfn** [comment]
2.7.0, AFAIK it doesn't have any fixes for this but would be great if you can give it try; the stacktrace line numbers will also change.

Can you paste you Tenant model?

**Comment by chrisan** [comment]
It's just a fresh model

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tenant extends Model 
{
  //
}
```

2.7.0 had same results.

I created a new project with composer, added ide-helper, generated a new Tenant model and updated .env to point at my previous database and ran the ide-helper models command and it worked.

I'm just completely baffled as to what I may have done.  2 models work in old project, the failing model works in the new project using old database.  So it must be either something I did or something in that Tenant guide

**Comment by chrisan** [comment]
OK, so its the article.  This is when laravel can no longer `make` by name

```
$this->app->bind(Tenant::class, function() use ($manager) {
      return $manager->getTenant();
});
```

I'm guessing this will be out of scope for this project, if so you may close

**Comment by mfn** [comment]
The model definitely has to be `make`able. Given the original error is:
> Exception: Call to a member function getConnection() on null

The model is not fully/correctly set up when ide-helper tries to access it's information for introspection, which is essential.

Unless you can get this working, you won't be able to generate the meta data for such models unfortunately.

**Comment by mnpenner** [comment]
Thanks @grantholle , your suggestion fixed it for me to. Wasn't in a service provider, but I found a `->bind()` call in `services/php/bootstrap/app.php`.

Changed this:

```php
$app->bind(\App\Models\User::class, function(\Illuminate\Foundation\Application $app) {
    return $app->make('auth')->user();
});
```

To this:

```php
if(!$app->runningInConsole()) {
    $app->bind(\App\Models\User::class, function(\Illuminate\Foundation\Application $app) {
        return $app->make('auth')->user();
    });
}
```

And it runs now!
