### ISSUE TITLE
Add inspections for methods that are only called within route files

### ISSUE THREAD

**Issue by danrichards** [barryvdh/laravel-ide-helper#927]
### My Routes file:

<img width="1045" alt="Screen Shot 2020-04-23 at 1 31 45 PM" src="https://user-images.githubusercontent.com/470255/80131024-966be300-8567-11ea-9a69-0b78fed89ec6.png">

### The only place this method is called:

> Note that PHPStorm is basically seeing it as dead code.

<img width="661" alt="Screen Shot 2020-04-23 at 1 31 18 PM" src="https://user-images.githubusercontent.com/470255/80131050-a08de180-8567-11ea-9295-74be98d1ded0.png">

### Example of how they can be fixed:

> Manually updated `_ide_helper.php` for sake of explanation

<img width="670" alt="Screen Shot 2020-04-23 at 1 33 54 PM" src="https://user-images.githubusercontent.com/470255/80131248-f1053f00-8567-11ea-95d1-904f5459af73.png">

### After the manual change

<img width="636" alt="Screen Shot 2020-04-23 at 1 41 12 PM" src="https://user-images.githubusercontent.com/470255/80131362-1db95680-8568-11ea-866f-b3b4348965eb.png">

👍 ?

---

1. Thank you for the great package, it's my first `require-dev` in all my Laravel / Lumen applications
2. Would love to see support for this use case in `ide-helper:generate` or separate `ide-helper:routes` command

**Comment by danrichards** [comment]
Relates to https://github.com/barryvdh/laravel-ide-helper/issues/787

**Comment by mr-feek** [comment]
I think this might be better suited for a laravel static analyzer
