### ISSUE TITLE
Using 'self' instead of FQCN in models helper generator's @method definitions

### ISSUE THREAD

**Issue by samirmh-dev** [barryvdh/laravel-ide-helper#935]
Why we don't use just `self` instead of `\App\User\SocialNetwork` (or another model namespace) ?

We can do this because, model definition is related to current class.

So,

`@method static \Illuminate\Database\Eloquent\Builder|\App\User\SocialNetwork whereCreatedAt( $value )`

must replaced with

`@method static \Illuminate\Database\Eloquent\Builder|self whereCreatedAt( $value )`

I will try to create PR when I will available

**Comment by mfn** [comment]
@barryvdh per https://github.com/barryvdh/laravel-ide-helper/pull/936#issuecomment-650759803 the issue can be closed :}

**Comment by mfn** [comment]
🤦‍♂️ was already closed
