### ISSUE TITLE
Composer memory exhausted when installing this package

### ISSUE THREAD

**Issue by tanthammar** [barryvdh/laravel-ide-helper#943]
If I have this package installed I am unable to perform `composer require` commands.
`composer update` works fine.
If I remove the package I have no issues.

"barryvdh/laravel-ide-helper": "^2.6",
Laravel Framework 7.12.0
"php": "^7.4.4",

Error:
```info
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52
```

**Comment by adrianschubek** [comment]
I had a similar issue. Deleting the vendor folder and installing again fixed it for me.

**Comment by tanthammar** [comment]
Thank you for the suggestion. Tried it, but it did not help :)

**Comment by mfn** [comment]
I can't see how this is an issue with the package; if, it's a composer problem no?

Try the latest beta and see if it works => `composer self-update --snapshot`

I had similar memory issues with https://github.com/rebing/graphql-laravel and just changing this fixed the build on travis

**Comment by mash1t** [comment]
You could also use an env var for ignoring this issue once
COMPOSER_MEMORY_LIMIT=-1 composer require --dev barryvdh/laravel-ide-helper

**Comment by tanthammar** [comment]
I think I was unclear when specifying my issue.
I have no problem installing **this** package.
But **after it is installed I cannot install any other package** without getting this error.
If I remove this package, and I can install other packages without issues.

**Comment by tanthammar** [comment]
> I can't see how this is an issue with the package; if, it's a composer problem no?
> 
> Try the latest beta and see if it works => `composer self-update --snapshot`
> 
> I had similar memory issues with https://github.com/rebing/graphql-laravel and just changing this fixed the build on travis

Tried this but I get a lot of symfony/thanks errors...

**Comment by squatto** [comment]
Since most people will scroll down to the bottom for the answer, I'll point you back up to [this comment](https://github.com/barryvdh/laravel-ide-helper/issues/943#issuecomment-634052189) ⬆️ 

> You could also use an env var for ignoring this issue once
> COMPOSER_MEMORY_LIMIT=-1 composer require --dev barryvdh/laravel-ide-helper

Nearly every time you hit a memory limit with composer, you can get around it by prefixing the command with `COMPOSER_MEMORY_LIMIT=-1`. You can find more information about this solution here: https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by tanthammar** [comment]
@squatto @mash1t Thank you.
Should it be exactly like this?
```COMPOSER_MEMORY_LIMIT=-1 composer require --dev barryvdh/laravel-ide-helper```
I get this error:
```
Failed to parse dotenv file due to unexpected whitespace. Failed at [-1 composer require --dev barryvdh/laravel-ide-helper].
```

**Comment by Sylk** [comment]
Thanks for the answers @squatto and @mash1t.
