### ISSUE TITLE
composer require --dev barryvdh/laravel-ide-helper fails with 404

### ISSUE THREAD

**Issue by tonjohn** [barryvdh/laravel-ide-helper#949]
![image](https://user-images.githubusercontent.com/7477471/84061106-2d52fa00-a972-11ea-9d28-f1c90f1774eb.png)

Running 'composer require --dev barryvdh/laravel-ide-helper' results in an error.

```
Installation failed, reverting ./composers.json to its original content.

[Composer\Downloader\TransportException]
  The "https://packagist.org/p/symfony/polyfill-ctype%24c05ac4e34d4a807da87b45b10085de37fc71dba5afb8f81da206af8f75920d53.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```

I had a friend try and he received the same issue.

**Comment by mfn** [comment]
Nothing we can do and apparently it's already fixed => please see https://github.com/composer/packagist/issues/1090

This issue can be closed, as it's not specific to this package.

**Comment by inventivo** [comment]
Problem still persists for me. A question of time?

**Comment by mfn** [comment]
Yes, and none this package can answer.
