### ISSUE TITLE
Inferred model properties from Interface

### ISSUE THREAD

**Issue by MartinP7r** [barryvdh/laravel-ide-helper#950]
Is there a way to make Laravel generated attribute accessors automatically available?  

How I'm doing it now: 

```php
/**
 * 
 * @property string $foo_bar
 */
interface IsFooBarable
{
    function getFooBarAttribute($value): string;
}
```

Without the `@property` pragma, `->foo_bar` does not show up as a suggestion for type hinted variables. e.g. 

```php
public function doSomething(IsFooBarable $model)
    {
        \Log::debug($model->foo_bar);
    }
```

I'm sorry if I'm missing something and this functionality is already available.

**Comment by mfn** [comment]
No, it's not. I wonder also how we could figure this out.

For models you can specify a directory where they can be found but it's also required they extend from `\Illuminate\Database\Eloquent\Model` so there's clear pattern how to identify them.

How could that work for an interface whose has no real connection to Eloquent except the naming "by convention"?

**Comment by mr-feek** [comment]
> How could that work for an interface whose has no real connection to Eloquent except the naming "by convention"?

I think it would be reasonable for us to assume that any method on a model (using reflection, therefore including the interface) matching get*Attribute is an accessor
