### ISSUE TITLE
limit not autocomplete

### ISSUE THREAD

**Issue by farazsahebdel** [barryvdh/laravel-ide-helper#951]
hi
after where(), limit() not autocomplete

![Screenshot_20200609_154343](https://user-images.githubusercontent.com/5825113/84141618-b0567c00-aa68-11ea-84d3-2f238f6bcb26.jpg)

but

![Screenshot_20200609_155011](https://user-images.githubusercontent.com/5825113/84141788-f4e21780-aa68-11ea-82b8-ae8264f7de0a.jpg)

and 

![Screenshot_20200609_155134](https://user-images.githubusercontent.com/5825113/84141908-265ae300-aa69-11ea-8abf-6d95008356bc.jpg)

**Comment by mfn** [comment]
Works for me in PhpStorm:
![image](https://user-images.githubusercontent.com/87493/84184280-5916d280-aa8d-11ea-8ea6-4ed824962eeb.png)

Do you have the `_ide_helper.php` generated in your project and is your IDE taking advantage of it?

**Comment by farazsahebdel** [comment]
yes !

**Comment by mfn** [comment]
So, nothing this package can fix, or?

**Comment by farazsahebdel** [comment]
no

**Comment by mfn** [comment]
Then we can close the issue 🤷‍♀️
