### ISSUE TITLE
[Improvement] Use original ReflectionDocBlock

### ISSUE THREAD

**Issue by barryvdh** [barryvdh/laravel-ide-helper#972]
I've forked ReflectionDocBlock: https://github.com/barryvdh/ReflectionDocBlock
But in time we might want to revert to the original project: https://github.com/phpDocumentor/ReflectionDocBlock

The reason I did this was because I couldn't write the docblocks in the newer versions. But we might be able to fix that in a more elegant way.

**Comment by barryvdh** [comment]
I tried a bit, but the biggest issue is that we can't just modify tags anymore with the original project. So replacing interfaces etc.

**Comment by mfn** [comment]
Hmm, also not sure if they're open to this, I only found https://github.com/phpDocumentor/ReflectionDocBlock/issues/175

**Comment by barryvdh** [comment]
Yeah that's the whole reason I forked it to begin with :P 
It was open a bit and I wanted to open it further for editing, but they wanted to be read-only.
