### ISSUE TITLE
wrong type for model cast with parameters

### ISSUE THREAD

**Issue by artelkr** [barryvdh/laravel-ide-helper#985]
`protected $casts = [ 'sell_price' => Money::class];` generate in docblock `/** @property \App\Support\Money $sell_price */`

but if add param to cast (`protected $casts = [ 'sell_price' => Money::class . ':sell_price'];`), ide-helper generate wrong (mixed) type  `/** @property mixed $sell_price */`

**Comment by mfn** [comment]
Seems the implementation in https://github.com/barryvdh/laravel-ide-helper/pull/913 maybe didn't cater for this.

I haven't looked into it in detail yet, but could be as simply as exploding on `:` and adding some tests.

Would you be interested doing this?
