### ISSUE TITLE
Bug with previous "Simplify full namespaces for already included resources" commit

### ISSUE THREAD

**Issue by brendt** [barryvdh/laravel-ide-helper#992]
This recent [commit](https://github.com/barryvdh/laravel-ide-helper/commit/6f20800eef08db1d6da7aafd383309fcfafc651a) breaks lots of code. Instead of the FQCN, the IDE helper now generates a class alias. Eg, instead of this:

```php
 * @method static \App\Context\Product\QueryBuilders\EMaterialQueryBuilder|\App\Context\Product\Models\EMaterial newModelQuery()
 * @method static \App\Context\Product\QueryBuilders\EMaterialQueryBuilder|\App\Context\Product\Models\EMaterial newQuery()
 * @method static \App\Context\Product\QueryBuilders\EMaterialQueryBuilder|\App\Context\Product\Models\EMaterial query()
```

The following is generated

```php
* @method static EMaterialQueryBuilder|EMaterial newModelQuery()
 * @method static EMaterialQueryBuilder|EMaterial newQuery()
 * @method static EMaterialQueryBuilder|EMaterial query()
```

The same problem happens for example with custom casts:

```php
 * @property \App\Context\Product\Enums\EMaterialType $type
```

Becomes

```php
 * @property EMaterialType $type
```

**Comment by barryvdh** [comment]
So without the use statement available?

**Comment by brendt** [comment]
Yes, there's no use statement

**Comment by barryvdh** [comment]
@LANGERGabriel can you check this out?
@mfn can you confirm this?

**Comment by mfn** [comment]
When that PR was merged I was on vacation 😄 💥 

@brendt can you provide some self-contained examples?

I don't have complex things in my project when just now tested the master version, but I noticed that e.g. I use a custom date class and
- when I manually import `use Carbon\CarbonImmutable` at the top, the data casts get changes to `@property CarbonImmutable $…`
- but when I remove the use, it gets rewritten to `@property \Carbon\CarbonImmutable`

So it seems the code figures our if something is important or not, at least in this scenario.

**Comment by brendt** [comment]
An example:

```php
class EMaterial extends Model
{
    public function newEloquentBuilder($query): EMaterialQueryBuilder
    {
        return new EMaterialQueryBuilder($query);
    }
}
```

```php
namespace App\Context\Product\QueryBuilders;

use Illuminate\Database\Eloquent\Builder;

class EMaterialQueryBuilder extends Builder
{
}
```

Running the models generate command results in this definition:

```
namespace App\Context\Product\Models{
/**
 * App\Context\Product\Models\EMaterial
 *
 * @method static EMaterialQueryBuilder|EMaterial newModelQuery()
 * @method static EMaterialQueryBuilder|EMaterial newQuery()
 * @method static EMaterialQueryBuilder|EMaterial query()
 * …
 */
	class EMaterial extends \Eloquent {}
}
```

There's no import at the top of the models file importing `EMaterialQueryBuilder`

**Comment by brendt** [comment]
In my testing I made a change to `ModelsCommand::getClassNameInModel`:

This is the original:

```php
    protected function getClassNameInModel(object $model, string $className): string
    {
        $className = trim($className, '\\');
        $usedClassNames = $this->getUsedClassNames($model);
        return $usedClassNames[$className] ?? ('\\' . $className);
    }
```

And I changed it to

```php
    protected function getClassNameInModel(object $model, string $className): string
    {
        $className = trim($className, '\\');

        return ('\\' . $className);
    }
```

Which fixes the issue, but of course that mapping is used for something somewhere, I'm just not sure why or where :)

**Comment by LANGERGabriel** [comment]
Hi,

@brendt 's fix will revert the new behaviour (using the short class name instead of the FQN).

I'm lookig into solving the issue.

**Comment by brendt** [comment]
@LANGERGabriel I already supposed my brute-force fix wasn't the best solution 😁 Thanks for looking into it!

**Comment by LANGERGabriel** [comment]
@brendt Added a pull request #993 .

I forgot in the initial implementation that you could write the phpdoc in another file.
