### ISSUE TITLE
::create and other methods missing

### ISSUE THREAD

**Issue by brendt** [barryvdh/laravel-ide-helper#994]
I noticed errors like these popping up all over my codebase. I always assumed the ide helper also took care of these methods, is that correct, or should I look somewhere else for the problem?

![Screen Shot 2020-07-17 at 07 55 11](https://user-images.githubusercontent.com/6905297/87753476-ff7b9380-c802-11ea-94b0-0d65b30ee01a.png)
![Screen Shot 2020-07-17 at 07 55 33](https://user-images.githubusercontent.com/6905297/87753481-00acc080-c803-11ea-9704-55b572e4f4d7.png)

**Comment by barryvdh** [comment]
Did you generate the ide helper file? I think the mixin for Eloquent probably does that.

**Comment by brendt** [comment]
My bad, it got removed by accident, sorry for the bother!
