### ISSUE TITLE
Specifying model name doesn't work

### ISSUE THREAD

**Issue by gpressutto5** [barryvdh/laravel-ide-helper#995]
I have this problem with every project. When specifying the model I want to write the docs it won't write to any model.

```sh
php artisan ide-helper:models JobSkill # won't write to JobSkill
php artisan ide-helper:models JobSkill.php # won't write to JobSkill
php artisan ide-helper:models Models\JobSkill # won't write to JobSkill
php artisan ide-helper:models App\Models\JobSkill # won't write to JobSkill
php artisan ide-helper:models --dir="app/Models" JobSkill # won't write to JobSkill

php artisan ide-helper:models --dir="app/Models/JobSkill.php" # will write to ALL models, INCLUDING JobSkill
php artisan ide-helper:models # will write to ALL models, INCLUDING JobSkill
```

This is the model class:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class JobSkill extends Model
{
    //
}
```

The table does exists, and `php artisan ide-helper:models` confirms this.

Not sure if it's a bug or if I'm using it wrong since I have this problem in every project.

**Comment by sdaicz** [comment]
The docs say:

> Note: With namespaces, wrap your model name in double-quotes (`"`): `php artisan ide-helper:models "API\User"`, or escape the slashes (`Api\\User`).

Did you try with `App\\Models\\JobSkill`?

**Comment by gpressutto5** [comment]
@sdaicz This note is referring to strings in the config file, so it's not the same case. But just to be sure, I tried `php artisan ide-helper:models App\\Models\\JobSkill` and `php artisan ide-helper:models Models\\JobSkill` and they didn't work as well.

**Comment by sdaicz** [comment]
The note refers to command line invocation. It includes an example.
Double quotes worked for me, like this: `php artisan ide-helper:models "App\Models\JobSkill"`

**Comment by CcSimple** [comment]
### Here's the problem。 When the Model Name parameter is used, $loadModels is parameter，But didn't use the model_locations。 So you should use the Model full path。 like this:  "App\Models\xx"

https://github.com/barryvdh/laravel-ide-helper/blob/ba95d18ef55c91295250ae8b7bfa73d8fb866b9b/src/Console/ModelsCommand.php#L195-L202

**Comment by mfn** [comment]
Hey all,

maybe it worked without FQN, but not in the past; who knows.

What's important is that _currently_ all of them require FQN 😬

And since bash dislikes unquoted `\`, you need to write `"App\Post"` or `'App\\Post'`; but this has already pointed on.

I double verified this and adapted the README to be more clear.
