### ISSUE TITLE
No support to specify table for model????

### ISSUE THREAD

**Issue by beselmonster** [barryvdh/laravel-ide-helper#998]
It does not generate properties for model if model name does not match table name. I have model name BankAccountHistory. But my table is called bank_accounts__history. So no properties were generated. I was trying to figure out how to specify table,but unfortunately this package is unusable without this option. May be there is but not documented?

**Comment by mfn** [comment]
Did you specify the `protected $table` property? This is required for ide-helper to introspect the respective table.

I just did a limited test and it worked for me.

If it still doesn't work for you, please provide more details:
- ide-helper version
- laravel version
- database driver used
- code of your model

Thanks

**Comment by mfn** [comment]
Closing due to no feedback
