### ISSUE TITLE
Incorrect resolution of return type if source file references it via "use"

### ISSUE THREAD

**Issue by SeinopSys** [barryvdh/laravel-ide-helper#999]
I just started to make use of the package [laravel-elasticsearch](https://github.com/cviebrock/laravel-elasticsearch) but ran into an issue with type generation using this command. [This file](https://github.com/cviebrock/laravel-elasticsearch/blob/c0216e3f201d48482046413778b5befe0970632c/src/Manager.php#L52) for example makes references to a class "imported" via `use` at the top of the file, and the helper file ends up containing the following as a result:
```php

namespace Cviebrock\LaravelElasticsearch { 

    /**
     * Class Facade
     *
     * @package Cviebrock\LaravelElasticsearch
     */ 
    class Facade {
        
        /**
         * Retrieve or build the named connection.
         *
         * @param string|null $name
         * @return \Cviebrock\LaravelElasticsearch\Client 
         * @static 
         */ 
        public static function connection($name = null)
        {
                        /** @var \Cviebrock\LaravelElasticsearch\Manager $instance */
                        return $instance->connection($name);
        }

        # ...
    }
 
}
```

Notice how `Client` was turned into `\Cviebrock\LaravelElasticsearch\Client` instead of `Elasticsearch\Client` which was originally intended.

**Comment by mfn** [comment]
@barryvdh can be closed as duplicate of https://github.com/barryvdh/laravel-ide-helper/issues/108

**Comment by SeinopSys** [comment]
Sorry about that!

**Comment by mfn** [comment]
Nothing to be sorry, it's hard to find these dupes and I spent way too much time going through all these issues to immediately recognize the dupes 😬
